### ISSUE TITLE
motioneye.py dated 8/30/2015 is 0 bytes

### ISSUE THREAD

**Issue by drknstrmyknight** [ccrisan/motioneye#1]

**Comment by ccrisan** [comment]
Yes, the file is no longer used and will be removed. The migration to setuptools and github is not yet complete. I'm working on some wiki pages that will help users install, configure and run motionEye on their systems. Until then, please stick with the bitbucket 0.26 version.

**Comment by drknstrmyknight** [comment]
Well, that was a wasted morning...

**Comment by ccrisan** [comment]
I'm sorry, what exactly was a wasted morning? For whom? I'm not sure I understand the issue here.

**Comment by drknstrmyknight** [comment]
going through the motions of installing 27.1Don't get me wrong, you're going great work, I just got caught in the flux

**Comment by ccrisan** [comment]
This migration to github, to PyPI and everything is long overdue. I knew it wouldn't be easy but it had to be done. As soon as I manage to put together new install docs, things will become a lot clearer for everyone.

**Comment by drknstrmyknight** [comment]
Had to change my source to squeeze to get ffmpeg installed on debian jessie - all is good now.

**Comment by ccrisan** [comment]
That's odd. I tried it with debian 8 and it went alright with "jessie". What was the problem, so I can update the docs?
