### ISSUE TITLE
Empty snapshot

### ISSUE THREAD

**Issue by pepijng** [ccrisan/motioneye#100]
When requesting a snapshot using the snapshot URL (http://ip:8765/picture/1/current/)
Could it be possible to change this in the way that http://ip:8765/picture/1/current/image.jpg (for example) just respond with a JPEG image?

**Comment by ccrisan** [comment]
Set [mjpg_client_idle_timeout](https://github.com/ccrisan/motioneye/wiki/Configuration-File#mjpg_client_idle_timeout) to 0 in your motioneye.conf file and you'll no longer get empty JPEGs (except for the very first request after you restart the server).
