### ISSUE TITLE
How to https link cam?

### ISSUE THREAD

**Issue by Girum** [ccrisan/motioneye#1000]
Hi!

I tried to make a website, hosted in Firebase. But when I use the http link for my cam in Motion, it doesn't works. It says something like Mixing (because http inside a https). But, when I change the link to https, it doesn't work. 

How to set the cam over a https?

Thanks

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneye/wiki/Running-Behind-Nginx if you want HTTPS.
