### ISSUE TITLE
Can't access video stream from IE or Edge?

### ISSUE THREAD

**Issue by alphanumeric007** [ccrisan/motioneye#1005]
I have set a password for admin and user, and set authentication to basic. I can access the web UI on port 80 no problem. However in Edge when I enter http://192.168.0.23:8081? I get a "cannot access download directory" message after entering my password? And in IE it prompts to download or save a file that is just random letters and numbers? If I click open or save it just endlessly downloads.  
Motion eye version 0.39.2
Motion version 4.1.1
OS version motionEyeOS 20180627
Raspberry Pi 3B with version 1 Pi camera. 
Video stream is viewable in Chrome.

**Comment by ccrisan** [comment]
Accessing a MJPEG stream directly from the browser often does not work. Moreover, the MJPEG stream is provided by Motion, not motionEye.
