### ISSUE TITLE
motioneye autologin?

### ISSUE THREAD

**Issue by Ma-Pa** [ccrisan/motioneye#1008]
Is there a way to autologin in fullscreen mode via html request for a specific camera?

I want the same view in one html request: 
1.) http://IP-addr
2.) login data
3.) choose camera
4.) klick with mouse on fullscreen mode

http://IP-addr?username=admin&password=1234&camera=1&fullscreen=true

The url examples ( snapshot, embedded, streaming) are not for what I am looking for, I want the possibility to view the recorded images and videos.

**Comment by ccrisan** [comment]
See Video Streaming > Useful URLs. One of them should suit your needs.
