### ISSUE TITLE
Fast Network Camera

### ISSUE THREAD

**Issue by andreluisos** [ccrisan/motioneye#1011]
Do we have this option for Motioneye (not motioneyeos)?

Extra question: to apply settings through command line on motioneyeos, I've been using this command: /etc/init.d/S84streameye restart && /etc/init.d/S85motioneye restart

However, the same doesn't work on Motioneye installed on top of Raspbian. What should I use?

**Comment by ccrisan** [comment]
You can use [streamEye](https://github.com/ccrisan/streameye) on top of Raspbian. You don't need motionEye for simple MJPEG streaming.
