### ISSUE TITLE
RTL8811AU not supported. 

### ISSUE THREAD

**Issue by zepplinc20** [ccrisan/motioneye#1019]
Wifi chipset RTL8811AU doesn't appear to be supported.

**Comment by ccrisan** [comment]
@zepplinc20 is this really motionEye or is it motionEyeOS you're running? What board? What version?

**Comment by zepplinc20** [comment]
motioneyeOS. Pi 3 B v1.2

**Comment by ccrisan** [comment]
@zepplinc20 have you tried the adapter on Raspbian? Does it work?

**Comment by zepplinc20** [comment]
I've not tried it on Raspbian. It would appear the answer is no. https://github.com/lwfinger/rtlwifi_new/issues/346

**Comment by ccrisan** [comment]
Well in that case, I'll have to say "won't fix" to this one.
