### ISSUE TITLE
Need help in building from source

### ISSUE THREAD

**Issue by sankarbha** [ccrisan/motioneye#1021]
First of all, this is a great piece of work.  Thanks so much for this.

I am a newbie to linux, raspberry pi and motioneye, but with your installation guide and other resources, I have managed to run motioneye (yes not motioneyeos) in my old RaspberryPi with 3 web cams.  Everything was smooth, until I had this wish of adding audio to captured videos.

Now I have managed to record a separate .wav file which sits in the same location as the video file.  I would like to upload to gdrive and clean up this .wav file as motioneye does for the video file.

To do this, I have to make some tweaks to the source and build motioneye from source.
Could you please provide some pointers or brief tips to build from source?

Thanks.

**Comment by ccrisan** [comment]
motionEye is written in Python. You don't build it from source - you just edit the files and restart the server :)
