### ISSUE TITLE
Can not record Videos on RTSP Stream...

### ISSUE THREAD

**Issue by fynnsh** [ccrisan/motioneye#1026]
![chrome_2018-10-16_22-08-10](https://user-images.githubusercontent.com/24509725/47044327-35a06500-d190-11e8-9171-3f477131ecd6.png)
![chrome_2018-10-16_22-08-37](https://user-images.githubusercontent.com/24509725/47044328-35a06500-d190-11e8-9ff9-fea128d400fc.png)
![chrome_2018-10-16_22-09-26](https://user-images.githubusercontent.com/24509725/47044329-35a06500-d190-11e8-9224-227f026f4506.png)
![chrome_2018-10-16_22-09-34](https://user-images.githubusercontent.com/24509725/47044330-35a06500-d190-11e8-973f-be888dd607a5.png)

Some screenshots might help...

**Comment by Harrie1966** [comment]
if you have not installed a raspberry pi. Then just try Mp4. That works fine for me.

**Comment by ccrisan** [comment]
@byEliteHacks what happens if you click the movies icon instead of the pictures one, on your camera frame?

**Comment by jimmyeao** [comment]
Did you find an answer to this? None of my RTSP cameras are recording video on motion, but they will save images. already tried MP4. Motioneye installed on Ubuntu 18.04

**Comment by clydefrog76** [comment]
Same issue here. RTSP stream works fine, I can take snapshots to the storage folder but it will not record anything. I tried all the motion settings including auto threshold and nothing is recorded. Any suggestions?

**Comment by marc0nline** [comment]
> Same issue here on Ubuntu 18.04.03 LTS. RTSP stream works fine, I can take snapshots to the storage folder but it will not record anything. I tried all the motion settings including auto threshold and nothing is recorded. Any suggestions?

I'm having same issue.

**Comment by sher-zaman** [comment]
Just change the movie format to H.264 (.mp4), This solved this issue for me @ Ubuntu 18.04.04 LTS.

**Comment by oyhel** [comment]
I had the same problem. Seems the issue is permissions (I assume). I added a folder CAM in my share (/mnt/myshare/CAM/), then chmod 777 and specified  root directory to /CAM in motioneye. Together with changing to H.264 (mp4) movies started to record to the share. Next problem; files are huge...

**Comment by sher-zaman** [comment]
I am also facing same issue with huge file size, 1 hr recording file is sizing at 3.6 GB.
