### ISSUE TITLE
Empty motioneye.log

### ISSUE THREAD

**Issue by aleixpellicer** [ccrisan/motioneye#103]
I start my server on server startup on ``rc.local`` with:

``sudo /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf > /var/log/motioneye.log &``

But it saves no log, just an empty file there.

**Comment by ccrisan** [comment]
How about removing the > redirection and the ampersand at the end. What do you see printed to the console? Then adding a -d would increase the log level.

**Comment by aleixpellicer** [comment]
I thought the > was needed to save the log and the ampersand to run in background, I'll try without the > and &

**Comment by aleixpellicer** [comment]
actually, what helped was to add -l

**Comment by ccrisan** [comment]
Yes they are, but i was trying to see if you get any output without redirecting it to a file.
