### ISSUE TITLE
Segmentation Fault when opening rtsp stream

### ISSUE THREAD

**Issue by NginUS** [ccrisan/motioneye#1032]
I followed the issue reporting instructions from here: 
https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue

But am reporting it here since there's nothing there regarding a segmentation fault. It happens when I try to open the stream in VLC as well. I authenticate, then a few seconds later they just disappear from the screen. It wasn't until I followed the CLI instructions that I saw what happened. I have no idea how to resolve this.

The camera is working on its own http server, & it's got rtsp on with the port set to 554, which is how I configured it in the motionEye web interface. Its got a thing it calls a RTMP port but I didn't see anywhere to set that, so I don't know if that's anything. The user/password combo I'm using works on Xeoma, so I know that's correct.

Sanitized logs, etc. attached here.

Any help is appreciated. Thanks.

[Issues.tar.gz](https://github.com/ccrisan/motioneye/files/2505823/Issues.tar.gz)

**Comment by ccrisan** [comment]
If you get a segfault from `motion`, please do follow the instructions you mentioned above.
