### ISSUE TITLE
mediafiles.py only cleans up movie thumb files but not the movie files themselves

### ISSUE THREAD

**Issue by diymusic** [ccrisan/motioneye#1035]
I set the @preserve_movies with value 1 but the disk space is not clean up and I looked into the code:
in line 268
exts = _MOVIE_EXTS + ['.thumb']

It cleans up only thumb files. Why don't delete the movie files themselves?

**Comment by ccrisan** [comment]
The code you mention builds a list of extensions that would be deleted. This includes the known movie extensions, contained by `_MOVIE_EXTS`.
