### ISSUE TITLE
Using ffmpeg command movie_end instead relayevent

### ISSUE THREAD

**Issue by Olegone23** [ccrisan/motioneye#1036]
Hi Crissan,

Nice to see the motioneye is drastically develops (fixing bugs, new features addings and etc.). 
Could u pls. suggest, is it possible to use  ffmpeg direct stroring command line for RSTP in motioneye.conf?
Motion supports the feature (pass through option), but as I can see that it's a bit tricky to make it work on motioneye.

Kind Regards,
Oleg

**Comment by ccrisan** [comment]
Use the *Extra Motion Options* configuration entry in your settings panel to pass whatever Motion-specific options you need. `motioneye.conf` is intended for configuring motionEye, not motion.
