### ISSUE TITLE
Network Camera "Unable to open video device" (FIXED)

### ISSUE THREAD

**Issue by pmh4** [ccrisan/motioneye#1037]
Hello,
I bought me a cheap IP camera (http://192.168.2.119/jpg_stream). Today I tried to put the cam into my local MotionEye setup on my Raspberry Pi 3B+. First I used the "Simple MPEG Stream" mode, which worked. Then I tried to use "Network Camera" mode to have recording, motion sensing and so on. But the VideoStream says Unable to open Video device. Can somebody help me?

EDIT:
I looked in /var/log/motion.conf. It says
```
 netcam_read_next_header: Header not JPEG
 netcam_setup_html: Failed to read first stream header - giv$
 vid_start: Netcam failed to open
```

Thanks

**Comment by TFCDRDEATH** [comment]
Im having same issue with a 
http://192.168.1.192/web/index.html

Kguard security Omni model no qrt-502 HD smart Wifi Camera

**Comment by ccrisan** [comment]
If you think the netcam streaming URL is correct and the Simple MJPEG Camera works well with it, please [report a Motion issue](https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue) about it.
