### ISSUE TITLE
Confused about continuous recording file logic

### ISSUE THREAD

**Issue by phibes4000** [ccrisan/motioneye#104]
If I set (via the UI) motioneye to create files that have the minute and second as part of the filename, it creates a new file each minute.  If I create a file with just the date and hour it records the hour as a single file.

This is with the max file size = 0.  I would have expected the filename to just timestamp the file, and otherwise keep appending to the file.

What is supposed to happen if the process restarts and a file exists? Append or overwrite?

**Comment by ccrisan** [comment]
This is a [motion](http://www.lavrsen.dk/foswiki/bin/view/Motion/WebHome) question rather than a motionEye one. As far as I know, it will overwrite the file and I don't know of any option to append to it.
