### ISSUE TITLE
open pictures browser doesn't work for one of my camera

### ISSUE THREAD

**Issue by vidae** [ccrisan/motioneye#1043]
Hello,
I store photos and videos directly in a local NAS via SAMBA (with a folder for each camera). I use a raspicam on a RASPBERRY PI2 and a DLINK in WIFI. MOTIONEYE in version 20180627 is installed on the same RASPBERRY. When I want to access photos and videos via "open pictures browser" it works perfectly for the DLINK (even with 3000 photos) but not for the RASPICAM regardless of the number of photos. The error message is either FAILED TO GET PICTURES LIST or nothing happens. The MOTIONEYELOG file shows the following error: "WARNING: 403 GET /login/?_=1540932178380 (192. 168. 1. 83) 4. 12ms 
2018-10-30 21:46:00:[motioneye] ERROR: timeout waiting for the media listing process to finish". I don't understand why this works for one and not for the other! 
Thank you in advance.

**Comment by ccrisan** [comment]
motionEye isn't the most efficient piece of software when it comes to gathering media files and showing them in the media browser. Unfortunately you'll have to remove some of your media files or increase the [list_media_timeout](https://github.com/ccrisan/motioneye/wiki/Configuration-File#list_media_timeout) configuration option.
