### ISSUE TITLE
Can't enter text in a REQUIRED FIELD when trying to add new camera.

### ISSUE THREAD

**Issue by Just-another-pleb** [ccrisan/motioneye#1049]
I have Motioneyeos installed on a RPZ (W) and have another one which I want to add to motioneyeos's list.

Irrispective of which type of camera I select, I can not enter text in the bottom field which is the camera name and is REQUIRED.

Though the "user name" and "password" fields are blank, it doesn't matter if I put text in them or not.
I still can't get to that last field.

![screenshot from 2018-11-04 08-19-37](https://user-images.githubusercontent.com/39888280/47957475-8c1ff700-e00a-11e8-8c19-c542be7a7850.png)

**Comment by ccrisan** [comment]
Your URL is invalid. That's just an IP address. Please enter a valid URL, such as http://192.168.0.91

**Comment by Just-another-pleb** [comment]
Thank you.

I probably should have worked that out myself.
