### ISSUE TITLE
Motioneye unable to connect to network camera

### ISSUE THREAD

**Issue by TFCDRDEATH** [ccrisan/motioneye#1064]
I bought a HD smart Wifi Camera 
model no QRT-502 

Kguard security brand

https://www.amazon.com/gp/aw/d/B01D1QMT9E?psc=1&ref=yo_pop_mb_yo_pop_mb_pd_t2

Issue can't get motioneye to connect to cam.

Only says not a supported device, 

But doesn't say why?

**Comment by ccrisan** [comment]
Please find the correct streaming URL (RTSP or MJPEG). We can't find it for you.
