### ISSUE TITLE
Misssing Setting

### ISSUE THREAD

**Issue by stonefox1958** [ccrisan/motioneye#1065]
Hi

**Question 1.**
 I'm truing to setup "MotionEyeOS controller Pro" on my Samsung Galaxy S8, but I have some problem, and find a youtube video about "Access MotionEye from Anywhere : Port Forwarding"  
In the video there is some setting for MotionEye : Network - Services - Expert Settings" and these three option I don't have.  ??

**Question 2**
Is there a good guide how to use "MotionEye" from mobile device ( android ) then I'm away from home ?

links: 
"MotionEyeOS controller Pro"  :  https://play.google.com/store/apps/details?id=com.thunkable.android.cpfmukke.MotionEyeOS_Pro&hl=da))

Youtube video : https://www.youtube.com/watch?v=sT6bIhqdWHI&t=18s

![motioneye question](https://user-images.githubusercontent.com/8201781/48476807-50eaa880-e800-11e8-8b40-cf1048cb0831.jpg)

**Comment by ccrisan** [comment]
**Question 1**: enable General Settings > Advanced Settings

**Question 2**: not that I know of.
