### ISSUE TITLE
ERROR: the maximum number of tasks (100) has been reached

### ISSUE THREAD

**Issue by diskball** [ccrisan/motioneye#1068]
Hello, I keep seeing the following line appearing multiple times in the motioneye.log

ERROR: the maximum number of tasks (100) has been reached

I am running motioneyeos on a rpi zero over wifi, with a ps3 eye camera on usb. At the same time I also noticed that the frame rate is really bad.

[motioneye.log](https://github.com/ccrisan/motioneye/files/2591781/motioneye.log)

**Comment by ccrisan** [comment]
You're asking too much of your Zero. Please upgrade to a RPi3 or reduce the resolution/framerate. A slow SD card might also be the cause for this.
