### ISSUE TITLE
Motioneye Stream Freezes.

### ISSUE THREAD

**Issue by db414813** [ccrisan/motioneye#107]
So I have motioneye on ubuntu 14.04 and a fast mjpeg stream from an rp2 going to motioneye. Both have the latest motioneye/os. After a while the stream will freeze. Leaving just a still on the motioneye page. I restart the pi and nothing happens. I restart the motioneye pc and everything is good again. Any ideas?
[log.zip](https://github.com/ccrisan/motioneye/files/96762/log.zip)

**Comment by ccrisan** [comment]
So let me see if I get your scenario: you have a RPI2 running motionEyeOS with Fast Network Camera enabled. On another machine you have an Ubuntu with motionEye. How have you added the RPI2 camera to your Ubuntu-based motionEye? As a Network Camera? as a Remote motionEye Camera or as a Simple MJPEG Camera?

**Comment by db414813** [comment]
You are correct. It is as a network camera with motion detection.

**Comment by db414813** [comment]
Also have a c920 web cam connected to Ubuntu machine.

**Comment by db414813** [comment]
Like to say thank you for developing Motioneye. It's mighty cool.

**Comment by ccrisan** [comment]
Actually this is the best scenario and I myself have been using motionEye(OS) this way for some time now. Here are some ideas for a further investigation:

 * send me all the logs from your motionEyeOS system
 * try keeping an open browser window with the streaming URL of your motionEyeOS and see if it also freezes when the motionEye frame freezes

**Comment by db414813** [comment]
Ok, it froze again. I emailed you every log file I could find and a screen shot of the freeze. The second fps "1.9" is stuck at that while the other fps is still changing?

**Comment by db414813** [comment]
Some more info. I used Mr.Daves motion and install ffmpeg via some ppa which I could dig up if you want me too. After installing ffmeg the guide I used also called for me to use apt get dist-uprade which I avoided because I thought it was a terrible idea haha.

**Comment by ccrisan** [comment]
I replied to your mail saying that your logs are full of brownout warning messages. Please replace your PSU with a more powerful one and see if the problem persists.
