### ISSUE TITLE
CPU usage around 21-25%, even when not within a working schedule

### ISSUE THREAD

**Issue by pereorga** [ccrisan/motioneye#1071]
Hi,

After installing motioneye on my Raspberry PI 3 B and setting up a working schedule, I've seen that the `motion` process always consumes at least 21-25% of CPU.

Is that a bug? I was thinking that if the time is not within working schedule, and I'm not streaming or doing anything with the camera, the CPU usage should be near 0%.

Does it make sense?

**Comment by ccrisan** [comment]
The Motion daemon runs even when the motion detection is disabled. It does that to capture video from your cameras and to stream it to motionEye clients.
