### ISSUE TITLE
can't install motioneye

### ISSUE THREAD

**Issue by ward0** [ccrisan/motioneye#1073]
Hello,

I'm getting an error during install:

LibreELEC:~ # docker run --name="motioneye" \
>     -p 8765:8765 \
>     --hostname="motioneye" \
>     -v /etc/localtime:/etc/localtime:ro \
>     -v /etc/motioneye:/etc/motioneye \
>     -v /var/lib/motioneye:/var/lib/motioneye \
>     --restart="always" \
>     --detach=true \
>     ccrisan/motioneye:master-armhf
Unable to find image 'ccrisan/motioneye:master-armhf' locally
master-armhf: Pulling from ccrisan/motioneye
a892dc37f295: Pull complete
53dbef18ed5a: Pull complete
dbb06872f481: Pull complete
26493be63d86: Pull complete
ccc99144c4a5: Pull complete
Digest: sha256:124ac45af550ed6252343aac6356ae7eb1bcf1cd24429bc0cd3eded2f0c62746
Status: Downloaded newer image for ccrisan/motioneye:master-armhf
d72efa8c6dee10783f84b6f60e5c4a36b887bbf761b4237a7f16d1cd3a779151
docker: Error response from daemon: error while creating mount source path '/etc/motioneye': mkdir /etc/motioneye: read-only file system.
LibreELEC:~ # mkdir /etc/motioneye
mkdir: can't create directory '/etc/motioneye': Read-only file system

Any ideas why?

LibreELEC:~ # docker version
Client:
 Version:      1.13.1
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   1.13.1
 Built:        Sat Jul 15 18:44:26 UTC 2017
 OS/Arch:      linux/arm

i'm running libreelec/KODI on a PI3, i have logged in as ROOT and can't sudo since already root.

**Comment by ward0** [comment]
update: 'installing this version: https://hub.docker.com/r/fafex/rpi-motioneye/
doesn't seem to have a problem... but i'm at version 0.38 of motioneye

**Comment by kleini** [comment]
Please check file permissions and existing path for volumes. The error message clearly states there is something wrong with the /etc/motioneye volume path. Please read Docker documentation regarding volumes. This is a users problem and not a problem of the docker container.
