### ISSUE TITLE
Opening picture/motion browser takes a while (20/30s)

### ISSUE THREAD

**Issue by JBS5** [ccrisan/motioneye#1078]
I am using motioneye in a docker on my 8th gen i5 NUC with 8GB RAM and a SSD.
Opening the picture/motion browser takes a while (> 20-30s) and I am not sure why. Is this normal behavior or should this work more fast?

**Comment by jantje88** [comment]
Seems to be because the amount of pictures. I have set the Preserve Pictures to 1 day, now the browser is opening within a few seconds. How do other experience this?
