### ISSUE TITLE
lost pieces of viedo recording

### ISSUE THREAD

**Issue by lucapizz** [ccrisan/motioneye#1083]
[20-08-07.zip](https://github.com/ccrisan/motioneye/files/2636859/20-08-07.zip)

The attached file is a movie captured from my rasp-cam and there are some second lost. It happens with different resolutions and frame rate and I can't understand it.
If you look at the clock (right low corner) you will see that, the second counter, skip the seconds from 12 to 16, so I am asking where are they gone?
Could you explain to me if this is normal or it is a general trouble?
And how can we solve it?

Thank you

**Comment by jasaw** [comment]
I think your "Capture After" is too short. Also note that this field takes "number of frames", not seconds, so you need to multiply your desired number of "captured after" seconds by your frame rate.

This is the capture behaviour:
If detection motion frames > "minimum motion frames" config item, i.e. motion detected, do this:
1. save all frames in pre-capture buffer. Number of frames in pre-capture buffer is set by "capture before".
2. save frames while motion is still detected.
3. motion is not detected anymore (no more red box in the video), continue to save frames until "capture after" expires, then pause capture.
4. If motion is detected again, repeat step 1, and you will see the video skips the boring "no motion" part.
5. If no motion for "n" number of seconds, finalize the video file. "n" is set by "motion gap" config item.

**Comment by lucapizz** [comment]
thank you very much, now it is clear to me, so we can close this question.
