### ISSUE TITLE
Motioneye Docker - Play recorded videos?

### ISSUE THREAD

**Issue by Shareisfun** [ccrisan/motioneye#1091]
I'm running motioneye on Open Media Vault

motionEye Version | 0.36.1
Motion Version | 4.0.1

And can't play recorded videos, i have to download them?

![motion](https://user-images.githubusercontent.com/45905922/50048189-da262100-00c5-11e9-88f0-de86b9315b21.jpeg)

**Comment by Shareisfun** [comment]
Nobody?

**Comment by ccrisan** [comment]
Please upgrade to motionEye 0.39 as well as Motion 4.1.
