### ISSUE TITLE
Can't edit camera settings

### ISSUE THREAD

**Issue by walterdevos** [ccrisan/motioneye#1104]
**Environment:** 
motionEye Version | 0.39.3
Motion Version | 4.1.1
OS Version | Linux 4.14.81-v8
Raspberry Pi 3 B+
(Hass.io) Home Assistant 0.84.6

Recreate:
- In Hass.io , install motionEye via Add-on store. Everything default.
- Configure and Start plugin en go to web interface.
- Add a netwerk camera (RTSP). Enter all details  (url, user, pass, etc).
- Save.

Changing settings:
**Expected behaviour:**
- Open web interface.
- Go to Video Device section
- be able to change URL , username and/or password
- Save

Observed behaviour:
- No fields for editing url, user or password are available (or read only).
- No edit button or link is visible.
( to change settings camera user needs to delete camera and add new )

![image](https://user-images.githubusercontent.com/3726763/50575650-5fb60a80-0e02-11e9-99b4-b53964abb3b7.png)

**Comment by TheBarret** [comment]
I think thats on purpose i don't know the reason behind it but just make a new camera entry.

**Comment by ccrisan** [comment]
That is indeed on purpose. Editing them in the UI would have required a more complex code on the server side. Given that they are not details that one would edit on a daily basis, users can remove and re-add their camera in case those settings change.

**Comment by JoseAlcerreca** [comment]
Workaround: backup settings, modify config files and restore.

**Comment by tdashmike** [comment]
> 
> 
> Workaround: backup settings, modify config files and restore.

Hi, where did you find the config files on the Home Assistant vm? Thank you.

**Comment by starbasessd** [comment]
Theoretically, you should be able to use backup/restore for the WebGUI (http:[ip_address]:8765 under Settings, General Settings, Di a Backup, save somewhere, edit the file using a Linux compatible text editor (NotePad++ in Windows is good) and then re-upload using Restore
If you need further suggestions, you could enable a volume share when starting the docker in HA, share /etc in the docker image to a local to the host folder. Step by step is beyond the scope of my support here. You could try asking over in HA.
