### ISSUE TITLE
run motioneye with remote motion

### ISSUE THREAD

**Issue by nrobert13** [ccrisan/motioneye#1108]
Hi,

I'd need to run motioneye with a remote motion. Basically I'm running motion on a router where the usb cam logitech quickcam sphere is connected and would like to use motioneye on a different system, and connect it to the motion running on the router.
How could I achieve this?

Thanks in advance.

**Comment by ccrisan** [comment]
You'll need to run motionEye on both systems. You can't use motionEye with motion if they run on separate systems.
