### ISSUE TITLE
Wiki minor tweak

### ISSUE THREAD

**Issue by Chiny91** [ccrisan/motioneye#1115]
https://github.com/ccrisan/motioneye/wiki/Running-As-Normal-User

Says:

> Edit the systemd unit file /etc/systemd/system/motioneye.service by adding a User directive to the [Service] section and changing the path to the configuration file:
> 
> ...
> [Service]
> ExecStart=/usr/bin/meyectl startserver -c /home/youruser/motioneye/motioneye.conf
> User=youruser
> ...

Installing motionEye Version | 0.39.3 on an R Pi 3+ as per the Wiki, I find that meyectl is actually in /usr/**local**/bin

I also had problems with  **adding a User** rather than **replacing** root by youruser; still under review as systemd is new to me.

**Comment by ccrisan** [comment]
Added a note in the aforementioned wiki page. Thanks.
