### ISSUE TITLE
Multiple instances of meyectl

### ISSUE THREAD

**Issue by laphlaw** [ccrisan/motioneye#1119]
Not sure if this is normal, but I see two instances of meyectl
Expected?

pi@raspberrypi:/var/lib/motioneye/Camera1/2019-01-14 $ ps aux|grep motion
root     11266  8.5  2.4  60588 22032 ?        Ssl  20:51   0:00 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
root     11280 10.7  3.4 176736 30944 ?        Sl   20:52   0:00 /usr/bin/motion -n -c /etc/motioneye/motion.conf -d 5
root     11285  0.2  1.4  32940 13052 ?        S    20:52   0:00 /usr/bin/python /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
pi       11290  0.0  0.0   4372   552 pts/0    S+   20:52   0:00 grep --color=auto motion

**Comment by ccrisan** [comment]
Yes, motionEye uses subprocesses to perform tasks that would otherwise block the main process.
