### ISSUE TITLE
adding network cam in hassio or linux mint give no picture

### ISSUE THREAD

**Issue by Melcos1970** [ccrisan/motioneye#1127]
adding network cam in hassio or linux mint give no picture.
Seems like it is a motioneye issues.

https://github.com/hassio-addons/addon-motioneye/issues/20

Please help. 
What am I doing wrong, and how to fix it ?

**Comment by ccrisan** [comment]
Does it work with plain Motion? See [this](https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue) to run Motion standalone with motionEye configuration.

**Comment by Melcos1970** [comment]
fixed
