### ISSUE TITLE
What does it mean the upper right integer

### ISSUE THREAD

**Issue by chfakht** [ccrisan/motioneye#113]
Hi , I’m using the latest rapbian jessie with motionEye , it'w working perfectly and the image are beign uploaded to google Drive :) 
**I want to know what does it mean  the upper right integer that appears on the camera capture (1800 , 80 , 58 ... )** i think it's related to motion Detection but i don't understand what it really mean :large_orange_diamond:

**Comment by ccrisan** [comment]
That's the number of changed pixels.

**Comment by chfakht** [comment]
Please  what is the algorithm used for motionDetection ?

**Comment by mvanbreeden** [comment]
It's in Motion by MrDave, which is used by MotionEye. Google it, you'll see that motion detection is done by comparing pictures and pixel change.

**Comment by chfakht** [comment]
@mvanbreeden  thanks i have  found a link here 
 [http://www.lavrsen.dk/foswiki/bin/view/Motion/MotionTechnology](url)
but it's not complete as i think , could you tell me where to find the source code for it.
many  thank

**Comment by mvanbreeden** [comment]
Sure @chfakht, it is the link that Calin has referenced on his github
repos: https://github.com/Mr-Dave/motion
Op za 30 jan. 2016 om 17:16 schreef chfakht <notifications@github.com>

**Comment by chfakht** [comment]
@mvanbreeden ok i have found it (1000 lines of code :mag: )
