### ISSUE TITLE
not a supported network camera - MJPEG

### ISSUE THREAD

**Issue by turbozapekanka** [ccrisan/motioneye#1130]
Trying to connect to an old MJPEG camera (model AICN500W) using raspberry pi
The url is like this: http://192.168.x.x/cgi/mjpg/mjpeg.cgi
Getting "not a supported network camera" error

Tried jpeg URL cgi/jpg/image.cgi and it allows to add a camera but it only shows green screen

Any suggestions appreciated.

**Comment by ccrisan** [comment]
You'll have to find the URL that will actually serve a MJPG, not a webpage that embeds itself a MJPG, which is probably your case.
