### ISSUE TITLE
USB camera not displaying image

### ISSUE THREAD

**Issue by malvar0929** [ccrisan/motioneye#1142]
Hello Crisan. I love the work you have done with MotioneyeOS. I'm running it on 3 Raspberry PI 3s very reliably. The issue I'm having is with a Raspberry Pi 3 running Raspbian + Motioneye. I need to run it this way because I need to run other Java based servers. The problem is I add the USB camera, Logitech C615, there is no video displayed on the main web interface. However video is shown on the video stream interface although it looks like it's a very low frame rate but it works none the less. I have noticed that an older lower resolution Logitech works great but I need to use the higher resolution camera. Any ideas what could be causing this? Thank you in advance.

motioneye: 0.39.3
motion: 4.1.1
camera Hardware: Raspberry Pi 3
camera OS: Raspbian Stretch 9.6

**Comment by ccrisan** [comment]
> The problem is I add the USB camera, Logitech C615, there is no video displayed on the main web interface. However video is shown on the video stream interface...

It's not clear to me where you *can* and where you *cannot* see the video. What do you mean by "video stream interface"? Can you maybe attach some screenshots exemplifying the issue?

**Comment by malvar0929** [comment]
Stream shows up on the stream port however no video is shown on the main interface.

![capture](https://user-images.githubusercontent.com/20633621/52894163-1f181380-315a-11e9-97b7-7c8c37bdc373.PNG)

**Comment by ccrisan** [comment]
This is strange. Could you please open the developer console in your browser and watch for JavaScript errors? Attaching a screenshot of it should be good enough.

**Comment by Amarok73** [comment]
Hello, 

It's the same effect as I describe in issue #1188 and still did not found the solution.

**Comment by Amarok73** [comment]
@malvar0929 please execute command tail -f -n 50 /var/log/syslog then connect to the motioneye web interface and see if motioneye will start to flood the log with some specific messages...

**Comment by malvar0929** [comment]
> @malvar0929 please execute command tail -f -n 50 /var/log/syslog then connect to the motioneye web interface and see if motioneye will start to flood the log with some specific messages...

Hello Amorok73
Please see messages from Motioneye. Hopefully this makes sense to you.
![_var_og_syslog pg2](https://user-images.githubusercontent.com/20633621/52919866-92856680-32bb-11e9-9f76-6e399b63c85f.PNG)
![_var_og_syslog pg1](https://user-images.githubusercontent.com/20633621/52919868-92856680-32bb-11e9-9122-74ad3e4fe031.PNG)

**Comment by malvar0929** [comment]
Crisan please see Chorme console error. Thank you for your help
![browser console](https://user-images.githubusercontent.com/20633621/52919879-b2b52580-32bb-11e9-9f35-8e1223f45972.PNG)

**Comment by ccrisan** [comment]
@malvar0929 you appear to be having a monitor command that cannot be executed. Please remove any of your monitoring commands and see if the problem persists.

**Comment by malvar0929** [comment]
> @malvar0929 please execute command tail -f -n 50 /var/log/syslog then connect to the motioneye web interface and see if motioneye will start to flood the log with some specific messages...

Please see images. Hopefully this makes more sense to you.
![_var_og_syslog pg2](https://user-images.githubusercontent.com/20633621/52919935-661e1a00-32bc-11e9-91d1-9349ca3f1812.PNG)
![_var_og_syslog pg1](https://user-images.githubusercontent.com/20633621/52919936-661e1a00-32bc-11e9-98d0-0fae8b273855.PNG)

**Comment by malvar0929** [comment]
> @malvar0929 you appear to be having a monitor command that cannot be executed. Please remove any of your monitoring commands and see if the problem persists.

This is a fresh install, all I did was add the camera. No monitor commands have been added by me. Where would I check to see if any have been inadvertently added?

**Comment by ccrisan** [comment]
What files do you have in /etc/motioneye?

**Comment by malvar0929** [comment]
You were right, there were some monitor entries in there. I deleted them and sure enough it fixed everything. Now that I recall, I think at some point I tried to restore a configuration from a previous installation of MotioneyeOS that I had running on this very RasPi and it must of added my old monitor entries. As always thank you for your great help and keep up the awesome work with Motioneye.
