### ISSUE TITLE
Configuration confusion

### ISSUE THREAD

**Issue by ir-fuel** [ccrisan/motioneye#1143]
Maybe it's me, or maybe the docs are not clear, but I have a configuration question:

If I have a couple of Raspberry Pi's, each with an RPi camera connected, is there a way to use only 1 Raspberry Pi as the central place where I can look at all the cameras, but have each camera use its own RPi to do the motion detection and cloud upload, so I don't overload the CPU of my central RPi when connecting a lot of cameras? I didn't find any info in the wiki about where the motion detection is handled in the different scenarios.

Thanks

**Comment by ccrisan** [comment]
You can do that, of course. Configure them individually as per your needs and then add all of them to one RPi which is designated the hub. Just make sure you add them as "Remote motionEye Camera".

**Comment by ir-fuel** [comment]
Thanks!
