### ISSUE TITLE
WebUI fails to display network camera image

### ISSUE THREAD

**Issue by NginUS** [ccrisan/motioneye#1148]
On Linux Mint 18.3, Firefox 65.0, Chrome 72.0.3626.109, Motion 3.2.12+git20140228-8build1, MotionEye 0.39.3.

I'm using the same rtsp & user information that works fine in VLC, but I get a black screen on the MotionEye WebUI instead of an actual image. Same problem on both browsers.

Screenshot attached.
![untitled](https://user-images.githubusercontent.com/8769067/52763310-3f749080-2fe9-11e9-93a6-16a496ea78c3.png)

**Comment by ccrisan** [comment]
Please upgrade to Motion 4.x. That's an awfully old Motion version.
