### ISSUE TITLE
Ability to play recorded videos in browser

### ISSUE THREAD

**Issue by PaulAnnekov** [ccrisan/motioneye#115]
Most browsers support playing video using `<video>` tag ([list of supported codecs/containers for browsers](https://developer.mozilla.org/en-US/docs/Web/HTML/Supported_media_formats#Browser_compatibility)). Mr Dave's `motion` [supports some formats](https://github.com/Mr-Dave/motion/blob/master/ffmpeg.c#L148) that can be played in browser (mp4, ogg, mkv).

You just need to detect the container of video from a list (it will be better to detect codec too), pass it to client side and show `Play` button in enabled/disabled state for each video. You can check if browser supports this container/codec using [canPlayType](http://stackoverflow.com/a/8134378/782599) method. Disabled state goes with `title` attribute with message: "Codec/container does not supported by your browser". On `Play` click it will show some html5 player like [Video.js](http://videojs.com/).

**Comment by jeff-h** [comment]
I'd love this too. You sound like you know what's what in terms of the code on this. Any chance you could put a PR together for it?

**Comment by PaulAnnekov** [comment]
Just checked the sources. Looks not so difficult. Will try.

**Comment by george-vieira** [comment]
I've read #218 and unless I misread it too quickly, did this get merged as I just checked out latest showing up as version 0.35.2 and doesn't seem to be there?

**Comment by Mrnt** [comment]
@george-vieira it got merged into the dev branch

**Comment by ccrisan** [comment]
Closing as the functionality is now present in the latest version.
