### ISSUE TITLE
lastsnap is overwritten by video thumbnail

### ISSUE THREAD

**Issue by hanssgo** [ccrisan/motioneye#1150]
in my thread-1.conf I have thi sscript to create the lastsnap

`on_picture_save /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" picture_save %t %f; cp %f /var/lib/motioneye/Camera1/lastsnap.jpg`

How do I change this so it only copies the saved motion captured images and not the video thumbnails?

**Comment by ccrisan** [comment]
As far as I can tell, it shouldn't have anything to do with video thumbnails and looks good as it is.

**Comment by hanssgo** [comment]
Nevermind! it was actually sending me the previous photo because webhook was set to do on_event_start. I've moved it to on_event_end
