### ISSUE TITLE
Motioneye 0.39.3 fail to startup - Ubuntu server 16.04LTS

### ISSUE THREAD

**Issue by jjeliebenberg** [ccrisan/motioneye#1168]
Hi there
When starting motioneye on Ubuntu 16.04LTS 64 bit server, it fails to start and I get the following error in the syslog:
Started motionEye Server.
`Mar  5 16:34:59 servxxx meyectl[2192]: Traceback (most recent call last):
Mar  5 16:34:59 servxxx meyectl[2192]:   File "/usr/local/bin/meyectl", line 9, in <module>
Mar  5 16:34:59 servxxx meyectl[2192]:     load_entry_point('motioneye==0.39.3', 'console_scripts', 'meyectl')()
Mar  5 16:34:59 servxxx meyectl[2192]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/meyectl.py", line 254, in main
Mar  5 16:34:59 servxxx meyectl[2192]:     import server
Mar  5 16:34:59 servxxx meyectl[2192]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/server.py", line 28, in <module>
Mar  5 16:34:59 servxxx meyectl[2192]:     from tornado.ioloop import IOLoop
Mar  5 16:34:59 servxxx meyectl[2192]:   File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 67
Mar  5 16:34:59 servxxx meyectl[2192]:     def fileno(self) -> int:
Mar  5 16:34:59 servxxx meyectl[2192]:                      ^
Mar  5 16:34:59 servxxx meyectl[2192]: SyntaxError: invalid syntax
Mar  5 16:34:59 servxxx systemd[1]: motioneye.service: Main process exited, code=exited, status=1/FAILURE
Mar  5 16:34:59 servxxx systemd[1]: motioneye.service: Unit entered failed state.
Mar  5 16:34:59 servxxx systemd[1]: motioneye.service: Failed with result 'exit-code'. `

Any ideas how I can solve or fix this?
Thanks

**Comment by blackdot** [comment]
Same here. (16.04.6 64-bit)

> systemd[1]: Started motionEye Server.
meyectl[16412]: Traceback (most recent call last):
meyectl[16412]:   File "/usr/local/bin/meyectl", line 11, in <module>
meyectl[16412]:     sys.exit(main())
meyectl[16412]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/meyectl.py", line 254, in main
meyectl[16412]:     import server
meyectl[16412]:   File "/usr/local/lib/python2.7/dist-packages/motioneye/server.py", line 28, in <module>
meyectl[16412]:     from tornado.ioloop import IOLoop
meyectl[16412]:   File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 67
meyectl[16412]:     def fileno(self) -> int:
meyectl[16412]:                      ^
meyectl[16412]: SyntaxError: invalid syntax
systemd[1]: motioneye.service: Main process exited, code=exited, status=1/FAILURE
systemd[1]: motioneye.service: Unit entered failed state.
systemd[1]: motioneye.service: Failed with result 'exit-code'.

Any advice?
Thanks

**Comment by blackdot** [comment]
Not sure how it happened, but I had "tornado 6.0.1" on my system.

I uninstalled it
`pip uninstall tornado`
and then installed it again
`pip install tornado`

And now I have "tornado 5.1.1", motioneye is running now well!

**Comment by daniel-widrick** [comment]
Same issue as @blackdot uninstall/reinstall worked like a charm

**Comment by ccrisan** [comment]
Tornado 6.x no longer supports Python 2, so the solution is to use Tornado 5.x.

**Comment by jjeliebenberg** [comment]
Uninstalled tornado 6.0.1, but when 'pip install tornado' then it install 6.0.1 again.  
What is the appropriate way to install tornado 5?
When trying 'pip install tornado-5.1.1' then get message 'No matching distribution found for tornado-5.1.1'

**Comment by jjeliebenberg** [comment]
Correct syntax is:
pip install tornado==5.1.1

**Comment by aihysp** [comment]
yep same issue 
pip install tornado==5.1.1

did the trick
