### ISSUE TITLE
problem configuring my camera

### ISSUE THREAD

**Issue by onnebe** [ccrisan/motioneye#1170]
I am having issue configuring my Panasonic BL-VP100 Series network camera, i keeps throwing up
"it cannot concatenate "str" and "Non type" objects. Is this software issue?

Please help

**Comment by ccrisan** [comment]
@onnebe either try to upgrade to the latest motionEye 0.40rc1 prerelease or downgrade your Tornado to 4.x.

**Comment by onnebe** [comment]
Do you have link to either the downgrade or the upgrade, this would surely help

**Comment by ccrisan** [comment]
@onnebe assuming you're using motionEye (not motionEyeOS), just do a `sudo pip2 install motioneye==0.40rc1`.
