### ISSUE TITLE
Any available version for Debian 10 (buster)

### ISSUE THREAD

**Issue by mcmidget** [ccrisan/motioneye#1173]
Hi, 

I'm a big fan of your software and have a few servers running ME successfully under Debian 9 (stretch) with no issues.

Is there any available version of MotionEye running out of the box under Debian 10 (buster), which provide python3?

Keep the great job.

**Comment by ccrisan** [comment]
motionEye does not work on Python 3. Debian 10 also provides Python 2 so please try installing it under the Python 2 environment.
