### ISSUE TITLE
get camera id from config file not from camera config file name

### ISSUE THREAD

**Issue by drajar** [ccrisan/motioneye#1178]
Now motioneye have:
_CAMERA_CONFIG_FILE_NAME = 'camera-%(id)s.conf'
and read the camera id with
pattern = '^' + _CAMERA_CONFIG_FILE_NAME.replace('%(id)s', '(\d+)') + '$'

But in my motion.conf I have 
camera /etc/motion/home.conf
camera /etc/motion/garden.conf
etc.

Yes I can replace mome.conf with camera-1.conf and garden.conf with camera-2.conf, but is more intuitive to name configuration files with suggestive names and read theh camera id from config file, not from file name.

**Comment by ccrisan** [comment]
You can't have that with motionEye. motionEye relies on that id, since not all motionEye cameras are Motion cameras (and sometimes not all Motion cameras are motionEye cameras).
