### ISSUE TITLE
pip install -upgrade motioneye doesn't work

### ISSUE THREAD

**Issue by evan-shaw** [ccrisan/motioneye#1186]
This is on raspbian stretch. Result is as follows: -

Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal import main
ImportError: No module named _internal

So I cannot upgrade to the new 0.40rc1

**Comment by ccrisan** [comment]
Doesn't look like a motionEye issue. Check your python/pip installation and make sure you can actually use pip.
