### ISSUE TITLE
Custom resolution not available

### ISSUE THREAD

**Issue by eldadh** [ccrisan/motioneye#1188]
I am trying to add a custom resolution of 1600*900 
from my dafang camera and it wont let me.

![image](https://user-images.githubusercontent.com/6177736/54491899-b217ab00-48ca-11e9-9a08-b4f43c83f054.png)

i am using the latest : ccrisan/motioneye:dev-amd64
 
![image](https://user-images.githubusercontent.com/6177736/54491879-92808280-48ca-11e9-96aa-300e61a4cc88.png)

Eldadh

**Comment by ccrisan** [comment]
@eldadh both Width and Height must be modulo 8.
