### ISSUE TITLE
Motion memory leak

### ISSUE THREAD

**Issue by thinkdao** [ccrisan/motioneye#119]
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
user   13522 11.1 88.7 2962116 1788184 pts/3 Sl+  Jan29 1226:45 /usr/bin/motion -n -c /var/www/user/sites/sitename/www/motioneye/dist/etc/motion.conf -d 5

>88.7 %MEM of 2048mb

**Comment by ccrisan** [comment]
I believe this should be reported upstream; it definitely is a motion problem and not a motionEye one.
