### ISSUE TITLE
Upgrade to 0.40rc3

### ISSUE THREAD

**Issue by nuiler** [ccrisan/motioneye#1190]
How can I upgrade to version 0.40rc3, currently i use 

motionEye Version 0.39.3
Motion Version 4.1
OS version Raspbian 9.4

**Comment by ccrisan** [comment]
`pip2 install --upgrade motioneye==0.40rc3` should do the job.

**Comment by 00lex** [comment]
or 
`pip install --pre motioneye --upgrade`

**Comment by nuiler** [comment]
I have Successfully installed MarkupSafe-1.1.1 backports-abc-0.5 futures-3.2.0 jinja2-2.10 motioneye-0.40rc4 pillow-5.4.1 pycurl-7.43.0.2 singledispatch-3.4.0.3 six-1.12.0 tornado-5.1.1 

but in the webinterface displayed 


motionEye Version | 0.39.3
Motion Version | 4.1
OS Version | Raspbian 9.4

**Comment by ccrisan** [comment]
@nuiler restart the server.

**Comment by vplustute** [comment]
can I start the update by SSH?
I connected via SSH und try to use
`pip2 install --upgrade motioneye==0.40rc3`
and
`pip install --pre motioneye --upgrade`
but it doesn't work

**Comment by 00lex** [comment]
try

`systemctl stop motioneye && pip install --upgrade setuptools && pip install --pre motioneye --upgrade && systemctl restart motioneye`

**Comment by vplustute** [comment]
No, it doesn't work.

`-sh: systemctl: command not found`

**Comment by ccrisan** [comment]
@vplustute either you're on motionEyeOS or you're on a system that uses sysvinit instead of systemd.
In the first case, use the latest nightly build. In the second case, use `/etc/init.d/motioneye stop`.
