### ISSUE TITLE
0.40rc4: streaming issue

### ISSUE THREAD

**Issue by 00lex** [ccrisan/motioneye#1191]
no effect on motion detection or the recorded footage. just the stream is broken 

[https://videos2.sendvid.com/98/04/bua3gbvq.mp4?validfrom=1552944753&validto=1552951953&rate=200k&burst=1000k&hash=h913%2F2zkiYGlSKPaRVUNfeQdYNU%3D](https://videos2.sendvid.com/98/04/bua3gbvq.mp4?validfrom=1552944753&validto=1552951953&rate=200k&burst=1000k&hash=h913%2F2zkiYGlSKPaRVUNfeQdYNU%3D)

btw. its a rtsp stream

**Comment by ccrisan** [comment]
@00lex 

> no effect on motion detection or the recorded footage

What *effect* are you expecting?

> https://videos2.sendvid.com/98/04/bua3gbvq.mp4?validfrom=1552944753&validto=1552951953&rate=200k&burst=1000k&hash=h913%2F2zkiYGlSKPaRVUNfeQdYNU%3D

The link is unauthorized here.

**Comment by 00lex** [comment]
https://cloud.hamburg.freifunk.net/f/e65638267e3849c5bfdd/

**Comment by ccrisan** [comment]
@00lex problems like that are often fixed by choosing TCP over UDP when adding the camera. If that still doesn't fix the problem, please run Motion independently of motionEye and report a Motion issue, following [these instructions](https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue).

**Comment by 00lex** [comment]
TCP/UDP doesn't fix it. I make a downgrade to rc3. maybe on Sunday a can make a report

**Comment by ccrisan** [comment]
@00lex if downgrading motionEye has an effect, please keep us posted.

**Comment by 00lex** [comment]
yes. with rc3 everything is ok

**Comment by MrChris79** [comment]
I too am having very similar issue with video using 0.40rc4 on my RPi3. However I just came across MotionEye and started playing/testing it. It finds my usb cameras no problem. Been playing with and using Motion by itsself for a while now with no real issues. Maybe if I try rc3 it will fix the video issue or rc5. :)

**Comment by ccrisan** [comment]
Fixed in https://github.com/ccrisan/motioneye/commit/114c8c29a383d31f3c680c299f0c8fa66bee1f3d. Please upgrade to 0.40rc5.

**Comment by 00lex** [comment]
works! thx
