### ISSUE TITLE
Failed authentication on Update

### ISSUE THREAD

**Issue by romankh3** [ccrisan/motioneye#1194]
I installed motion Eye on Raspberry Pi and after that tried to update it.
And I've got next:
```
Authentication is required to restart 'motioneye.service'.
Authenticating as: root
```
What kind of credentials do I need to write?
<img width="512" alt="2019-03-23 в 09 33 34" src="https://user-images.githubusercontent.com/16310793/54863244-00a3ca00-4d4f-11e9-8695-a20330d2705f.png">

Best regards, 
Roman B.

**Comment by ccrisan** [comment]
Root authentication problems on your system do not constitute a motionEye issue.

**Comment by romankh3** [comment]
@ccrisan, hello!
I tried to pass my own system credentials and I've got the same result. 
That's why I decided it can be related to MotionEye settings. Am I right?

**Comment by ccrisan** [comment]
@romankh3 I don't think you're right. What do your system credentials have to do with motionEye settings?

**Comment by romankh3** [comment]
It's default credentials for Raspbian OS. I have installed Motion Eye due to [manual ](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian) and after that, I ran update.

**Comment by ccrisan** [comment]
@romankh3 I'm still not following you. What do the default Raspbian OS credentials have to do with you installing motionEye?
