### ISSUE TITLE
Running migrateconf.sh

### ISSUE THREAD

**Issue by djehrenr** [ccrisan/motioneye#1198]
Hi there,

When trying to run migrateconf.sh  with ./ I get "Permission Denied".  If I use sudo I receive an error saying file not found.

**Comment by ccrisan** [comment]
@djehrenr is your `migradeconf.sh` executable?

**Comment by djehrenr** [comment]
Thanks for the reply,

I did run sudo chmod +x migrateconf.sh and then ./migrateconf.sh 

I receive this error:
./migrateconf.sh: line 7: syntax error near unexpected token `newline'
./migrateconf.sh: line 7: `<!DOCTYPE html>'

**Comment by ccrisan** [comment]
What does your `migrateconf.sh` content look like?

**Comment by djehrenr** [comment]
I went ahead and rebuilt everything. I wanted to clean up some other issues, so uninstalling everything helped.

Thanks!

**Comment by ccrisan** [comment]
I'm glad it worked.
