### ISSUE TITLE
Update Raspbian 9.8 motioneye problem

### ISSUE THREAD

**Issue by NikonD7200** [ccrisan/motioneye#1202]
motioneye stop to work after raspbian update
motion.log
motion: error while loading shared libraries: libxãb-drh3.{o>0: cannot open shared object file: No such file or directory

motion.conf
x @enabled on
x@show_advanced on
x @normal_password xxxxxxxxx
x @admin_username xxxx
x @admin_password xxxxxxxxxx
x@normal_username xxxx

webcontrol_html_output on
webcontrol_port 7999
setup_mode off
webcontrol_localhost on

thread thread-1.conf
thread thread-3.conf
thread thread-2.conf

webcontrol_parms 2

control_html_output on
control_localhost on
control_port 7999__

**Comment by bob-lee** [comment]
What versions of motion and motioneye were you running before upgrading to `9.8`?
I upgraded Raspbian to `9.8` and motioneye `0.40rc5` with motion `4.2.2` seems keep working. You can try reinstalling motioneye:
```
sudo pip uninstall motioneye
sudo pip install motioneye==0.40.rc5
```

**Comment by NikonD7200** [comment]
I have motioneye 0.39 uninstall dont work ... i try again

**Comment by NikonD7200** [comment]
sudo pip uninstall motioneye = Instruction no allowed

**Comment by ccrisan** [comment]
` libxãb-drh3.{o>0` - looks like a filesystem corruption. Definitely not a motionEye issue.
