### ISSUE TITLE
0.40-rc5, Installation on Xiaomi Dafang with modded firmware and entware, webserver access problem. 

### ISSUE THREAD

**Issue by derBG** [ccrisan/motioneye#1204]
Hello,

i've tried to install motioneye on a xiaomi dafang camera.
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks

I have a working enviroment with entware.
https://github.com/EliasKotlyar/Xiaomi-Dafang-Hacks/issues/542

The Camera has a mips processor.

Needed progs are installed i think.
`Python 2.7.14`

`   DEBUG: using motion version 3.4.0-Git-78ba2da`

`ffmpeg version 3.2.9 Copyright (c) 2000-2017 the FFmpeg developers
  built with gcc 5.4.0 (OpenWrt GCC 5.4.0 r223-a006495)`

jinja tornado pillow etc also installed.

When i start the server everything looks fine
> [root@DAFANG:motioneye-0.40rc5]# /opt/usr/bin/meyectl startserver -d -c /opt/etc//motioneye/motioneye.conf  
>     INFO: hello! this is motionEye server 0.40rc5
>    DEBUG: using motion version 3.4.0-Git-78ba2da
>    DEBUG: using ffmpeg version 3.2.9
>    DEBUG: reading main config from file /opt/etc/motioneye/motion.conf...
>     INFO: main config file /opt/etc/motioneye/motion.conf does not exist, using default values
>    DEBUG: loading additional config structure for main, without separators
>    DEBUG: additional config section: network
>    DEBUG: listing config dir /opt/etc/motioneye/...
>     INFO: cleanup started
>     INFO: wsswitch started
>     INFO: tasks started
>     INFO: mjpg client garbage collector started
>     INFO: server started

Now when i try to access the motioneye webinterface i became following message:

>    DEBUG: loading additional config structure for main, with separators
>    DEBUG: additional config section: network
>    DEBUG: loading additional config structure for camera, with separators
> /bin/sh: lsb_release: not found
> /bin/sh: uname: not found
>    ERROR: [Errno 20] Not a directory: '/opt/usr/lib/python2.7/site-packages/motioneye-0.40rc5-py2.7.egg/motioneye/templates/main.html'
> Traceback (most recent call last):
>   File "/opt/lib/python2.7/site-packages/tornado/web.py", line 1590, in _execute
>     result = method(*self.path_args, **self.path_kwargs)
>   File "/opt/usr/lib/python2.7/site-packages/motioneye-0.40rc5-py2.7.egg/motioneye/handlers.py", line 251, in get
>     mask_width=utils.MASK_WIDTH)
>   File "/opt/usr/lib/python2.7/site-packages/motioneye-0.40rc5-py2.7.egg/motioneye/handlers.py", line 107, in render
>     content = template.render(template_name, **context)
>   File "/opt/usr/lib/python2.7/site-packages/motioneye-0.40rc5-py2.7.egg/motioneye/template.py", line 65, in render
>     template = _jinja_env.get_template(template_name)
>   File "/opt/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_template
>     return self._load_template(name, self.make_globals(globals))
>   File "/opt/lib/python2.7/site-packages/jinja2/environment.py", line 804, in _load_template
>     template = self.loader.load(self, name, globals)
>   File "/opt/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
>     source, filename, uptodate = self.get_source(environment, name)
>   File "/opt/lib/python2.7/site-packages/jinja2/loaders.py", line 171, in get_source
>     f = open_if_exists(filename)
>   File "/opt/lib/python2.7/site-packages/jinja2/utils.py", line 154, in open_if_exists
>     return open(filename, mode)
> IOError: [Errno 20] Not a directory: '/opt/usr/lib/python2.7/site-packages/motioneye-0.40rc5-py2.7.egg/motioneye/templates/main.html'
>    ERROR: 500 GET / (192.168.178.150) 113.75ms 

Uname is in dropbear included on the system.
The lsb_release is missing.

I'am using a raspi with motioneye os also and there is no lsb_release.

>   ERROR: [Errno 20] Not a directory: '/opt/usr/lib/python2.7/site-packages/motioneye-0.40rc5-py2.7.egg/motioneye/templates/main.html' 

This is a zip file and can not be opened to acces the files?

> [root@DAFANG:~]# unzip -l /opt/usr/lib/python2.7/site-packages/motioneye-0.40rc5-py2.7.egg
> .....
>  2020801                     102 files

**Comment by ccrisan** [comment]
Your system is not one of the systems supported by motionEye (meaning that I have no means to test it), so you're on your own with it.

Your Python installation seems to prefer compressed egg files to a proper package installation. I personally don't know how to help you with that, but this is not a motionEye issue.

Please use our [forum](https://groups.google.com/forum/#!forum/motioneye) to reach out to other users who might have experienced problems similar to yours.
