### ISSUE TITLE
How can I Update to  0.40rc5

### ISSUE THREAD

**Issue by vplustute** [ccrisan/motioneye#1207]
At the Moment I'm using

motionEye Version
0.39.3
Motion Version
4.1.1 

When I connect by SSH to my RaspberryPi with motioneyeOS and try to make an update it doesn't work.

`[root@meye-e1d88f77 ~]# pip install --upgrade motioneye
-sh: pip: command not found`

**Comment by ccrisan** [comment]
That's motionEyeOS you're using, not motionEye. Install the latest nightly build if you want to have motionEye-0.40rc5.

**Comment by vplustute** [comment]
OK, there is a difference between MotionEye and MotionEyeOS.
Sorry that was my mistake.
Thx
