### ISSUE TITLE
Not possible to update?

### ISSUE THREAD

**Issue by vplustute** [ccrisan/motioneye#1209]
Hello,
I'm using the motionEyeOS
motionEye Version
0.39.3
Motion Version
4.1.1
OS Version
motionEyeOS dev20190203

I tried to update my MotiomEye,
At first I tried it by using the update button but I got the infomation there is no update.
Then I connect my Raspery PI by SSH an tried to use
`pip install --upgrade motioneye`
Then I get the Information -sh: pip: command not found
What I'm making wrong?

**Comment by rotrials** [comment]
See #1207

**Comment by vplustute** [comment]
Oh sorry, my mistake. 
Thx
