### ISSUE TITLE
"Run a command" on motion detection - is it possible to add path to saved file?

### ISSUE THREAD

**Issue by Dinth** [ccrisan/motioneye#1219]
Hi. This is not really an issue, but i was struggling with that for a while and potentially it may be a feature request. 
At the moment, ive got "run a command" notifications set up:
mosquitto_pub -h 10.10.1.5 -t cameras/FrontGarden/motion -m "ON"
and when motion is no longer detected:
mosquitto_pub -h 10.10.1.5 -t cameras/FrontGarden/motion -m "OFF"

Motioneye also saves pictures and videos when motion is detected.

Is it somehow possible to add path of the saved image and video to the following notifications?
By doing something like:
mosquitto_pub -h 10.10.1.5 -t cameras/FrontGarden/motionImage -m "$image"
?

**Comment by ccrisan** [comment]
Use the conversion specifiers that show up when you hover the question mark next to the Run A Command box.
