### ISSUE TITLE
netcam_highres  for manual screenshot

### ISSUE THREAD

**Issue by aLiEnHeAd13** [ccrisan/motioneye#1259]
Hi,
I configured my camera according to 
https://github.com/ccrisan/motioneye/issues/880
with a low-res viewing stream and a hi-res recording stream via netcam_highres.
The motion deteced screenshots and movies are hi-res but manual screenshots are low-res.
In my opinion manual screenshots should use the high resolution as well.

**Comment by ualex73** [comment]
This sounds more of a motion request, and not a motionEye request. motionEye just calls the API to trigger a snapshot.

**Comment by zagrim** [comment]
@aLiEnHeAd13 are you using `movie_passthrough` together with `netcam_highres`, or just `netcam_highres` alone? Motion docs state quite clearly that with `movie_passthrough` the behaviour should be just the way you've experienced, but the docs don't mention how it behaves without the passthrough option. Anyway, you should ask that from [motion project](https://github.com/Motion-Project/motion/issues).

**Comment by aLiEnHeAd13** [comment]
Hi @zagrim the only additional motion option is netcam_highres. No passthrough. OK. I'll have a look at the motion project.

**Comment by aLiEnHeAd13** [comment]
created an issue at motion:
[https://github.com/Motion-Project/motion/issues/942](https://github.com/Motion-Project/motion/issues/942)
