### ISSUE TITLE
Thumbnails on recorded videos

### ISSUE THREAD

**Issue by okotgnal** [ccrisan/motioneye#126]
i have installed motioneye in a raspberry, everything is working except the thumbnails on recorded videos, i can't see a frame picture of video recorded. Have some way to fix?

**Comment by ccrisan** [comment]
Please attach your motioneye.log file.

**Comment by okotgnal** [comment]
Hi ccrisan, i don't find this log, is in /var/log? i just find the motion.log, i installed manually the motioneye for raspberry b+ 1.2 
![thumb1](https://cloud.githubusercontent.com/assets/6302668/13106242/57b66914-d54e-11e5-980f-034b5ca569ca.png)
![thumb2](https://cloud.githubusercontent.com/assets/6302668/13106247/5baf3e10-d54e-11e5-9299-d9652f6c1465.png)

**Comment by okotgnal** [comment]
Hi ccrisan, i solved it, i install libavresample2, and worked!
