### ISSUE TITLE
How to FTP only, without using also the local storage?

### ISSUE THREAD

**Issue by PieBru** [ccrisan/motioneye#1271]
Hi,

how can I send videos to my internal FTP,  without duplicating them on the local storage /share/motioneye/... ?
Maybe I'm missing something, but from HA MotionEye admin UI I'm not able to save FTP config withouth defining a local storage, which I regularly purge using a cron job.
I'm using Arch Linux.

Thank you,
Piero

**Comment by ccrisan** [comment]
Theoretically you can't upload media files without storing them (at least temporarily) on the local SD card. However, you have three solutions, each one with its disadvantages:

 1. Set a pattern name that does not contain any variables (and thus files created will always have the same name).
 2. Enable the automatic cleanup to remove the local files after a short period.
 3. Use the File Storage > Run A Command option in conjunction with a script that does the uploading and remove the generated file right away. If things happen quick enough, it might not even actually get written to the SD card.
