### ISSUE TITLE
Problems in arm/disarm motion detection via motion Web API

### ISSUE THREAD

**Issue by SebastianSchultz** [ccrisan/motioneye#1294]
Hello,

I have a problem with arm/disarming the motion detection via Motion Web API.
I pause the motion detection by the following urls:

http://192.168.178.245:7999/1/detection/pause
http://192.168.178.245:7999/2/detection/pause

with the following urls I can check the status of the motion detection:

http://192.168.178.245:7999/1/detection/status
http://192.168.178.245:7999/2/detection/status

That works fine but after a few minutes without any changes at the web interface or something the detection resumes.
The working schedule is off for both cameras.

Is it possible that something in the background restarts the detection?

I need this option to activate and deactivate the motion detection via URL from another system.

Can you please help whats going on here?

**Comment by Buckler89** [comment]
Can you explain briefly why you closed the problem? could also be useful to me.
thanks a lot
