### ISSUE TITLE
Action buttons display

### ISSUE THREAD

**Issue by est-08** [ccrisan/motioneye#1295]
Hello,
I activated the action buttons to use the ptz functions using node-onvif scripts and it works perfectly.
On the other hand, the display of the buttons is done on two lines (see screenshot) whereas they could be displayed on a line.
Is there a setting to solve this problem?
![img1](https://user-images.githubusercontent.com/39032795/58565823-b435a880-822f-11e9-8a6b-47dd72d0675f.JPG)

**Comment by ccrisan** [comment]
Hi,

Unfortunately the way the current code handles those action buttons, there's no way to arrange them differently than they currently are. They are arranged on a 2x8 matrix, the second line being displayed only when there are more than 4 buttons. I'm open to receive PRs on this matter, but for now there are other priorities.
