### ISSUE TITLE
Question (run in docker from hass.io): recommended way to store videos on external USB

### ISSUE THREAD

**Issue by PieBru** [ccrisan/motioneye#1301]
Hi, I'm using MotionEye in a docker container under home-assistant supervisor (actually hassio), all in an Arch Linux beefy server.
Host mounted /mnt/usb1 device is not visible as "storage device" in MotionEye.
What's the recommended way to use it? Remove docker container "protection"? Add some parameter somewhere?
Please point me in a good direction.
Thanks,
Piero

**Comment by kleini** [comment]
Hi,
this depends how you want to use your USB device.
If you want to unplug it while motioneye is still up an running, it would be useful to pass through the according /dev entry into the container.
If it is just some filesystem, that does not need to be unplugged. Create a volume bind mount when launching the motioneye container.
Forwarding devices and bind mounting volumes is both described in the wiki: https://github.com/ccrisan/motioneye/wiki/Install-In-Docker
