### ISSUE TITLE
Restore from Backup not working?

### ISSUE THREAD

**Issue by jordipalet** [ccrisan/motioneye#1311]
Hi,

Using Ubuntu.

I did a backup of my configuration (5 cameras), and saved it correctly.

Upgraded with pip install motioneye --upgrade and the cameras are gone.

I restored the backup and restarted and still say no cameras defined ...

even if I restore manually the contents of /etc/motioneye, it looks like not recognizing the config files.

Any hints?

**Comment by zagrim** [comment]
You are not telling the versions you upgraded from and to, but just a guess: Have you followed the instructions mentioned in [the release notes](https://github.com/ccrisan/motioneye/releases/tag/0.40)? You need to run configuration migration when upgrading from 0.39 to 0.4x.

**Comment by jordipalet** [comment]
Missed that, thanks a lot, just did it and it worked perfectly !
