### ISSUE TITLE
Request: Is there a way to not show camera feeds until login?

### ISSUE THREAD

**Issue by mikepruett3** [ccrisan/motioneye#1318]
I don't know if this is possible functionality or not... but I would like a way to turn off camera streams at the default page... until login.

Currently, if you browse to the MotionEye page, all camera streams are displayed (but not controllable). I would like to provide access to my MotionEye install remotely, but only to users whom have logged in only.

Is there a fix for this? Having public access (visable) to RTSP streams of my cameras just feels creepy!

**Comment by CRImier** [comment]
That's weird. I'm not the main developer, but I manage a system of many interconnected MotionEye cameras and I don't have this issue - when opening the motioneye webpage, I see the login page without any feeds (just "enter your username and password"), unless I've logged in using that browser before, of course. Do you have both user and admin passwords set (non-empty)? Are the feeds password-protected (uner the "video streaming" tab? [unrelated, but make sure they are] Can you maybe provide a screenshot?

**Comment by mikepruett3** [comment]
Thank you! That was it! I only had the admin password filled out, not the user password.

**Comment by CRImier** [comment]
great! Since your problem is solved, please close this issue =)
