### ISSUE TITLE
Fix installation guide for Archlinux

### ISSUE THREAD

**Issue by ilovelinux** [ccrisan/motioneye#1320]
Motion isn't on official Archlinux repositories but in AUR. Arch users need to follow this steps:

1. Install base-devel and git: `$ pacman -S base-devel git`
2. Clone Archlinux's aur package: `$ git clone https://aur.archlinux.org/motion.git`
3. Join in the directory and build: `$ cd motion && makepkg -is`

Installation guide: https://github.com/ccrisan/motioneye/wiki/Install-On-Arch

**Comment by ccrisan** [comment]
I had no idea they removed it from official repos. I've now update the wiki page. Thanks.

**Comment by ilovelinux** [comment]
They just re-added it to the official repos: https://www.archlinux.org/packages/community/x86_64/motion/ (Also in ARM repos, just checked)

**Comment by ilovelinux** [comment]
@ccrisan as I said you should remove the commands to build Motion by themselves because it has been added to the official repository again

**Comment by ccrisan** [comment]
Updated. Thanks!
