### ISSUE TITLE
Video not showing when chrome lazyload feature is enabled

### ISSUE THREAD

**Issue by rajendrant** [ccrisan/motioneye#1324]
When chrome lazyload feature is enabled, motioneye videos are not showing up.
This is caused by motioneye javascript code using property name 'loading' for img elements.
This property name is reserved when lazyload feature is enabled, and breaks motioneye setups.

See this chromium bug for more details
https://bugs.chromium.org/p/chromium/issues/detail?id=976468#c2

**Comment by bob-lee** [comment]
I wonder `loading` property name is reserved by whom / when..

**Comment by rajendrant** [comment]
The property name is being reserved by the html standardization group
https://github.com/whatwg/html

So all browsers would support it.
Though the name clash bug would essentially only trigger when they fully implement it.
