### ISSUE TITLE
How to get always the same Image File Name?

### ISSUE THREAD

**Issue by bojanopatje** [ccrisan/motioneye#1327]
Hi.
i'm making webcam on my personal website that will show some landscape, but I need that motioneye upload on the server, file with always the same name "picture.jpg". On motioneye settings it appears that I can't do this (%Y-%m-%d/%H-%M-%S). Is there anny other way?
Thank you.

**Comment by michalchrzastek** [comment]
Of course you can do it, just overwrite the file name.
Then in the file browser there is only 1 photo and is overwritten every second or every frame. 

![Screenshot 2019-06-24 at 19 05 42](https://user-images.githubusercontent.com/38867528/60041451-5cb21d80-96b3-11e9-84a2-023c1db79307.png)
![Screenshot 2019-06-24 at 19 06 09](https://user-images.githubusercontent.com/38867528/60041452-5cb21d80-96b3-11e9-96e0-67665871ebc2.png)

**Comment by bojanopatje** [comment]
Thank you. I asked before I tried. I saw that it is possible to name by date, time,... and I thought that it is not possible in other way. Thank you again.
