### ISSUE TITLE
Insert a camera-stream from another motioneye

### ISSUE THREAD

**Issue by holgerbusch** [ccrisan/motioneye#1329]
Hello from Germany.
I have one raspberry with a Pi-Camera with motioneye running. 
Now I want to run a second raspberry with motioneye as well - like a server, so that the first one just used like an IP camera. 
I activated the streaming with no authentication on raspberry one and I can watch it by opening the stream in a browser. 
When I want to insert an camera into the second, motioneye finds the stream and insert it, but theres no picture to see. 
I installed both raspberries with fresh downloaded motioneye yesterday. 
Maybe you can help me to solve the problem?

Thanks from Germany.
Holger
![motioneye1](https://user-images.githubusercontent.com/33656326/60034305-9f232c80-96aa-11e9-90f4-18cf0d07c0d7.PNG)

**Comment by michalchrzastek** [comment]
I had this issue as well. Set the first camera as FastNetworkCamera under Expert setting, then on your second Pi, add it again. Try those settings (obviously with your own IP).

![Screenshot 2019-06-24 at 18 50 52](https://user-images.githubusercontent.com/38867528/60040761-9b46d880-96b1-11e9-9b98-c728446b2e1a.png)

**Comment by holgerbusch** [comment]
@michalchrzastek thanks.
That worked.

Amazing.
Thanks from Germany.

**Comment by ilovelinux** [comment]
Problem has been solved. Please @holgerbusch close this issue
