### ISSUE TITLE
More settings?

### ISSUE THREAD

**Issue by Henrietta1989** [ccrisan/motioneye#1337]
Are there any more settings i could use to customize MotionEye even more?

Advanced settings is on and i can see all "Preferences ... Working Schedule" settings.

Any plugins?

**Comment by ccrisan** [comment]
Nope. No plugins.

**Comment by jurgenweber** [comment]
how do you turn on advanced settings? I can find no such option

**Comment by ccrisan** [comment]
@jurgenweber you don't. Advanced Settings are gone. Well, not the settings themselves, they are all visible now to admin users.

**Comment by jurgenweber** [comment]
ah, cool. A little confusing since there are references to them in the doco.

**Comment by ccrisan** [comment]
@jurgenweber please point them out so we can remove then.

**Comment by jurgenweber** [comment]
https://github.com/ccrisan/motioneye/wiki/Install-In-Docker#image-from-docker-hub

4th paragraph down.
