### ISSUE TITLE
0.31 stopped sending pictures.

### ISSUE THREAD

**Issue by trainspotta** [ccrisan/motioneye#135]
Updated to latest build just now.

I get a motion notification via mail but there are no longer pictures attached.

Ubuntu 14.04.4 LTS

Images are still saved to disk.

**Comment by ccrisan** [comment]
Alright I'll look into it.

**Comment by trainspotta** [comment]
Any news? I'm leaving the house for a few days.

**Comment by ccrisan** [comment]
I tried reproducing the issue without success. Please send me your config files (**removing sensitive data**) and I'll try to find the problem.

**Comment by trainspotta** [comment]
So now it is getting kind of funny ;)

So I removed the cam completely and set it up again. Now I'm getting mails with pictures again but the working schedule gets completely ignored. No matter if active or not and no matter what time, I always get mails.

What kind of files do you need? motioneye.conf and thread?

Thanks for your work btw.!

**Comment by ccrisan** [comment]
thread-1.conf and motion.conf

**Comment by trainspotta** [comment]
`# @enabled on
# @show_advanced on
# @normal_password XXXX
# @admin_username XXXX
# @admin_password XXXX
# @normal_username XXXX


thread thread-2.conf
thread thread-1.conf
control_port 7999

control_html_output on
control_localhost on

setup_mode off`

**Comment by trainspotta** [comment]
<script src="//pastebin.com/embed_js/n1FBctQn"></script>

**Comment by trainspotta** [comment]
<iframe src="//pastebin.com/embed_iframe/n1FBctQn" style="border:none;width:100%"></iframe>

**Comment by trainspotta** [comment]
http://pastebin.com/embed/n1FBctQn

**Comment by ccrisan** [comment]
How about attaching those files here, directly. I can't seem to find them anywhere in your link (did it expire already?).

**Comment by trainspotta** [comment]
So I just deleted every config file, deleted motioneye and reinstalled everything. I jsut finished the configuration. I will attach all files here if this didn't help.

Thank you for your time. motioneye is a really great project!

**Comment by sherm8n** [comment]
I am also having this issue.
Was receiving attached images with no problem. Then they suddenly stopped.
I've tried deleting/reattaching the camera, but that didn't help.
In the motioneye log, I get the error:

2016-03-13 19:41:05: [sendmail]    ERROR: timeout waiting for the media listing process to finish
2016-03-13 19:41:06: [sendmail]     INFO: email sent

I still get the email, just with no picture.

**Comment by ccrisan** [comment]
The error indicates that there are too many media files to be scanned in due time. Please clean up your media files dir.

**Comment by trainspotta** [comment]
Removing and setting up all cameras fixed the issue. Media folder was emptied before.
