### ISSUE TITLE
Enhancement: "Power Line Frequency" in Hertz instead of 0/1/2

### ISSUE THREAD

**Issue by PieBru** [ccrisan/motioneye#1360]
Hi,

without a mouseover tooltip, 0 sounds obviously = "disabled", but 1 and 2 are a bit confusing.
I suggest to modify the slider labels from 0/1/2 to Disabled/50Hz/60Hz or, as suggested [here](https://sourceforge.net/p/motion/mailman/message/35461294/):
- Ignore
- Disabled
- 50Hz
- 60Hz
- Auto

[Motion documentation](https://htmlpreview.github.io/?https://raw.githubusercontent.com/Motion-Project/motion/master/motion_config.html#vid_control_params) isn't exhaustive on this point, and the top-level source code loops pointing back to the documentation :)
```power_line_frequency``` is available in motion [since v3.4.1](https://github.com/Motion-Project/motion/blob/c43a56095e78a41e337010f8a1e016a4bf57014f/CHANGELOG#L216)

Piero

**Comment by ccrisan** [comment]
That option comes from `v4l2-ctl` as is and is not adjusted in any way by motionEye.
