### ISSUE TITLE
"Preferences - "Layout Columns" not visible and does not work on Safari

### ISSUE THREAD

**Issue by Pi-DD** [ccrisan/motioneye#1366]
I cannot change Layout Columns on Safari (iPad Air2, iPhone 6s, iOS 12.3.1) because it is not visible. Likewise FireFox on iOS. 

If I try on FireFox (Win 10) I can see it and change it, but the changes are not reflected in Safari.
First Picture from iOS Safari, second from Win10 Firefox

![Motioneye-Safari](https://user-images.githubusercontent.com/38586714/61067362-3c969400-a3ff-11e9-9ffb-97a5dfb1c02d.JPG)

![MotionEye-Firefox](https://user-images.githubusercontent.com/38586714/61067368-402a1b00-a3ff-11e9-96d7-4f2b76389fdb.JPG)

**Comment by zagrim** [comment]
I think this is by design. A comment in the UI code says "always 1 column when in full screen or mobile" (here "mobile" means having display width less than or equal to 1200 pixels).

**Comment by Pi-DD** [comment]
You are so right! The screenshots in the Wiki show it too, but are not super explicit.

My error of understanding!

Thanks
