### ISSUE TITLE
Upload to Google Drive Failing - FIXED

### ISSUE THREAD

**Issue by JBlyth** [ccrisan/motioneye#1373]
My uploads to Google Drive have been failing since yesterday, and I don't seem to be able to re-authorise the process.

Has Google changed something in their API since they disconnected Drive from Photos????

**Comment by JBlyth** [comment]
I found the problem... The SD Card was full!

I feel like a bit of an idiot for not realising it, but once the Rasbian system started to misbehave further, I was soon back in full operation by deleting some Security Camera images....

**Comment by zagrim** [comment]
Please close this issue if it's resolved.
