### ISSUE TITLE
Multiple issues with 0.40

### ISSUE THREAD

**Issue by RaspberryTech01** [ccrisan/motioneye#1385]
I am running the latest version of motionEye (0.40) on a Raspberry Pi 2B raspbian stretch (latest version) lite. No overclock, gpu split 256 mb. 

First issue:

The "Video Streaming" settings even when in the "off" position still control the preview of the camera from the admin interface.

Second issue:

My camera is working. When I change ANY settings, after clicking apply it says unable to open video device. How can I fix this?? (p.s. the only way I can fix this currently is if I switch to a different resoloution and then back again to the original one)

Edit: when a live preview is shown in the admin login, if I take a picture the picture comes out as "Unable to open device".

**Comment by darkplatinum** [comment]
<img width="1073" alt="Screenshot 2019-07-27 at 8 02 37 pm" src="https://user-images.githubusercontent.com/31044433/61998534-87740500-b0a9-11e9-901c-bcfe3f5be82f.png">
