### ISSUE TITLE
How do i use the command "sudo" on the Raspberry Pi Motion-Eye-OS?

### ISSUE THREAD

**Issue by bhvyaismeduh21** [ccrisan/motioneye#1389]
It gives me the error: "-sh: sudo: command not found".
Thanks for your time.

**Comment by bhvyaismeduh21** [comment]
The steps in the FAQ:

"mount -o remount,rw /
mount -o remount,rw /boot"

don't work.

**Comment by bhvyaismeduh21** [comment]
its

> The steps in the FAQ:
> 
> "mount -o remount,rw /
> mount -o remount,rw /boot"
> 
> don't work.

it gives me "mount: can't find /boot in /etc/fstab"

**Comment by jasaw** [comment]
Are you running motionEyeOS? There's no need to sudo on MotionEyeOS because admin user is root.

Where are you executing the mount command from? It will work on MotionEyeOS.

**Comment by bhvyaismeduh21** [comment]
I am running motionEyeOS. I was not aware of this. Thank you.

**Comment by bhvyaismeduh21** [comment]
thanks
