### ISSUE TITLE
Multiple Cameras

### ISSUE THREAD

**Issue by legotheboss** [ccrisan/motioneye#139]
Hi, 

I upgraded my motioneye software from 0.29 to 0.31.1. My motionEye server connects to two remote motionEye cameras. After the update, I am able to see one camera but unable to see my second camera on the main page... I am able to downgrade and return to the multi-camera view... Both my cameras are remote motionEye cameras. I have also set the settings to show 2 cameras in the layout... What is the solution to this?

**Comment by ccrisan** [comment]
Please try removing the cameras completely and adding them from scratch. Config file format has changed a bit and you may be facing some incompatibility issues.

**Comment by legotheboss** [comment]
@ccrisan I was able to fix it by updating all my cameras to the latest version. Thanks for your help!
