### ISSUE TITLE
Significant delay on wpa_supplicant.conf during boot

### ISSUE THREAD

**Issue by Elrendhel** [ccrisan/motioneye#1396]
Seeing a significant (approx 3 minute) delay on the boot of RPi Zero W once boot sequence lands on "WPA_Supplicant.conf" line.  It does eventually complete and Wireless WiFi works fine: I can access MotionEyeOS via static IP I assigned.  Just not sure if the substantial delay is a cause for concern, or if it is actually normal.

**Contents of wpa_supplicant.conf:**

ctrl_interface=DIR=/var/run/wpa_supplicant
update_config=1
country=US

network={
scan_ssid=1
ssid="myssid"
psk="mypassword"
}

**Comment by ccrisan** [comment]
@Elrendhel wrong project. You're looking for https://github.com/ccrisan/motioneyeos. Nevertheless, try the latest nightly build for the Zero and see if the problem persists.
