### ISSUE TITLE
Updating a docker installation with configuration preserved.

### ISSUE THREAD

**Issue by peterg10** [ccrisan/motioneye#1410]
I've looked through the Wiki documents but I can't find anything that describes how to update an existing installation and preserve the configuration. I don't mind if I need to pull a new docker image again and drop the configuration back into it.

Apologies if I've missed it.

**Comment by bob-lee** [comment]
@peterg10 afaik configurations files are untouched between installations.. which versions (from, to) are you trying to install on which hardware?

**Comment by kleini** [comment]
The guide for the Docker images mentions to use volumes for motioneye storage. This includes the configuration.
