### ISSUE TITLE
Docker Compose version 3.5

### ISSUE THREAD

**Issue by joseeduardoperes** [ccrisan/motioneye#1423]
Please update the docker compose to be compatible with docker compose file version 3.5

When I try to use on docker compose 3.5 I am getting the error:
Unsupported config option for services.motioneye: 'volumes_from'

**Comment by kleini** [comment]
Maybe you can upgrade that docker-compose.yml on your own a provide us your changes in a pull request.

**Comment by yurnov** [comment]
I think that this issue can be closed with [this commit](https://github.com/ccrisan/motioneye/commit/252432ad8e03f01a4141c577864f0f71fad0b639)

**Comment by ccrisan** [comment]
Closed via https://github.com/ccrisan/motioneye/commit/252432ad8e03f01a4141c577864f0f71fad0b639.
