### ISSUE TITLE
Should have an option to "Delete" when viewing a saved image/video

### ISSUE THREAD

**Issue by derekantrican** [ccrisan/motioneye#1425]
Currently delete for saved images/videos is only possible from the "list view". This should also be available from the "single view". IE these should be acceptable steps:

1. Click on camera in motioneye
2. Click on play button to view saved videos
3. Click on saved video to view it
4. Click "Delete" button

Also, once clicking the "Delete" button, the dialog should not go back to the list view, but should instead go to the "next newest" image/video (the same as clicking the "left arrow" on the image/video to navigate to the "next newest" image/video). If there are none left, then go to the list view.

This would make it very easy to clean up "false recordings". The workflow would be

1. Once in video list view, click on latest recording
2. Play recording
3. If false recording, click "Delete". If valid recording, click "<" (to go to next newest recording)

I see [the place to change this](https://github.com/ccrisan/motioneye/blob/dev/motioneye/static/js/main.js#L3645) but I'm not quite skilled enough with javascript to know what I'm doing

**Comment by zagrim** [comment]
Also requested in #1409, #1309 and #550 (but great that you also thought of what should happen _after_ deleting the currently displayed video).
