### ISSUE TITLE
Video stream not visible in main UI

### ISSUE THREAD

**Issue by rvdeijk** [ccrisan/motioneye#1428]
For some reason I'm unable to see my video streams in the main UI of motionEye..
When I grab the stream and open it for example in VLC it works fine. Also when I grab the streaming URL from MotionEye and paste into my browser and I fill in my credentials the stream works fine.

The console mentions the following message: Unchecked runtime.lastError: The message port closed before a response was received. What am I doing wrong? I already reinstalled motionEyeOS. I tested it with version 20190427 and version 20190619. In the past it worked fine. So I have no idea what have been changed..

The issue seems to be a bit simular to ticket: 1142. Altough I reinstalled everything and configured the cameras from scratch so there shouldn't be any blocking old configurations.

motionEye version: 0.40
motion version: 4.2.2
OS version: motionEyeOS 20190619
camera Hardware: Raspberry Pi 3+
![StreamNotVisible](https://user-images.githubusercontent.com/35557458/63649488-a7492800-c73e-11e9-8388-dc73346b7350.jpg)
![StreamNotVisible2](https://user-images.githubusercontent.com/35557458/63649543-22aad980-c73f-11e9-8a0f-1181794e4268.png)

**Comment by rvdeijk** [comment]
After reading some other issues it seems to be related to Chrome 76. When I disable this setting in chrome: chrome://flags/#enable-lazy-image-loading everything works fine. 

When will there be a new release, I don't like to use nightly's.

**Comment by bob-lee** [comment]
`0.41rc1` seemed working ok on chrome:
```
sudo pip uninstall motioneye
sudo pip install motioneye==0.41rc1
```

**Comment by virtuallight** [comment]
> After reading some other issues it seems to be related to Chrome 76. When I disable this setting in chrome: chrome://flags/#enable-lazy-image-loading everything works fine.
> 
> When will there be a new release, I don't like to use nightly's.

@rvdeijk Thanks for sharing. That fix worked for me as well 👍

**Comment by pentiumduck** [comment]
> After reading some other issues it seems to be related to Chrome 76. When I disable this setting in chrome: chrome://flags/#enable-lazy-image-loading everything works fine.

Just perfect. Thanks a lot !!
