### ISSUE TITLE
using æøå in camera name

### ISSUE THREAD

**Issue by MagnusRef** [ccrisan/motioneye#1453]
Hello,
I have just  set up motioneye, and was renaming my only network camera from "Camera 1" -> "Indkørsel"
Motioneye seems not to like Danish/Norwegian characters. gives me an error, no explanation.
"Indkørsel" just happened to mean driveway in danish.   
![image](https://user-images.githubusercontent.com/32013604/64912862-a0a64300-d735-11e9-9f03-56f3f01ce88f.png)

Edit: motionEye Version = 0.36.1 Motion Version = 4.0.1

**Comment by ccrisan** [comment]
Sorry but accented, non-ASCII characters are not allowed in camera name. Even if we allowed them here, there are many places where things could go wrong due to non-ASCII text.
