### ISSUE TITLE
Motion detection "suppression time"

### ISSUE THREAD

**Issue by MrPumo** [ccrisan/motioneye#146]
Please evaluate adding "suppression time" between motion detection. So after First detection for an amount of time next detection will not trigger.
THX a lot

**Comment by ccrisan** [comment]
This is something that the motion daemon needs to implement. It's not a motionEye related request. Most of the users are fine with the Event Gap settings.

**Comment by MrPumo** [comment]
Added as request to MrDave motion fork
https://github.com/Mr-Dave/motion/issues/101
