### ISSUE TITLE
thread-1.conf file is empty

### ISSUE THREAD

**Issue by jshridha** [ccrisan/motioneye#147]
I'm using a bit of a custom setup

I'm trying to add all configuration files (motioneye.conf, motion.conf, thread-x.conf) to a directory called /config

I chaged conf_path in motioneye.conf to point to this directory. Whenever I add a new camera, the thread-X.conf file is made, but it has very little info. This means the advanced configuration of the camera is diasabled and I don't have a way to enable it besides making the conf file manually.

This is what is in the conf file:

```
# @id 1
# @proto mjpeg
# @enabled on
# @name Camera1
# @url http://HIDDEN-FOR-MY-SECURITY

```

Any help would be great. Thanks!

**Comment by ccrisan** [comment]
If you're trying to add Simple MJPEG Cameras, you shouldn't expect anything more than a... well.. simple mjpeg camera. No motion detection will be done, no notifications, no streaming, no nothing. Please read the text that shows up in the Add Camera dialog when you add a new camera. I believe you'll want to add your camera as Network Camera.
