### ISSUE TITLE
Motioneye on raspbian not working 

### ISSUE THREAD

**Issue by iojienedy** [ccrisan/motioneye#1473]
Hello 

I have just installed motioneye on Raspbian following your instructions.
All went well , no error during the installation , motioneye service is up and running , but unfortunately  when I try to access it from the web browser it is not working . 

Please give me an advice . 

Thank you

**Comment by CRImier** [comment]
How exactly is it "not working", can you elaborate?

**Comment by iojienedy** [comment]
My mistake , I was expecting that the used port is 80. 
It is working fine if I use port 8765

**Comment by CRImier** [comment]
happy to hear that! please close the issue.
