### ISSUE TITLE
System time

### ISSUE THREAD

**Issue by Winki43** [ccrisan/motioneye#148]
Hi
How can I change system time? My System has a timestamp from 1970. :-(

**Comment by ccrisan** [comment]
I'm assuming this is about motionEyeMake sure your PI has access to the internet and that it can resolve domain names through a DNS server.

**Comment by Winki43** [comment]
Hi and thank you for this quick response.
Yes, it is motionEyeOS running on a PI. The PI is connected with my rooter via cable. What more can I do?

**Comment by ccrisan** [comment]
Have you set a static IP for your motionEyeOS?

**Comment by Winki43** [comment]
Yes. As I had connected my PI via WLAN systime was correct. Didn't try it again but will do on weekend.

**Comment by ccrisan** [comment]
When using static IP, make sure you set a correct DNS server. That's the most probable cause for this issue.

**Comment by bojanopatje** [comment]
Hi, I have the same problem, selected static IP, DNS as it is in terminal...
What I'm doing wrong?

![motioneyeos](https://user-images.githubusercontent.com/50545415/57582892-d5299a00-74ca-11e9-80cb-c1942df90ce4.jpg)
![Pi2 motioneyeos](https://user-images.githubusercontent.com/50545415/57582900-dbb81180-74ca-11e9-9815-dea433a0b0fd.jpg)

**Comment by jasaw** [comment]
@bojanopatje Your DNS server is outside of your subnet. Make sure your DNS server address is configured correctly, and your raspberry pi can ping your DNS server at 192.168.160.13

**Comment by bojanopatje** [comment]
Hi, thank you for response. The problem was in wifi file that I created following an tutorial from linustechtips. The problem was that I did not change county code.
https://pastebin.com/raw/WCedfA6s
Thank you again and sorry for problems :)
