### ISSUE TITLE
Allow more motion detection tuning options

### ISSUE THREAD

**Issue by hasbridge** [ccrisan/motioneye#15]
I am getting tons of false alerts from my outdoor cameras, due to tree shadows moving around in the wind. It would be nice to be able to specify a greater pixel change percentage than 20, as well as setting the noise level greater than 25%. Also adding support for the despeckle options would be nice, as well as the ability to upload a sensitivity mask image. Instead of trying to build a fancy interface to create a mask, my suggestion would be to have a simple file upload which takes a jpeg file, and on upload converts it to pgm format.

**Comment by ccrisan** [comment]
Motion detection mask is on the way.

**Comment by ektus** [comment]
Is there any progress on the detection mask project? I've got a wide-angle outdoor camera that's triggering lots of false motion recordings due to movement of trees in the field of view. I would like to mask the trees away to greatly improve this situation.

**Comment by DawsonLeBrown** [comment]
As Motion detection mask is already on the way, it's probably already been thought of or done, but it would be great if the current mask could be visualised through the camera preview - this way you will know that you have the mask set up correctly AND can confirm that the mask file you have created is covering the correct part of the image.
- btw, thanks for all your work on this.

**Comment by ccrisan** [comment]
Added in 0.34.
