### ISSUE TITLE
Video format

### ISSUE THREAD

**Issue by Winki43** [ccrisan/motioneye#150]
My video files appear with extension .avi.
Allthough I can not open them in any player. VLC reports unknown file format, VIDEO in Ubuntu reports unknown file format .undef.

**Comment by ccrisan** [comment]
Is this still an issue? Sorry for the late reply.

**Comment by Just-Incase** [comment]
Hello,

I just got to record video to USB, but with USB in Win 10 laptop, i cannot veiw .avi file.  My others videos play as they should.

Thanks!

Amazing software / OS!!!

**Comment by ccrisan** [comment]
The latest version offers the possibility to choose the video codec. It's a bit experimental and you should run some tests to see how it works, but it may be what you need.
