### ISSUE TITLE
"Invalid configuration file line: motion_binary" when ever anything is changed

### ISSUE THREAD

**Issue by nraygun** [ccrisan/motioneye#1517]
I get an "CRITICAL:root:failed to read settings from "/data/etc/motioneye.conf": invalid configuration file line: motion_binary" whenever I change any setting upon first boot of a freshly imaged SD card on my RPi3 with motioneyeos-raspberrypi3-20190911.img.
Any ideas?

**Comment by nraygun** [comment]
To reproduce the problem, all I did was create a new microSD using the image above, turned on SSH amd hit apply. The system rebooted and I get the error above.

**Comment by ccrisan** [comment]
Guys could you please try reproducing the issue with the *Expert Settings* section opened and see if the *Motion Binary* entry gets changed (by Chrome's autofill, for example) while you edit your options?

**Comment by ccrisan** [comment]
Fixed via https://github.com/ccrisan/motioneye/commit/2caacf7f899070fc169ecdad5bc066214c1d1712.

Also related: https://github.com/ccrisan/motioneyeos/issues/2147.
