### ISSUE TITLE
Google Drive location?

### ISSUE THREAD

**Issue by user150aa346** [ccrisan/motioneye#152]
ccrisan thanks for a cool program. Can you tell me what the syntax is for the Google Drive location? Thanks.

**Comment by ccrisan** [comment]
It's the common /path/to/folder syntax. Just make sure that the entire path actually exists on your GDrive.

**Comment by user150aa346** [comment]
Just to clarify which is the correct syntax from the picture attached?

/My Drive/Ipsecuritycam/Video
/Ipsecuritycam/Video
https://drive.google.com/drive/folders/xxxxxxxxxxxxxxxxx

I've tried all the variations and still no luck. Thanks.


Regards,
Mike
------------------------------------
Michael A. McKenna
(c) 339-237-2004
I ride to support cancer research:
*You can click this link to donate to my PMC ride
<http://www2.pmc.org/profile/MM0613>*

**Comment by ccrisan** [comment]
Please attach the picture here in github.

**Comment by user150aa346** [comment]
Sorry no attachment came thru.


Regards,
Mike
------------------------------------
Michael A. McKenna
(c) 339-237-2004
I ride to support cancer research:
*You can click this link to donate to my PMC ride
<http://www2.pmc.org/profile/MM0613>*

**Comment by user150aa346** [comment]
sorry, misunderstood what you meant. I've just uploaded to the github.


Regards,
Mike
------------------------------------
Michael A. McKenna
(c) 339-237-2004
I ride to support cancer research:
*You can click this link to donate to my PMC ride
<http://www2.pmc.org/profile/MM0613>*
