### ISSUE TITLE
motioneye starts motion?

### ISSUE THREAD

**Issue by xenpac** [ccrisan/motioneye#1522]
question:

On ubuntu, i installed motion with defaults to be run as a daemon
Then installed motioneye.

I wonder if motioneye does start/restart motion anytime config changes.
In this case there is no need to have motion already running as a daemon.??

Maybe you can clarify if the runstate of motion is controlled by motioneye.
thanks

**Comment by zagrim** [comment]
Yes, MotionEye starts and controls Motion, so you should probably not have Motion running as daemon in the first place. Did you follow the [Ubuntu installation instructions](https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu)?
