### ISSUE TITLE
camera buffering no video

### ISSUE THREAD

**Issue by om111** [ccrisan/motioneye#1534]
hi i just install the motion eye OS version 20180602 and my camera is buffering i have no idea what to do please help me out in this.
2) do i have to update the  OS to 2019011 and if i have to please help me how to do

**Comment by jasaw** [comment]
Are you using Chrome web browser? If yes, please update to the latest motionEyeOS. There was a change in Chrome that broke video streaming, which means video stream won't work on older motionEyeOS versions.
If you have physical access to the device, it's best if you reflash it with the latest image.

**Comment by JairajJangle** [comment]
Related #1449
