### ISSUE TITLE
No static images in browser

### ISSUE THREAD

**Issue by mekatum** [ccrisan/motioneye#1537]
Hi!

I have installed motioneye from PIP-repos on Centos 7. 

I go to web-interface and not see any static image on site. Buttons on site is work.

```
$ pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
$ python --version
Python 2.7.5
$ motion -h
motion Version 4.2.2
```

motioneye installed on VM (VM on server), I try from other client-machine with Firefox 70.0.1 and Chrome 78.0.3904.97

But static images can be opened if I enter address to image into address string.

[install_log.txt](https://github.com/ccrisan/motioneye/files/3832053/install_log.txt)
![screenshot](https://user-images.githubusercontent.com/16961803/68601015-8c23c400-04b4-11ea-8ab8-0a79af1040ca.png)

I do not know, may be you want any other logs?

Any way, thank you for your work!

**Comment by ccrisan** [comment]
Install mime-types.
