### ISSUE TITLE
Proposal: If the Mobile phone is in the WIFI Network then Motion Detection recording will Disable

### ISSUE THREAD

**Issue by girardpeter** [ccrisan/motioneye#1539]
I hope this option will be possible for the next update.

Explanation:
If the mobile phone device is connected in the wifi network then motion eye will stop/disable the recording.

If the mobile phone device is not connected in the wifi network then motion eye will activate/enable recording if there is motion detected.

**Comment by girardpeter** [comment]
also if the bluetooth from mobile phone is within the range of raspberry pi. the motion eye will not save motion. vice versa

**Comment by girardpeter** [comment]
Hi Cris,
Hope this will be available soon.

**Comment by klausmcm** [comment]
I'd love to see this feature too. Phone would act as an indicator of whether someone is at home or now. Could maybe provide an option to ping a device name/IP every so often?

**Comment by klausmcm** [comment]
Could do the symlink approach in #659 in the meantime.
