### ISSUE TITLE
Numeric camera names are not allowed

### ISSUE THREAD

**Issue by tomvleeuwen** [ccrisan/motioneye#1546]
I have different house numbers for each camera, without any prefix and postfix. With the new config file, MotionEye crashes. Either the conversion tool should add a prefix, or preferably MotionEye should accept numeric camera names.

My config file contains the following line:
`camera_name 11`
If I add a prefix it works fine again.

**Comment by zagrim** [comment]
I think I've seen this reported already earlier, but couldn't find the issue. But yeah, there should either be validation in the UI to block all-numeric names, or handling of the name fixed so that it is handled correctly.
