### ISSUE TITLE
"Authorization Key" This app has not yet been verified by Google

### ISSUE THREAD

**Issue by sk8darr** [ccrisan/motioneye#1557]
When i try to use Google Drive or Google Photo storage to upload media files and try to obtain key for authorization key y get this error:
"This app has not yet been verified by Google in order to use Google Sign in."

Info:
MotionEye Version : 0.41
Motion Version : 4.0

![image](https://user-images.githubusercontent.com/1724673/69820343-83c2cd00-11c6-11ea-8369-782b9f3ab379.png)

**Comment by ccrisan** [comment]
Duplicate of https://github.com/ccrisan/motioneye/issues/1541.
