### ISSUE TITLE
Take a picture with a USB camera via command line

### ISSUE THREAD

**Issue by tajohnsen** [ccrisan/motioneye#156]
First, thank you for this great project.  I'm having a lot of fun playing around with it!
My issue is that I have a USB camera pointing outside and the trees keep setting off the motion detection.  I used area_detect to isolate the trees but for the life of me I can't figure out what command to put after on_area_detected to take a picture with a USB camera..  I'm using motioneyeos on Raspberry Pi 2.

**Comment by ccrisan** [comment]
Not possible yet.

**Comment by ccrisan** [comment]
This could probably be solved using a mask.

**Comment by supremeliter** [comment]
Thanks for the reply. I don't need a full explanation but can you elaborate a little on what you mean by mask?

**Comment by ccrisan** [comment]
The mask feature has been introduced relatively recently and allows you to define areas that are excluded from motion detection. You can filter out trees or things that move on a regular basis in your camera field of view.
