### ISSUE TITLE
Error update motioneye

### ISSUE THREAD

**Issue by Ferrox12** [ccrisan/motioneye#1560]
Hello,
when I try to update my motioneye, the system returns me this message "The update process has failed!".
I've installed this release:

motionEye Version: 20170212
Motion Version: 4.0.1+git37b3595

Can you help me?

**Comment by zagrim** [comment]
Hi, you really should provide the output of the whole update process for anyone to be able to help, not just the end result.

**Comment by ccrisan** [comment]
You won't be able to upgrade from a version as old as 2017, due to significant differences in partition layout. Please write your OS image from scratch.
