### ISSUE TITLE
can't do much in setup_mode

### ISSUE THREAD

**Issue by Zixim** [ccrisan/motioneye#1584]
this is all i get at http://ip:8080/

![image](https://user-images.githubusercontent.com/7814664/71557827-f1734a80-2a4b-11ea-8651-a098cfd30542.png)

I get the feeling I'm missing something ?

**Comment by jasaw** [comment]
try http://ip:8765 ?
Check your `/etc/motioneye/motioneye.conf` file, find which port number has been configured. Default port number is 8765 I think.

**Comment by Zixim** [comment]
port 8765 runs fine, but that is beside the point.
I'm trying to get into setup_mode , as per [the wiki](https://motion-project.github.io/motion_config.html#setup_mode).

**Comment by kleini** [comment]
@Zixim Are you talking about motioneye or motion? Your link to the wiki points to an option of motion not motioneye. motioneye uses motion underneath but not motions setup_mode.
