### ISSUE TITLE
Not able to detect CSI Camera 

### ISSUE THREAD

**Issue by Mageschu** [ccrisan/motioneye#159]
Hi, i'm sorry to post a new issue with motioneye and the csi camera module. Motioneye isn't detecting the camera so i can really use some help.

I'm using a Pi 2 with:
- latest version of raspbian with already latest v4l-utils
- latest version of motioneye 
- using prebuild motion branch binaries out of your wiki link
- added bcm2835-v4l2 to the last line to /etc/modules
- enabled camera in raspi-config
- functional csi camera (tested with raspistill)

I can't use motioneyeOs cause there will be other running programms on raspbian after getting motioneye working with the camera.

Any ideas?

Thanks for your help!

**Comment by ccrisan** [comment]
See if `bcm2835-v4l2` is in the `lsmod` list. If not, see if you can manually `modprobe bcm2835-v4l2`. Do you have the `/dev/video0` device by the way?

**Comment by Mageschu** [comment]
Hi, thanks for helping. I forgot to note: I ran `modprobe bcm2835-v4l2` manually. Without checking `bcm2835-v4l2` in `lsmod`. I'll check the `/dev/video0` device later when i'm home again.

**Comment by Mageschu** [comment]
So the bcm2835-v4l2 is in the lsmod list and with ls -ltr /dev/video* i got this: crw-rw----+ 1 root video 81, 0 Mär 28 20:35 /dev/video0

**Comment by ccrisan** [comment]
Now I'm puzzled. How do you know motionEye doesn't see this camera? Can I see some screenshots? A log file? An error message, anything?

**Comment by Mageschu** [comment]
I made some screenshots / pictures.
![2016-03-29_22 07 37](https://cloud.githubusercontent.com/assets/18125578/14122257/3fb79518-f5fb-11e5-9a0f-a15c25aa7557.jpg)
![20160329_215927](https://cloud.githubusercontent.com/assets/18125578/14122263/4cb8ff04-f5fb-11e5-8b33-f647c8e7aa20.jpg)

**Comment by ccrisan** [comment]
If you click on Camera Type, do you have the "Local Camera" option?

**Comment by Mageschu** [comment]
I don't have any options to choose. 

If i change the port to 80 i'm getting the report, that the connection on port 80 refused.

**Comment by ccrisan** [comment]
Can you give me remote ssh access to your setup? There's something fishy going on I think.

**Comment by Mageschu** [comment]
I misunderstood your Question, sorry! I thought "Camera" was meant... Sorry :-) Klicking on "Camera type" i'll get two options:
1) Remote motionEye camera
2) MJPEG camera
There's no option called "local camera". Maybe someting went wrong during the installation? I have another Card with a freshly installed Raspbian Jessie... should i try to setup the whole system or do you think that will be wasting time? 
Remote ssh access is still on my to-do list to get to learn but it seems to be a simple task ;-)

**Comment by ccrisan** [comment]
I would like to try to debug this setup. We might find a real problem. Can you send me a screenshot of the UI with the settings menu opened?

**Comment by Mageschu** [comment]
Here it is
![20160330_183440](https://cloud.githubusercontent.com/assets/18125578/14149817/4372f106-f6a6-11e5-9cd3-c7a557a848c1.jpg)

**Comment by Mageschu** [comment]
Whatever happened during the first installation doesn't happened on the second one (other sdcard). It works fine =)

Do you still want to debug the first system? It seems to bei a local and no further existing problem.

**Comment by ccrisan** [comment]
Yes i really want to know what went wrong.

**Comment by ccrisan** [comment]
If you type `motion -h` on command line what do you get?

**Comment by Mageschu** [comment]
Command not found. Before typing the command i became root.

**Comment by ccrisan** [comment]
Well have you installed motion? :)
