### ISSUE TITLE
%f in web hook results in empty string

### ISSUE THREAD

**Issue by wimdecorte** [ccrisan/motioneye#1596]
I have this web hook used when motion is detected:
Using a POST (form)
https://myserver.com/api/webhook/v1/motioned/catch?file=%f&host=%{host}

The web hook api sees the incoming as:

![2020-01-03_15-57-19](https://user-images.githubusercontent.com/5022743/71748882-e51f3100-2e41-11ea-8591-e513f5a45a16.png)

As per the motion documentation (https://motion-project.github.io/motion_config.html#conversion_specifiers) I would expect %f to give the full file name and path.
If I change "f" to "F" I get the part of the file name without path or extension.

**Comment by wimdecorte** [comment]
This is with:
motionEye Version	0.42
Motion Version	4.2.2
OS Version	Raspbian 10

**Comment by ccrisan** [comment]
That's using `on_event_start` behind the scenes which doesn't accept `%f`. At that time, the file might not be created at all, let alone being fully written. Also, it might be a movie, a jpeg, both, or none.

See if *File Storage > Call A Web Hook* works for you. Worst case scenario, use *File Storage > Run A Command* and provide your own shell script.
