### ISSUE TITLE
leak option to add new camera 

### ISSUE THREAD

**Issue by ronboni** [ccrisan/motioneye#1598]
hi guys,
first- 10x for the great "motionEye" app !!!

i installed the app on raspberry pi 3b
after installation, when i tried to add new camera i got leak option 
only : "remote motionEye camera"  and "simple MJPEG camera" available
the " network camera" option disappear
![leak options](https://user-images.githubusercontent.com/59505524/71766000-9f2aa180-2f03-11ea-98ff-361f3336a524.png)

10x for help

**Comment by ccrisan** [comment]
Install Motion.
