### ISSUE TITLE
Too many bare exceptions in the codebase

### ISSUE THREAD

**Issue by cclauss** [ccrisan/motioneye#1599]
Bare exceptions are strong discouraged in PEP8 for good reasons...
https://realpython.com/the-most-diabolical-python-antipattern

To find all instances try __flake8 . --select=E722__

**Comment by ccrisan** [comment]
Fixed via https://github.com/ccrisan/motioneye/commit/181312e3588a25a132c0ab9dabbe24c674a87fe1.
