### ISSUE TITLE
Compatibility with Micro USB OTG port?

### ISSUE THREAD

**Issue by mrymont** [ccrisan/motioneye#160]
Hello,

I own a Banana Pro board and was interested in using the Micro USB OTG port with an OTG to female USB converter and a USB camera. So OTG port->converter cable->usb camera. I know the Banana .iso file is not specifically created for the Banana Pro, but I was wondering if there was any compatibility with this unique port using a special configuration. Thank you for any information you can provide and feel free to delete this if this is not an intended feature for MotionEye.

**Comment by bovine** [comment]
I think you intended to open this against this instead:
https://github.com/ccrisan/motioneyeos
