### ISSUE TITLE
Slow load times when loading movies for a camera

### ISSUE THREAD

**Issue by rakeshdas1** [ccrisan/motioneye#1605]
I'm using motionEye v0.42 in a docker container and I'm having an issue when I am loading a camera's movies. I have my camera set to record whenever it detects motion and has about 200 movies on it across 5 days. When I press the movies browser button to view the recorded snippets, it takes on average 1.7 mins to retrieve the list of recorded events and show it on the list according to the Chrome Dev Tools. 

Is there anyway to improve this metric?

Currently, I've set motioneye to record to a folder on the machine which is an NFS share on an SSD

**Comment by dtbaker** [comment]
I have the same issue here, takes minutes to pull back recent recordings. I think it's because motioneye has to look at the filesystem for recent videos instead of querying a database.
