### ISSUE TITLE
Can't get RTSP stream

### ISSUE THREAD

**Issue by Kallagan99** [ccrisan/motioneye#1606]
hello Motioneye team

I just installed Motioneye for the 1st time on a Debian Stretch.
I've got 3 different cameras.
Vivotek/Noname/Revotech
No issue with the 2 first ones.

With the last one (Revotech - NVSIP clone), **I can't get the stream through MotionEye**.
The RTSP adress is
rtsp://login:pass@ip:5544/live0.264
I have no pbme to get it correctly using VLC.
I can see this camera with "ONVIF Device manager" and get the stream also.

The camera can be added into MotionEye, recognized as a RTSP/TCP camera (tried with some no_tcp option, didn't fix my issue). But I've no stream displayed.

Can someone help me ?
Thx !

Kallagan

**Comment by bakerm99** [comment]
Hello,

Firstly i love this project and its helped me out massively thank you.

I had the above problem and i found the solution via another application.

In a nutshell i had to use the following layout

rtsp://192.168.1.18:554/stream0?username=admin&password=????????????

The ip address comes first then the user details. to ensure the connection works use the same program i did https://sourceforge.net/projects/onvifdm/

Use the link provided in OnvifDM in Motion n > add the camera as a network camera and away you go

Hope this helps
