### ISSUE TITLE
Dual cameras + Equal resolutions results in no stream 

### ISSUE THREAD

**Issue by PedroC1999** [ccrisan/motioneye#1609]
Hello, 

I bought two 1280x1024 camera sensors off of eBay for cheap and I am using them as cameras for MotionEye on an RPI3B.
Individually they work fine at their rated resolution and framerate, however when paired together, they cannot be set to the same resolution without causing both cameras to fail. Dropping the resolution 1 step lower results in both camera feeds coming back to life. 

They are connected straight to the Pi with no USB hub joining them. 

My goal is to have both cameras running at their highest resolution at the same time

**Comment by zagrim** [comment]
RPi3 might not have enough CPU power to be able to decode the feed coming from both of the cameras and again encode it for streaming and/or saving as video. If you don't want to use any lower resolution, you could try with halving the framerate to see if that could work for your purposes. If that doesn't work for you then I'd just suggest getting another RPi for the other camera, or getting something with more CPU capacity instead to do the job.

**Comment by PedroC1999** [comment]
Even at 1fps it doesn't work with both 

It appears to be a genuine bug

**Comment by zagrim** [comment]
Could you please provide some logs (Motion + MotionEye), tell which versions of Motion and MotionEye you're using, and also check the CPU load of the RPi?
