### ISSUE TITLE
smb.conf file - write permission wanted

### ISSUE THREAD

**Issue by muznz** [ccrisan/motioneye#161]
Hi There,

I loaded motioneyeos image onto my raspberry pi3 and everything works fine.
Except one seemingly simple thing.  I want to change the workgroup in the smb.conf file.
I'm logged in as root and using nano can open smb.conf but I only have read permission.  I've tried everything to get write permission but to no avail.  I have access directly in pi3 using mouse keyboard & monitor. Plus Putty & FTP access from my Windows10 PC.  I have even changed the workgroup on my PC to MOTIONEYE hoping this will help 

How do I get write permission to smb.conf

Thanks muznz

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#why-do-i-get-read-only-file-system-when-trying-to-edit-a-file
