### ISSUE TITLE
Is motionEye available in OpenWrt?

### ISSUE THREAD

**Issue by probonopd** [ccrisan/motioneye#1614]
Is motionEye available via `opkg` in OpenWrt?

**Comment by kleini** [comment]
I don't think, that hardware underneath of OpenWrt router software is powerful enough to decode video streams. It is not available and maybe does not even make sense to think about porting it there.

**Comment by probonopd** [comment]
OpenWrt can run on hardware such as generic x86_64 and various powerful ARM platforms. So it may well be worth a try. The `motion` daemon runs rather well on it.

**Comment by kleini** [comment]
Okay, then it may make sense if the `motion` daemon runs well. But the answer remains the same, that it is currently not available. But motioneye is only Python 2. Get Python 2 running on OpenWrt and then motioneye should not be a problem any more and the guides for other Linux distributions should fit somehow.
