### ISSUE TITLE
Why streaming settings matter when streaming is off?

### ISSUE THREAD

**Issue by lutierigb** [ccrisan/motioneye#1619]
I've got *Video Streaming* off in MotionEye but I noticed the *Streaming Frame Rate* dictates the capture(???) fps(the y in "x/y fps" overlay). why? isn't that the frame rate for streaming only? I'm not streaming.

Also, noticed that motion detection is affected, usually delayed, if the Video Streaming option called *Motion Optimization* is on. I figured that Motion Optimization will result in capturing 1 fps when there is no motion and that delays the Motion Detection systems due to the low fps.

Another thing I noticed is the presence of several stream_* options in the camera config file even when streaming is turned off, which possibly explains why those setting are affecting the experience. For example, with Video Streaming turned off and applied:

```
% grep -in stream_ camera-1.conf 
33:stream_quality 85
40:stream_maxrate 10
42:stream_localhost on
50:stream_port 8081
52:stream_auth_method 0
62:stream_motion off
66:stream_authentication user:
```

Is MotionEye turning on streaming for its own benefits? 

versions:

motionEye Version | 0.42
Motion Version | 4.2.2
OS Version | Linux 4.15.0-70-generic

Lovely project, btw!

**Comment by Pi-DD** [comment]
See...
https://github.com/ccrisan/motioneye/issues/1641

For another situation I have found where streaming parameters affect things unexpectedly.
