### ISSUE TITLE
Extreme cpu usage on rpi3

### ISSUE THREAD

**Issue by zettam** [ccrisan/motioneye#162]
I've been using motion with 3 web-cams connected to my raspberry pi 3. They work fine with 30 fps streaming (all working at the same time). I made a custom web page to display all of the videos on a single web page so it's soft of like a camera-view panel. However than I realized this will be too much work to built a console/panel from scratch and started looking for an alternative.
 That's how I found motioneyeos and motioneye.

I set it up, now it's running on myraspberry pi. I've added two cameras, and made up their settings to stream with 30 fps. I've took both sliders to 30 fps and saved.

However, the streams are pretty slow, around 1-5 fps most of the times. I've realized the cpu usage of the motioneye is extreme compared to barebones motion.

Am I missing a step here? I would love to know how to configure this properly if this is a configuration error.

I don't need video recording features, I just want to see from the cameras in real time that's all... If something I don't know is causing this slow down I would love to learn what it is and configure motioneye in a way that this does not happen.

The software looks promising, thank you for that as well.

**Comment by ccrisan** [comment]
Other users have reported performance issues with motionEyeOS and RPI3. I'll look into it.

**Comment by zettam** [comment]
Thank you.
