### ISSUE TITLE
Motion.conf blank

### ISSUE THREAD

**Issue by Saku241** [ccrisan/motioneye#1623]
Hello, 
Due to a bug, my 'motion.conf' in 'etc/motioneye/' is blank. 

Can someone send me his file ? Thanks

**Comment by zagrim** [comment]
The default contents for one camera are like this:

```
# @enabled on
# @show_advanced on
# @normal_password 
# @admin_username admin
# @admin_password 
# @normal_username user

webcontrol_port 7999
setup_mode off
webcontrol_parms 2
webcontrol_localhost on

camera camera-1.conf

webcontrol_interface 1
```

Would you care to share what bug you are talking about, so it could perhaps be fixed? Or did you have your own scripting modifying that file?

**Comment by Saku241** [comment]
Thank you !

Actually I just added a second camera and after a moment I tried to reconnect and it said Invalid Creditentials so I Check motion.conf and it went blank mysteriously

**Comment by zagrim** [comment]
Uh, that sounds like something not easily reproducible. Do you have the logs on that time still available? Was it anyway able to add the second camera?
