### ISSUE TITLE
Error doing a pip upgrade

### ISSUE THREAD

**Issue by stuartbloom** [ccrisan/motioneye#163]
hi there.  I am running 0.30; today I ran:

pip install --upgrade motioneye

However it seems to have experienced an error.  the pip.log file, renamed .txt, is attached.

Any ideas?

Thanks

Stuart

[pip.txt](https://github.com/ccrisan/motioneye/files/199723/pip.txt)

**Comment by ccrisan** [comment]
Well it's pretty clear that you don't have permissions to upgrade:

    OSError: [Errno 13] Permission denied: '/usr/local/bin/meyectl'

Did you run this as root (with sudo)?

**Comment by stuartbloom** [comment]
Oops, you are absolutely correct, sorry; must have been in weekend mode early
