### ISSUE TITLE
Adding Camera name to Filename

### ISSUE THREAD

**Issue by jonvic1891** [ccrisan/motioneye#1631]
Hi, Ive tried searching for how to add the camera name into the file name but without success. I have a FTP set up where i need all files landed in the same directory for the watcher to pick them up therefore i cant use subfolders but I need to know what camera the image came from. I have tried adding cam1-%Y-%m-%d/%H-%M-%S but this doesnt create the file with that name in the ftp just the %Y-%m-%d/%H-%M-%S.  when i enable sub folders I see it create a folder of cam1-date/time but the files inside do notcontain the cam1 pre-fix.

**Comment by rpitns** [comment]
Not sure if this will work for FTP as I'm using Samba.
The format I'm using for the directory is:
`motioneye/%Y/%m/%d/Corridor1_%H%M%S`
This gives me the following directory
`/mnt/SambaSharePi/motioneye/2020/03/12`
and a file name of
`Corridor1_01-36-01.jpg`

The FTP address seems to be
`ftp://camera01/storage/motioneye_192_168_1_22_samba_pi_pi/motioneye/2020/03/12/`
