### ISSUE TITLE
camera video permission

### ISSUE THREAD

**Issue by bakerm99** [ccrisan/motioneye#1632]
Hello,

Using this guide "https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu" everything is working perfectly........ 

just one hiccup and i bet its a permission thing :) camera feed (RTSP Stream)

what are the permissions required for the camera videos to be saved to the local disk also is there a set user?

Apologies in advance for such a simple question

**Comment by zagrim** [comment]
MotionEye runs as user "root" by default, so it should've access pretty much everywhere. However, it's worth checking if the folder set as storage location has write permission since something might actually check that.
If that doesn't help, you should probably post your motioneye/motion logs here.
