### ISSUE TITLE
Cannot open video device or no video device available

### ISSUE THREAD

**Issue by donatom805** [ccrisan/motioneye#1645]
I have used motioneyeOS before and had no trouble getting it up and running on Raspberry Pi 3B.

Recently I purchased a RP 4B and hooked up the same compatible camera that I used on the RP 3B.
I am now using Raspbian Buster full version with motioneye app. I have activated video using raspi-conf, have added the bcm2835-v4l2 driver to /etc/modules and increased RAM to GPU to 256 megabytes.

I can use the attached camera to produce still shots, so I know that the camera works, but whenever I start up motioneye on a browser, I get an error stating that "cannot open video device".

I followed the wiki to install motioneye and everything went smoothly.

Here is the output from journalctl:

[motioneye.log](https://github.com/ccrisan/motioneye/files/4217634/motioneye.log)

**Comment by Heisenberg389** [comment]
![image](https://user-images.githubusercontent.com/42702949/76557393-80c3c200-64c1-11ea-91d2-b08b0e6f09ca.png)
@donatom805 if you have a USB camera, try selecting a UVC camera instead of bcm2835-codec-decode.

**Comment by donatom805** [comment]
Thanks, @Heisenburg389. I got it to work. I made a very basic mistake: I
neglected to select the proper (attached) camera. Once I did that, it
worked well. I couldn't find my thread, so I wasn't able to note this on
the thread.
