### ISSUE TITLE
Remote motioneEye Camera - authentication failed

### ISSUE THREAD

**Issue by k-redas** [ccrisan/motioneye#1646]
Hi,

I would like to install motioneye sytem with multiple Raspberry pi (zéro, rpi3). I installed motioneye in each of them with one camera (usb).
One of them is the "server" where i would like to agregate all camera.
And when i would like to add a remote motionEye camera on my Raspberry, i have a message which said : "authentication failed".
![image](https://user-images.githubusercontent.com/57940928/74721864-5111f900-5238-11ea-81ce-79b8e6ba20b2.png)

Have you some ideas about this issue ?
Thank you

**Comment by k-redas** [comment]
The problem is solved,

In fact, this device (cam) dont support 5Ghz wifi, but only 2.4Ghz. So you must use the 2.4Gz network wifi at home and you must configure the wpa_supplicant.conf like this :

country=FR
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1

network={
    ssid="xxxxx"
    psk="xxxxx"
    key_mgmt=WPA-PSK
}

**Comment by jakepals** [comment]
I'm experiencing the same issue. However, I'm not on wifi. My machine is connected via ethernet.
