### ISSUE TITLE
Google Drive Permission Scopes

### ISSUE THREAD

**Issue by gordol** [ccrisan/motioneye#1651]
Basically...

Motioneye wants this:
> See, edit, create, and delete all of your Google Drive files

But this is possible:
> View and manage Google Drive files and folders that you have opened or created with this app

The scopes of allowance are entirely different.

I see no reason that motioneye needs full access to Google Drive just to manage some folders/files.

Currently it's using v2: https://developers.google.com/drive/api/v2/about-auth#OAuth2Authorizing

Any plans to go to the current v3?

Check out the scopes here, though, for v3: https://developers.google.com/identity/protocols/googlescopes#drivev3

Regardless of v2 or v3, why can't we use an app folder?
https://www.googleapis.com/auth/drive.appfolder

I know a normal google drive user cannot browse their app data folders... so that complicates things... but can't we just implement our own file browser?

The only way around the issue, otherwise, is with a service account just for motioneye, and one could do normal Google drive folder sharing between accounts...but most people won't go through that trouble.

Think of a tool like rclone, though. It only has access to its own files... and it's still a useful tool, because it encapsulates the mechanism for both sending and retrieving the files. Can we do the same?

**Comment by lucabiasotto** [comment]
I agree with you Thomas!

How do you perform the Google Drive login in MotionEye using service account?
