### ISSUE TITLE
Feature request: Delete button in play mode

### ISSUE THREAD

**Issue by kbfifi** [ccrisan/motioneye#1657]
Hi

Great project!! I hope this is the place to do requests too. To get in "play mode": click camera view->play button->click recorded video. Now that you have the option to play, pause, close and download, it would really be convenient to be able to delete the current recording. 

At the moment you need to remember te recorded timestamp then close the dialog and lookup the recording again

I'm using Motioneye Version 0.42 in the docker image on a Rock64 SBC with Ubuntu bionic

**Comment by zagrim** [comment]
Also requested in #1425 and several others.

**Comment by petrbrown** [comment]
---------- Forwarded message ----------
