### ISSUE TITLE
Added wrong url in webhook

### ISSUE THREAD

**Issue by Keldandorin** [ccrisan/motioneye#1661]
Added following url in File Storage webhook
**http://node-red.domain.com/motioneye?path=\\10.1.15.172\sdcard\Camera1\%Y-%m-%d\%H-%M-%S.jpg;Name=%Y-%m-%d\%H-%M-%S.jpg**

Guess its the **;** before Name that made it happen.

Made motioneye to say I have not added any cameras anymore

**Comment by ccrisan** [comment]
Unfortunately the `;` is going to cause problems, no matter what we do about it. It's the commands separator. I recommend using the URL-encoded value `%3B` instead.

**Comment by zagrim** [comment]
@Keldandorin In case you hadn't done that already, you can get the missing cameras back by manually editing `motioneye.conf` and finding that setting and removing the part starting with the semicolon `;`.
