### ISSUE TITLE
snapshot url, can i use it without authentication?

### ISSUE THREAD

**Issue by dennishd** [ccrisan/motioneye#1664]
Hi,

I installed MotionEye and I love it, it works simple and fast!

i'm trying to integrate the snapshot feed into the iSmartGate so i can monitor if the garagedoor is opened or closed. I can only use the snapshot url, but this isn't working. the url works on different devices (like ipad/iphone) the time/date is set to the same time zone and the time is the same. 

is it possible to create a url without authentication/token? like as it is possible with the streaming url?

Regards, Dennishd

**Comment by ccrisan** [comment]
@dennishd the snapshot URL includes a signature that is valid regardless of the timestamp. You should be able to use it on any device having any time zone or date/time setting.
