### ISSUE TITLE
Unable to add remote motionEye Camera - RPi4B with Raspbian Buster

### ISSUE THREAD

**Issue by scottc42** [ccrisan/motioneye#1668]
MotionEye is not allowing the addition of remote motionEye cameras.  When I try I get the message at the top of motionEye "An error occurred. Refreshing is recommended.".  Refreshing the browser (FireFox version 74.0 (64-bit)) does not resolve the issue.

Note that I am able to add a local V4L2/USB camera.  On the remote systems, I am able to add the RPi4B/Buster system's camera. 

Local system:
Hardware: RPi4B
OS: Raspbian Buster (Raspbian 10) 
motionEye version: 0.42 
motion version: 4.2.2

Remote systems (3):
Hardware: RPi2B, RPi3B, RPi3B+
OS: Raspbian Stretch (Raspbian 9.11)
motionEye version: 0.42 
motion version: 4.2.2

**Comment by sorriso93** [comment]
for me the problem was no space on sd card...
