### ISSUE TITLE
thumbnails not removed.

### ISSUE THREAD

**Issue by zajc3w** [ccrisan/motioneye#1669]
After deleting video files all thumbnails are left behind

**Comment by zagrim** [comment]
I could reproduce this. It seems that when deleting a movie file group ("delete all") no thumbnails are deleted specifically, contrary to the case when deleting only a single movie. If there were no snapshot pictures, thus leaving only thumbnails around after deleting all movies, then also "delete all" should delete the remaining thumbnails (but I didn't actually test this in practice).

I guess omitting of thumbnail removal has either been a mistake or premature optimisation, but I'll create a PR soon with a fix.
