### ISSUE TITLE
Issue with light

### ISSUE THREAD

**Issue by trainspotta** [ccrisan/motioneye#167]
I'm using motioneye for a while now an ccrisan helped me to fix all my issues faster than any company I know! I'm really really grateful for that! Thanks mate!

I'm so sorry but I have to bug you with another issue. I tried a lot of configurations but I constantly get mails because of light changes comming from the windows. Like 200 Mails a day and that is quite annoying. I tried every sensitivity and every bit of light switch detection but nothing helps.

Any tipps?

Regards!
Björn

**Comment by ccrisan** [comment]
Not really. You should seek help on forums related to the motion daemon.
