### ISSUE TITLE
Feature request: Motion mask per time span

### ISSUE THREAD

**Issue by kbfifi** [ccrisan/motioneye#1677]
I'd love to have this possible:
setup a specific motion  mask per time span

This way one could detect different objects per time of day

**Comment by lacojim** [comment]
You could possibly use a script with a cron job to change out the masks at a given time. The masks are saved in /etc/motioneye. Just rename them and cronjob the files for the given time.

**Comment by kbfifi** [comment]
Perfect! Thanks for the tip!
