### ISSUE TITLE
Docker is not building 

### ISSUE THREAD

**Issue by FredClement91** [ccrisan/motioneye#1678]
If that can help improving the product, I get following error when building the docker :

> Step 9/16 : RUN pip install motioneye==$MOTIONEYE_VERSION
>  ---> Running in 12c4b5fd110f
> Downloading/unpacking motioneye==0.37
>   Running setup.py (path:/tmp/pip_build_root/motioneye/setup.py) egg_info for package motioneye
>     
> Downloading/unpacking tornado>=3.1 (from motioneye==0.37)
>   Running setup.py (path:/tmp/pip_build_root/tornado/setup.py) egg_info for package tornado
>     /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
>       warnings.warn(msg)
>     
>     warning: no files found matching '*.yaml' under directory 'demos'
>     no previously-included directories found matching 'docs/build'
>     warning: no files found matching 'tornado/test/README'
> Downloading/unpacking jinja2 (from motioneye==0.37)
> Downloading/unpacking pillow (from motioneye==0.37)
>   Running setup.py (path:/tmp/pip_build_root/pillow/setup.py) egg_info for package pillow
>     Traceback (most recent call last):
>       File "<string>", line 17, in <module>
>       File "/tmp/pip_build_root/pillow/setup.py", line 304
>         yield from self.features
>                  ^
>     SyntaxError: invalid syntax
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
> 
>   File "<string>", line 17, in <module>
> 
>   File "/tmp/pip_build_root/pillow/setup.py", line 304
> 
>     yield from self.features
> 
>              ^
> 
> SyntaxError: invalid syntax
> 

Sadly, I am not an python expert at all and I don't know what it means.

**Comment by kleini** [comment]
motioneye 0.37??? This is completely outdated. We're today now at version 0.42. You should update your cloned source code repositories.

**Comment by FredClement91** [comment]
Thanks for your reply,

Sorry, I will do that indeed.

Fred
