### ISSUE TITLE
motion log many warnings/errors

### ISSUE THREAD

**Issue by hgestel** [ccrisan/motioneye#168]
While evaluating i got a lot of warnings (errors) while the system is working well.

 Non-streaming camera (keep-alive not set)
[2] Content-length present
[1] Non-streaming camera (keep-alive not set)
[1] Content-length present
[1] Non-streaming camera (keep-alive not set)
[1] Content-length present

When it stops collecting the message in syslog is :+1: 
netcam_init_jpeg: no new pic, no signal rcvd

where do I have to look to get the plenty of messages solved?

**Comment by ccrisan** [comment]
Yeap I might need to reduce the log level even further as many things are treated as warnings whereas they occur so often that they should be treated as plain info or even debug messages.

**Comment by ccrisan** [comment]
This should no longer be a problem with recent motion versions.
