### ISSUE TITLE
Is there a way to install and run motioneye on MacOS ?

### ISSUE THREAD

**Issue by danch99** [ccrisan/motioneye#1681]
Hi,

Just wondering, I have a Mac mini as a server and several pi zero with cameras and motioneyeOS, I’d like to install motioneye on the mac to use it as a motioneye hub.
Is there a way to install motion eye on Mac OS as it’s linux based ?

Thanks

**Comment by shaynethiessen** [comment]
You could use the docker image.

**Comment by runestate** [comment]
Does not work for me: If I run the docker-compose file, access the UI (http://localhost:8765/) and try to add a running pi zero/motioneye, then i get an error "an error occurred".  From the logs it looks like the remote zero. itself is requesting video config from the local (mac) machine, which then fail's with "Failed to open /dev/video0: No such file or directory".
