### ISSUE TITLE
i5-6600T hwaccel help

### ISSUE THREAD

**Issue by ceeeru** [ccrisan/motioneye#1682]
Hello motioneye-users!
First of all: sorry for my terrible english :)
I have a little problem with hwaccel on my setup, maybe here somebody can help me.
Hardware: Lenovo M700 tiny with Intel(R) Core(TM) i5-6600T CPU, Intel B150 chipset.
Debian buster headless, up to date.
motion version: 4.3.0+git20200307-4eab1d4
motioneye version: 0.42
As I know this is libmfx and vaapi-capable on decoder and encoder side too, and ffmpeg can use vaapi.
I added 7pcs of cameras:
4pcs HD720 (1280x720), name it 'small'
3pcs HD1080 (1920x1080), name it 'big'

My questions:
-2 small cameras has no motion-detection or recording setup, motion only re-streaming them to http port. Their setup need hwaccel too? In this conversion (rtsp to http) hwaccel can help me?
-2 small cameras and 3 big cameras has motion-detection ,recording to internal storage and re-streaming to http port too.
 How can I set up the hardware acceleration on them correctly (as I know in this 5 cams needed to encode and decode the stream to make motion detection)?
 The CPU is working on 65-70%, and the GPU (as intel_gpu_top says) is idle.
 Camera configs (camera 1-4 =small, camera 5-7 =big)
(cat /proc/cpuinfo, ffmpeg -hwaccels, ffmpeg -encoders, ffmpeg -decoders, cat /etc/motion/motion.conf, cat /etc/motioneye/motion.conf and camera configs are attached)
Thanks for Your help:
Sincerelly:
Norbert
[cpuinfo.txt](https://github.com/ccrisan/motioneye/files/4399659/cpuinfo.txt)
[etc-motioneye-camera-1.conf.txt](https://github.com/ccrisan/motioneye/files/4399660/etc-motioneye-camera-1.conf.txt)
[etc-motioneye-camera-2.conf.txt](https://github.com/ccrisan/motioneye/files/4399661/etc-motioneye-camera-2.conf.txt)
[etc-motioneye-camera-3.conf.txt](https://github.com/ccrisan/motioneye/files/4399662/etc-motioneye-camera-3.conf.txt)
[etc-motioneye-camera-4.conf.txt](https://github.com/ccrisan/motioneye/files/4399663/etc-motioneye-camera-4.conf.txt)
[etc-motioneye-camera-5.conf.txt](https://github.com/ccrisan/motioneye/files/4399664/etc-motioneye-camera-5.conf.txt)
[etc-motioneye-camera-6.conf.txt](https://github.com/ccrisan/motioneye/files/4399665/etc-motioneye-camera-6.conf.txt)
[etc-motioneye-camera-7.conf.txt](https://github.com/ccrisan/motioneye/files/4399666/etc-motioneye-camera-7.conf.txt)
[etc-motioneye-motion.conf.txt](https://github.com/ccrisan/motioneye/files/4399667/etc-motioneye-motion.conf.txt)
[etc-motion-motion.conf.txt](https://github.com/ccrisan/motioneye/files/4399668/etc-motion-motion.conf.txt)
[ffmpeg-decoders.txt](https://github.com/ccrisan/motioneye/files/4399669/ffmpeg-decoders.txt)
[ffmpeg-encoders.txt](https://github.com/ccrisan/motioneye/files/4399670/ffmpeg-encoders.txt)
[hwaccels.txt](https://github.com/ccrisan/motioneye/files/4399671/hwaccels.txt)

**Comment by peturdainn** [comment]
I'm in a similar boat, but trying to figure out how to pass the correct decoder.
I see you are using

movie_codec mp4:h264_omx

which is (AFAIK) controlling the *encoder*, to configure the *decoder* you probably need to change:

netcam_decoder <codec>

As I said, haven't got this working yet as I stumbled on your post while investigating this
