### ISSUE TITLE
JPG Url

### ISSUE THREAD

**Issue by helmar74** [ccrisan/motioneye#1684]
Hi,

I want to use a motioneyeos cam with a Fritzbox based door intercom system.
The problem is, that the fritzbox requires an URL with .jpg on the end for live cam pictures, which are shown on a FritzFon.
The URL of a snapshot picture unfourtnately doesn't have a file extension.
So is there a possibilty to get the URL of a "current picture" with a file extension?

Example URL, how it should look like:
http://IP_OF_CAM:PORT/current.jpg

Thanks a lot 

Helmar

Here's a Screenshot of the Fritzbox confíguration dialog:
![image](https://user-images.githubusercontent.com/25499089/77894491-a4368d00-7275-11ea-8e7a-c86b2558c359.png)

**Comment by ccrisan** [comment]
You'll need to use a reverse proxy server, such as Nginx if you want to change URLs.
