### ISSUE TITLE
Cannot reach web ui

### ISSUE THREAD

**Issue by lukasig** [ccrisan/motioneye#1686]
Hi
i did a fresh install of motioneye in raspbian buster lite on a rpi4 using [these instructions](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian).
I got no errors whatsoever, but i cannot reach the web gui. In fact i scanned all ports using fing and only port 22 (ssh) seems to be open.

any help is appreciated
thanks

**Comment by digiltd** [comment]
check to see if it is running using `systemctl status motioneye` if it is stopped, then `systemctl start motioneye`

**Comment by lukasig** [comment]
I figured it out...

Raspbian buster uses Python3 as default, and i did not adapt commands to `pip2` while installing.
