### ISSUE TITLE
about motion eye in raspberry dont command in terminal

### ISSUE THREAD

**Issue by adsports** [ccrisan/motioneye#1689]
hello i have installed the versions
motioneyeos-raspberrypi-20190911.img
motioneyeos-raspberrypi3-20190911.img
I can see the local camera as on the internet, but in the raspi I cannot enter basic commands sudo raspi-config or passwd does not work, it is still admin without password
when I enter the local address for example 192.168.1.12 and change the network parameters or advanced and restart the raspberry no longer works, on the command line it only comes out
/data/etc/motioneye.conf: invalid configuration line: motion: binary

thanks for support

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-cant-seem-to-find-apt-get-or-any-other-package-manager-what-gives.
