### ISSUE TITLE
Save last recorded image

### ISSUE THREAD

**Issue by maxholgasson** [ccrisan/motioneye#169]
Hello,

I tried to save the current image and store it when motion is detected. Unfortunatly it doens't work as there is no jpg-ending (http://192.168.2.28:8765/picture/1/current)
is there another way to save the last recorded image? (or the current one which i can pick when motion is detected?
I have a pyhton script running when motion is detected and it transmits a file via ftp. Works but the file is empty as the download doesn work

**Comment by ccrisan** [comment]
Try the File Storage > Run A Command option. You could use curl for ftp to upload the media files wherever you need them to be. Otherwise there's always this `lastsnap.jpg` symlink created by motion in the media root directory.
