### ISSUE TITLE
run without installation as service

### ISSUE THREAD

**Issue by vkuehn** [ccrisan/motioneye#1690]
after git clone the repo is there a way to run motioneye from command line with having the whole setup or just a venv installation ?

**Comment by HJSK** [comment]
Whats a venv installation? 
I also used the repo and run in several problems, files like /usr/local/share/motioneye/extra/motioneye.systemd-unit-local are not there. Even total directory from /usr/local/share/ are missing. Same for motioneye.conf.sample, not to find in the repro / installation procedure.
After looking here on github I found the file but think is not the right one or has something to do with rights. 
I want to give this repo way a try while in motioneyeOS I run into a overheating from CPU (higher then 80 degrees!) with use of 2-3 IP rtsp CAM's

**Comment by ccrisan** [comment]
> after git clone the repo is there a way to run motioneye from command line with having the whole setup or just a venv installation ?

You can  run `python2 motioneye/meyectl.py startserver` or `python2 -m motioneye.meyectl startserver`. You may have to adjust your `PYTHONPATH` though.

**Comment by vkuehn** [comment]
there is no python3 support ?

**Comment by vkuehn** [comment]
@HJSK Venv as in python3 -m vena
@ccrisan with that I get
 Traceback (most recent call last):
  File "motioneye/meyectl.py", line 275, in <module>
    main()
  File "motioneye/meyectl.py", line 248, in main
    load_settings()
  File "motioneye/meyectl.py", line 57, in load_settings
    for i in xrange(1, len(sys.argv)):
NameError: name 'xrange' is not defined

**Comment by ccrisan** [comment]
@vkuehn there's no stable Python3 support yet. There's an [experimental branch](https://github.com/ccrisan/motioneye/commits/python3) though that you can use with Python 3.
