### ISSUE TITLE
gpg/gpg encryption for emails

### ISSUE THREAD

**Issue by klausmcm** [ccrisan/motioneye#1693]
Is encrypting emails with gpg planned? When sending potentially sensitive images, I would like them to be encrypted. I know there is an option to run a command under **Motion Notifications**. Would making the name of the generated image/video as a variable be an option?

I'm happy to share the function for creating gpg encrypted ciphertext of an email with attachments if that helps.

**Comment by BeWog** [comment]
You can use this option [on_movie_end](https://motion-project.github.io/motion_config.html#on_movie_end) and use your own script to send encrypted emails.

**Comment by klausmcm** [comment]
> You can use this option [on_movie_end](https://motion-project.github.io/motion_config.html#on_movie_end) and use your own script to send encrypted emails.

Thank you, I will check that out.
