### ISSUE TITLE
FR: Possibility to turn cameras on and off

### ISSUE THREAD

**Issue by M0ebiu5** [ccrisan/motioneye#1704]
I have multiple esp32-cam's - the cams have an mqtt interface which allows them to be turned on and off (en/disable the stream). One reason is to reduce the used bandwith on the wifi, the other is the power consumption (also on the server side).

Now it would be nice, if motioneye had the possibility to define on / off buttons for each cam, where the user could execute some sort of script / command, when pressing the button.
Another use case is, that an external motion sensor should be able to trigger the on/off/record command via an url.

**Comment by jmichault** [comment]
to define buttons, look at https://github.com/ccrisan/motioneye/wiki/Action-Buttons

**Comment by M0ebiu5** [comment]
Great, thanks for the hint!
