### ISSUE TITLE
Adding a camera creates problems

### ISSUE THREAD

**Issue by Fillip38** [ccrisan/motioneye#1706]
Hello,

I am running on my Debiam 10 system motioneye 0.42. I only completely redesigned the system last weekend. I currently have 4 cameras running there. If I add a 5th now, then the overview of the camera shows me the image of the 5th camera in position 5 AND position three. The settings of camera 3 are correct, however, is called camera 3, it only shows the wrong picture, see screenshot ... Is there anything known?

![4_Cams](https://user-images.githubusercontent.com/40865814/79321274-5ffceb00-7f0b-11ea-8fb1-271182aa11a3.PNG)

![Uploading 4_Cams.PNG…]()
![5_Cams](https://user-images.githubusercontent.com/40865814/79321224-4d82b180-7f0b-11ea-8693-fac2ba6d24e8.PNG)

**Comment by ccrisan** [comment]
Your camera IP addresses and/or port numbers got mixed up somehow. Remove all of them and add them from scratch, one by one. If that' seems like a lot of work, verify your `motion.conf` and `camera-*.conf` files and check for streaming port duplicates.

**Comment by Fillip38** [comment]
Ahh Perfekt. Yes Camera 3 and (the new) Camera 5 was the same Port 8085. Now i have change this ans it´s work!
