### ISSUE TITLE
Artifacts on screen while streaming

### ISSUE THREAD

**Issue by Massgun** [ccrisan/motioneye#172]
Hi,

first of all I would like to thank you for this easy to use piece of software. I am using it since yesterday evening and am very impressed :)

I have a question tho, when I am watching the live streams on my computer via the link to the Pi. The longer the connection is open the more 'artifacts' are shown. When I logout and login again there is no change. When I change the resolution or quality it's good for a limited amount of time but the artifacts will return. 

I added a picture to show you what I mean. 
![homebase](https://cloud.githubusercontent.com/assets/18397664/14427095/258d2746-fff3-11e5-8a96-d7aa40a6f500.JPG)

How can I fix this? Or is it maybe camera related?

**Comment by ccrisan** [comment]
Please open this issue on a motion-related forum. When problems like this occur, there's nothing motionEye can do about it. Sorry.

**Comment by Massgun** [comment]
Ok, thank you anyway :)
