### ISSUE TITLE
ONVIF cam

### ISSUE THREAD

**Issue by WirelessMind** [ccrisan/motioneye#1721]
Hello!
Why can't I find the possibility to use ONVIF ???
Where is it located or how can I enable ONVIF?

Thanks

**Comment by HawtDogFlvrWtr** [comment]
There is no onvif support. You have to know the mjpeg or rtsp path and port for your specific camera. You can use the following site to find your camera, and the appropriate location. It has a pretty good list.

https://www.ispyconnect.com/sources.aspx
