### ISSUE TITLE
Cam DID number

### ISSUE THREAD

**Issue by WirelessMind** [ccrisan/motioneye#1722]
Hello!
I have a camera (https://www.amazon.it/gp/product/B07VN4MSJH/) that **I use with YI iot app**.
I know DID number, ip and my YI account credentials, but **I don't have any cam credentails**.

Can I add this to MotionEye? How?

**Comment by mmeah** [comment]
If it has an open protocol, then it should work. See if your camera can be connected to VLC or iSpy or any other program first. https://www.ispyconnect.com/search.aspx?q=Fredi is a great resource. From the quick googling I did, the camera url may look like this http://[IP]/videostream.asf?user=[USERNAME]&pwd=[PASSWORD]&resolution=[WIDTH]*[HEIGHT]

http:// | videostream.asf?user=[USERNAME]&pwd=[PASSWORD]&resolution=[WIDTH]x[HEIGHT]
-- | --




http:// | videostream.asf?user=[USERNAME]&pwd=[PASSWORD]&resolution=[WIDTH]x[HEIGHT]
-- | --

**Comment by WirelessMind** [comment]
Unfortunately I only have the username and password of the account, not of the single camera. I guess it's not open...

**Comment by mmeah** [comment]
If all you need is the IP address, you can use a tool like Fing to scan your network to find it.
https://play.google.com/store/apps/details?id=com.overlook.android.fing

**Comment by WirelessMind** [comment]
I know the IP address.
The problem is that that camera doesn't have a username and password.
I can watch the video through its app and access it through the app's banknotes that are used for all the webcams in the account.
The webcam does not have "his" credentials.
