### ISSUE TITLE
Motioneye cannot connect to remote Motioneye using the generated Streaming URL

### ISSUE THREAD

**Issue by timdonovanuk** [ccrisan/motioneye#1728]
Trying to add a remote camera on another motioneye server. The remote Pi running meyeos in "Fast Networking Camera" mode it generates the streaming url: http://piz2.home:8081/ but this is reported as "connection refused" on the motioneye server. The URL works fine in browser. Authentication mode is set to none.

![image](https://user-images.githubusercontent.com/8156439/80482934-06ee7780-894d-11ea-8989-7ed48e0f299a.png)

![image](https://user-images.githubusercontent.com/8156439/80482873-e58d8b80-894c-11ea-884b-5bde5b21f330.png)

This issue has been reported here too: https://github.com/ccrisan/motioneye/issues/219#issuecomment-304312656

**Comment by Bearic** [comment]
I did this for the first time today. Under 'Camera Type', you have to select 'Remote Motioneye Camera', then for the URL, you put the address for the motioneye dashboard of the other computer e.g. http://piz2.home:8765, and then your admin username and password for that machine.
