### ISSUE TITLE
WebHook when no more motion detected

### ISSUE THREAD

**Issue by andre1000** [ccrisan/motioneye#1729]
Hello, it is possible to send a WebHook when no more motion detected?
I will trigger with this function my homeautomation (iobroker) to display the video string. 
Actually I start the display with the WebHook and stop with a delay.

Thank you, André

**Comment by Links2004** [comment]
is there a solution, from looking at the code base `on_event_end` can only trigger commands and no webhooks :(

https://github.com/ccrisan/motioneye/blob/c918ced0b3b51c3b9601afec56b526c11ae621c2/motioneye/config.py#L1008-L1013

**Comment by Links2004** [comment]
needed changes where easier then expected, PR opened :)

**Comment by MichaIng** [comment]
Merged for next release.
