### ISSUE TITLE
Full screen view doesn't work all the times anymore

### ISSUE THREAD

**Issue by JBS5** [ccrisan/motioneye#1731]
I did not have any problems viewing a camera in full screen, but using this feature in the last couple of days, it is not working as expected anymore.

When toggling full screen mode, the camera is shown as below. After some refreshing and/or resizing the browser window, the full screen view pops up. 

![image](https://user-images.githubusercontent.com/25594213/80789386-1f98a080-8b8c-11ea-9364-44ba7d4cd7ee.png)

![image](https://user-images.githubusercontent.com/25594213/80789233-aef18400-8b8b-11ea-97da-16ec48551035.png)

![image](https://user-images.githubusercontent.com/25594213/80789330-faa42d80-8b8b-11ea-85c0-8db102ed664b.png)

Using Firefox 75.0 (64-bits) and Chrome 81.0.4044.129 (Officiële build) (64-bits)
motionEye 0.41 on Ubuntu 18.04.

Does anyone recognize this?

**Comment by twinstef** [comment]
I have the same problem.

**Comment by JBS5** [comment]
Not having the problem anymore, using Chrome now 83.0.4103.97 (Officiële build) (64-bits) and Firefox 77.0.1 (64-bits) now. Maybe it was browser version related?
