### ISSUE TITLE
Rotating a fast network camera steam doesn't rotate the resolution with it.

### ISSUE THREAD

**Issue by MesteMonokrom** [ccrisan/motioneye#1736]
When using the fast network camera function and rotating the video 90 or 270, the resolution is still landscape. So there is a lot missing on the top and bottom of the video.

This has only been tested with 800 x 600; I haven't been able to see if other resolutions have the same issue.

Many thanks, M.

![Screenshot from 2020-05-06 16-17-51](https://user-images.githubusercontent.com/24511479/81195025-376d8b80-8fb5-11ea-825c-a3f0af028d46.png)
![Screenshot from 2020-05-06 16-17-06](https://user-images.githubusercontent.com/24511479/81195030-38062200-8fb5-11ea-9119-118f283f2c67.png)

**Comment by Bootscreen** [comment]
I have the same Problem. It doesn't change the orientation. It doesn't matter whether i change it directly on my pi with MotioneyeOS configured as fast network camera or my freenas Server with motioneye .
