### ISSUE TITLE
Option to delete files when drive gets above certain percent full.

### ISSUE THREAD

**Issue by nixcamic** [ccrisan/motioneye#1742]
This is really the only thing I miss from Zoneminder, the ability to keep all stored files indefinitely and just cull the oldest when the drive gets above 90% full.

**Comment by mmeah** [comment]
I agree. I've caught my pi acting erratic at times, only to find out that the the drive is full. An auto roll feature after some threshold to full would be nice.

**Comment by seaniedan** [comment]
Agree - old files should be deleted when necessary, not because of their age.
