### ISSUE TITLE
Controls for contrast, brightness

### ISSUE THREAD

**Issue by maxholgasson** [ccrisan/motioneye#175]
Hi, is there any chance to add controls for contrast, brightness etc. That would be great as my night images are quite soft

**Comment by ccrisan** [comment]
Contrast and brightness are already there if your camera supports them. What camera do you use?

**Comment by maxholgasson** [comment]
Hi,
i'm using an analog camera with an EasyCap Video USB Grabber Fushicai UTV007

**Comment by ccrisan** [comment]
What's the output of the following command:

    v4l2-ctl -d /dev/video0 --list-ctrls

**Comment by maxholgasson** [comment]
mh, it doesn't display anything. no output at all

**Comment by ccrisan** [comment]
Well if there's no output to that command, motionEye will consider that your video device has no controls at all. I'm sorry but there's nothing motionEye can do to implement brightness/contrast controls for your camera.
