### ISSUE TITLE
Display same picture for 2 differents camera in Gui but Record is OK

### ISSUE THREAD

**Issue by twinstef** [ccrisan/motioneye#1769]
Hello,

I have 7 cameras.
2 are identical models "yi dome 1080p" via rtsp.
both are on different places.
Motioneye display the same picture (video)  on the gui for the two cameras.
But the displayed camera name is different as expected and the recorded videos are also differents (as expected).

I check motioneye.conf, motion.conf and cameras-[1..7].conf and everything is good.
A reboot do not resolve the problem.

I can change the picture displayed on the cameras:
 - i desactivate both cameras (video device:off) and i reactivate them.
 - The image choosen for the both is the image of the first camera reactivated.

Does anyone have an idea ?

raspberry pi3 raspbian (buster)
motioneye 0.41
motion 4.2.2

**Comment by zagrim** [comment]
Have you by chance tried copying camera settings by copying the camera config files? Anyway, here's a solution for a similar case, I hope that helps: https://github.com/ccrisan/motioneye/issues/1286#issuecomment-494231656
