### ISSUE TITLE
iFrame based on Streaming URL

### ISSUE THREAD

**Issue by Tokn59** [ccrisan/motioneye#1772]
Hi, maybe not really an issue but when I want to use the streaming URL from a camera (http://xxx.xxx.xxx.xxx:8082 for example) on another website I seem to be needing to pass on user id and password even when the authentication mode is set to disabled. Do I need to use a specific syntax like http://admin:password@xxx.xxx.xxx.xxx:8082 or something similar ?

Thanks for your help !

Tony

**Comment by Mattncb** [comment]
Im having the same problem with the streaming url not working with not authentication required, and am wondering the same thing
