### ISSUE TITLE
How to "Add an init script, configure it to run at startup"

### ISSUE THREAD

**Issue by joeydream** [ccrisan/motioneye#1775]
I have few pi camera connected with RPi zero W with MotioneyeOS installed and recently a RPi4 is installed with Raspbain. An motioneye (not motioneyeOS) is expected to install on it to connect all camera. I just follow the instruction on page on Wiki of this ccrisan/motioneye page, title named as: "Install On Raspbian". Every things were seen very good and only to 

Step 7: Add an init script, configure it to run at startup and start the motionEye server:

i just wonder the 3 command are not excepted type on ssh but also should save in "the" file which should be run one every time when i reboot/startup my machine. Right?

But i don't know where and which file i should edit by nano.

thank you for your help.

**Comment by zagrim** [comment]
Below the item 7 "Add an init script, configure it to run at startup and start the motionEye server" there are four lines / commands, have you tried executing those? Those add a service to systemd, enable it and start it up. Nothing else should be required for MotionEye to start automatically at system startup.
