### ISSUE TITLE
feature-request: show video in html5-browser - expand "run a command" on filesave

### ISSUE THREAD

**Issue by ozett** [ccrisan/motioneye#178]
i discovered that .webm files run directly in modern browsers and i access my motioncaptuerd files via a filedirectoy in the browser.

the "run a command" for saving files has no variable for the filename, it would be fantastic to convert the captured file to a .webm format.

it is easy in debian like
`ffmpeg -i $f /var/www/html/motion/$i-$DAY.webm`
[http://rachaels-ubuntu.blogspot.de/2015/12/script-to-convert-motion-captured-avis.html](url)

`avconv -i tears_of_steel_720p.mkv -c:v:0 libvpx -crf 10 -vb 4M -c:a copy   tears_of_steel_vp8.mkv`
[https://wiki.debian.org/ffmpeg#Encode_video_in_VP8](url)

may you could expand motioneye to convert captured files to another format (with/without delete afterwards), or expand the run-a-command variables, to put it there?

**Comment by tintamarre** [comment]
I am using `run-a-command` to send a message to slack (instead of an email). A variable for the filename in the command would be useful. Thx.

**Comment by ccrisan** [comment]
Use %f.

**Comment by tintamarre** [comment]
Thank you for your quick answer.

I tried several commands (i.e. `echo %f >> /tmp/test.tmp`) but can't make it work ... Do you have an example ?

**Comment by ccrisan** [comment]
Hmm, can you check your thread-*.conf file and see what the line starting with `on_event_start` looks like? It should be made up of commands separated by `;`. Depending on what you have chose to happen at the moment of a motion event, you may have multiple commands. One of them should be the command that you have typed in the *Run A Command* field. What does it look like?

**Comment by tintamarre** [comment]
`motioneye # cat thread-*.conf | grep on_event_start`

`on_event_start /usr/lib/python2.7/site-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" start %t; echo %f >> /tmp/test.tmp`

**Comment by ccrisan** [comment]
Ah, scratch that (well partially). I hope you were referring to the *File Storage > Run A Command* option (rather than the one under *Motion Notifications*). The first one should support the `%f` argument and should be found next to the `on_movie_end` and/or `on_picture_save` config options.

**Comment by tintamarre** [comment]
<img width="473" alt="screen shot 2016-08-17 at 09 34 18" src="https://cloud.githubusercontent.com/assets/409734/17728106/d121b814-645d-11e6-86a0-d7e1a134c492.png">

**Comment by ccrisan** [comment]
Just use the *File Storage > Run A Command* option.

**Comment by tintamarre** [comment]
Better ! 
`duplo motioneye # tail -f /tmp/test.tmp
/var/lib/motioneye/2016-08-17/2016-08-17_09-44-33.avi`

Thx.

**Comment by ozett** [comment]
i tested the conversion. the files got suprisingly small. :+1: 
wow. but as i laid them manually into the recordings-direcotry. the dont show up in the motion-eye recordings-gui.

is there a filter? can you add .webm files to show up?

i wanted to test, if i see them running in the recordings preview windows. i am using chrome.
i would be fantastic, if i had the small video in .webm format running in the preview of motioneye-rcordings. ....
:+1:

**Comment by ccrisan** [comment]
Webm is not among the supported motion codecs, so motionEye won't recognize them either. As soon as motion starts supporting webm, I'll make sure to add support for them in motionEye as well.

**Comment by ozett** [comment]
ok. thanks for reply.
my simple assumption was, that is "would" be displayed in any html-page, as long as the brower supports this.

so i wished myself into the dream, that all files in the recordings dir would be "automagically" played in the preview...as long as the fileformat like .webm could be simply displayed in the right html-browser...

if this is actually not the case, i will use file-hook to convert after recording and view them in a directory where the html-server shows them in a listing..

a pity to jump off that wonderful motioneye-gui for this :cry:

**Comment by Harvie** [comment]
Currently there are several file formats supported in modern browsers like chrome. Motion supports swf, flv and mp4. I succesfully played files from motion in chrome. This should be easy to do. At least the basic functionality.

**Comment by ccrisan** [comment]
Closing as the functionality is now present in the latest version.
