### ISSUE TITLE
How to fix this fake detection ?

### ISSUE THREAD

**Issue by Saku241** [ccrisan/motioneye#1801]
Hello 
Sometimes my camera detect fake mouvement and I’d like to fix it, I try multiple things but still the same

https://drive.google.com/drive/folders/1-8Ya_qDtP_HwlrB7xYXfKQbMtui0GveP

You will find one video with its debug files, I could add more if needed

Motion detection is set to 0.6% (if not it doesn’t detect during night)
Light motion is set to 14%

Thanks

**Comment by Dvorf** [comment]
this is not motioneye issue, all motion detection question you should address to motion project

**Comment by zagrim** [comment]
@Saku241 There seems to be quite a lot of noise in the video. It's quite visible from the original video, with plenty of pixel color changes in the tile wall. You could try increasing "Noise Level" under "Motion Detection" until you no longer get "movement" in areas with actually nothing happening. Alternatively you could "Auto Noise Detection" in the same place.

**Comment by zagrim** [comment]
After getting the noise propely dealt with, you'll most likely need to re-adjust the motion detection threshold to get real movenent detected in the way you wish.

**Comment by Saku241** [comment]
Alright thanks @zagrim !
