### ISSUE TITLE
Can't disable motion detection in docker

### ISSUE THREAD

**Issue by think-free** [ccrisan/motioneye#1807]
motioneye_1  |    ERROR: failed to disable motion detection for camera with id 1: Failed to connect to 127.0.0.1 port 7999: Connection refused
motioneye_1  |    ERROR: failed to disable motion detection for camera with id 4: Failed to connect to 127.0.0.1 port 7999: Connection refused
motioneye_1  |    ERROR: failed to disable motion detection for camera with id 1: Failed to connect to 127.0.0.1 port 7999: Connection refused
motioneye_1  |    ERROR: failed to disable motion detection for camera with id 4: Failed to connect to 127.0.0.1 port 7999: Connection refused
motioneye_1  |    ERROR: failed to disable motion detection for camera with id 1: Failed to connect to 127.0.0.1 port 7999: Connection refused
motioneye_1  |    ERROR: failed to disable motion detection for camera with id 4: Failed to connect to 127.0.0.1 port 7999: Connection refused

**Comment by smhgit** [comment]
@think-free did you ever get an answer? did you find a solution?

**Comment by think-free** [comment]
> @think-free did you ever get an answer? did you find a solution?

Disabling camera completely ... 
I think that if you enter the container you can make a (web) request from inside but I didn't investigate too much

**Comment by think-free** [comment]
Closed ?!?

**Comment by starbasessd** [comment]
@think-free Last activity was Oct 28 2020, no further responses. Just trying to clean up issues older than 60 days (Pre 2020-01-01 last activity)
If you still need help, you should be able to re-open.
