### ISSUE TITLE
Dockerfile does not build

### ISSUE THREAD

**Issue by marcopaganini** [ccrisan/motioneye#1818]
The existing Dockerfile won't build a new image since it's based on ubuntu 18:10, which is not a LTS version and thus unavailable in hub.docker.org.

I cleaned up the existing Dockerfile and converted it to use debian buster (with a locked version of SID for the components that need SID). Please let me know if you're accepting contributions and I'll end the PR.

**Comment by kleini** [comment]
We will accept a PR if everything builds in Travis CI.

**Comment by marcopaganini** [comment]
Excellent. I'm sending the PR and will watch the travis run to see if
everything works.
