### ISSUE TITLE
trigger GPIO via 'Run Command' upon motion detection

### ISSUE THREAD

**Issue by emosbek** [ccrisan/motioneye#182]
Is it possible to enable GPIO's e.g for LED when motion is detected on remote MotionEye device?

**Comment by ozett** [comment]
![zwischenablage01](https://cloud.githubusercontent.com/assets/5937811/14596228/43fd2fe4-0545-11e6-8515-00cbcf38b5d2.png)

**Comment by emosbek** [comment]
Thank you, i have found this, but can i run root commands thru this, like 'gpio mode 0 out', 'gpio write 0 1'?

**Comment by ozett** [comment]
use normal linux/unix commands like
`sudo`
or put it in there directly. because i think motioneye is runnung as root by default...
