### ISSUE TITLE
Update Archlinux installation instructions to include AUR package

### ISSUE THREAD

**Issue by JSkier21** [ccrisan/motioneye#1821]
Hi,

Would you please update the wiki to include ArchLinux AUR package (as another option to using pip)? I maintain the package, and have / will for awhile. 

AUR package page is here: https://aur.archlinux.org/packages/motioneye/

Jay

**Comment by ManuLinares** [comment]
no need, it's already in Community here https://www.archlinux.org/packages/community/x86_64/motion/

Should close this.
