### ISSUE TITLE
Feature Request: Would love to see WebRTC integrated with the Janus and jStreamer

### ISSUE THREAD

**Issue by silversword411** [ccrisan/motioneye#183]
Was reading this article: http://www.rs-online.com/designspark/electronics/blog/building-a-raspberry-pi-2-webrtc-camera

and would love to be able to click when watching feed to start a live WebRTC session with the camera. Looks like the packages are already there, just need hooking in! I see on the Roadmap you already have Audio on the todo list.

Security, interactive edition :)

**Comment by ccrisan** [comment]
This is too complex and requires too much work while other important features are missing.
