### ISSUE TITLE
Video is blurry or showing rainbow colors, what could be the issue?

### ISSUE THREAD

**Issue by DBuit** [ccrisan/motioneye#1835]
Hello,

I got motion eye running with my reolink rlc-410w.
It is detecting motion but i am getting alot of images that are blurry or showing alot of colors like a rainbow:
Example:
![motion detection image rainbow](https://user-images.githubusercontent.com/17079647/86776258-5a212c80-c058-11ea-9401-7d948361247c.png)

What could be the problem? I have the reolink app running with motion and never seen this kind of images on that...

**Comment by jasaw** [comment]
It could be packet drop, or broken camera.
Are you reading the camera stream via UDP or TCP? Try TCP.
Try lowering the resolution and/or framerate too.

**Comment by antonoal** [comment]
I've had a similar issue although sporadically. At some point I tracked it down to the following sequence. When I reboot one of my cameras I get that in motioneye.

**Comment by 1ubuntuuser** [comment]
I think it's related the reolink "Iframe configureation" issue. Blue iris forums talk of it.
