### ISSUE TITLE
Detect camera dropping offline

### ISSUE THREAD

**Issue by MYeager1967** [ccrisan/motioneye#1838]
Is there any way to detect when a camera has gone offline? Seeing as most of us use this pretty much headless with little interaction (a testament to the reliability of motion/motionEye), it would be nice to monitor it from home automation or wherever and be able to be notified when a camera goes offline. Unfortunately, it does happen from time to time...

**Comment by spinko101** [comment]
+1 

I had a camera over WiFi and it used to go offline once or twice a week (probably due to the WiFi link). I only noticed it some days later. A notification would have been useful. Thank you.
