### ISSUE TITLE
Motion Timeline

### ISSUE THREAD

**Issue by hemskgren** [ccrisan/motioneye#1841]
1. version [x.y.z, hash, other]:  latest pip 0.42.1
2. installed as a package or compiled from sources [deb, rpm, git, other]:  deb from motion and pip for motioneye. 
3. standalone or part of third party: standalone 
4. video stream source: net cam rtsp
5. hardware: arm
6. operating system : Debian 10 

I like to have timeline with motion from all/selected camera in one view.

**Comment by spupuz** [comment]
would like it too i'm using latest dev/edge verion
