### ISSUE TITLE
Snapshot URL - 401: Unauthorized

### ISSUE THREAD

**Issue by allmoney** [ccrisan/motioneye#1844]
I have problem in motioneye in Home Assistant.
"Snapshot URL" only works in same session.
If I open Snapshot URL in incognito chrome mode - I see error "401: Unauthorized".
Why? How fix?

![image](https://user-images.githubusercontent.com/939594/87461023-74d64100-c616-11ea-9712-ffa0f5eda5fb.png)

**Comment by GrinchUA** [comment]
I also think that this resource should be without authorization

**Comment by starbasessd** [comment]
With a normal current install of motionEye or motionEyeOS, and you click on Snapshot URL, it gives you a link with the embedded username and hashed password to allow access:
http://[ip_address]/picture/1/current/?_username=admin_signature=d1231995ea72e4bb200a718b047a7c9fab677c06
which works in all browsers and works across reboots. Have you contacted the HomeAssistant support group?

**Comment by starbasessd** [comment]
Works in Private or incognito modes also.

**Comment by sargus123** [comment]
Links are provided differently than above, and unfortunately it does not work in a different browser and on the phone.

401

![image](https://user-images.githubusercontent.com/32904697/113705773-2144df80-96de-11eb-8348-0877d204f04e.png)
and : 

![image](https://user-images.githubusercontent.com/32904697/113705907-4d606080-96de-11eb-88c7-ec783d97dd8f.png)

**Comment by starbasessd** [comment]
Then contact the HA Community, and FRENCK, as he stated previously that his wrapper doesn't change anything, but it obviously does.

**Comment by midnight1979** [comment]
use cookies in http request and it is woking!
