### ISSUE TITLE
motioneye.conf.sample is bad referenced in the wiki

### ISSUE THREAD

**Issue by DiomedesDominguez** [ccrisan/motioneye#1847]
In the [wiki for Ubuntu](https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu#instructions) says that the `motioneye.conf.sample` file is in `/usr/local/share/motioneye/extra/` but after `sudo find / -name "motioneye*"` I found it in `/home/[User]/.local/share/motioneye/extra/`

**Comment by ccrisan** [comment]
The wiki also states that you should run all commands as `root` (i.e. with `sudo`). If you did that, you would (probably, hopefully) find the file at the indicated place.
