### ISSUE TITLE
Does frame change threshold need to change when I add a mask?

### ISSUE THREAD

**Issue by melvinraju** [ccrisan/motioneye#1854]
Im wondering when I mask off an image do I have to adjust the frame change threshold percentage to account for the active area or does it still refer to the whole unmasked image?
Eg. My frame change threshold is 10% before adding a mask. If I add a mask over 50% of my image will the system effectively be looking for 20% now? or 5? or still 10?

**Comment by zagrim** [comment]
From [Motion docs](https://motion-project.github.io/motion_config.html#threshold): "The threshold is the number of changed pixels counted after noise filtering, masking, despeckle, and labelling." The threshold percentage shown in MotionEye GUI is calculated againts the image size, so adding a mask doesn't change it (or the Motion `threshold` option value). So, if you mask half of the image, there's never any change affecting the detection in 50% of the image, but the change threshold for detection is still the same. Of course, if you have been compensating "irrelevant" change/motion before adding the mask by increasing the threshold, you'll likely need to lower it after adding the mask. It's the same as with all major changes in motion detection parameters, one parameter is likely to cause a need to tune the others, too.

I think showing (and thinking of) the threshold as a percentage is only helpful in the beginning when guessing for the initial value (and not even there if there's a lot of noise or irrelevant change), after than it just adds confusion. You're not the first one to ask this kind of question.
