### ISSUE TITLE
Motioneye in docker no networkshare possible

### ISSUE THREAD

**Issue by holzfelix** [ccrisan/motioneye#1871]
I try to install and run motioneye in docker. I have set it up with docker-compose 

![image](https://user-images.githubusercontent.com/6866699/89030723-5d46ca00-d331-11ea-8e26-85988be470ba.png)

`---
version: "3.5"
services:
  motioneye:
    image: ccrisan/motioneye:master-amd64  # Change to ccrisan/motioneye:master-armhf for ARM chips (Pi etc.)
    ports:
      - "8081:8081"
      - "8765:8765"
    volumes:
      - etc_motioneye:/etc/motioneye
      - var_lib_motioneye:/var/lib/motioneye

volumes:
  etc_motioneye:
  var_lib_motioneye:`

After this I imported my config from raspberrypi and now I can't select network devices as file storage.
![image](https://user-images.githubusercontent.com/6866699/89030802-823b3d00-d331-11ea-9b39-84471637d4cb.png)

How can I solve this?

Thanks.

**Comment by kleini** [comment]
You should mount the network file storages on the Docker host and mount the host filesystem then into the container. Network mounts in containers are discouraged. Keep in mind, that a container is meant to run a single process, not a whole Linux operating system.

**Comment by holzfelix** [comment]
Thats correct didn't thought about it. Thanks
