### ISSUE TITLE
support for rtmp

### ISSUE THREAD

**Issue by Ethocreeper** [ccrisan/motioneye#188]
when i tri to put my camera stream rtmp it says **protocol rtmp not supported**
what do i do now. i am using (pi3b)
the link is correct because manged to open the stream from the vlc media player

found that doesn support it in [this ](https://github.com/ccrisan/motioneye/issues/166#issuecomment-210290172)issue

**Comment by ozett** [comment]
you need a motion.binary which supports the procol.
mr-dave version (look in the wiki of motioneye) supoports rtsp, 
may rtmp is also supported? 
i dont know, you have to investigate there...

**Comment by ccrisan** [comment]
I don't think the motion daemon supports RTMP. If some versions do support it, please feel free to reopen the issue and I'll make sure the UI accepts it.
