### ISSUE TITLE
Can't play H265

### ISSUE THREAD

**Issue by LMRig** [ccrisan/motioneye#1880]
Hi, I was recording 2 days in H265, I can't play any of these records in VLC, there is just the black screen but the video is running.
I thought it's a codec problem, but when I play some movie in H265 (HEVC), again in VLC, it works...

Even when I try to watch it through GUI it says it's not supported.
I tried Windows media player, it said I have to download the H265 codec, it downloaded itself and after that, it's still not playing it.
There must be something wrong...

I really need to get this working, because it's 850MB vs 1,7GB of 1-hour record.

Thanks

**Comment by zagrim** [comment]
I have no idea of the cause of the issue, but you could try comparing a non-playing H265 video file against a well-playing H265 video file by doing `ffprobe  -show_streams myvideofile` for both the files and comparing the parameters.

It might be something similar to how H264 has different profiles some of which are not supported on some platforms/software. But if it is like that, then the likely solution would perhaps be to lower the quality setting and thus making the resulting file somewhat larger.
