### ISSUE TITLE
attempting to set motioneyes os to record to an attached USB drive and I cannot find the device path to enter in motioneyes

### ISSUE THREAD

**Issue by swaziguy** [ccrisan/motioneye#1898]
I am fairly new to linux/unix so I have limited knowledge of commands.  I and setting up motioneyes as a CCTV server in South AFrica for the farm and school where we are located.  Motioneyes is running great and the cameras I have attached are working as expected.  I have attached a 1TB USB3 drive to the Raspberry Pi 4B 8GB that I am using as the server but I cannot seem to find the USB drive,  I have attempted to use ssh and the commands I have found through Google but so far I am not finding the path I need to enter for the USB drive.  Any help is appreciated.

**Comment by Johnny-quattro** [comment]
Check to see if the disk is recognised:

**_sudo dmesg -T_**
(possibly appears as /dev/sda)

**_lsusb_**

If the disk is indeed mounted, look in **_/media/..._**

Here's an example from my own Pi, with a Samsung external HDD:

**_[Tue Oct 20 11:09:48 2020] sd 0:0:0:0: [sda] 312581808 512-byte logical blocks: (160 GB/149 GiB)
[Tue Oct 20 11:09:48 2020] sd 0:0:0:0: [sda] Write Protect is off
[Tue Oct 20 11:09:48 2020] sd 0:0:0:0: [sda] Mode Sense: 28 00 00 00
[Tue Oct 20 11:09:48 2020] sd 0:0:0:0: [sda] No Caching mode page found
[Tue Oct 20 11:09:48 2020] sd 0:0:0:0: [sda] Assuming drive cache: write through
[Tue Oct 20 11:09:48 2020] sd 0:0:0:0: Attached scsi generic sg0 type 0
[Tue Oct 20 11:09:48 2020]  sda: sda1
[Tue Oct 20 11:09:48 2020] sd 0:0:0:0: [sda] Attached SCSI disk_**

**Comment by starbasessd** [comment]
Closing, this is a motionEyeOS issue. If you need further assistance ask at
https://github.com/ccrisan/motioneyeos/issues
