### ISSUE TITLE
lightswitch settings enhancement request

### ISSUE THREAD

**Issue by bjs-pdx** [ccrisan/motioneye#19]
I'm having problems with some of my cameras triggering motion events due to significant changes in light.  MotionEye has a setting to turn on the lightswitch setting but sets it to 50 (%).  I made a manual change to the thread file for one of the cameras to set this to 25% but then made other changes through the MotionEye interface.  It appears that when I used the interface the lightswitch setting was also changed back to 50.

I would suggest that allowing one to set the percentage through the interface would be useful, or at least for the interface to not reset the parameter.

**Comment by ccrisan** [comment]
Yes, I guess making that option a slider may be helpful for some users. I'll consider your request.
