### ISSUE TITLE
Fresh install on Pi2 - A couple of issues

### ISSUE THREAD

**Issue by KiwiNibbler** [ccrisan/motioneye#1900]
I just rebuilt an RPi2 with the 20200606 build. I have attempted to get the motion settings tweaked. I either get nothing or a photo every second or so.

I can't find a happy medium. Does someone have recommendations? I've been using MotionEye off and on for a few years and I have never been able to get things quite right. Recommendations would be helpful.

Item 2: I couldn't configure the option to use Google Photos. Which, is a nice new feature, but I couldn't get it to work. Not really that big of a deal.

Item 3: I configured a Google Drive output. It sometimes works. I changed it to an FTP output. It sometimes works. My Pi has taken more than 1700 photos today and 9000 yesterday. None have been sent to my FTP site from today. 25 from yesterday.

**Comment by starbasessd** [comment]
Closing, this is a motionEyeOS issue. If you need further assistance ask at
https://github.com/ccrisan/motioneyeos/issues
