### ISSUE TITLE
MMAL Camera Not Picking Up When Adding Cam - Raspberry Pi 4 8Gb

### ISSUE THREAD

**Issue by Tobinuk** [ccrisan/motioneye#1901]
Hi,

I have 2 SD cards. One installed with MotionEyeOS & the other has Raspbian installed....

The MotionEyeOS SD has been flashed and seem to install and boot with the wifi supplicant files all booting done!

When I access MotionEye through the browser and IP address I can login as admin and get asked to add a cam. My cam is a nightvision camera purchased on ebay. The ribbon type. However it does not display under MMAL cameras when adding.

There are "No cameras"??

Why is this not picking up??

I ran a sudo command (forget now) which stated no cameras supported & no cameras installed?!

I shutdown MotionEyeOS and switched SD cards. 

When my Raspbian booted up I configured the camera, rebooted and I was able to take video and shots, then save to Rasp desktop....... So I know the camera works and that I have installed/fitted correct.

I then switched SD cards again...... Going back to MotionEyeOS, booted up and returned to my browser after successful boot.
Still no camera detected when trying to add MMAL cam :(

Does anyone have any ideas please?? I am very new to this. However I dont like to be beaten :)

Thanks for ready. Hope we can sort this!!

------------------------------------------------

Here are a few other sudo commands which I tried, hopefully it will provide some info for us :)

[root@meye-17edee66 ~]# lsmod
Module                  Size  Used by    Tainted: G
ipv6                  458752 28 [permanent]
brcmfmac              315392  0
brcmutil               16384  1 brcmfmac
sha256_generic         20480  0
spidev                 20480  0
cfg80211              643072  1 brcmfmac
bcm2835_v4l2           45056  0
bcm2835_codec          36864  0
snd_soc_bcm2835_i2s    16384  0
v4l2_mem2mem           24576  1 bcm2835_codec
bcm2835_mmal_vchiq     32768  2 bcm2835_v4l2,bcm2835_codec
snd_soc_core          192512  1 snd_soc_bcm2835_i2s
rfkill                 28672  2 cfg80211
v4l2_common            16384  1 bcm2835_v4l2
videobuf2_dma_contig    20480  1 bcm2835_codec
videobuf2_vmalloc      16384  1 bcm2835_v4l2
videobuf2_memops       16384  2 videobuf2_dma_contig,videobuf2_vmalloc
raspberrypi_hwmon      16384  0
snd_bcm2835            28672  0
snd_compress           20480  1 snd_soc_core
videobuf2_v4l2         24576  3 bcm2835_v4l2,bcm2835_codec,v4l2_mem2mem
hwmon                  16384  1 raspberrypi_hwmon
snd_pcm_dmaengine      16384  1 snd_soc_core
videobuf2_common       45056  4 bcm2835_v4l2,bcm2835_codec,v4l2_mem2mem,videobuf2_v4l2
snd_pcm                98304  4 snd_soc_bcm2835_i2s,snd_soc_core,snd_bcm2835,snd_pcm_dmaengine
snd_timer              32768  1 snd_pcm
videodev              200704  6 bcm2835_v4l2,bcm2835_codec,v4l2_mem2mem,v4l2_common,videobuf2_v4l2,videobuf2_common
i2c_bcm2835            16384  0
snd                    73728  5 snd_soc_core,snd_bcm2835,snd_compress,snd_pcm,snd_timer
spi_bcm2835            20480  0
media                  36864  3 bcm2835_codec,v4l2_mem2mem,videodev
vc_sm_cma              36864  1 bcm2835_mmal_vchiq
rpivid_mem             16384  0
uio_pdrv_genirq        16384  0
uio                    20480  1 uio_pdrv_genirq
fixed                  16384  0
i2c_dev                20480  0
i2c_bcm2708            16384  0
overlay               106496  3
[root@meye-17edee66 ~]# ls /dev/video*
/dev/video10  /dev/video11  /dev/video12
[root@meye-17edee66 ~]# v4l2-ctl --list-devices
bcm2835-codec-decode (platform:bcm2835-codec):
        /dev/video10
        /dev/video11
        /dev/video12

Cannot open device /dev/video0, exiting.

**Comment by Johnny-quattro** [comment]
Check to see if the camera is connected properly and supported first:
**_/usr/bin/vcgencmd get_camera_**

Mine reports the following:
**_supported=1 detected=1_**

Secondly, I had a problem adding the camera and I eventually deduced that the motion daemon was being started and grabbing control of the camera. I disabled motion from starting by editing the file **_/etc/default/motion_**.

Hope this helps.

**Comment by starbasessd** [comment]
Closing, this is a motionEyeOS issue. If you need further assistance ask at
https://github.com/ccrisan/motioneyeos/issues
