### ISSUE TITLE
Cannot locate motioneye.conf on motioneyeOS

### ISSUE THREAD

**Issue by soflyj** [ccrisan/motioneye#1908]
Hi

I have installed and can connect to my IP cam perfectly using the MotioneyeOS for the Raspberry PI.

I want to be able to control my IP cam directions/ PTZ but I cannot find the config file to add the options.

**Comment by codelover96** [comment]
According to [](https://github.com/ccrisan/motioneyeos/wiki/motioneye.conf)
`motioneye.conf` file is located at `/data/etc/motioneye.conf`

**Comment by starbasessd** [comment]
Closing, this is a motionEyeOS issue. If you need further assistance ask at
https://github.com/ccrisan/motioneyeos/issues
