### ISSUE TITLE
Vertical white line in the picture

### ISSUE THREAD

**Issue by xinyue** [ccrisan/motioneye#1920]
How to remove the white line on the right of picture?

![white-line](https://user-images.githubusercontent.com/977224/95530906-ad1cce00-0a11-11eb-9514-1de1e21c5286.PNG)

**Comment by codelover96** [comment]
Does motioneye detect it as a motion event?

**Comment by starbasessd** [comment]
Where / how did you install motionEye? Which version of motion & motionEye are you running, and which OS? (found in Settings, General in the WebGUI.)
