### ISSUE TITLE
Import the driver for Sony IMX219-200 camera modul

### ISSUE THREAD

**Issue by Johannes-288** [ccrisan/motioneye#1921]
Hello everbody, 
I want to integrate the camera module from the Sony IMX219-200 (https://www.waveshare.com/wiki/IMX219-200_Camera) into the system. Unfortunately this is currently not supported. A config file is available on the manufacturer's homepage. (https://www.waveshare.com/w/upload/e/eb/Camera_overrides.tar.gz). Can someone help me to integrate this camera?
[Camera_overrides.tar.gz](https://github.com/ccrisan/motioneye/files/5361297/Camera_overrides.tar.gz)

**Comment by starbasessd** [comment]
If it is a missing firmware issue, they can be added to your image under /lib/firmware. If it is something else ???
If you need help loading the firmware, I can give you semi-step by step on how to do it.
If you are installed on another system (Like Ubuntu, RaspberryPiOS, Debian, etc.) you should be able to install following WaveShare's instructions. If you are installing on motionEyeOS you are in the wrong forum, ask over in https://github.com/ccrisan/motioneyeos/issues
