### ISSUE TITLE
Motioneye can't control motion detection

### ISSUE THREAD

**Issue by sambul13** [ccrisan/motioneye#193]
Once motioneye service is started, detected motion pictures and videos aren't saved into target directory or anywhere. There're no relevant records visible in motioneye or motion log. It appears, setting _control_html_output_ on or off isn't recognized by Motioneye. 

Only if webcontrol_html_output is turned on, its possible to activate detected motion recording to disk via native Motion webui. But as soon as any changes are made in Motioneye webui, motion detection is set to Pause again by Motioneye, despite its shown active in its webui. But cam picture is not red framed.

Can it be because motioneye attempts to control motion on the same port as native motion API control, despite that control is in TEXT mode, i.e. can't be controlled via html?

**Comment by sambul13** [comment]
Here's this [pic](http://s32.postimg.org/vzw1ittxh/motioneye_detection.jpg) showing motioneye puts detection to PAUSE at each settings change of any cam.

**Comment by ccrisan** [comment]
Most likely you have the working schedule option turned on.
