### ISSUE TITLE
ESP32-CAM

### ISSUE THREAD

**Issue by lodv** [ccrisan/motioneye#1935]
Hi,

I installed MotionEye in Home Assistant.
I want to add my ESP32-CAM, but that's not possible.
I get the message that the camera is not a supported network camera.
The camera has an ip address and I can open the stream in a browser.
The IP address I type in = http://192.xxx.xxx.xxx/ Maybe it must have a portnumber? I don't use a portnumber in the browser.
Everywhere I see tutorials where they add ESP32-CAM into Home Assistant, so I'm wondering if you know what's going on.
Camera and Home Assistant (running on a Raspberry Pi) are attached to the same network.
Thank you for your help.
Yvonne

**Comment by slash153** [comment]
assuming you use the example streaming server, you need to use "http://192.xxx.xxx.xxx:81/stream" (without quotes) to add the video stream into motioneye/motioneyeos. Please note it defaults to lowest settings, if you need a better resolution, you need to change it in the esp32-cam administration and it resets to default after reboot/power loss.

**Comment by lodv** [comment]
Thank you so much. That is the right answer.

Kind regards,
Yvonne

________________________________
Van: slash153 <notifications@github.com>
Verzonden: donderdag 29 oktober 2020 12:23
Aan: ccrisan/motioneye <motioneye@noreply.github.com>
CC: lodv <yvonne@kasbah.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [ccrisan/motioneye] ESP32-CAM (#1935)


assuming you use the example streaming server, you need to use "http://192.xxx.xxx.xxx:81/stream" (without quotes) to add the video stream into motioneye/motioneyeos. Please note it defaults to lowest settings, if you need a better resolution, you need to change it in the esp32-cam administration and it resets to default after reboot/power loss.
