### ISSUE TITLE
RTSP POE Camera ..? 

### ISSUE THREAD

**Issue by an6059** [ccrisan/motioneye#1950]
Anyone have a recommendations  on a RTSP/POE Camera to use with motioneye, that's hopefully available on Amazon ? 

Thanks

**Comment by gitpower2017** [comment]
I have Reolink Cams (RLC-410-5MP). This work good.
This is the url for motioneye.
rtsp://<IP-CAM>/h264Preview_01_main

**Comment by an6059** [comment]
Thank you much appreciated

**Comment by mcmidget** [comment]
You can use **ANY** camera supporting RTSP protocol.
Saddly, supported protocols are something that Amazon's sellers don't use to add to the description, so maybe you need to check the reviews or ask the seller if RTSP is supported on offered device.
