### ISSUE TITLE
Change request: don't remove working schedule for interval shots

### ISSUE THREAD

**Issue by influenced** [ccrisan/motioneye#196]
I'd like to capture pictures every 30s during a set of hours, but not have it going all night (since the cameras don't actually show anything in the dark). If I switch that camera from motion detection to interval mode, various options disappear, including the Working Schedule; I don't think it really needs to remove that?

**Comment by ccrisan** [comment]
I understand your wish and I think it makes sense in some use cases. However I wouldn't be able to implement it given the way snapshots are taken by the motion daemon. It's either snapshots at regular intervals or motion-detection-induced. Now the working schedule can only control the motion detection mechanism. Sorry about that.
