### ISSUE TITLE
start motioneye on boot

### ISSUE THREAD

**Issue by nolram16** [ccrisan/motioneye#198]
i owned a raspberry pi 2 and it has ubuntu mate 16.04 as OS. i was able to successfully installed motioneye and can run it using command below 

note: meyectl is located in /usr/local/bin

`meyectl startserver -c /etc/motioneye/motioneye.conf -l  -b`

i tried to add the command above to /etc/rc.local but i've got no luck on starting it up on boot up. any work around?

**Comment by sgiannulli** [comment]
why don't you use the wiki suggestion for ubuntu with systemd-based?

**Comment by nolram16** [comment]
i tried but its not working :(
