### ISSUE TITLE
No stills recorded after os upgrade

### ISSUE THREAD

**Issue by anarch9791** [ccrisan/motioneye#1995]
After running update/upgrade on Raspbian my motioneye stopped saving stills. I have 20GB of free space. Camera is working as I can see live feed. It is not capable of recording still images. I get the blanc screen with unable to open video device error,. 
 I am running motionEyeOS ver: 0.42.1
 I am using the following board/model: Raspberry PI 3B+.
My motionEye unit is connected to the network via: WiFi

**Comment by starbasessd** [comment]
If you are still having issues, please open a new issue.
