### ISSUE TITLE
((Not an issue just a question)) Upnp on motioneyeos??

### ISSUE THREAD

**Issue by vaggelis305** [ccrisan/motioneye#2004]
Hey, I'm thinking about getting 2 raspberry pi but I have an HUAWEI E5576 for wifi router and I don't know if it support's port forwarding but it support's Upnp. Is it supported on motioneyeos??

Pls tell me.  

BTW sorry for bad english, I'm greek.

**Comment by vaggelis305** [comment]
My router: https://consumer.huawei.com/ie/routers/mobile-wifi-3s/

BTW it's a 4g router coz the camera's are at my work!!

**Comment by vaggelis305** [comment]
Oh, I just found out that it support's Port forwarding... 0____0

I'm closing it. 0____0

**Comment by starbasessd** [comment]
This is for motionEye on another OS, you want to post at:
https://github.com/ccrisan/motioneyeos/issues
for motionEyeOS.
