### ISSUE TITLE
not able to add pi camera module v2.1 noir

### ISSUE THREAD

**Issue by guocity** [ccrisan/motioneye#207]
I have used the motioneyeos-raspberrypi3-20160410.img.gz image, with no problem,
however, i tried to follow the instruction to install motion eye in Raspbian, the camera module v2.1 noir can not be detected by motion eye. i am able to use python piCamera library to capture still image.
Is the driver for motion eye missing?

**Comment by ccrisan** [comment]
Have you loaded the `bcm2835-v4l2` module?

**Comment by guocity** [comment]
thanks ccrisan, it's the driver issue
is there any page shows how to setup IR for pi camera noir?

**Comment by legotheboss** [comment]
Try running these commands... It fixed my issues with Raspberry Pi Zero 1.3 and Pi NoIR V2

`sudo apt-get update` 

`sudo apt-get dist-upgrade`

**Comment by ccrisan** [comment]
Unless this is really about [motionEyeOS](https://github.com/ccrisan/motioneyeos), there shouldn't be a problem with any of the RPi cameras on an up-to-date Raspbian.
