### ISSUE TITLE
Cameras do not fit vertically

### ISSUE THREAD

**Issue by jraydoran** [ccrisan/motioneye#208]
I have added 4 x raspberry pi cameras to a 5th raspberry pi 3 acting as a hub. I have the 4 x cameras in 2 columns. I cannot get the 4 camera's to fit on screen. I have to scroll down to see the bottom 2 cameras. I have selected the "Fit Frames Vertically" option on all the cameras and the hub.

Any advice?

Kind regards
Jason

**Comment by ccrisan** [comment]
A screenshot would help. The Fit Frames Vertically option makes sure that at least one *row* of frames fits vertically on the screen.

**Comment by jraydoran** [comment]
Hi ccrisan,

Thank you so much for the feedback. Attached is a screenshot.

Kind Regards
Jason


![screen shot 2016-05-25 at 14 56 32](https://cloud.githubusercontent.com/assets/17763657/15540802/9e7948de-2289-11e6-9faa-2058d473daed.jpg)

**Comment by ccrisan** [comment]
Well yeap, as I said, the fit vertically option makes sure that one row of frames fits in the window boundaries. In your case I'd recommend setting 3 frames/row so that the frames are proportionally smaller and thus two rows will fit vertically in your window.

**Comment by jraydoran** [comment]
Thank you very much ccrisan.
