### ISSUE TITLE
the camera does not support newer versions of browsers 

### ISSUE THREAD

**Issue by sargus123** [ccrisan/motioneye#2085]
Camera | Received HTTP/0.9 when not allowed

the camera does not support browser versions newer than 44

  icsee application supports this camera.
    there is no update to this camera 

camera firmware : V5.00.R02.000529B2.10010.040600.0020000

![obraz](https://user-images.githubusercontent.com/32904697/113453331-0df7f280-9406-11eb-8565-cb40adb43a99.png)

**Comment by starbasessd** [comment]
Which camera?
Your command URL is saying 'command=snap' (for snapshot?) but motion/motionEye is looking for some sort of stream to manipulate...

**Comment by sargus123** [comment]
I found a somewhat combined solution. I installed the iSpy application (windows 10).
and thanks to her I found the rstp address.
I got a tip from the page:   https://community.home-assistant.io/t/add-icsee-camera-to-ha-rtsp/290852 
to 10 points

**Comment by starbasessd** [comment]
Would have helped here if you had posted the make and model of the camera here. I would have pointed you to the database for iSpy at https://www.ispyconnect.com/cameras
without the need to install any apps...
