### ISSUE TITLE
there isn't network storage option

### ISSUE THREAD

**Issue by iSlide** [ccrisan/motioneye#209]
Hi,
first of all many thanks for your attention.
In the past I used MotionEye Os and I could save my video in a network folder on my nas.
Now I installed MotionEye togheter to Raspbian, it works very fine, but I've a problem with the network storage....I haven't this option!!! I can choice only custom path option.
Can you help me?

**Comment by ccrisan** [comment]
Set [smb_shares](https://github.com/ccrisan/motioneye/wiki/Configuration-File#smb_shares) to `true`.

**Comment by iSlide** [comment]
Many thanks!!!! Now it's perfect!
