### ISSUE TITLE
Spelling mistake : sites-avaiable should be sites-available

### ISSUE THREAD

**Issue by hasse-basse** [ccrisan/motioneye#2092]
On the page 

https://github.com/ccrisan/motioneye/wiki/Running-Behind-Nginx

there is a spelling mistake

/etc/nginx/sites-avaiable/motioneye.example.com
should be
/etc/nginx/sites-available/motioneye.example.com

An l (small L) is missing in  available

**Comment by starbasessd** [comment]
Oops. Fixed. Thanks.
