### ISSUE TITLE
How to provide my external IP address on an alert from Motioneye

### ISSUE THREAD

**Issue by Hard2findaNameHere** [ccrisan/motioneye#212]
I have successfully installed motioneye on a raspberrypi3 and set up a static internal IP address.  Everything appears to be working great, remote access via the internet, alerts etc. 
I have also attempted to set up a NO-IP DDNS and associated it to my router and this works, but unfortunately I cannot install DUC (Dynamic Update Client) to advise NO-IP if my external IP address changes at anytime.

Is it possible that Motioneye could incorporate within its GUI and alerts and option to advise of the external IP address? Maybe only necessary if it changes but on all alerts it would be extremely useful.

**Comment by bakroistvan** [comment]
I think this feature is not feasible to the motioneye.

Try https://duckdns.org (hackster friendly DDNS)
 - Sign in
 - Create subdomain
 - Click install on the top
 - Choose the domain
 - Click your OS eg.: pi
 - Follow instructions

**Comment by ccrisan** [comment]
Such a feature has nothing to do with motionEye.

**Comment by Hard2findaNameHere** [comment]
Hi Calin,
When you eventually get around to implementing a few more action buttons could you let us know please. I really need them for the motioneye. Just simple buttons like UP, DOWN, LEFT and RIGHT would be fantastic and greatly appreciated.

----- Reply message -----
