### ISSUE TITLE
Can't create symlink: Operation not supported

### ISSUE THREAD

**Issue by MrRies** [ccrisan/motioneye#2133]
Hi everyone,

i have several instances of motioneye running on different Raspi Zeros. Motioneye takes a pictures every 5 seconds and saves it to my NAS (Terramaster with TrueNAS running).
Sometimes I get this error. I can't reproduce it. It happens on all cameras. The NAS has a normal smb share without symlinks. I think the pictures aren't saved, when those error occure. Can someone please help me?

Thank you, Ries

Jun  3 17:43:32 Kamera_10 user.notice throttlewatch: currently: ok, temperature: 49 C
Jun  3 17:43:36 Kamera_10 user.err motion: [1:ml1:Kamera10] [ERR] [EVT] event_image_snapshot: Could not create symbolic link [2021-06-03/17-43-30.jpg]: Operation not supported
Jun  3 17:43:45 Kamera_10 user.err motion: [1:ml1:Kamera10] [ERR] [EVT] event_image_snapshot: Could not create symbolic link [2021-06-03/17-43-40.jpg]: Operation not supported
Jun  3 17:43:55 Kamera_10 user.err motion: [1:ml1:Kamera10] [ERR] [EVT] event_image_snapshot: Could not create symbolic link [2021-06-03/17-43-50.jpg]: Operation not supported
Jun  3 17:44:08 Kamera_10 user.err motion: [1:ml1:Kamera10] [ERR] [EVT] event_image_snapshot: Could not create symbolic link [2021-06-03/17-44-00.jpg]: Operation not supported
Jun  3 17:44:28 Kamera_10 user.err motion: [1:ml1:Kamera10] [ERR] [EVT] event_image_snapshot: Could not create symbolic link [2021-06-03/17-44-10.jpg]: Operation not supported
Jun  3 17:44:32 Kamera_10 user.notice throttlewatch: currently: ok, temperature: 49 C

**Comment by starbasessd** [comment]
What version of motion?
What version of motionEye?
Is it motionEye on another OS, or motionEyeOS? If mE on another OS, what's the base OS?
If mEOS, which version?
Are you doing:
Settings, File Storage, Storage Device, Network, or  
Settings, File Storage, Storage Device, Custom Path, and Media Upload?
What is the free local drive space on the PiZero?
