### ISSUE TITLE
remote configuration changes

### ISSUE THREAD

**Issue by sebPomme** [ccrisan/motioneye#2134]
Hi, 

Do you think it is possible to create some web endpoint to:
- `<GET=get | POST= enable| DELETE=disable>` notification `/api/v1/notification`
- `<GET=get | POST=enable | DELETE=disable>` motion detection `/api)/v1/motion_detection`
- Or some new idea ?

I think this can be useful to let another system (like homeassistant or jeedom or a custom script with curl) to enable / disable this features when no one is at home, or some more complex senarios.

**Comment by starbasessd** [comment]
Look at the document for motion:
https://motion-project.github.io/motion_config.html
Look for section beginning "Web Control"
Some of those features already exist in the motion back end.

**Comment by zagrim** [comment]
There have been others requesting this kind of thing, too, see #800 and #1223 and also #203 and #229. There are some ideas and workarounds in the comments.

**Comment by sebPomme** [comment]
@zagrim @starbasessd  
Verry usefull links thanks. I think we can close this one for the moment.
