### ISSUE TITLE
Motioneye video

### ISSUE THREAD

**Issue by monit-org** [ccrisan/motioneye#2144]
Hi, I want show videos,  not created by motioneye, on motioneye video output in browser. Is there any way to do that?

**Comment by starbasessd** [comment]
You can upload to the FTP or SMB folders if using motionEyeOS, if they are the same format (usually mp4) they should show up when you drill through the videos.
You need to enable Write feature in Settings, Services for whichever service you want to use.
If you want to upload to another OS running motion/motionEye, that is beyond the scope of my support, you should be able to find instructions for adding the share and settings.

**Comment by monit-org** [comment]
> You can upload to the FTP or SMB folders if using motionEyeOS, if they are the same format (usually mp4) they should show up when you drill through the videos.
I'm not using motionEyeOS, it only motionEye
> You need to enable Write feature in Settings, Services for whichever service you want to use.
Please can specify that in which serivce I have to do this,
> If you want to upload to another OS running motion/motionEye, that is beyond the scope of my support, you should be able to find instructions for adding the share and settings.

To be more specific, I'm making 1min video in motionEye, Sometime I want to view 30mint video, so I merge these 30 one mint videos into one, but the problem is that I can't view this 30mint merge video on motionEye video view section. I don't want to use FTP and other service to do that. Is it possible?

**Comment by starbasessd** [comment]
Where are you editing/creating them? They would have to be in the camera path.

**Comment by monit-org** [comment]
> Where are you editing/creating them? They would have to be in the camera path.

Yes, the video is in camera path.

**Comment by starbasessd** [comment]
Do you not see the file? What format is the original, and what format is the 30 minute file?

**Comment by monit-org** [comment]
> > Where are you editing/creating them? They would have to be in the camera path.
> 
> Yes, the video is in camera path.
> Thanks it workes.
