### ISSUE TITLE
Change port on Raspbian install?

### ISSUE THREAD

**Issue by dsbhough** [ccrisan/motioneye#215]
Hi,

First off, thanks very much for your work. 

I recently installed motioneyeOS and it's running great, I selected the port I wanted and so on. I've now decided to run Raspbian and install motioneye on it, however, I can't seem to change the port from the default - am I overlooking something on the interface?

Thanks again

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/wiki/Configuration-File#port
