### ISSUE TITLE
Missing options in motioneye on HA

### ISSUE THREAD

**Issue by s0res** [ccrisan/motioneye#2174]
hi ! im using motioneye on my raspberry pi 4 for several weeks now, but since the latest HA update, motioneye is missing... basically ALL options there was. im confused, can anyone help ?
![Screenshot_1](https://user-images.githubusercontent.com/89044525/129625462-800e1cd9-ffd1-4a4b-a82c-d53337ce76ee.png)

**Comment by starbasessd** [comment]
You are logged in as user, not admin. Previous screen, click the head, change user.

**Comment by s0res** [comment]
Hmmmm, didnt even know that was a thing. I don't have any other credentials tho, so im not quite sure what i did wrong

**Comment by s0res** [comment]
Okay, got it. I indeed confused my credentials with HA 🤦🏻‍♂️🤦🏻‍♂️🤦🏻‍♂️ thanks 4 ur help!!
