### ISSUE TITLE
Image rasbian?

### ISSUE THREAD

**Issue by Oxize** [ccrisan/motioneye#220]
Does anyone have a Rasbian Jessie with MotionEye working on it? I tried to install it yesterday following crisan his steps, but couldnt get it working. 

Would be nice if there was some image with Rasbian + MotionEye preinstalled on it so i could place it on my Pi3B.

**Comment by iSlide** [comment]
Hi
I've installed MotionEye on Raspbian Jessie on Pi3, and works fine.
Are you sure that you download the correct version?
First time I download wrong version?for Pi3?

**Comment by Oxize** [comment]
Yes i had Jessie version 27-05-2016 which is the lastest build. 

https://downloads.raspberrypi.org/raspbian_latest

I am using an Raspberry Pi 3B. I can try again to install it and let you guys know were it got stuck.

**Comment by Oxize** [comment]
When i add bcm2835-v4l2 to /etc/modules, it says at at startup this:

![image](https://cloud.githubusercontent.com/assets/3933702/16017331/a40dad4c-319f-11e6-8bc5-e5a7118ac087.png)

**Comment by sgiannulli** [comment]
CSI camera: enable it via `sudo raspi-config` and append `bcm2835-v4l2` to your `/etc/modules` file, then reboot.
do you mean `/usr/local/share/motioneye/extra/motioneye.conf.sample` is missing?

**Comment by Oxize** [comment]
Ye i had that with package from mrdave. I didnt run that today, and now i have the config sample.
Ive enabled the camera now also and tested it with modprobe. Camera is working.

Seems i can reach MotionEye now.

![motioneye](https://cloud.githubusercontent.com/assets/3933702/16019107/9ffac0b6-31a7-11e6-98e5-7c442f58e43d.png)

Thanks!
