### ISSUE TITLE
motioneye in docker motion detection menu missing?

### ISSUE THREAD

**Issue by boyphongsakorn** [ccrisan/motioneye#2209]
i install motioneye in docker this work but many menu is missing (like motion detection,webhook) (i login on admin)
![This is an image](https://i.ibb.co/HKcqmzk/image.png) https://i.ibb.co/HKcqmzk/image.png
how i fix this or motion detection not work on ccrisan/motioneye:master-armhf

**Comment by starbasessd** [comment]
@Korte68 How about some more info? 
BaseOS? Which version of docker? What is your docker run command?

**Comment by Korte68** [comment]
Home assistant core add-on install.

**Comment by starbasessd** [comment]
Just threw RaspberryPiOS Lite on a Pi3B+
Ran 
sudo apt update && sudo apt upgrade -y
sudo reboot
sudo apt install docker.io -y
sudo usermod -aG docker pi
sudo reboot
docker run --name="motioneye" \\
-p 8765:8765 \\
--hostname="motioneye" \\
-v /etc/localtime:/etc/localtime:ro \\
-v /etc/motioneye:/etc/motioneye \\
-v /var/lib/motioneye:/var/lib/motioneye \\
--restart="always" \\
--detach=true \\
ccrisan/motioneye:master-armhf 
Opened web browser on Win10
Connected to http://ip_address:8765
Added Network camera \(d-link DCS-5020L\)
Screenshots showing Motion Detection, and both locations with Web Hooks.
![image](https://user-images.githubusercontent.com/20134429/138168926-283cc068-1f6c-4330-a7f4-a90c849e00da.png)
![image](https://user-images.githubusercontent.com/20134429/138169055-8dacc3e1-d9c6-4a0c-bfd2-8ea4ac746bac.png)
![image](https://user-images.githubusercontent.com/20134429/138169226-9be937b9-e427-492d-a3e7-569c18193931.png)
All functioning normally.
I would suggest setting up a separate docker, or direct install, if you don't get any help from HA Community.
