### ISSUE TITLE
Custom hostname?

### ISSUE THREAD

**Issue by Fudge0952** [ccrisan/motioneye#221]
MotionEyeOS has this feature

ref: https://github.com/ccrisan/motioneyeos/issues/103

Just wondering if it's coming to the standalone?

**Comment by ccrisan** [comment]
Nope. motionEye has nothing to do with the hostname of the system it runs on.

**Comment by Fudge0952** [comment]
I mean like being able to change the hostname of it? OS version has a Hostname: ____ field. Right now my pi box is named "pi2" but when I connect is there any way I can possibly have a more user friendly named like "Surveillance System" without compromising the hostname field for easy ssh'ing?

**Comment by ccrisan** [comment]
Unfortunately no. The only thing you can do is to change the title of the window with ?title=sometitle

**Comment by Fudge0952** [comment]
Ok no worries

**Comment by ioquatix** [comment]
My system has multiple hostnames. How do I select which one is shown?

**Comment by ccrisan** [comment]
@ioquatix you have posted on both motionEye and motionEyeOS issue trackers. Which one are you really using?

motionEye will display whatever `socket.gethostname()` returns. You could override the title if that's what's bothering you, using ?title=sometitle.

**Comment by ioquatix** [comment]
I'm using both -I'm using one on a RPI for a camera and one on a arch linux box as a public server.
