### ISSUE TITLE
Cpu Load after reboot

### ISSUE THREAD

**Issue by iSlide** [ccrisan/motioneye#222]
Hi,
I've MotionEye installed with Raspbian.
I looked that when I start the Raspbian the cpu load is 0%, after the first access to MotionEye by browser,the cpu load is 23-25% and also when I logout of MotionEye the cpu load is stable to 25%. 
Now I'm not sure that the MotionEye automatic start with Raspbian, but only after first Login.
Is it correct this procedure? Is correct cpu load?
Many thanks for your support

**Comment by ccrisan** [comment]
That sounds about right.

**Comment by iSlide** [comment]
perfect, I'm very happy.
I've a question, is motioneye active also without first access by browser with cpu load 0%?

many thanks

**Comment by ccrisan** [comment]
motionEye is "active" but streaming starts on demand. It will stop after 10 seconds of idling.
