### ISSUE TITLE
Debian 11 Bullseye

### ISSUE THREAD

**Issue by kurazli** [ccrisan/motioneye#2220]
Did anyone successfully install motioneye on Debian 11 Bullseye yet?
Are there any plans to support Debian 11?

**Comment by starbasessd** [comment]
Will re-test Debian instructions in a bit.

**Comment by starbasessd** [comment]
Created a subset of the original instructions oriented to Debian 11 Buster, confirmed Working.

**Comment by kurazli** [comment]
works, thank you!

**Comment by starbasessd** [comment]
Thank you for pointing it out. Glad it's working for you.

**Comment by starbasessd** [comment]
More camera issues explained by RPiFoundation:
https://www.raspberrypi.com/news/bullseye-camera-system/#comment-1566990
