### ISSUE TITLE
video streaming problem

### ISSUE THREAD

**Issue by iSlide** [ccrisan/motioneye#223]
Hi,
after a reboot the video streaming of the camera is blocked. But if I change a value of setup and then click on "APPLY" all video streaming work fine.
Can you help me?

Many thanks for you support

**Comment by ccrisan** [comment]
What camera type do you use? If it's a USB webcam, it might be a problem with the driver.

**Comment by iSlide** [comment]
Hi,
I use only lan camera. 3 D-Link cameras and 3 VStarcam cameras.
In the past I used a microsoft usb camera but now it's delete.

Many thanks for you help.

**Comment by ccrisan** [comment]
I'm sorry but I think I won't be able to help you with this one. Buggy camera drivers may often cause motion to crash or to hang.
