### ISSUE TITLE
Motioneye SSH Sudo Commands Not Working?

### ISSUE THREAD

**Issue by IsmaelPR1977** [ccrisan/motioneye#2233]
I have the latest version of Motioneye on my Raspi 3 B+ with 2 usb cameras and all is working well. All I want to do is swap the order that they appear in but no matter what I try in SSH (Putty) I get a **-sh: sudo command not found**. What exactly is going on? I just want to rename the camera-1.conf and camera-2.conf files (swap them) through Putty, is that not possible?

Thanks!
Iz

**Comment by starbasessd** [comment]
Running motionEye or motionEyeOS?
If motionEyeOS, you are already admin/root, no need to use sudo.
If you want to modify conf files, mod the ones in /data/etc (most of the OS is read-only)

**Comment by IsmaelPR1977** [comment]
I am running MotioneyeOS. So I can just use the commands without sudo?

**Comment by starbasessd** [comment]
Correct.

**Comment by IsmaelPR1977** [comment]
Thank you for clearing that up so quickly! All set now.
