### ISSUE TITLE
Why is feature development stopped?

### ISSUE THREAD

**Issue by developerfromjokela** [ccrisan/motioneye#2252]
@ccrisan

**Comment by developerfromjokela** [comment]
@starbasessd if this is a duplicate question, please link the original issue.

**Comment by starbasessd** [comment]
After so many requests for updates, I stopped.

**Comment by starbasessd** [comment]
And, technically it's not 'stopped', Just that ccrisan hasn't posted any. Jawsper and Jasaw and others have posted updates, fixes, a new build, and there are several forks out there...

**Comment by developerfromjokela** [comment]
> And, technically it's not 'stopped', Just that ccrisan hasn't posted any. Jawsper and Jasaw and others have posted updates, fixes, a new build, and there are several forks out there...

Could you link repos with active builds?

**Comment by starbasessd** [comment]
I can't support Jawsper's build (I don't have an RPiZeroW2) but it's in thread 
https://github.com/ccrisan/motioneyeos/pull/2829
Do you expect every github project to cross link with every other forked project?
