### ISSUE TITLE
broken/missing icons on motioneye server

### ISSUE THREAD

**Issue by jcherndon** [ccrisan/motioneye#226]
I have a centos7 box with 0.32 motioneye install installed but the image labels are missing.
Ideas?

**Comment by ccrisan** [comment]
Make sure you have the `/etc/mime.types` file present. I found [this](https://bugzilla.redhat.com/show_bug.cgi?id=251908) link that might help, although I have no experience with centos.

**Comment by jcherndon** [comment]
awesome, works, thanks!
