### ISSUE TITLE
ERROR: could not start mjpg client for camera id 1: not enabled or not local

### ISSUE THREAD

**Issue by Maja61** [ccrisan/motioneye#2262]
Hi all,

i get an error on my Pi4 bullseye installation during startup of Motioneye. 

`● motioneye.service - motionEye Server
     Loaded: loaded (/etc/systemd/system/motioneye.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-01-04 10:02:44 CET; 9min ago
   Main PID: 416 (meyectl)
      Tasks: 5 (limit: 4915)
        CPU: 48.140s
     CGroup: /system.slice/motioneye.service
             ├─416 /usr/bin/python2 /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf
             └─937 /usr/bin/python2 /usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf

Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 2: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 2: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 2: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 2: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 2: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 2: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 2: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 1: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 1: not enabled or not local
Jan 04 10:12:13 MotionPi meyectl[416]:    ERROR: could not start mjpg client for camera id 1: not enabled or not local
`

i made a backup of an older debian 10 installation on a fresh debian 11 installation and i am not able to start my cameras. There is also no Motion Version visible on the GUI, i think it is related to my problem. 

![Motion](https://user-images.githubusercontent.com/33453078/148037192-cd555a68-17f5-4198-9e20-f3812b179b1a.png)

What could be wrong?

**Comment by starbasessd** [comment]
It appears motion is not installed, or at least discovered.
Also, check permissions of camera-X.conf files, they should be 644 root:root
I would, at a minimum go through the install instructions from:
https://github.com/ccrisan/motioneye/wiki/Install-on-Debian-11-(Bullseye)
You may have used the old instructions for Debian Buster...
I just checked the install instructions for Bullseye on a clean fully updated Debian Bullseye
on 22 Dec 2021. I can check again if needed.

**Comment by Maja61** [comment]
during troubleshooting i found a lots of issues with my system, thats why i decided to make a complete new installation. Now its running again. Thx and close :-)
