### ISSUE TITLE
authentication

### ISSUE THREAD

**Issue by jfbdevs** [ccrisan/motioneye#227]
I just installed motioneye, but unfortunately I am unable to understand how authentication works.
I can access with admin - no password.
Where can I change this? I couldn't see it in the wiki.
Thanks!

**Comment by ccrisan** [comment]
Use the admin password field.

**Comment by jfbdevs** [comment]
thanks ccrisan, sorry to be such a beginner... but can I ask you where do I find it the password field? I have been looking around the UI and found only how to enable authentication for streaming..

**Comment by ccrisan** [comment]
It's the 7th field from the top in the settings menu.

**Comment by jfbdevs** [comment]
ok I guess I have some problems to see the menu then... sorry I will check again and post if I have problems

**Comment by ccrisan** [comment]
posting a screenshot could help.
