### ISSUE TITLE
Login info

### ISSUE THREAD

**Issue by recfrf44** [ccrisan/motioneye#2273]
how to make the code of the main page not visible when authorizing in the background?

**Comment by starbasessd** [comment]
What are you referring to? Screen Shot maybe?

**Comment by recfrf44** [comment]
and another html code, I want to see only the authorization window, without unnecessary information

![pi](https://user-images.githubusercontent.com/52332812/149671123-d0396954-c1e5-4a06-bb4f-bf5f4aaa7d7a.png)

**Comment by starbasessd** [comment]
What is 'unnecessary info'? You could re-write the python login code, I suppose, if you don't want to see which motionEye you are logging into, You can remove the temperature wherever you added it, etc.

**Comment by recfrf44** [comment]
any information other than the authorization window is insecure. Authorization must go first, and then the rest

**Comment by starbasessd** [comment]
No different than any other website anywhere on the internet.
