### ISSUE TITLE
Time Zone without GMT or UTC references - Wrong Daylight Saving Time (DST) for Brazil

### ISSUE THREAD

**Issue by rtek1000** [ccrisan/motioneye#2276]
Hi,

Please, add "GTM-x"/"GTM+x" or "UTC-x" / "UTC+x" to each line in the time zone list.

The time in "America/São Paulo" is wrong (UTC-2).

Brazil no longer has daylight saving time (UTC-3).

As there is no "UTC" or "GTM" reference, I don't know which GTM-3 alternative I can use.

You have to keep searching on the Internet which country uses GTM-3, it is unnecessary if the reference is already on the list.

Thank you.

**Comment by starbasessd** [comment]
It's not motionEye, motionEye & motionEye in docker pulls time, date and zone from the host OS. I am sure timezone info will be updated in the next build update for motionEyeOS.
