### ISSUE TITLE
USB camera losing access

### ISSUE THREAD

**Issue by rtek1000** [ccrisan/motioneye#2279]
Hi,

After resolving the power supply issue, which was causing MotionEyeOS to restart, and the Raspberry Pi 3's red LED flashing,

The USB camera started to lose connection.

Sometimes MotionEyeOS could not find the camera to add.

So I glued a heatsink to the board, and it stopped failing. This glue is better than adhesive because it can fill in spaces better. But it's strong, don't try to pull it later, make sure you don't need to remove the heatsink.

I thought it was the camera that was getting too hot from the sun, but it was the Raspberry Pi that was getting hot, the USB ports were facing up, the board was upright, and the USB connectors were quite hot.

The board was inside an airtight box. I believe that a lot of people use this way, so I came to comment on this sink,

I found an image on the internet about the heating of the board and this reinforces the need to use a heatsink, which should accompany the board.

![Screenshot_20220118-123408](https://user-images.githubusercontent.com/8660811/149970115-dc0b29e3-7425-40df-9c51-3450e04534fd.png)
![Screenshot_20220118-123524](https://user-images.githubusercontent.com/8660811/149970219-15d5a828-95aa-46bd-bdd3-4bcb3c02e7f9.png)
![Screenshot_20220118-123606](https://user-images.githubusercontent.com/8660811/149970328-954f940a-e70b-469c-815c-af158857df2b.png)

**Comment by starbasessd** [comment]
You don't show airflow, or lack therof, which can also be a big issue. My best outdoor case is vertically mounted, airflow openings at the bottom, and divided to left is up, right is down, across heat sinks, fan at bottom right blowing out. No precipitation penetration. Outer case has aluminum foil on surfaces to reflect heat/sunlight. Works well for me.
