### ISSUE TITLE
Unable to install on RPi 3b+ linux 11 bullseye

### ISSUE THREAD

**Issue by mudassar791** [ccrisan/motioneye#2284]
Pkg is not upgrded for updated version of rpi 3b+.

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

**Comment by starbasessd** [comment]
What do you mean pkg is not upgrded for updated version of rpi 3b+?
I have a Pi3B+ with Bullseye and motionEye installed (using these [docs](https://github.com/ccrisan/motioneye/wiki/Install-on-Raspbian-Bullseye)) and running. You cannot use MMAL (CSI ribbon cameras due to RPiFoundation breaking the raspivid and raspipic support structure) but network and USB cameras still work.

**Comment by mudassar791** [comment]
![Screenshot_20220123_103620](https://user-images.githubusercontent.com/32223328/150666392-cdfd2dc9-97e2-47e8-9171-67ca395b1732.jpg)

**Comment by mudassar791** [comment]
Every thing got completed but facing error in CP, so service canot be iniitated and started.

**Comment by JohnZable** [comment]
I had the same issue.  You need to make sure both pip2 is installed, as pip3 installs in a different place, and you use sudo for the commands so you have write permission to the locations.

**Comment by starbasessd** [comment]
Looks like you may be installing as a 'normal' user. You need to install as sudo, THEN follow the instructions [here](https://github.com/ccrisan/motioneye/wiki/Running-As-Normal-User) to run as a normal user.

**Comment by starbasessd** [comment]
I just completed a new clean install using the following (from the Wiki for RaspberryPiOS-Bullseye) and it works as 'normal'. I then ran the Wiki for [Run as a Normal User](https://github.com/ccrisan/motioneye/wiki/Running-As-Normal-User)  and it is working 'normally'
[Install for RPiOS Bullseye plus motionEye.txt](https://github.com/ccrisan/motioneye/files/7920429/Install.for.RPiOS.Bullseye.plus.motionEye.txt)
Instructions for Install RPiOS-Bullseye updated with Testing date.

**Comment by mudassar791** [comment]
Thankyou so much, just started from writing pi os on memory card then followed you, working perfectly.
