### ISSUE TITLE
enable WiFi, motion not detected?

### ISSUE THREAD

**Issue by cyked82** [ccrisan/motioneye#238]
Let me know what logs you'd like to view..

I have a RPi 2 with the 5mp cam and it ran fine for a number of days.  It seems when I enable wifi (5g won't connect) the settings all seem fine and i can view the stream without issue, log in, etc. but motion is not detected and no motion capture images are saved.

Has this been an issue before?

**Comment by ccrisan** [comment]
Normally there's no connection between the motion detection and the network connection. Check your motion detection settings and make sure you have disabled working schedule.

**Comment by cyked82** [comment]
Thanks for replying.  I swear I'm not crazy and the initial setup was ethernet, motion sense on with motion notification emails.  I feel like enabling wifi flipped the flag on motion detection.  At any rate, motion was disabled and it works fine (of course) when motion detection is on.
