### ISSUE TITLE
Gmail refuse to send mail from motioneye

### ISSUE THREAD

**Issue by cpagura** [ccrisan/motioneye#239]
Motioneye 032 on Raspberry PI3 and raspicam NOIR v3.

All is ok, but It seems that now gmail server refuses to accept mail from "low security standard" app. As the matter of fact may be that meyectl when send e-mail is not "trusted" by gmail servers. 
Moreover, the motioneye interface write in clear all the parameters from web interface, pswd included, in "thread-1.conf", not a good policy, imho ...  ;-).

I will try another way to send e-mail notification ...

**Comment by cpagura** [comment]
I found the solution: increase the tolerance of gmail account! see:
https://support.google.com/accounts/answer/6010255?hl=en now all is working! ... even if not 100% safely :-)

**Comment by ccrisan** [comment]
@cpagura I agree that reducing the security level of your Google account is not desirable. However there is another way where you actually increase the security level while enabling separate apps to access your account the old way: https://support.google.com/accounts/answer/185833. In a nutshell, you enable two-steps verification for your Google account and you create separate passwords for each app you want to give access to your account. You'll then need to create a password for motionEye.

**Comment by pdesimonee** [comment]
@cpagura: I cannot find this thread-1.conf file in the email I receive. Help

**Comment by starbasessd** [comment]
@pdesimonee Open a new issue with your specifics. 
This issue was closed 5 years ago, and MANY things ( including motion, motionEye, and Google )have changed since then. I would be more than happy to help, but need YOUR CURRENT specifics.

**Comment by pdesimonee** [comment]
ok. Why, when I disable the email notification the configuration of the email get lost?. Sometime I want the email [when I am on leave] sometimes not. But the configuration should not be lost every time I switch off the notification. How to go around it?

**Comment by starbasessd** [comment]
@pdesimonee ignored for not following directions. This issue is closed and now locked.
