### ISSUE TITLE
Frames captured during motion gap

### ISSUE THREAD

**Issue by Shinao** [ccrisan/motioneye#24]
First of all, thanks for the soft, it's amazing.

I've got a 'Motion Gap' of 600, meaning that if the motionpie detect a motion, it will only send a notification once, and wait for a 10 minutes no-motion before detecting another one.

This part works and it's great, but it still takes pictures when it detects something, so I've got 300+ shots taken in minutes (but only 1 notification), and the storage is full in a matter of hours.
I don't think it's supposed to happen.

Also I'm using the latest version of motionpie with motioneye 20150719 (Up-to-date apparently)

Thanks.

**Comment by ccrisan** [comment]
There's no way (that I know of) to configure motion so that it doesn't take picture snapshots during that period, other than completely disabling still images.
