### ISSUE TITLE
Monitoring commands

### ISSUE THREAD

**Issue by Redferne** [ccrisan/motioneye#240]
Hi, 

Please help getting the monitoring command working, followed the example below but I get nothing overlayed on the stream. No usable information in the debuglog. 
https://github.com/ccrisan/motioneye/wiki/Monitoring-Commands

BR, 
Rickard

**Comment by ccrisan** [comment]
1. What version?
2. Where have you placed the file?
3. What name did you give the file?
4. Did you make it executable?
5. If you run it manually from the command line, does it return immediately and output the expected text? If yes, which is the text?

**Comment by maglub** [comment]
You will get the output of the monitoring command in the "border" of the camera, when you click on the camera in question.

![image](https://cloud.githubusercontent.com/assets/2961018/16546178/c0472198-4142-11e6-98e4-560d2987a426.png)

**Comment by Redferne** [comment]
Ah, now I see. It works here aswell, but I was expecting it to be "burnt
into the stream/screenshot".
Is it possible to add this functionality? Cameraname and Timestamp is
currently beeing "burnt into the image".
That would be a very powerful option, we can have a small table on the
topleft with all kind of information :-)

BR,
Rickard

**Comment by ccrisan** [comment]
Nope, that's not possible as it would require changing the source code of motion.

**Comment by maglub** [comment]
A workaround would be to use the MotionHttpApi, sending the text you would like to burn in per "curl".

I did this:

* On the motioneye, find the "webcontrol_port" which should be 7999

```
[root@meye-77c702cd etc]# grep control *
motion.conf:webcontrol_localhost on
motion.conf:webcontrol_html_output on
motion.conf:webcontrol_port 7999
```

* Use "curl" to send a new text to the text you want:

```
[root@meye-77c702cd etc]# curl http://localhost:7999/2/config/set?text_left="my%20text"
```

Before:

![image](https://cloud.githubusercontent.com/assets/2961018/16567649/56759d46-4221-11e6-9b86-3e79c281fa2f.png)

After:

![image](https://cloud.githubusercontent.com/assets/2961018/16567677/8f70d8d6-4221-11e6-88b8-289a5034bd69.png)

**Comment by ccrisan** [comment]
@maglub actually that is a great idea indeed. I never thought of that. Thanks for sharing it with us.
