### ISSUE TITLE
Adding remote motioneye camera

### ISSUE THREAD

**Issue by KrisJoyce** [ccrisan/motioneye#247]
Thanks for motioneye I love it.

My issue is when I try to add a second camera in motioneye, in the camera drop down menu it says "no camera".
I have added one previously and worked, but if I try to add the first one again it shows "no camera" as well. Both camera are set for Fast Network camera.

Thanks

**Comment by ccrisan** [comment]
You can have only one Fast Network Camera per motionEyeOS unit. There are however two things that are unclear to me:

* Fast Network Camera is available only with motionEyeOS, not with a plain motionEye install; are you actually running motionEyeOS, even though you have opened the issue for motionEye?
* When you have enabled the Fast Network Camera mode, the camera dropdown menu should no longer be displayed. Can I see a screenshot of your camera dropdown menu as well as of the Fast Network Camera setting?

**Comment by KrisJoyce** [comment]
I have two raspberry Pi running motionEyeOS with 1 CSI camera on each. With a PC running MotionEye to do the motion detection and recording.

![camera1](https://cloud.githubusercontent.com/assets/20348181/16691181/d017e3d8-44e8-11e6-89f9-0e300820a750.JPG)
![motioneye server](https://cloud.githubusercontent.com/assets/20348181/16691182/d024c062-44e8-11e6-91ff-4708305548ea.JPG)
![camera2](https://cloud.githubusercontent.com/assets/20348181/16691183/d03d2080-44e8-11e6-84be-ffb06ab795f1.JPG)

**Comment by ccrisan** [comment]
If you're trying to add Fast Network Cameras to a motionEye server then you'll have to add them as... well... Network Cameras. They are not managed as motionEye cameras.

**Comment by KrisJoyce** [comment]
When I try that I get "not a supported network camera".

**Comment by ccrisan** [comment]
Most likely you tried to add the web interface (port 80). Use port 8081 or whatever streaming port you have configured for your Fast Network Camera.

**Comment by KrisJoyce** [comment]
You help worked but now I get "An error occurred. Refreshing is recommended." I did this several time and it does not add the camera.

**Comment by ccrisan** [comment]
Please send me your motioneye.log file. You can obtain it by running `journalctl -u motioneye > motioneye.log`.

**Comment by KrisJoyce** [comment]
I did a quick check and found out my storage was full. I emptied it and was able to and the 2nd camera.

Thank you very much for all you help.

**Comment by ccrisan** [comment]
Happy to help.
