### ISSUE TITLE
Changing Admin username?

### ISSUE THREAD

**Issue by Fudge0952** [ccrisan/motioneye#250]
Don't know if it's by design, but is there any way of changing the administrator's username to access the system?

**Comment by ccrisan** [comment]
It's by design.

**Comment by Bluscream** [comment]
Any news on this? i would like to choose a harder to guess admin name.

**Comment by yed30** [comment]
I totally agree with @Bluscream. 
The way I found was to edit /etc/motioneye/motion.conf and change the below line like (in bold):
# @admin_username **myadminusername**
then restart MotionEye
I hope this help

**Comment by ccrisan** [comment]
This works (and used to work this way) but when you'll try to log in using SSH, FTP or SMB, you'll see that your new admin user won't work. This is because it's difficult to update the username for all these services.

**Comment by Bluscream** [comment]
@yed30 thank you very much <3

**Comment by yed30** [comment]
Thanks @ccrisan for your answer. I just use MotionEye web frontend (which I find very handy ! :) ), behind a NGinx server, so I guess this shouldn't be a problem.

**Comment by DelightedD0D** [comment]
Might be useful to have the ui show "admin" in the readonly field and remove the red exclamation icon indicating that its a "required field". Its super confusing as it stands as the UI tells you that you have to fill in this non-functional field.
