### ISSUE TITLE
Recorded and visualized video imperfections

### ISSUE THREAD

**Issue by lozziboy** [ccrisan/motioneye#252]
I started using motionEyeOs for raspberry PI2 recording video from two IP network cameras (RTSP) 1280x720p.
I encountered some imperfection in the video visualized by the motioneye daemon and consequently into the recorded and stored video. 
The two IP cameras are connected via ethernet cable and if i try to capture the RTSP with my laptop (VLC media player) there aren't imperfections.
I thought the reason was the poor power of the raspberry pi2 and so i upgraded my system switching it onto an ubuntu server (Amd quad core 2,1 Ghz processor + 4gb ram ddr3) but to my great surprise the issue remains. In the system monitor the CPU resource is used at 26/28 % and what i think now is that there should be something wrong in the motioneye daemon.

Here there are some pictures about the problem

![motioneye issue 1](https://cloud.githubusercontent.com/assets/16566804/16894984/e6d8aaa0-4b67-11e6-9936-2aa538a9292b.jpeg)
![motioneye issue 2](https://cloud.githubusercontent.com/assets/16566804/16894985/e6dde51a-4b67-11e6-8251-872c1917b134.jpeg)
![motioneye issue 3](https://cloud.githubusercontent.com/assets/16566804/16894986/e6e00ae8-4b67-11e6-8515-cd8f4bdc0470.jpeg)

**Comment by lozziboy** [comment]
Problem solved!
The issue was related to the internet protocol used (UDP).
So, what i suggest is to use TCP in order to avoid any imperfection.

![motioneye solution](https://cloud.githubusercontent.com/assets/16566804/16995967/492a888c-4eaf-11e6-9889-22b1a4b1b758.jpeg)

**Comment by ccrisan** [comment]
Hmm, you're not the first one to have a better RTSP experience with TCP. I'll make sure TCP comes as the first option from now on.
