### ISSUE TITLE
Message: An error occurred. Refreshing is recommended.

### ISSUE THREAD

**Issue by lozziboy** [ccrisan/motioneye#259]
Hello Calin,
after some weeks of perfect working i got this error in the motioneye service.
No video are visualized and if i try to refresh the page the problem appears again.
What can i do in order to help you find the reason?

UPDATE: This issue lastest for three hours and then motioneye restarted working normally without any human intervention. 
The only change i made in the last days was the RTSP video acquisition via TCP option, can be the issue related to this?  

![error](https://cloud.githubusercontent.com/assets/16566804/17059301/cc85ffba-5024-11e6-9eff-98e3c849c564.gif)

**Comment by ArmandH** [comment]
Maybe something was hanging, motioneyeos has watchdog enabled by default, so could be that your OS has rebooted.

Checkout if you find anything related in the troubleshooting section:
https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting

**Comment by luetzel** [comment]
I had exactly the same problem. No way to add one of my remote MotionEye Cams using the 'Add Camera' dialog, although I was able to reach the camera's control interface. However, I was able to fix this issue, by copying and editing /etc/motioneye/thread-2.conf, changing both # @id and # @host.
Only one out of four camera devices was affected, all having 0.33 installed.

**Comment by woodboy12** [comment]
I had this problem. Check your storage space available. Mine was completely full. Motioneye started giving me errors when trying to adding cameras and ssh'ing into the system. I started from scratch with a new SD card and everything seems to work fine now.

**Comment by starbasessd** [comment]
@woodboy12 This issue was opened 5 years ago. I doubt it is being followed now.
