### ISSUE TITLE
1080p support

### ISSUE THREAD

**Issue by cvpeck** [ccrisan/motioneye#269]
Hi, 1080p picture size isn't supported in the video size options. Works fine if I manually edit the thread config files but gets reset every time I open the camera configuration. Just need 1200x1080 adding.

**Comment by ozett** [comment]
👍

**Comment by ericjanvanputten** [comment]
1920x1080 added rigth? :)

**Comment by ccrisan** [comment]
It is now, if you use motion 4.0 and a camera that supports that resolution.
