### ISSUE TITLE
failed to read settings, unknown configuration option

### ISSUE THREAD

**Issue by sinbrkatetete** [ccrisan/motioneye#27]
Total noob here, sorry for possibly using the wrong channel to seek help and perhaps report an issue. Please do point me in the right direction if it's not too much trouble.

I'm trying to set up an EC2 Ubuntu server instance and motioneye on it, to control two of my raspberry pis running motionpie (since one of them is a B version, I'd like to try and set it up as a fast network cam and do all the motion work on the EC2 instance). I've followed your installation instructions for Ubuntu and got to the starting of the motionEye server, but the following pops up:
"CRITICAL:root:failed to read settings from "/etc/motioneye/motioneye.conf": unknown configuration option: motion:control_localhost"

I'm using your sample conf as the starting conf file. http://pastebin.com/0dW0G1SS

**Comment by ccrisan** [comment]
What version of motionEye do you use?

**Comment by sinbrkatetete** [comment]
Hey. Thanks for taking the time to answer. Even bigger thanks for taking the time to bring us these great tools. I'm using version 0.28.1
I've commented the setting out and now I'm testing what does and what does not work.... For now, I've managed to connect the cameras as remote MotionEye cameras. It seems the my local upload speed poses the biggest problem.

**Comment by pengocha** [comment]
Got the same here today, sorry for the double post.

**Comment by ccrisan** [comment]
It's a known bug, recently fixed. The fix will be available in 0.28.2. Until then, please just comment out "motion_control_localhost" in your motioneye.conf.

**Comment by pengocha** [comment]
I put '#' before motion_control_localhost true, get message back saying: 'CRITICAL:root:failed to read settings from "/etc/motioneye/motioneye.conf": invalid configuration line: '

**Comment by ccrisan** [comment]
Can I see your config file?

**Comment by pengocha** [comment]
Sure: http://pastebin.com/zv0iuEvc

**Comment by ccrisan** [comment]
Your config file seems alright. Are you sure you don't have any hard-to-spot stray character somewhere in the file?

**Comment by pengocha** [comment]
Not that i know or see. For tonight im done. I'll try tommorow to delete the entire file and replace it with the one pasted by sinbrkatetete earlier. Maybe that will help. I'll let you know.

**Comment by pengocha** [comment]
You where right, on top of motioneye.conf was an lost $. All working again. Thanks so much !!
