### ISSUE TITLE
Web-UI -> Motion Notifications Settings Issue

### ISSUE THREAD

**Issue by helgetnt** [ccrisan/motioneye#274]
Hallo...
first sorry for my english. I'm from Germany. I've found an issue in the Web-UI -> Motion Notifications Settings. After i type my settings in and press Apply it goes right to the config file (and does the job) but in the Web-UI the options are not in the right line and some are missing. If i make all other changes in the settings before the notifications i've no problem, but if not i have to retype my mail-settings. please have a look at these, because it's quite terrible. 

THX

**Comment by drcyber** [comment]
Hi,
first of all thanks for this Nice Software!
I have the same Problem. The testmail works and when i click "Apply" the Settings are moved up one line.
im Runnig it on an RasPi3 with Jessie.

**Comment by ccrisan** [comment]
Please try configuring it from scratch. There have been many changes when it comes to configuration since 1 year ago.

**Comment by drcyber** [comment]
Thank you , now its working :)
