### ISSUE TITLE
grey screen when connecting via rtsp... help needed

### ISSUE THREAD

**Issue by an6059** [ccrisan/motioneye#282]
Hi I am running motioneye version .33 on Debian jessie 

I can connect to my rtsp camera via rtsp://192.168.1.27:554/ in the camera device field but all I get on the camera is " unable to connect to video device "  - a grey screen 

This same camera ( Qcam IP2m822E )   works fine with VLC and i can see video , it also works with motioneyeos ( raspberyy PI2 )  , but i want to use it with  Debian jessie.

Video recording lags / slow  on Raspberry Pi2, so want to switch to use a desktop PC 

I have read lots of the threads and says to switch to Mr_Dave motion to solve issue but I have no idea how to change to that version ,  so simple instructions for that would be great ( beginner to linux )  , if I am going down the right path to solve this . If i'm not on right path any help to solve this would be great 

Thanks in advance 
![screenshot from 2016-08-14 10 58 19](https://cloud.githubusercontent.com/assets/21025269/17650892/5f6d3866-620e-11e6-97a4-1eeb412e71f0.png)

![screenshot from 2016-08-14 10 55 07](https://cloud.githubusercontent.com/assets/21025269/17650880/c24f9a88-620d-11e6-874a-4803aa4c985d.png)
![screenshot from 2016-08-14 10 57 49](https://cloud.githubusercontent.com/assets/21025269/17650888/1e74cd24-620e-11e6-9343-f74489cbdd80.png)

**Comment by ccrisan** [comment]
Motion 3.2.12 does not support RTSP. Please follow [these instructions](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian) to get a newer version of motions on your Raspbian.
