### ISSUE TITLE
Change request: change the direction of the scroll arrows when looking at still pictures

### ISSUE THREAD

**Issue by Rouzic6666** [ccrisan/motioneye#283]
Hello,
Actualy the right arrow go to the past and left to the futur. Can you change the role of arrows? it would be more natural.

**Comment by ccrisan** [comment]
Indeed, media file browsing feels reversed to me as well. I will make sure to fix this.

**Comment by ccrisan** [comment]
3eaeb4edb303705864251da6d5d07d26e96f5b89 fixes this issue.
