### ISSUE TITLE
unknown configuration option: motion_control_localhost

### ISSUE THREAD

**Issue by pengocha** [ccrisan/motioneye#29]
Hi, i recently changed webcams, deleted webcam from the gui and added the new cam. It worked at first but after a system reboot the gui was no longer reachable on the adress i always use. I updated motioneye today in an attempt to fix it but no such luck. I always start motioneye with $ sudo meyectl startserver -b -c /etc/motioneye/motioneye.conf that always worked but now i'm getting error: 'CRITICAL:root:failed to read settings from "/etc/motioneye/motioneye.conf": unknown configuration option: motion_control_localhost'. 
Can anyone advice? Thx alot!

**Comment by ccrisan** [comment]
It's a known bug that has been fixed and will be included in 0.28.2. Until then, please just comment out the "motion_control_localhost" in your motioneye.conf.
