### ISSUE TITLE
Feature request: change interval of snapshots

### ISSUE THREAD

**Issue by dancorrigan1** [ccrisan/motioneye#295]
I can't seem to find this ability in motioneye UI or the motion.conf thread files it creates. 1 picture every second is way too much. Apologizes if I'm just missing this existing setting.

**Comment by ccrisan** [comment]
Set *Still Images* > *Capture Mode* to *Interval Snapshots*.

**Comment by dancorrigan1** [comment]
How the hell did I miss that... jezzz..

Thanks.

**Comment by dancorrigan1** [comment]
Well.. Can you change the interval of snapshots that get triggered BY motion detection ?
