### ISSUE TITLE
install on debian - no working gui

### ISSUE THREAD

**Issue by speeskeek** [ccrisan/motioneye#298]
when installing on debit wheezy, I get a  non functional web UI.
I'm running behind ngix.
seems to me nginx can't find the image files and css files.

thank you for your help.

![motion](https://cloud.githubusercontent.com/assets/8826404/18133247/16ad18dc-6f9a-11e6-89b8-0a53a78118d1.png)

**Comment by speeskeek** [comment]
get the same when going to http://IP:8765


when I try to locate a (missing) image:
http://IP:8765/cams/static/img/motioneye-logo.svg
gives me {"error": "not found"}

**Comment by ccrisan** [comment]
have you set [base_path](https://github.com/ccrisan/motioneye/wiki/Configuration-File#base_path) to `/cams`?

**Comment by speeskeek** [comment]
Yes ...

**Comment by ccrisan** [comment]
Well the base path won't change the address at which the motionEye server *serves* the static files; It will only change the location embedded in the HTML at which the static files will be *requested*. They should still be available at /static/... when accessing the motionEye server directly. However, nginx should forward everything that starts with /cams to /, to the motionEye server.

**Comment by speeskeek** [comment]
Thats why I have this:

`location /cams/ {
proxy_pass http://192.168.1.250:8765/;
proxy_read_timeout 120s;
access_log off;
}`

No?

**Comment by ccrisan** [comment]
Yeap. Try debugging the requests issued by nginx towards motionEye. The must *not* contain the /cams prefix.

**Comment by speeskeek** [comment]
I dont understand what you mean.

But should surfing to http://IP:8765 give me a fully working interface?

**Comment by speeskeek** [comment]
ok, I got it working by simlinking the static dir in my /var/www/cams/static to 
/usr/local/lib/python2.7/dist-packages/motioneye/static


maybe dirty, but it works

**Comment by ccrisan** [comment]
The http://IP:8765 link should *not* give you a working interface after having set base_path to something different than the default. The reason is that the HTML served will contain links formed in such a way that they are valid when accessed through the reverse proxy (nginx), and not directly.

The help buttons probably are working, but not the way you'd expect them to. Just hover them with the mouse and you'll see a tooltip.
