### ISSUE TITLE
failed to get motion detection status for camera with id

### ISSUE THREAD

**Issue by francesconuma** [ccrisan/motioneye#3]
Any hint?

2015-08-31 18:12:10: [motioneye]     INFO: hello! this is motionEye server 0.27.1
2015-08-31 18:12:15: [motioneye]     INFO: cleanup started
2015-08-31 18:12:15: [motioneye]     INFO: wsswitch started
2015-08-31 18:12:15: [motioneye]     INFO: thumbnailer started
2015-08-31 18:12:15: [motioneye]     INFO: server started
2015-08-31 18:12:25: [motioneye]    ERROR: failed to get motion detection status for camera with id 1: HTTP 599: Failed to connect to 127.0.0.1: Network is unreachable
2015-08-31 18:12:25: [motioneye]  WARNING: skipping motion detection status update for camera with id 1
2015-08-31 18:12:35: [motioneye]    ERROR: failed to get motion detection status for camera with id 1: HTTP 599: Failed to connect to 127.0.0.1: Network is unreachable
2015-08-31 18:12:35: [motioneye]  WARNING: skipping motion detection status update for camera with id 1
...
2015-08-31 18:15:05: [motioneye]    ERROR: failed to get motion detection status for camera with id 1: HTTP 599: Connection timed out after 5041 milliseconds
2015-08-31 18:15:05: [motioneye]  WARNING: skipping motion detection status update for camera with id 1
2015-08-31 18:15:15: [motioneye]    ERROR: failed to get motion detection status for camera with id 1: HTTP 599: Connection timed out after 5041 milliseconds
2015-08-31 18:15:15: [motioneye]  WARNING: skipping motion detection status update for camera with id 1
2015-08-31 18:15:17: [motioneye]  WARNING: control hue not found for device /dev/video0
2015-08-31 18:15:18: [motioneye]  WARNING: control hue not found for device /dev/video0
2015-08-31 18:15:19: [motioneye]  WARNING: control hue not found for device /dev/video0
2015-08-31 18:15:25: [motioneye]    ERROR: failed to get motion detection status for camera with id 1: HTTP 599: Connection timed out after 5041 milliseconds
....

syslog

Aug 31 18:18:06 camgrappa motion: [1] mmap information:
Aug 31 18:18:06 camgrappa motion: [1] frames=4
Aug 31 18:18:06 camgrappa motion: [1] 0 length=115200
Aug 31 18:18:06 camgrappa motion: [1] 1 length=115200
Aug 31 18:18:06 camgrappa motion: [1] 2 length=115200
Aug 31 18:18:06 camgrappa motion: [1] 3 length=115200
Aug 31 18:18:07 camgrappa motion: [1] Resizing pre_capture buffer to 1 items
Aug 31 18:18:07 camgrappa motion: [1] Started stream webcam server in port 8081
Aug 31 18:18:07 camgrappa motion: [1] Resizing pre_capture buffer to 3 items
Aug 31 18:18:36 camgrappa motion: [1] Calling vid_close() from motion_cleanup
Aug 31 18:18:36 camgrappa motion: [1] Closing video device /dev/video0
Aug 31 18:18:37 camgrappa kernel: [  424.008409] bcm2835-v4l2: error 0 waiting for frame completion
Aug 31 18:18:39 camgrappa motion: [0] Motion terminating
Aug 31 18:18:40 camgrappa motion: [0] Processing thread 0 - config file /etc/motioneye/motion.conf
Aug 31 18:18:40 camgrappa motion: [0] Processing config file thread-1.conf
Aug 31 18:18:40 camgrappa motion: [0] Unknown config option "locate_motion_style"
Aug 31 18:18:40 camgrappa motion: [0] Motion 3.2.12 Started
Aug 31 18:18:40 camgrappa motion: [0] ffmpeg LIBAVCODEC_BUILD 3482368 LIBAVFORMAT_BUILD 3478785
Aug 31 18:18:40 camgrappa motion: [0] Thread 1 is from thread-1.conf
Aug 31 18:18:40 camgrappa motion: [0] httpd bind(): Cannot assign requested address
Aug 31 18:18:40 camgrappa motion: [0] httpd thread exit
Aug 31 18:18:40 camgrappa motion: [1] Thread 1 started
Aug 31 18:18:40 camgrappa motion: [1] cap.driver: "bm2835 mmal"
Aug 31 18:18:40 camgrappa motion: [1] cap.card: "mmal service 16.1"
Aug 31 18:18:40 camgrappa motion: [1] cap.bus_info: "platform:bcm2835-v4l2"
Aug 31 18:18:40 camgrappa motion: [1] cap.capabilities=0x85200005
Aug 31 18:18:40 camgrappa motion: [1] - VIDEO_CAPTURE
Aug 31 18:18:40 camgrappa motion: [1] - VIDEO_OVERLAY
Aug 31 18:18:40 camgrappa motion: [1] - READWRITE
Aug 31 18:18:40 camgrappa motion: [1] - STREAMING
Aug 31 18:18:40 camgrappa motion: [1] Test palette YU12 (320x240)
Aug 31 18:18:40 camgrappa motion: [1] Using palette YU12 (320x240) bytesperlines 320 sizeimage 115200 colorspace 00000001
Aug 31 18:18:40 camgrappa motion: [1] found control 0x00980900, "Brightness", range 0,100 
Aug 31 18:18:40 camgrappa motion: [1] #011"Brightness", default 50, current 46
Aug 31 18:18:40 camgrappa motion: [1] found control 0x00980901, "Contrast", range -100,100 
Aug 31 18:18:40 camgrappa motion: [1] #011"Contrast", default 0, current 0
Aug 31 18:18:40 camgrappa motion: [1] found control 0x00980902, "Saturation", range -100,100 
Aug 31 18:18:40 camgrappa motion: [1] #011"Saturation", default 0, current 0
Aug 31 18:18:40 camgrappa motion: [1] found control 0x0098090e, "Red Balance", range 1,7999 
Aug 31 18:18:40 camgrappa motion: [1] #011"Red Balance", default 1000, current 1000
Aug 31 18:18:40 camgrappa motion: [1] found control 0x0098090f, "Blue Balance", range 1,7999 
Aug 31 18:18:40 camgrappa motion: [1] #011"Blue Balance", default 1000, current 1000
Aug 31 18:18:40 camgrappa motion: [1] mmap information:
Aug 31 18:18:40 camgrappa motion: [1] frames=4
Aug 31 18:18:40 camgrappa motion: [1] 0 length=115200
Aug 31 18:18:40 camgrappa motion: [1] 1 length=115200
Aug 31 18:18:40 camgrappa motion: [1] 2 length=115200
Aug 31 18:18:40 camgrappa motion: [1] 3 length=115200
Aug 31 18:18:40 camgrappa motion: [1] Resizing pre_capture buffer to 1 items
Aug 31 18:18:40 camgrappa motion: [1] Started stream webcam server in port 8081
Aug 31 18:18:40 camgrappa motion: [1] Resizing pre_capture buffer to 3 items
Aug 31 18:19:10 camgrappa motion: [1] Calling vid_close() from motion_cleanup
Aug 31 18:19:10 camgrappa motion: [1] Closing video device /dev/video0
Aug 31 18:19:11 camgrappa kernel: [  457.939604] bcm2835-v4l2: error 0 waiting for frame completion
Aug 31 18:19:13 camgrappa motion: [0] Motion terminating
Aug 31 18:19:13 camgrappa motion: [0] Processing thread 0 - config file /etc/motioneye/motion.conf
Aug 31 18:19:13 camgrappa motion: [0] Processing config file thread-1.conf
Aug 31 18:19:13 camgrappa motion: [0] Unknown config option "locate_motion_style"
Aug 31 18:19:13 camgrappa motion: [0] Motion 3.2.12 Started
Aug 31 18:19:13 camgrappa motion: [0] ffmpeg LIBAVCODEC_BUILD 3482368 LIBAVFORMAT_BUILD 3478785
Aug 31 18:19:13 camgrappa motion: [0] Thread 1 is from thread-1.conf
Aug 31 18:19:13 camgrappa motion: [0] httpd bind(): Cannot assign requested address
Aug 31 18:19:13 camgrappa motion: [0] httpd thread exit
Aug 31 18:19:13 camgrappa motion: [1] Thread 1 started
Aug 31 18:19:13 camgrappa motion: [1] cap.driver: "bm2835 mmal"
Aug 31 18:19:13 camgrappa motion: [1] cap.card: "mmal service 16.1"
Aug 31 18:19:13 camgrappa motion: [1] cap.bus_info: "platform:bcm2835-v4l2"
Aug 31 18:19:13 camgrappa motion: [1] cap.capabilities=0x85200005
Aug 31 18:19:13 camgrappa motion: [1] - VIDEO_CAPTURE
Aug 31 18:19:13 camgrappa motion: [1] - VIDEO_OVERLAY
Aug 31 18:19:13 camgrappa motion: [1] - READWRITE
Aug 31 18:19:13 camgrappa motion: [1] - STREAMING
Aug 31 18:19:13 camgrappa motion: [1] Test palette YU12 (320x240)
Aug 31 18:19:13 camgrappa motion: [1] Using palette YU12 (320x240) bytesperlines 320 sizeimage 115200 colorspace 00000001
Aug 31 18:19:13 camgrappa motion: [1] found control 0x00980900, "Brightness", range 0,100 
Aug 31 18:19:13 camgrappa motion: [1] #011"Brightness", default 50, current 45
Aug 31 18:19:13 camgrappa motion: [1] found control 0x00980901, "Contrast", range -100,100 
Aug 31 18:19:13 camgrappa motion: [1] #011"Contrast",

**Comment by ccrisan** [comment]
Have you re-added your camera after upgrading to 0.27? Or is this a completely new installation?

**Comment by francesconuma** [comment]
I removed the older version (folder and rc.local script) and installed the 0.27 as explained in the new wiki.
Also tried removing and reinstalling motion via apt-get (raspbian).
I also launched apt-get update /upgrade and firmware update on raspberry.
Maybe I can try from a new fresh image.
Regards.

**Comment by francesconuma** [comment]
A fresh install resolved the problem.
Now It's all working.
