### ISSUE TITLE
Error in service start

### ISSUE THREAD

**Issue by Lewatoto** [ccrisan/motioneye#30]
Hello, I have this error, i follow this guide https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian and install motion-mrdave, Raspbian Jessie, Rpi 2 B

pi@raspberrypi ~/motioneye/extra $ sudo /etc/init.d/motioneye start
[....] Starting motioneye (via systemctl): motioneye.serviceJob for motioneye.service failed. See 'systemctl status motioneye.service' and 'journalctl -xn' for details.
 failed!

pi@raspberrypi ~/motioneye/extra $ sudo systemctl status motioneye.service
● motioneye.service - LSB: Start the motionEye server
   Loaded: loaded (/etc/init.d/motioneye)
   Active: failed (Result: exit-code) since Tue 2015-10-20 06:32:35 UTC; 3min 24s ago
  Process: 5843 ExecStart=/etc/init.d/motioneye start (code=exited, status=1/FAILURE)

Oct 20 06:32:35 raspberrypi motioneye[5843]: Starting motionEye server:CRITICAL:root:failed to read settings from "/etc/motioneye/motioneye.conf": unknown configuration option: motion_control_localhost
Oct 20 06:32:35 raspberrypi motioneye[5843]: failed!
Oct 20 06:32:35 raspberrypi systemd[1]: motioneye.service: control process exited, code=exited status=1
Oct 20 06:32:35 raspberrypi systemd[1]: Failed to start LSB: Start the motionEye server.
Oct 20 06:32:35 raspberrypi systemd[1]: Unit motioneye.service entered failed state.

**Comment by ccrisan** [comment]
It's a known bug that has been recently fixed. Please hold on another couple of hours until I release the 0.28.2 version.
