### ISSUE TITLE
Movie files not saved

### ISSUE THREAD

**Issue by retrostrobe** [ccrisan/motioneye#300]
Hi Calin, the following is a bit of a mystery to me and wonder if you can shed some light please. The movies that are motion triggered aren't saved onto the RBPi drive. I've had it working, but after some upgrades of MotionEye this has stopped working.

Is there a way of looking in the logs or somewhere else to see that it's not a permission thing that's stopping the creation of files?

**Comment by ccrisan** [comment]
Well the log files should tell us what's going on. Are you on motionEyeOS or just motionEye?

**Comment by retrostrobe** [comment]
Okay. I reverted back from motion 3.4.x to your prebuilt library and it now works. Somehow I was getting the following errors. 

> conf_cmdparse: Unknown config option "ffmpeg_output_movies"
conf_cmdparse: Unknown config option "ffmpeg_variable_bitrate"
conf_cmdparse: Unknown config option "ffmpeg_video_codec"
conf_cmdparse: Unknown config option "movie_filename"
conf_cmdparse: Unknown config option "on_movie_end"
conf_cmdparse: Unknown config option "ffmpeg_bps"

**Comment by ccrisan** [comment]
well config directives have changed a bit between versions so that is understandable.

**Comment by retrostrobe** [comment]
Thanks @ccrisan I'm closing this now.
