### ISSUE TITLE
Camera not detected

### ISSUE THREAD

**Issue by ghost** [ccrisan/motioneye#316]
Hi there ,

Instead of overflow other topic, i'm making a personnal one...
I've installed everything on raspbian.
pi upgraded
package updated and upgraded too
sudo modprobe bcm2835-v4l2 done too

Camera is not detected...

raspistill -o image.jpg is working and making picture correctly...

Any ideas?

Thanks for support.

**Comment by Tom-Neverwinter** [comment]
I have a similar issue with a orange pi pc + (modprobe gc2035)
when I start motion manually I can see it is taking pictures, however motioneye cannot find a camera board. motion does not seem to be starting automatically? seems to be compiled correctly and functioning just not automatically

( This is my current setup; http://forum.armbian.com/index.php/topic/2168-motioneye-opi/)

**Comment by Kombarris** [comment]
I've got the same problem - Were you able to fix this?

**Comment by chrisf4lc0n** [comment]
What version of motion are you using?

**Comment by ccrisan** [comment]
Closing due to lack of feedback.
