### ISSUE TITLE
[feature-request] Display Disk Space Available / Used

### ISSUE THREAD

**Issue by tmack8001** [ccrisan/motioneye#324]
It would be helpful display the percentage / actual disk space used "5.0 GB out of 6.0 GB" somewhere within the UI this would give some information on if video files should be deleted or not. Also it would be helpful to provide "x.x GB used" per day to see how much space is used per day in the pictures browser and movies browser.

**Comment by yanoschik** [comment]
Well, what about using the [monitoring commands](https://github.com/ccrisan/motioneye/wiki/Monitoring-Commands) ? ...actually, they're made exactly for this kind of tasks :)
And something like this would give you the usage:
`df -h | grep /dev/root | awk '{print "Space available: " $5}'`
or
`df -h | grep /dev/root | awk '{print "Space: " $3 " of " $2 " available."}'`

**Comment by tmack8001** [comment]
Monitoring Commands if I read it correctly will show up on the video feed. That isn't what I'm looking for. From the UI that lists images and videos taken by the camera I want to display space available. As having an overlay on the camera feed only is useful on the live view of the camera to see how much space is used or available, which if you are looking at previous recordings or images that is no longer reflecting the current state of the system.

**Comment by azakharov3** [comment]
Not sure that's what you are looking for but:
![image](https://cloud.githubusercontent.com/assets/9060963/19567069/5b8346f6-96a1-11e6-9f7f-47ee512e56d6.png)

**Comment by tmack8001** [comment]
That works for now, thanks for pointing that out.
