### ISSUE TITLE
Motion notification won't run command.

### ISSUE THREAD

**Issue by Sparklapse** [ccrisan/motioneye#325]
Hi

I've written a simple python script which sends a serial signal to an arduino through usb. When the ardunio recives the serial signal it plays a buzzer for half a second. I've tested the script through the console and it works fine.

When I assign the script to the motion notification section the script all of a sudden doesn't run when there is motion. I've made the script executable with chmod but that doesn't change anything. I've stored the file in /data

Any help would be greatly appreciated.

**Comment by ccrisan** [comment]
Please attach your logs after enabling debugging in motioneye.conf

**Comment by Sparklapse** [comment]
Here are my log files.
[boot.txt](https://github.com/ccrisan/motioneye/files/518146/boot.txt)
[dmesg.txt](https://github.com/ccrisan/motioneye/files/518143/dmesg.txt)
[messages.txt](https://github.com/ccrisan/motioneye/files/518144/messages.txt)
[motion.txt](https://github.com/ccrisan/motioneye/files/518145/motion.txt)
[motioneye.txt](https://github.com/ccrisan/motioneye/files/518147/motioneye.txt)

**Comment by ccrisan** [comment]
`/data/serials.py: Permission denied` - make sure you have indeed made it executable.

**Comment by Sparklapse** [comment]
Thanks for the help! Turned out I also had to add "#!/usr/bin/python" to the start of the script.

**Comment by ccrisan** [comment]
Well yeah :)
