### ISSUE TITLE
motioneye service not starting on boot

### ISSUE THREAD

**Issue by kw12157** [ccrisan/motioneye#331]
I believe it is because the USB HDD where the camera saves the files has not initialized before motioneye tries to start. I can start the service and it works fine after I get to the desktop.

**Comment by kw12157** [comment]
Any suggestions on the best way to delay MotionEye service from starting until after the USB HDD has finished starting?

**Comment by peppelinux** [comment]
You have two solution with systemd:
"
[Unit]
Description=motionEye Server
RequiresMountsFor=/run/media/xxx/mount_point_folder_name

[Install]
WantedBy=run-media-xxx-mount_point_folder_name

OR

[Unit]
Description=motionEye Server
RequiresMountsFor=/run/media/xxx/mount_point_folder_name

**Comment by kw12157** [comment]
Thanks for the response!
I'll give them a try the next time I get to the unit. I put it in place at a location with no remote access 2 days ago...
I'll let you know if it works, but it might be a week or two.

**Comment by drovosek91** [comment]
I solved this problem  creating a mounting point in /etc/fstab for my usb storage device and, at the boot, it is mounted  before the motioneye service starts. It works fine !

**Comment by ccrisan** [comment]
@drovosek91 thanks for your suggestion.
