### ISSUE TITLE
Missing NoIR camera [Pi Zero]

### ISSUE THREAD

**Issue by KB0x** [ccrisan/motioneye#333]
I've used the guide to install motioneye on Raspbian on my Raspberry Pi Zero. I followed the: Install On Raspbian guide. I have the web panel up but no cameras are in the list. I'm using the V2.1? NoIR camera. 

I've installed the motioneyeos build image and that's actually working, it automatically detected and opened the camera without even selecting it from a list.

I've ensured that the camera works by taking shots and a 20 second video with it. I'm wondering what I've done wrong or have missed?

**Comment by ccrisan** [comment]
Do you have the bcm2835-v4l2 module loaded? Do you have a working motion binary installed?

**Comment by KB0x** [comment]
Thank you. I missed the step of having the module loading at startup.
