### ISSUE TITLE
How To Store Motioneye still images or movies on PI 3 SD Card.

### ISSUE THREAD

**Issue by joyce-mickey11** [ccrisan/motioneye#337]
To store still images or moves on rpi 3 SD card, I assume the File Storeage Selection Menu must be properly used. How should the following items on that menu be answered - Storeage Device, Root Directory, Upload Media Files, Call A Web Hook, Run A Command?

**Comment by mixpc** [comment]
Why don't you just use default storage in Root directory? That goes into the SD Card /var... folder.
Upload Media Files, Call A Web Hook, Run A Command should be off, for your purpose.
