### ISSUE TITLE
smart mask not working

### ISSUE THREAD

**Issue by mosh1** [ccrisan/motioneye#344]
Are there tips for debugging the smart mask? I have it to output the black and white motion debug images and not seeing any red overlays where the mask should be building up from constant trees moving. I set the smart mask slugginess from 5 to 10 and still the same result.

**Comment by mosh1** [comment]
Looks like smart mask is working after I configured a despeckle_filter, perhaps the small speckle of the trees wasn't triggering the mask somehow.

**Comment by ccrisan** [comment]
What value did you use for the despeckle filter option?

**Comment by mosh1** [comment]
the suggested default works well for me. despeckle_filter EedDl

**Comment by ccrisan** [comment]
@mosh1 thanks. I'll make sure to add support for this option in the UI.

**Comment by mosh1** [comment]
@ccrisan  great, that'll be good. It'll also be good to have a checkbox to enable ffmpeg_output_debug_movies and output_debug_pictures, this way you can see what the smartmask and/or despeckle_filter is  doing as well.

**Comment by ccrisan** [comment]
8108dfa5721f32c529419b2e4b4b813df6902528 adds support for ffmpeg_output_debug_movies/output_debug_pictures.
