### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by dennis071nl** [ccrisan/motioneye#346]
Where can i find the CSS files, i need to change the logo a little bit..

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/tree/master/motioneye/static/css

**Comment by dennis071nl** [comment]
Calin, 

Forgive me, but once installed, how can i change the css??

**Comment by ccrisan** [comment]
It really depends on your installation. You should find the files somewhere in /usr/[local/]lib/python2.7/[site|dist]-packages/motioneye*/. Use the find command to find the CSS files you're looking for.

**Comment by dennis071nl** [comment]
Thanks, worked out fine!

2016-11-03 9:48 GMT+01:00 Calin Crisan <notifications@github.com>:

**Comment by dennis071nl** [comment]
Calin, just one little extra question:

My setup is an orangepi, running armbian and one RTSP camera. Is there a
possibility for me to view the camera of an Raspberry pi Zero into the
motioneye installation on the Orange pi??

thanks!
Dennis

2016-11-03 10:12 GMT+01:00 Dennis Smit <dennis@dennissm.it>:

**Comment by ccrisan** [comment]
Yes, just make sure your RPi runs the latest version of motionEye and add it as a remote motionEye camera to your Orange PI motionEye server.

**Comment by dennis071nl** [comment]
wow, excellent! gonna try that!

thank you very much for your support!

2016-11-03 10:24 GMT+01:00 Calin Crisan <notifications@github.com>:

**Comment by zakariassoul** [comment]
@dennis071nl were you able to edit the css or html files even tho they're ReadOnly files ?
