### ISSUE TITLE
led control missing?

### ISSUE THREAD

**Issue by cb350f** [ccrisan/motioneye#349]
I installed motioneye 0.35 on a Raspberrypi 3 with a CSI camera.  Everything appears to work fine, but there is no option in the advanced settings to disable the camera led.  I have previously installed motioneyeos, and the option was there.  Is this a bug, or have I misconfigured something?

**Comment by ccrisan** [comment]
motionEye is not specific to the Raspberry PI, nor the Raspberry PI camera. Therefore there's no LED control option. You're probably looking for [motionEyeOS](https://github.com/ccrisan/motioneyeos) for the Raspberry PI.
