### ISSUE TITLE
Missing Icons Webinterface

### ISSUE THREAD

**Issue by cryptoluks** [ccrisan/motioneye#35]
![motioneye-missing-icons](https://cloud.githubusercontent.com/assets/9020527/10814625/48dbee10-7e27-11e5-9b8b-27b95aa134ce.png)
Hi!

I installed Motioneye like in the Wiki and all worked fine for some days.
But now, all images (like buttons, etc) are missing in the webinterface.

What I have done already:

- removed motioneye (pip uninstall) and all dependencies
- deleted pip cache
- deleted config files
- reinstalled --> same

Before it got 'broke' I worked on the nginx config to access motioneye via ssl.

- Using Archlinux 4.2.4
- running motioneye with root, so there should be no permission problem to access img folder
- same result with port 8765 / nginx proxy
- same result on different devices

--> I discovered, that PIL and pillow where both installed. But they are in conflict? I uninstalled PIL, reinstalled everything.. but same result..

Thank you!

**Comment by cryptoluks** [comment]
![motioneye-missing-icons](https://cloud.githubusercontent.com/assets/9020527/10814610/398443ae-7e27-11e5-9bef-db378ec8a37c.png)

**Comment by ccrisan** [comment]
Does `pacman -S mime-types` solve the problem?

**Comment by cryptoluks** [comment]
Yes!! Thank you very much! :+1:

**Comment by ccrisan** [comment]
I'll update the wiki page accordingly.
