### ISSUE TITLE
surveillance user

### ISSUE THREAD

**Issue by RudySixOw** [ccrisan/motioneye#351]
After some days i can't see camera in surveillance user but in admin user all are ok.
Do you have any idea ?

no log about this even in debug mode.
any version of motioneye and motion.
But actualy is 
motionEye Version 	0.35
Motion Version 	3.4.1~rc01

**Comment by ccrisan** [comment]
Please give us more details about your system configuration: what computer, what OS, what camera?

**Comment by RudySixOw** [comment]
OS: Debian 8.6 stable Linux camera 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
under a kvm vm (proxmox)

**Comment by ccrisan** [comment]
And the camera?

**Comment by RudySixOw** [comment]
some Axis, Foscam (rtsp), linksys but when i'm connected in user admin no probleme.

**Comment by ccrisan** [comment]
Please attach your motioneye log file.

**Comment by RudySixOw** [comment]
there is no log 
cat /var/log/motioneye.log
even in debug mode

**Comment by ccrisan** [comment]
When using systemd, you have the journalctl command to help you with logs:

    journalctl -u motioneye > motioneye.log

**Comment by RudySixOw** [comment]
no log too

**Comment by ccrisan** [comment]
Then I'm out of ideas.

**Comment by RudySixOw** [comment]
# the log level (use quiet, error, warning, info or debug)
log_level debug

**Comment by RudySixOw** [comment]
i have some log on motion.log

**Comment by RudySixOw** [comment]
I find the problem. It was the prefs.json.
