### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by lucacalcaterra** [ccrisan/motioneye#355]
Hi, did you plan a multilanguage translation? I want contribute to translate it in italian, let me know if we can tracking it...

**Comment by ccrisan** [comment]
There are no plans to add translation support any time soon. Thanks for offering, though!

**Comment by lucacalcaterra** [comment]
I don't have enough  knowledge  about github but... if  i fork  your  repo
and translate  It ?

Il 11 Nov 2016 6:16 PM, "Calin Crisan" <notifications@github.com> ha
scritto:

**Comment by ccrisan** [comment]
I don't recommend that.
