### ISSUE TITLE
Upload to S3

### ISSUE THREAD

**Issue by MourIdri** [ccrisan/motioneye#364]
Hi, 

Is it possible to have the images uploaded to any S3 compatible account ( blacblaze, amazon or bluemix ) ? 

Dropbox or gdrive are available right now, but api are too restrictive.
The fact is I would like to use face/human recognition to delete the images of my cat :)  
I am using bluemix ( bluemix has 250 free requests per day, fairly enough for  home usage)  
Currently, I am using a script that is triggered when a movement is detected. 
The script checks if there is a "human" form on the pictures  currently stored in the storage folder, if not, it delete the images, if yes, it stores the image and send an xmpp alert.

**Comment by adamtbeames** [comment]
@MourIdri I know that this issue was some time ago now, but I thought I'd let you know that I'm wanting S3 support too.  I've submitted a [PR](https://github.com/ccrisan/motioneye/pull/1063) that adds very basic functionality to the dev branch.
