### ISSUE TITLE
Motioneye for solid state (no network)

### ISSUE THREAD

**Issue by oaf2015** [ccrisan/motioneye#365]
My intent is to also use it as a solid state camera/system. Is there a way around this? How can I accomplish this? I appreciate your help.

**Comment by ccrisan** [comment]
What does a "solid state camera" mean and what are the requirements from motionEyeOS for such a camera?

**Comment by oaf2015** [comment]
Meaning not a network camera. When I start motioneye on my raspberry pi 3,
it needs to be wired to a network. How do I tweak it so I have the option
for either or?

**Comment by ccrisan** [comment]
Set [os_networkless](https://github.com/ccrisan/motioneyeos/wiki/os.conf#os_networkless) to `true`.

**Comment by oaf2015** [comment]
I cd/ls my way through it and I see the os.conf file. I ran sudo nano to edit it but it says "command not found". I really appreciate your help.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/FAQ#why-doesnt-sudo-work
