### ISSUE TITLE
Feature Request: Notification if camera is lost

### ISSUE THREAD

**Issue by bruffdj** [ccrisan/motioneye#366]
Is it possible to receive an email if a configured camera stops streaming or goes off line?

Thanks for the great software!

**Comment by CatoAntonsen** [comment]
Actually I would like all the same notifications as when motion is detected...

**Comment by elfhelmp** [comment]
I subscribe to this request, it can come in very handy if someone decides to unplug your USB camera to do a web conference while you're monitoring stuff with it... or if it breaks down. Definitely.

**Comment by ccrisan** [comment]
There's no UI option for that and there's no plan to add one in the near future.

However, if you must have that notification, you can use the [on_camera_lost](http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#on_camera_lost) motion option by adding it manually to the Extra Motion Options.

You'll have to provide your own command/script to be executed when that happens.

**Comment by chrisf4lc0n** [comment]
If you want to receive an email notification it is rather simple to do that:
1. Configure ssmtp.
2. In the Extra Motion Options write:
on_camera_lost echo "**Camera name** camera feed lost $t $d" | mail -s "**Camera name** camera feed lost $t $d" **your email address**

**Comment by bruffdj** [comment]
Thanks for the suggestion.  That command isn't working for me, is it working for anyone else?  Apart from my email this is what I used.  

SMTP is up and running already - I get email notification for motion events.  

`on_camera_lost echo "Garage camera feed lost $t $d" | mail -s "Garage camera feed lost $t $d" nottelling@gmail.com`

**Comment by chrisf4lc0n** [comment]
Have you configured ssmtp?

**Comment by chrisf4lc0n** [comment]
Addition, you have to install mailutils too.

**Comment by bruffdj** [comment]
I'm running motionEyeOS.  By the look of things I will have a hard time installing ssmtp and mailutils.  Assume my best option would be to install a different OS and install motionEye within that.

**Comment by bruffdj** [comment]
Is there no way to make use of the SMTP client I've already configured in motionEye?

**Comment by chrisf4lc0n** [comment]
Yup, unless with the next revision Calin decides to build it with mail and
ssmtp...

**Comment by chrisf4lc0n** [comment]
There is, but I would need to dig through the code to find out which one
was installed and what commands do you need to send an email.

**Comment by chrisf4lc0n** [comment]
It looks like you would need to write a piece of code yourself...
Have a look in here:
https://github.com/ccrisan/motioneye/blob/master/motioneye/sendmail.py

On 2 Dec 2016 12:56 p.m., "bruffdj" <notifications@github.com> wrote:

Is there no way to make use of the SMTP client I've already configured in
motionEye?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/ccrisan/motioneye/issues/366#issuecomment-264448367>,
or mute the thread

**Comment by ccrisan** [comment]
@bruffdj you could take a look at your current `/data/etc/thread-*.conf` and search for the line starting with `on_event_`. Next to it you'll have the current command that's executed upon a motion event. As @chrisf4lc0n pointed out, in the end it will execute the `sendmail.py` script. You can copy that over to the `on_camera_lost` option but you'll obviously get the exact same message as when your camera detects motion.

**Comment by chrisf4lc0n** [comment]
Bear with me as I am not a programmer, nor any kind of IT specialist...
I think I may have a work around for your problem, but that assumes a few things:
1. You know how to ssh to your MotionEyeOS.
2. You know what directory you need to create this file.

You could create a simple no_feed.py file and simply add:

import datetime
import logging
import os
import re
import signal
import smtplib
import socket
import time

from email import Encoders
from email.mime.text import MIMEText
from email.MIMEMultipart import MIMEMultipart
from email.MIMEBase import MIMEBase
from email.Utils import formatdate

from tornado.ioloop import IOLoop

import settings

import config
import mediafiles
import motionctl
import tzctl
 
fromaddr = "YOUR ADDRESS"
toaddr = "ADDRESS YOU WANT TO SEND TO"
msg = MIMEMultipart()
msg['From'] = fromaddr
msg['To'] = toaddr
msg['Subject'] = "Camera" %(camera)s/%(hostname)s" at %(moment)s (%(timezone)s lost feed "
 
body = "Camera" %(camera)s/%(hostname)s" at %(moment)s (%(timezone)s lost feed"
msg.attach(MIMEText(body, 'plain'))
 
server = smtplib.SMTP('smtp.gmail.com', 587)
server.starttls()
server.login(fromaddr, "YOUR PASSWORD")
text = msg.as_string()
server.sendmail(fromaddr, toaddr, text)
server.quit()

Edit where necessary and then in Extra Motion Option create an entry:
on_camera_lost /path/to/no_feed.py

**Comment by chrisf4lc0n** [comment]
Calin is probably looking at this message now and laughing ;)

**Comment by ccrisan** [comment]
Why would I be laughing? I'm more than happy to see users helping out other users. And, although not tested, your script looks legit to me :)

**Comment by chrisf4lc0n** [comment]
Thanks Calin
1. I must have imported more modules than the script really requires.
2. Any person knowing how to program or being more computer literate most probably knows easier solutions to this problem. 
;)
