### ISSUE TITLE
Camera ID is empty

### ISSUE THREAD

**Issue by retrostrobe** [ccrisan/motioneye#368]
On v0.35.1, the read-only field Camera ID is empty preventing me from saving any changes made to preferences. I deleted the camera, then added it, but issue remains.  

![screen shot 2016-11-25 at 2 03 15 pm](https://cloud.githubusercontent.com/assets/19503690/20611924/02e55ad2-b318-11e6-97af-81a26b00fb40.png)

**Comment by ccrisan** [comment]
Please try clearing the browser cache and reloading the page.

**Comment by retrostrobe** [comment]
Thanks @ccrisan! It worked once I restarted the browser.
