### ISSUE TITLE
RSTP protocol not supported

### ISSUE THREAD

**Issue by antikuza** [ccrisan/motioneye#369]
Hi. I can't add RSTP stream to Motion. I get error "protocol rtsp not supported"
Motion Eye Advanced Settings:
![default](https://cloud.githubusercontent.com/assets/23737976/20622194/5fb47d50-b30a-11e6-9201-5f34a78ebc74.png)

"motion -h" on server:
```
motion Version 4.0.1+git9df0c11, Copyright 2000-2016 Jeroen Vreeken/Folkert van Heusden/Kenneth Lavrsen/Motion-Project maintainers
```

**Comment by ccrisan** [comment]
Well your motion version in use is 3.2.12. You need to tell motionEye to use the 4.0 binary. Check your [motion_binary](https://github.com/ccrisan/motioneye/wiki/Configuration-File#motion_binary) setting.

**Comment by teco13** [comment]
I have motioneye (not motioneye os) version 0.37.1 and motion 4.0.1 from https://github.com/Motion-Project/motion, but it does not work rstp (protocol rstp not supported)
![version](https://user-images.githubusercontent.com/28703760/31378837-d4ae9468-adac-11e7-85ab-a693977a3fd7.jpg)
![rstp not supported](https://user-images.githubusercontent.com/28703760/31378839-d637e424-adac-11e7-9732-53963568d811.jpg)

Could you help me?
Thanks in advance

**Comment by ccrisan** [comment]
It's rtsp, not rstp.
