### ISSUE TITLE
Instructions for setting up a hub

### ISSUE THREAD

**Issue by wandering213** [ccrisan/motioneye#370]
I'm trying to connect a MotionEyeOS device to a server with MotionEye installed and I am getting authentication errors. Can you provide some instructions for the proper way to add a MotionEye camera to a hub?

**Comment by ccrisan** [comment]
[This](https://github.com/ccrisan/motioneyeos/wiki/Usage-Scenarios) is the only doc on this matter. Make sure you run the latest motionEye(OS) versions on all units (even prereleases) in order to avoid compatibility issues.

**Comment by wandering213** [comment]
I did see that and I have the latest version on both computers, what's the correct URL to use?

**Comment by ccrisan** [comment]
The URL should be simply http://ip/ (motionEyeOS) or http://ip:8765/ (motionEye).

**Comment by wandering213** [comment]
I give that a try, I get the following behavior. Authentication error and then the login prompt which won't accept any credentials until I refresh the page.:

![image](https://cloud.githubusercontent.com/assets/6215667/20653820/a548a394-b4d8-11e6-97bc-27273121324e.png)

![image](https://cloud.githubusercontent.com/assets/6215667/20653858/1dbe049a-b4d9-11e6-8300-871659733008.png)


My credentials are the same for both locations.

**Comment by ccrisan** [comment]
Any special characters in that password? Have you tried changing it to something simpler?

**Comment by wandering213** [comment]
Yes, that was it.I dropped the special characters and it worked.

**Comment by ccrisan** [comment]
Please tell us which special characters you were using.

**Comment by wandering213** [comment]
I used space and !.

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/commit/9d54c882477599c7fcf713998e2c2e9a5b92dccf fixes the use of spaces in passwords.
