### ISSUE TITLE
Free Human Body recognition 

### ISSUE THREAD

**Issue by MourIdri** [ccrisan/motioneye#377]
Guys, 

During hacakthon, I am using motioneye with watson for Human recognition. Since 250 images per day are free, It can be nice to share.. 
So this script is triggered when a motion is detected ( Motioneye functionality), then the image is sent to Watson analysis, and is uploaded to Bluemix cloud. Then It sends mail ( so I disabled Motioneye mail option) in the mail, there is the cloud url where the image is stored,  it also send a google hangout update for a given enduser. 
So you need a gmail account for sms and mail ( here https://accounts.google.com/SignUp?continue=https%3A%2F%2Fwww.google.fr%2F%3Fgws_rd%3Dssl%26pli%3D1&hl ) and a bluemix account for watson image recognition and easy 25gigs cloud storage ( here https://console.ng.bluemix.net/registration/ ).

Save the txt file below to a "script.py" file and it will do the job.

**Comment by MourIdri** [comment]
[FACE_RECOGNITION_MAIL_XMPP_UPLOAD_IMAGE_TO_CLOUD.txt](https://github.com/ccrisan/motioneye/files/628936/FACE_RECOGNITION_MAIL_XMPP_UPLOAD_IMAGE_TO_CLOUD.txt)

**Comment by thundergreen** [comment]
@MourIdri I have a question: I wanna have a XMPP Upload with pictures / videos to my httpuplad ejabberd server or just a link to the file. Do you have an idea how to make it? Your script wont send it to an xmpp account

**Comment by MourIdri** [comment]
This is what my script does but using hangout (gmail xmpp). To use jabber, You will have to change the script a little bit in order to change jabber account calls. ( else Use gmail, this more convenient).
