### ISSUE TITLE
Stream Keeps freezing on Port 8081 with VLC and the Raspi home page doesn't have an image.

### ISSUE THREAD

**Issue by CBR900RRR** [ccrisan/motioneye#382]
Even while I was trying to download the log files, it would break connection and I'd have to time it for the connection to stay alive long enough for the file transfer to complete. not sure exactly when this started happening but it has been a couple weeks now for sure.

[messages (1).zip](https://github.com/ccrisan/motioneye/files/638504/messages.1.zip)

**Comment by ccrisan** [comment]
Your messages.log file says:

    Dec  3 09:40:20 meye-07d70a40 user.notice brownout: low power supply voltage detected

and some of

    Dec  3 09:40:44 meye-07d70a40 user.notice wifi: disconnected for 20 seconds, rebooting

I recommend using a better power supply.

**Comment by CBR900RRR** [comment]
thanks so much, sorry for wasting your time. Love the app. really makes it easy for us to use.
