### ISSUE TITLE
Unable to open video device

### ISSUE THREAD

**Issue by sapcons** [ccrisan/motioneye#390]
All of a sudden my cameras turned grey with the above error message. When I select the camera I can see the fps values are changing. Network connection is stable. Is there any file I can search for the root cause?

**Comment by xmflsct** [comment]
I assume ffmpeg is the core used for streaming videos.

I had a similar issue, that motionEye says cannot connect to camera. Then I use ffmpeg try to connect to the stream, and then I can debug from there. Correct me if I am wrong @ccrisan.

**Comment by sapcons** [comment]
Thanks for your help. The point is that I didn't change a thing. I am currently upgrading pi and motioneye to see whether this can fix the problem...

**Comment by xmflsct** [comment]
No worries. :) But run ffmpeg, you will be able to see more details, at least what is the error message of connecting.

**Comment by sapcons** [comment]
Can you please explain a bit more in detail? Thanks

**Comment by xmflsct** [comment]
Example:
`ffmpeg -loglevel debug -i "rtsp://yourcamera" /saveto/localfile.mp4`
With loglevel to **debug** or even to **trace**, I could see what is the error message.
Reference: [https://trac.ffmpeg.org/wiki/StreamingGuide](FFmpeg Streaming Guide)

**Comment by sapcons** [comment]
Couldn't find the root cause. Restored my backup and everything is running ok now. Thanks for your help.
