### ISSUE TITLE
Attached item in mail notification

### ISSUE THREAD

**Issue by Odwyn** [ccrisan/motioneye#391]
Hello,

Please, can you add the possibility to have an attached item on notification email.
Like the last picture during motion.

Thanks

**Comment by ccrisan** [comment]
This is already possible. See https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-should-i-do-to-have-pictures-attached-to-motion-notification-emails.

**Comment by FredClement91** [comment]
Hello,
It doesn't work for me. I see that he calls a url looking like "/usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" picture_save 1 /home/video/picture.jpg"

I first found out that maybe some curl version don't support the space in "Content-Type:application/json", but that was a simple fix. Anyway, the system is still not sending pictures.
