### ISSUE TITLE
Storage Device

### ISSUE THREAD

**Issue by Odwyn** [ccrisan/motioneye#392]
Hello,

i can't open a request.
Can you add a storage device like SSH path, or a webdav where storage picture or movies ?

Thanks.
Regards

**Comment by chrisf4lc0n** [comment]
No need for the SSH... You can use the SSHFS to map your remote drive locally and then just point MotionEye to save files to it.

**Comment by ccrisan** [comment]
Upload via SSH (SFTP) is planned. Webdav, nope (I don't have experience with that). Until then, as @chrisf4lc0n said, sshfs is your option.

**Comment by hellyberry** [comment]
rsync via ssh is also currently possible and very powerful, and low on system-resources, to automatically delete files once transferred and verified,..

**Comment by ericjanvanputten** [comment]
Is storage like network drive as in motioneyeos possible as well?
For more computing power i divided across multiple devices, to now encounter that non-os doesnt have network disk available... 

still cool solution :)

**Comment by ccrisan** [comment]
@ericjanvanputten set [smb_shares](https://github.com/ccrisan/motioneye/wiki/Configuration-File#smb_shares) to `true` and make sure your motionEye runs as root.

**Comment by ericjanvanputten** [comment]
@ccrisan and i was adding packages and looking into hard mounting... silly me ;) 
thanks man!
