### ISSUE TITLE
Streaming resolution

### ISSUE THREAD

**Issue by ivalion2133123** [ccrisan/motioneye#399]
Hello is it possible to stream video from camera in lower resolution (Streaming Resolution) but without resolution reduction in my own gui?

**Comment by chrisf4lc0n** [comment]
It is it will get upscaled, but the quality will not be that great.

**Comment by ivalion2133123** [comment]
Can't understand you what i want is to stream with low resolution to other motioneye instance but the resolution in the original motioneye must stay the same.

At the moment it also chenges.

**Comment by chrisf4lc0n** [comment]
Oh, sorry now I get you. I think ;)
You just want to change the Streaming Resolution under Streaming Tab?
You can reduce the quality, but no resolution at the moment.

**Comment by chrisf4lc0n** [comment]
Are you using MotionEye or MotionEyeOS?
If you are using MotionEye installed on another system, you can make the lighttpd or any other web server to catch the stream, reduce the resolution and stream it back out on a another port.

**Comment by ccrisan** [comment]
@ivalion2133123 you can reduce the streaming resolution using Preferences/Resolution Dimmer. It will scale down the streaming resolution proportionally to what you choose there, leaving the capture resolution untouched.
