### ISSUE TITLE
Problem to install Motioneye on Ubuntu 16.04LTS 

### ISSUE THREAD

**Issue by richardsith** [ccrisan/motioneye#404]
I've a problem to install Motioneye on Ubuntu 16.04Lts Server, that one is a VM on VMware Fusion.
I saw the guide here
[here](https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu)

but after the step 3 when I run the pip command receive that error:

**$: pip install motioneye**
Traceback (most recent call last):
  File "/usr/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 215, in main
    locale.setlocale(locale.LC_ALL, '')
  File "/usr/lib/python2.7/locale.py", line 581, in setlocale
    return _setlocale(category, locale)
locale.Error: unsupported locale setting

I'd like to have a Video HUB Controller on the VM and different RPI device with camera, in other way to have all camera controlled via controller.

thanks a lot

**Comment by richardsith** [comment]
any suggest??

**Comment by chrisf4lc0n** [comment]
[http://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting](http://stackoverflow.com/questions/36394101/pip-install-locale-error-unsupported-locale-setting)

**Comment by richardsith** [comment]
the error has been resolved running these commands
```
**$: export LC_ALL=C**
**$: pip install motioneye-0.35.1.tar.gz**
Processing ./motioneye-0.35.1.tar.gz
Collecting tornado>=3.1 (from motioneye===0.35.1)
  Downloading tornado-4.4.2.tar.gz (460kB)
    100% |################################| 
......
......
......
```
then I've continued with the steps suggested on site 

[here](https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu)

close the issue

**Comment by richardsith** [comment]
another errors have been resolved in this way 

step5:
```
**$: sudo mkdir -p /etc/motioneye
$: sudo cp .local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf**
```

Step7:
Ubuntu 16.04Lts 
```
**$: sudo cp /home/<user>/.local/share/motioneye/extra/motioneye.systemd-unit-local /etc/systemd/system/motioneye.service
$: sudo systemctl daemon-reload
$: sudo systemctl enable motioneye
$: sudo systemctl start motioneye**
```

now I can close that issue as resolved.

**Comment by chrisf4lc0n** [comment]
All good then!

**Comment by stressdidri** [comment]
Executing /lib/systemd/systemd-sysv-install enable motioneye
insserv: warning: script 'K01motioneye' missing LSB tags and overrides
insserv: warning: script 'K01vncserver' missing LSB tags and overrides
insserv: warning: script 'motioneye' missing LSB tags and overrides
insserv: warning: script 'vncserver' missing LSB tags and overrides
update-rc.d: error: motioneye Default-Start contains no runlevels, aborting.
root@ThinkCentre-M55:~#
