### ISSUE TITLE
Can't find RPi v2 camera?

### ISSUE THREAD

**Issue by czarina** [ccrisan/motioneye#410]
Hi,

I am unable to get motioneye to recognize my RPi v2 camera on my raspbian RPi Zero. As you can see here, there is no camera to select.

![image](https://cloud.githubusercontent.com/assets/3465676/21614833/fc96a6fe-d18f-11e6-8c7e-233f51812090.png)

- I followed the instructions here https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian
- I ran 'sudo modprobe bcm2835-v4l2' 
- My camera is enabled and I successfully tested it using raspivid/raspistill

**Comment by ccrisan** [comment]
What does `motion -h` say?

**Comment by czarina** [comment]
Sorry, looks like I didn't install Motion properly. Thanks :)

**Comment by czarina** [comment]
Another question - how do I configure settings like fps/resolution/rotation for the motioneye stream? I wasn't able to find documentation of this in the wiki.

**Comment by ccrisan** [comment]
Have you enabled advanced settings?

**Comment by czarina** [comment]
I had not. This gives me some of what I need, although there are some more advanced changes I'd like to make (video stabilization would be great, if available) - is there a full list of available options somewhere?

**Comment by ccrisan** [comment]
That kind of options is not available with motion. For that, you'd either need to use motionEyeOS in Fast Network Camera mode (and lose motion detection, notifications & so on) or try other Raspberry PI camera-specific solutions.
