### ISSUE TITLE
Axia cameras authorization failed

### ISSUE THREAD

**Issue by danbuntu** [ccrisan/motioneye#415]
Hello

We have some axis M1004-W cameras they we are trying to add to motion eye.

We have added them via rtsp://[IP]/axis-media/media.amp and with a username and password. Motion eye finds the cameras and added them but they show no video.

In the logs we see:

[2] [ALR] [NET] rtsp_connect: unable to open input(rtsp://[IP]:554/axis-media/media.amp): -825242872 - Server returned 401 Unauthorized (authorization failed)

This would suggest that the username or password is wrong. However we know they are correct as we can use the same rstp stream, user and password in vlc and they open fine.

We can also set the camera to 'Enable anonymous viewer login' and they work.

Any ideas what we're doing wrong here please?

**Comment by ccrisan** [comment]
This is a [motion](https://github.com/Motion-Project/motion) issue. Please open the issue there.
