### ISSUE TITLE
new Camera ID field

### ISSUE THREAD

**Issue by carnighi** [ccrisan/motioneye#417]
Hi,
I have added my new ipcam on motioeye sucessfully, so it recognizes the cam, and I can see the video stream, but when i try to change the cam configuration through the settings:

![image](https://cloud.githubusercontent.com/assets/25054784/21845851/a28d0fde-d7f4-11e6-96b7-1ce12b46e096.png)

The "Camera ID" field remain empty and it is read only!
If i try to apply the new settings, motioneye show me this message:

![image](https://cloud.githubusercontent.com/assets/25054784/21845886/cc865ff2-d7f4-11e6-934e-a180de146f37.png)

Someone can help me? 

I've already tried to modify manually the conf file to add the missing field value without success. :(

Thank you!

**Comment by ccrisan** [comment]
Please clear your browser's cache.

**Comment by carnighi** [comment]
It works! :) Thank you very much!
