### ISSUE TITLE
Motioneyeos on Pi Zero with enc28j60 ethernet module

### ISSUE THREAD

**Issue by FWSquatch** [ccrisan/motioneye#424]
I'm trying to get motioneyeos to work on my Pi Zero which is using an enc28j60 module (like this one: [enc28j60](http://www.ebay.com/itm/Mini-ENC28J60-Network-Module-Schematic-For-Arduino-51-AVR-LPC-STM32-UK-DI-/252213354808?hash=item3ab9166138:g:9NcAAOSw3KFWb23Z) ). 

I have been able to use the module fine in Raspbian by enabling SPI and adding dtoverlay=enc28j60 to the /boot/config.txt file but I'm not sure how to do this in motioneyeos. Is this even possible or should I try another route?

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/Tweaks#partition-layout for editing stuff on /bot. I'm afraid though that it won't survive upgrades.
