### ISSUE TITLE
FTP server

### ISSUE THREAD

**Issue by oaf2015** [ccrisan/motioneye#427]
Is there any way to utilize motioneye with FTP servers (Filezilla or something as such)? Are Google drive and Dropbox the only 2 options? I appreciate your help.

**Comment by oaf2015** [comment]
Do you have any instructions for the central server usage scenario?

**Comment by chrisf4lc0n** [comment]
The answer to your 1st question:
https://github.com/ccrisan/motioneye/issues/392

What do you mean by central server usage scenario?

**Comment by oaf2015** [comment]
I am trying to upload to my own FTP server rather than Google drive or Dropbox but do not know how to go about it under the GUI.

**Comment by chrisf4lc0n** [comment]
No option in GUI, you have to map SFTP drive locally and point the MotionEye to save files to it.

**Comment by oaf2015** [comment]
Under the .conf file?

**Comment by oaf2015** [comment]
Do you have an example of the command?

**Comment by chrisf4lc0n** [comment]
What OS?

**Comment by oaf2015** [comment]
Jessie

**Comment by chrisf4lc0n** [comment]
[https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh](https://www.digitalocean.com/community/tutorials/how-to-use-sshfs-to-mount-remote-file-systems-over-ssh)

**Comment by oaf2015** [comment]
Great I will try it out. Thanks!
