### ISSUE TITLE
mjpg-streamer support

### ISSUE THREAD

**Issue by jk0** [ccrisan/motioneye#431]
How much work would it be to add support for mjpg-streamer? An example use case would be not needing motion detection, yet still have the ability to stream over the motioneye web interface and record constantly.

My 8 IP cameras are almost melting the hardware running motioneye, which is rather unfortunate since I don't need MD.

**Comment by ilovelinux** [comment]
@ccrisan hasn't this feature already been implemented?

**Comment by jasaw** [comment]
Enable constant recording and disable motion detection?

Anyway, this question was asked 2 years ago and no update since then. I think this issue can be closed.

**Comment by ccrisan** [comment]
I don't think MJPEG Streamer is something to be considered when it comes to motionEye. We've got Motion, a well maintained piece of software that does a far better job than MJPEG Streamer. And it does a lot more than that.
