### ISSUE TITLE
Cannot find "Expert Settings"

### ISSUE THREAD

**Issue by Budman1758** [ccrisan/motioneye#434]
Title says most of it.  Expert settings are not anywhere I can find.  I am logged in as admin and "advanced settings" enabled.  This is true on both the camera page and the hub page.  I have tried with 3 different browsers too.  Any ideas?

**Comment by spinoinside** [comment]
Same problem ... Have you solved it ?
My setting:
motionEye Version 0.35.3 
Motion Version 4.0.1 
Raspbian Jessie Lite

**Comment by ccrisan** [comment]
Can I see a screenshot of your settings panel?

**Comment by spinoinside** [comment]
[
![senzanome](https://cloud.githubusercontent.com/assets/4184470/23331983/c453dd42-fb70-11e6-8171-80e9224e3e0d.jpg)
](url)

**Comment by ccrisan** [comment]
You're running motionEye, not motionEyeOS. Expert Settings are a motionEyeOS-specific thing. Any feature you're missing from the Expert Settings, I'm afraid is not available or not covered by plain motionEye.

**Comment by stealthwolf** [comment]
fuck
