### ISSUE TITLE
mask creation and rotation of picture is inconsistent

### ISSUE THREAD

**Issue by hansrijn** [ccrisan/motioneye#437]
When I create a mask with edit-mask in the web-front-end with a rotated picture (270 degrees, in my case) everything looks fine until the pgm file is saved. Motion log says it tries to resize, but fails.

log lines:
[1:ml1] [WRN] [ALL] get_pgm: The mask file specified is not the same size as image from camera.
[1:ml1] [WRN] [ALL] get_pgm: Attempting to resize mask image from 1280x720 to 720x1280

wrong image:
![image](https://cloud.githubusercontent.com/assets/17705433/22596154/bdcd68f0-ea2a-11e6-8c86-509bb1df23b6.png)

when rotated 270 back to 0: gives mirrored pgm picture
![image](https://cloud.githubusercontent.com/assets/17705433/22596264/1e738112-ea2b-11e6-902e-2a09828f7e10.png)

It was my intention to mask everything except for the pathe to my house but this cannot be done with the tool when picture is rotated. As below.
![image](https://cloud.githubusercontent.com/assets/17705433/22596578/6e444c98-ea2c-11e6-8bc2-042871b348f3.png)

My work around: no rotation and all is well. I try to find other means to create a mask. Could you  advise?

**Comment by hansrijn** [comment]
My way to create a rotated pgm: 
1 download mask_1.pgm to windows7, 
2 convert pgm to jpeg with irfanview, 
3 rotate jpeg with windows7,
4 then convert from jpeg to pgm with irfanview
5 upload to pi's /etc/motioneye

**Comment by ccrisan** [comment]
Hmm, the mask should be rotated as well once you have rotated the stream. I'll look into this.

**Comment by hansrijn** [comment]
Hi Calin,

That would be nice. For me works the workaround. Probably not many that
need rotation.

I appreciate your program and effort very much,

met vriendelijke groet,

Hans Reijnen
+31 6 3754 5659

Op 4 feb. 2017 9:52 p.m. schreef "Calin Crisan" <notifications@github.com>:

**Comment by ccrisan** [comment]
@hansrijn can you please describe step by step the problem you're encountering? Ideally you should rotate your camera first, edit your mask and never rotate it back. Doesn't it work that way?

**Comment by hansrijn** [comment]
actions: 1 rotation, 2 edit, save, apply, 3 try to re-edit.

![image](https://cloud.githubusercontent.com/assets/17705433/22735217/1a8779ec-edf9-11e6-9483-8a65ebc9f1a2.png)


![image](https://cloud.githubusercontent.com/assets/17705433/22735253/3d5c9308-edf9-11e6-8a9d-6bc4255467d2.png)


![image](https://cloud.githubusercontent.com/assets/17705433/22735281/4dd87350-edf9-11e6-8251-b1dde1984dce.png)

Again, after clear

![image](https://cloud.githubusercontent.com/assets/17705433/22735340/7e064048-edf9-11e6-8aba-813883528eec.png)

![image](https://cloud.githubusercontent.com/assets/17705433/22735343/88f562d6-edf9-11e6-95e8-4c479c802cbe.png)

And again
![image](https://cloud.githubusercontent.com/assets/17705433/22735358/a35878ca-edf9-11e6-8857-d5a5456cf799.png)

![image](https://cloud.githubusercontent.com/assets/17705433/22735363/aafae5a4-edf9-11e6-96f5-f2a5b8940bad.png)

**Comment by hansrijn** [comment]
I hope this is of help, if you need more, just ask,

regards,

**Comment by hansrijn** [comment]
Logging was:

[1:nc1] [ALR] [NET] netcam_handler_loop: Camera handler thread [3] started
[1:ml1] [WRN] [ALL] get_pgm: The mask file specified is not the same size as image from camera.
[1:ml1] [WRN] [ALL] get_pgm: Attempting to resize mask image from 1280x720 to 720x1280

**Comment by hansrijn** [comment]
rotation with imagemagick's convert is easier.
apt install imagemagick
convert -rotate 270 original.pgm rotated.pgm

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/commit/43288b22aba1987cea3e24b6576a8395afffeea3 fixes this issue. @hansrijn, thanks again for taking the time to help me reproduce the issue. I wasn't able to reproduce it because I was trying with a MJPEG netcam where the actual resolution was directly detected (and thus the rotation had no negative impact).

**Comment by hansrijn** [comment]
perfect, works like a charm, thanks.

**Comment by hansrijn** [comment]
Ai, yes editing was like a charm, but....
the mask seems not to be used. The debug output says it is, yet the actual detection uses the entire picture. And, what is more, it now detects motion where no motion is. I get almost continuous saved pictures, where the "frame change window" shows the entire picture.

![image](https://cloud.githubusercontent.com/assets/17705433/22854280/291f9ac4-f06b-11e6-95e7-78c7c00094fd.png)

![image](https://cloud.githubusercontent.com/assets/17705433/22854329/6b4b6c4c-f06c-11e6-8990-6c1801b58503.png)

All pictures in above list are identical (but overlay text).

from syslog, maybe of help,

Feb 11 15:12:43 harijnmotion motion: [1:ml1] [DBG] [EVT] exec_command: Executing external command '/usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" stop 1'
Feb 11 15:12:43 harijnmotion motion: [1:ml1] [NTC] [ALL] motion_loop: End of event 15
Feb 11 15:12:43 harijnmotion meyectl[413]: DEBUG: recevied relayed event stop for thread id 1 (camera id 1)
Feb 11 15:12:43 harijnmotion meyectl[413]: DEBUG: clearing motion detected for camera with id 1
Feb 11 15:12:43 harijnmotion meyectl[413]: DEBUG: 200 POST /_relay_event/?_username=admin&event=stop&thread_id=1&_signature=26ad2a9135dd82501c7e1b4da2e6679aa8deb3f6 (127.0.0.1) 5.90ms

If you need more, pls ask.
