### ISSUE TITLE
motion 4.0-1 on Ubuntu arm64 (Pine64 with ubuntu-Image Xenial)

### ISSUE THREAD

**Issue by Leonid1973** [ccrisan/motioneye#440]
Hello,
i'm running motioneye on a Pine 64 with Ubuntu Image (Xenial 16.04). Pine64 is a Single-Chip Computer arm64.
Motioneye runs fine but the installed motion version is 3.2.12+git20140228.
Is it possible to Update to motion Version 4.0.1? I didn't find a binary... 
Can somebody help?

Best regards
Leo

**Comment by ccrisan** [comment]
This has nothing to do with motionEye. I believe the way to do this is to install the package from [here](https://github.com/Motion-Project/motion/releases). In any case, if you stumble upon dependency errors or any other problems, you should seek on the motion project page.
