### ISSUE TITLE
Desktop Capture

### ISSUE THREAD

**Issue by msburgess3200** [ccrisan/motioneye#444]
I've been using MotionEye for 3 JPEG cameras. And it works GREAT! Congratulations on your success!
So, I've got this program that is called, "Show My Screen." It uses basic HTTP auth, and the WebGUI sees it like my other JPEG cameras, as a JPEG Camera. However, upon connecting to it, it reports as "Unable to Open Video Device Since" and the time and date. However, it provides it's own HTML page which refreshes the screen.jpg. And I can access the screen.jpg via web browser just fine. But MotionEye can't seem to view it.

Suggestions?

Thanks in advance!

**Comment by ccrisan** [comment]
If the UI says it's a valid JPEG camera, the the backend motion should also support it. If it doesn't, make sure you run the latest version (4.x). If you do, please [report the bug to motion](https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue).
