### ISSUE TITLE
Missing Icons on centos 7

### ISSUE THREAD

**Issue by romsworld** [ccrisan/motioneye#447]
Hi,

I have installed motioneye on Centos 7. I have some icons not visible. Do you know why ?

![2017-02-17_165736](https://cloud.githubusercontent.com/assets/12545407/23072526/4ac5f224-f532-11e6-926a-f75e560c149e.png)

Thanks,

Feb 17 16:53:47 Installed: epel-release-7-9.noarch
Feb 17 16:54:47 Installed: libjpeg-turbo-1.2.90-5.el7.x86_64
Feb 17 16:55:21 Installed: python-backports-1.0-8.el7.x86_64
Feb 17 16:55:21 Installed: python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
Feb 17 16:55:22 Installed: python-setuptools-0.9.8-4.el7.noarch
Feb 17 16:55:23 Installed: python2-pip-8.1.2-5.el7.noarch

**Comment by ccrisan** [comment]
Make sure you have the file `/etc/mime.types` present. The package on Arch Linux is called `mime-types`.

**Comment by romsworld** [comment]
Thanks !
It's provided by mailcap on centos

 yum install mailcap
