### ISSUE TITLE
webdav nexcloud

### ISSUE THREAD

**Issue by Philippe-M** [ccrisan/motioneye#448]
Hello, Is it possible to add the ability to mount a webdav space managed by an external nexcloud server to store images and videos?

**Comment by ccrisan** [comment]
Is this motionEye or motionEyeOS?

**Comment by Philippe-M** [comment]
I'm use motionEyeOs but I do not know if it's up to motionEye or motionEyeOs to handle it

**Comment by ccrisan** [comment]
On motionEyeOS you could use FTP, SFTP or SMB to mount your camera system in your nextcloud server. WebDAV is not something that will happen to motionEyeOS.

If you were on Raspbian + motionEye, I'd advise googling for WebDAV Raspbian.

**Comment by WisseHesNL** [comment]
a good tuturial for mounting webdav on raspbian is https://ajclarkson.co.uk/blog/auto-mount-webdav-raspberry-pi/ it is a bit outdated but it still works
