### ISSUE TITLE
Can't insert "CAMERA ID"

### ISSUE THREAD

**Issue by TyTnMonz** [ccrisan/motioneye#450]
Hi all, first of all thanks for your work, it's amazing!

I just updated to the last revision of MotioEye (0.35.2) on Debian 8 and I see in this version there is a new Config Field named "Camera ID" but I can't edit it, it seems to be a read-only field...this field is mandatory so I can't add new cameras o modify the existing one.

Here you can see a screenshot of the issue : [screen](https://s1.postimg.org/leq9q5s5b/2017_02_21_09_07_10.png)

Thanks to all,
regards.

EDIT: ooops...I'm so sorry, I just figured it out...I logged off and in on the web interface and now the Camera ID is automatically assigned when you add a new camera and the other already configured has got their own ID. Don't know...maybe a browser cache issue? Anyway now everything is working like a charm.

**Comment by ccrisan** [comment]
Yes, this was most likely a browser cache issue.
