### ISSUE TITLE
Can't add RTSP camera due to URL formatting.

### ISSUE THREAD

**Issue by hede0n** [ccrisan/motioneye#451]
Cameras I am using are only streaming over RTSP. I cannot add them to motioneye because of different URL formatting they are using: 

rtsp://user:password@**ipaddress**/onvif1

This doesn't seem to be an issue in VLC

I would love to be able to use those camras because they are extremely cheap, very good quality so far, and work well in LAN only (had issues with other cameras)
http://www.banggood.com/Digoo-DG-M1Q-960P-2_8mm-Wireless-Mini-WIFI-Night-Vision-Smart-Home-Security-IP-Camera-Onvif-Monitor-p-1123595.html

**Comment by ccrisan** [comment]
Have you tried entering the username & password separately, in their corresponding fields?

**Comment by hede0n** [comment]
Yes, I did. When adding new camera after typing IP address forth field with drop down list is showing up correctly so I am assuming Motioneye is recognising camera under this IP. However, picture stays grey forever. 
The only way to see the stream in any software I have tried so far was by using URL formatted like in the issue I have submitted. When using this format in MotionEye it seams to not recognise it...

**Comment by hede0n** [comment]
Scrap it! It does work. As RTSP UDP not tcp. Streams takes fair amount of time to show but it does work. Sorry, solved.

**Comment by ccrisan** [comment]
Good to hear :)

**Comment by chrisf4lc0n** [comment]
On top of that, what I have noticed with some of the RTSP cameras, when you try to add them as TCP and  it does not take it, you have to restart MotionEye to try to add it as UDP otherwise it does not recognise the camera at all.

**Comment by ccrisan** [comment]
Anyways if you got it working, I'll close the issue.

**Comment by wouterkabouter77** [comment]
I have the same camera and problem. How can i add a camera as  UDP camera and what wil be the url?

**Comment by mikeys4u** [comment]
After an hour of mucking around in Tinycam monitor for android, the rtsp url is exactly this 
rtsp://user:password@ipaddress/onvif1
using RTSP over UDP (mpeg h264/h265)

Thank you......

**Comment by chrisf4lc0n** [comment]
Finding the right streaming URL can be a real pain!  I am glad, that you got to the bottom of it!

**Comment by mrdmiba** [comment]
Is user name in rtsp link email address used as login name for Guudgo Cloud or something else?
