### ISSUE TITLE
Reboot or gain access to the terminal of the OS

### ISSUE THREAD

**Issue by lozziboy** [ccrisan/motioneye#454]
Installing motioneye service into an hosting operator system i think can be useful to gain access to the terminal of the OS directly from the web-fronted daemon.
This way is be possibile to run commands (e.g. Reboot the pc, Restart/Update motioneye directly from the web page). That's very useful in case of remote access via DDNS.
Alternativelly to this option i ask to add reboot and update buttons in the web page like done for the motioneyeOs

**Comment by ccrisan** [comment]
The reboot/poweroff buttons will show up if you set [enable_reboot](https://github.com/ccrisan/motioneye/wiki/Configuration-File#enable_reboot) to `true`.

As for a remote terminal embedded inside motionEye's UI, that's never going to happen. It's too much work, it has nothing or very little to do with video surveillance and very few people would find it useful in real life.
