### ISSUE TITLE
Working Schedule have no impact on Still Images

### ISSUE THREAD

**Issue by Dodutils** [ccrisan/motioneye#462]
Hello,

I scheduled on motionEye to work only daytime but got still images around the clock.

Not a big deal, I could turn still images off and cron captures by myself or make some "night-pictures-cleaner" script.

But wondering if it was normal or not.

By the way I found an interesting source that can give sunset/sunrise according to a geographical position (plus other extra options) that can be called thru a script can be useful for sepcific schedules. 

https://sourceforge.net/projects/sunwait4windows/ (compile fine on Linux and Raspi too)

regards.

**Comment by ccrisan** [comment]
The Working Schedule setting only affects motion detection. Unfortunately it doesn't inhibit all creation of media files.
