### ISSUE TITLE
Reboot and shutdown buttons 

### ISSUE THREAD

**Issue by JacquesBB** [ccrisan/motioneye#463]
In  motioneyeos,  
there are reboot and  shutdown button. 

These are very useful, when one does have only access through  a browser. 

Will it be possible to implement those also in the motioneye version ? 

Thanks 

Jacques

**Comment by ccrisan** [comment]
Set [enable_reboot](https://github.com/ccrisan/motioneye/wiki/Configuration-File#enable_reboot) to `true` in your motioneye config file.
