### ISSUE TITLE
Command to start and stop recording?

### ISSUE THREAD

**Issue by librunso** [ccrisan/motioneye#467]
Hello,

Is there a command to manually start and stop recording? My goal is to configure a systemd timer to record for 10 seconds every 10 minutes. Ideally, I'd like to keep the motioneye service running but configured with recording off, and just trigger the recording by command.

Currently I have this workaround in /etc/crontab with motion configured to continuously record, but it doesn't work great because the recording duration depends on how long it takes for the motioneye service to start and stop:

*/10 *     * * *   root    /bin/systemctl start motioneye.service > /dev/null 2>&1
*/10 *     * * *   root    sleep 18; /bin/systemctl stop motioneye.service > /dev/null 2>&1

Thanks!

**Comment by ccrisan** [comment]
There's no other way.
