### ISSUE TITLE
Capture mode  MQTT request

### ISSUE THREAD

**Issue by rene9900** [ccrisan/motioneye#468]
Awsome program, im using it every day 👍 
im using a esp8266 with PIR to light up my yard, thats also where i have motioneye, just 10 mins ago a fat cat triggered the PIR which send a signal to light up a LED worklight, and send a publish to light up a small red led inside, all worked, except no pictures of the cat, i saw it live on the camera but i guess it was in between 2 frames or so..
im guessing that if motion eye had the option (Capture mode) triggered by MQTT publish also, it would be much more IOT friendly 🥇

**Comment by ccrisan** [comment]
The idea is not bad and you're not the first to propose it, but there are other priorities. Sorry.
