### ISSUE TITLE
motionEye without network connection

### ISSUE THREAD

**Issue by Henrietta1989** [ccrisan/motioneye#475]
Is there any way to use motionEye in Raspberry Pi 3 which has only two USB cams and maybe one ethernet, cam without keeping internet connection on?

This type of setups are used a lot in places without possibility to have network connection.

Now if i close internet connection and open browser, it dont find motionEye webpage at all.

Thanks

**Comment by ccrisan** [comment]
I believe you're referring to motionEyeOS. If that is the case, see [this](https://github.com/ccrisan/motioneyeos/wiki/FAQ#how-can-i-run-motioneyeos-without-a-network-connection).

**Comment by Henrietta1989** [comment]
Actually it is motionEyes not motionEyesOS. Thanks

**Comment by ccrisan** [comment]
If it's motionEye, then it has nothing to do with the network connection.
