### ISSUE TITLE
Motioneye and debian

### ISSUE THREAD

**Issue by alientouch** [ccrisan/motioneye#476]
Hi,

I have installed motioneye on debian but how can i have the same options that motioneye os on raspberry pi please ?

Many thanks

**Comment by ccrisan** [comment]
What options are you interested in?

**Comment by alientouch** [comment]
Hi,
I would like to store images and videos on a nas and i can't.
And is it possible to have an update button on the web interface ?

**Comment by ccrisan** [comment]
Set [smb_shares](https://github.com/ccrisan/motioneye/wiki/Configuration-File#smb_shares) to `true` and make sure your motionEye runs as root.

**Comment by alientouch** [comment]
Ok i will test it 
Many thanks
