### ISSUE TITLE
Editable Mask not working after save "edit Mask", changed Picture size

### ISSUE THREAD

**Issue by cottaer** [ccrisan/motioneye#478]
motionEye Version	0.35.2
Motion Version	3.2.12+git20140228
Linux version 4.2.6-1-pve (root@elsa) (gcc version 4.9.2 (Debian 4.9.2-10) ) #1 SMP Thu Jan 28 11:25:08 CET 2016
Debian GNU/Linux 8 \n \l
----------------------------------------------------------------------------------------
befor edit maskfile from the webfrontend - (example mask_1.pgm)
```
root@MotionEyeOS-eau90:/home/steffen# cd /etc/motioneye/
root@MotionEyeOS-eau90:/etc/motioneye# exiftool -p '$Filename $ImageSize' *.pgm
mask_1.pgm 320x240
mask_2.pgm 320x240
mask_3.pgm 640x480
mask_4.pgm 640x480
mask_5.pgm 1280x720
mask_6.pgm 720x480
mask_7.pgm 1280x720
mask_8.pgm 1280x720
mask_9.pgm 1280x720
    9 image files read
```
editing edit maskfile mask_1.pgm from the webfrontend  -
Result -
```
root@MotionEyeOS-eau90:/etc/motioneye# exiftool -p '$Filename $ImageSize' *.pgm
mask_1.pgm 256x192
mask_2.pgm 320x240
mask_3.pgm 640x480
mask_4.pgm 640x480
mask_5.pgm 1280x720
mask_6.pgm 720x480
mask_7.pgm 1280x720
mask_8.pgm 1280x720
mask_9.pgm 1280x720
    9 image files read
```
an the effect is,  motion detection works not for Camera 1 

Unfavorable workaround - 

```
root@MotionEyeOS-eau90:/etc/motioneye# convert -size 256x192  mask_1.pgm -resize 320x240 mask_1.pgm
root@MotionEyeOS-eau90:/etc/motioneye# exiftool -p '$Filename $ImageSize' *.pgm
mask_1.pgm 320x240
mask_2.pgm 320x240
mask_3.pgm 640x480
mask_4.pgm 640x480
mask_5.pgm 1280x720
mask_6.pgm 720x480
mask_7.pgm 1280x720
mask_8.pgm 1280x720
mask_9.pgm 1280x720
    9 image files read
```

an the effect is,  motion detection works fine for Camera 1

i think it is the same problem like - https://github.com/ccrisan/motioneyeos/issues/677
So far I found no solution for it, did you have an idea?
It did not work with previous versions from motioneye.
thank you in advance, and thanks for the good software

**Comment by ccrisan** [comment]
Please upgrade to motion 4.0 if you want to use a mask.
