### ISSUE TITLE
Keyring issue on Raspbian

### ISSUE THREAD

**Issue by RogueIMP** [ccrisan/motioneye#48]
I was getting a GPG error when trying to add the repository.  You may want to add the below instruction prior instead of after, for users who are using Raspbian.  It will save some confusion, and time.

sudo apt-get install deb-multimedia-keyring

**Comment by ccrisan** [comment]
It's already there in the [instructions](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian#instructions). It's just that you need an initial `apt-get update` before `apt-get install deb-multimedia-keyring` and yes, you'll get a warning.
