### ISSUE TITLE
Problem storing Images on a Network Share with Motion detection

### ISSUE THREAD

**Issue by Mo-O** [ccrisan/motioneye#480]
Hi all,

i´m a little bit confused/unsure about the settings at the Motion detection section.

My goal is to detect a motion and take a picture after 10 frames. The picture should be uploaded to a network share. The picture should overide the new motion detected picture.

Configuration in Motion detection section are:
Motion Gap 30
Captured Before 1
Captured after 10
Minimum Motion Frames 20

Problem: Not the whole picture was uploaded. Sometimes only the half of the picture is uploaded and the rest is grey or the picture has 0KB and it is completly white.

My thought: After detecting a motion it takes the picture and overides it. So while copying, the picture gets overide again and that´s the problem because the picture is in use?

I tried instead of Motion detection to take interval snapshot every 30 seconds, overide the pictures and upload it to the network share. So far it works fine.
The snapshot interval creates two images one is lastsnap.jpg and the other is the .jpg with the image file name. Is this a link to lastsnap or a copy?

So why the interval Snapshot is working fine? Or are my Motion detection settings wrong?

Best Mo

**Comment by ccrisan** [comment]
If you want to take pictures 10 seconds apart I strongly recommend using the snapshot interval, as you have discovered yourself.

When you use the motion detection mechanism, all frames that are captured during the event period are dumped. Depending on how you name your media files, many of them will probably overlap.

Anyways, if you want to have pictures taken after 10 seconds of movement, I believe the best way is to calculate the number of frames elapsed in 10 seconds and set the Minimum Motion Frames to that value. The Captured Before/After don't work very well as far as I know and even if they did, they don't do what you expect: they try to include frames from before and from after the event into the event's media file(s). Motion Gap, on the other hand, will end the current motion event after that number of seconds of "silence" (i.e. no movement).

For more details on these parameters, see http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Options_Motion_Detection.
