### ISSUE TITLE
Request: FTP upload scheduled and motion images

### ISSUE THREAD

**Issue by m4rky-m4rk** [ccrisan/motioneye#486]
Hi,

Posted in wrong place.... I reposted this request here:
https://github.com/ccrisan/motioneyeos/issues/824

I would like to FTP upload images to my website . Both on a schedule at regular intervals and also extra uploads should any motion occur. I already do this with my other IP cameras and would like MotionEye to do this too. 

This very convenient. I just check my web page and see all images from all cameras. Usually its  just scheduled half hourly shots which means all is running OK.

If FTP upload is not possible could MotionEye save images to a drive on a schedule AND also on motion. It seems that I cannot do both.

Thanks, Mark

**Comment by maxholgasson** [comment]
Oh that would be great!!!
I spent now the entire evening trying to upload images taken by interval to a ftp server without success..  would be great

**Comment by m4rky-m4rk** [comment]
I should have posted this on MotioneyeOS !!

**Comment by maxholgasson** [comment]
I would appreciate that for the regular motioneye not for the OS one

**Comment by maxholgasson** [comment]
Are there are any plans to implement that in the nearer future into the regular motioneye?
Would be great :)

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneye/commit/296c29714ce2ab8deb0c9461b074ef39493b770a adds support for uploading to FTP servers.

**Comment by sv-kov** [comment]
The test connection to the FTP server passes. Photo is done once a minute. And on the FTP server, nothing is sent. What did I not include or configured?
Thank you in advance.

**Comment by sv-kov** [comment]
I can not send photos to FTP. Can I give a brief instruction on how to do this?

**Comment by ccrisan** [comment]
Does your motioneye log show any errors?
