### ISSUE TITLE
Run motion outside of Motioneye

### ISSUE THREAD

**Issue by Mr-Dave** [ccrisan/motioneye#488]
Since Motioneye uses different directories <code>/etc/motioneye</code> than the regular motion provide documentation in the motioneye site/application/help wiki on how to run motion outside of the application.

**Comment by ccrisan** [comment]
We have the [Report Motion Issue](https://github.com/ccrisan/motioneyeos/wiki/Report-Motion-Issue) page referenced from pretty much everywhere possible. I'll write something similar for plain motionEye before closing this isssue.

**Comment by ccrisan** [comment]
Done: https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue.
