### ISSUE TITLE
active stream when motion eyes is disabled

### ISSUE THREAD

**Issue by Blacksly** [ccrisan/motioneye#496]
Hi guys ! 
It's possible to enabled the streaming camera ( port 8082 for me) when motion eyes is disabled ?
I explain, i use domoticz for enabled/disabled motion eyes whith my security system. But with domoticz 
I want to be able to take a picture even when the system is off. 
It's possible ? 

Sorry for my english, i trying to translate myself but if you don't understant i will go use translator. 

thanks

**Comment by ccrisan** [comment]
When motionEye is disabled (read: stopped), the motion daemon is also stopped and therefore it can do the streaming part. So the answer is no.

**Comment by Blacksly** [comment]
Okay, thanks for fast answer !
