### ISSUE TITLE
"no camera" found RPi Zero W

### ISSUE THREAD

**Issue by cephasiii** [ccrisan/motioneye#497]
Greetings,
     I am having an issue getting motioneye to recoqnize the camera. I have setup two other RPi's without issue. I ran the "raspistill -o cam.jpg" with success. Also, "bcm2835-v4l2" is added to "/etc/modules". 

     Any suggestions?
![no camera](https://cloud.githubusercontent.com/assets/20966943/24245846/e15686c8-1007-11e7-8bff-a7f9e471dda0.jpeg)

**Comment by wagsforever** [comment]
I have the same issue. On the motioneyeos page the developer said the Zero W is not supported yet so I assume it's the same issue for the motioneye

**Comment by cephasiii** [comment]
Thanks. I just installed motioneye/os on another Zero W without issue. I tried the camera on a Zero and still can't find the camera. I think I narrowed it down to a software issue, but its weird because, like I said, I installed everything on another Zero W without any issues.

**Comment by wagsforever** [comment]
Let me know if you work it out because, as I say, I have the same issue.

**Comment by cephasiii** [comment]
Bump... Anyone have a solution for this issue?

**Comment by ccrisan** [comment]
Have you checked this troubleshooting article? https://github.com/ccrisan/motioneye/wiki/Troubleshooting#raspberry-pi-camera-module-not-detected

**Comment by Jay-Arr** [comment]
One point of contention: if you're using a Raspberry Pi Zero W with a camera module, and the new official Pi Foundation case, check to make sure the connector for the camera sensor is attached on the board correctly.  If you're not careful, when you put the camera module into the lid of the case, the connector on the front of the module's board that comes from the camera sensor and lens can get tilted and disconnect, and so the software will not detect the module at all, even if the ribbon connector to the Pi is connected correctly.  That's what happened to me.  Take the module out, and check to make sure the connector on the front is straight and level.  Even disconnect it and reconnect it to make sure it's on there properly.  I went back and forth between the motioneye on Raspbian, and motioneyeos, trying to figure out why camera wasn't working.  Finally settled on the os version once I figured out it was this odd hardware issue.  Works great now!

**Comment by Jay-Arr** [comment]
Here's a pic of what I'm talking about:
![pi-camera-v2-1](https://cloud.githubusercontent.com/assets/11681115/24378229/345e9120-1310-11e7-8a14-a52be07bd210.jpg)

**Comment by aptonline** [comment]
Refered to as the Sunny connector I believe.

**Comment by Jay-Arr** [comment]
The original connector was yellow.

**Comment by cephasiii** [comment]
I will check the connector, thanks.

**Comment by wagsforever** [comment]
Hi Jay-Arr. I'm still having no camera showing up even after updating motioneye. Did your camera work with raspistill before you fixed the issue with the connector?

**Comment by Jay-Arr** [comment]
No.  But once I fixed the connector it did.  The circuitry for the camera is right in the lens module on the camera board.  If the above circled connector isn't flush and level, the computer won't see the camera module at all, regardless of the state of the external ribbon cable that goes to the Pi.  The board just has a few resistors for power and such.

**Comment by wagsforever** [comment]
See my camera does work with raspistill so this can't be the issue. Annoying. Thanks anyway

**Comment by Jay-Arr** [comment]
Have you tried the camera with the new March build of motioneyeos?  See if that works.  That's what I'm using now.

**Comment by wagsforever** [comment]
I'll give it a go. Cheers

**Comment by Jay-Arr** [comment]
You won't need to change the /etc/modules like you do on Raspbian.  You WILL need to use a USB Ethernet port to get network access from the start (the system reboots continually if it doesn't find a network connection on boot), but that's only temporary.  Wireless settings can be configured remotely through the web interface, and then you're good, but you can at least test the camera through wired Ethernet first, since that's your problem.  You can alternatively create a wpa_supplicant.conf file with the wireless connection settings.  

It is an embedded-style Linux build though, so you'll have limited command-line utilities if you do try to use a local console.  If you're just looking to use the included features, it's probably better to use the OS version for simplicity's sake, but YMMV.

**Comment by soydepr** [comment]
i have same issue on pi 3 i can see camera with raspistill but motion eye does not see it

**Comment by agilob** [comment]
No longer an issue on raspi 0 W, works out of box.
