### ISSUE TITLE
Timelapse pictures auto mode very unstable brightness

### ISSUE THREAD

**Issue by Dodutils** [ccrisan/motioneye#499]
Hello,

I use RaspiCam outdoor with "auto brightness ON" but still pictures (every minutes for a TimeLapse) have very "unstable" brightness and even at full night the pictures are ... gray not black (too much brightness).

If I set brightness manually to a "correct" value it's OK but as it is outdoor pictures the value will be ok right now and not ok later depending weather/light condition changes.

Using Raspistill I have so such problem the only thing I know is that Raspistill wait a few seconds before taking the shoot for the camera to auto-adjust correctly.

So question is, is there a way to get auto-brightness produce "good" brightness ? may be adding some "Extra motion option" ?

I also have a USB cam on an other RasPi and no such problem occur with still pictures they are all fine.

regards.

**Comment by ccrisan** [comment]
Don't use automatic brightness. It is known not to work well.
