### ISSUE TITLE
Mask

### ISSUE THREAD

**Issue by dorkygrin** [ccrisan/motioneye#50]
Is there a way to set a file as a mask as in the regular version of Motion? It would be helpful to mask out traffic and known areas of movement.

**Comment by ccrisan** [comment]
Not yet.

**Comment by jamox** [comment]
Does `mask_file /home/pi/mask.pgm` to Extra Motion Options work. I've been using it for a while, and most of the time it seems like it's working. However I haven't really confirmed whether it really works.

**Comment by hamamoko** [comment]
Thanks jamox for that hint! mask_file works great 
... for testing i just turned on "Show Frame Changes" under "Motion Detection"

**Comment by ccrisan** [comment]
Added in 0.34.
