### ISSUE TITLE
motioneye on Raspian-Jesse

### ISSUE THREAD

**Issue by pgas37** [ccrisan/motioneye#504]
according instructions:
http://www.howtoembed.com/projects/raspberry-pi/95-motioneye-with-raspberry-pi
i installed the "motioneyos-20170212.tar.gz"" to / home/pi/motioneye.

It should be possible to start motioneye with the command "./motioneye.py", but such a file is not available.

What is the command to start motioneye manually?

thanks for the help

**Comment by ccrisan** [comment]
That is an old article on motionEye. You have downloaded [motionEyeOS](https://github.com/ccrisan/motioneyeos). Follow [these](https://github.com/ccrisan/motioneyeos/wiki/Installation) instructions.

**Comment by ccrisan** [comment]
Also if you really want plain motionEye on Raspbian, see [this](https://github.com/ccrisan/motioneye/wiki/Installation).
