### ISSUE TITLE
Minor Layout Issue - Video Stream Authentication Selection

### ISSUE THREAD

**Issue by aaron9412** [ccrisan/motioneye#508]
Just completed successful setup using MotionEyeOS, Raspberry Pi Zero W, and Pi Camera. 
Able to stream to WAN on :8081. Thank you @ccrisan. 

When setting stream authentication to basic, page will not scroll down far enough to see selection options besides "disabled". I am using a build formatted for the pi zero w, so this may be irrelevant to stable builds.
Workaround: select authentication mode arrow with mouse, then use down arrow on keyboard to select basic. Or "restore down" window, and it will display.

I think this could just be fixed by changing html padding.

Chrome Version: Version 57.0.2987.133 (64-bit)
OS Version: motioneyeos-raspberrypi-20170307
Client OS: Windows 10 Pro
OS Download URL: https://onedrive.live.com/?authkey=%21ANn93Iq82BtG30c&cid=BC8E04F6FE864163&id=BC8E04F6FE864163%2134300&parId=BC8E04F6FE864163%2134299&action=locate

Not a complaint, just feedback hoping to be helpful to other users! Great program.

**Comment by ccrisan** [comment]
Can you please attach a screenshot exemplifying what you describe here?
