### ISSUE TITLE
Unable to add RSTP Camera with Fadora

### ISSUE THREAD

**Issue by canz78** [ccrisan/motioneye#509]
For the past few days I have been trying to setup motioneye on a fadora box, after working through a few issues with the install i was able to get everything up and running. However i have run into a issue when i try to add my RSTP Camera, In the add camera box i get "RSTP is not supported". 
I noticed that my install is only running motion version  3.3.0 looking at the motion wiki it looks like RSTP may not be supported in this version. Also just to check its running motioneye version 0.35.2 ( I think that is the most current version) 

Sorry for asking as i am newer to Linux but Using Fadora how do I update motion to the current release I think 4.0.1.  Any help would be greatly appreciated. Thanks

**Comment by ccrisan** [comment]
Motion 4.0 is indeed the answer. However this is not the place to ask how to upgrade motion on Fedora. Please ask the [motion](https://github.com/Motion-Project/motion) guys if they can provide a RPM (or whatever Fedora uses these days). Otherwise I believe you'll have to compile it from sources.
