### ISSUE TITLE
Cannot write to motioneye.conf file

### ISSUE THREAD

**Issue by EpicGamer1YT** [ccrisan/motioneye#512]
I want to edit smb shares to true because I want to connect to my network drive, but I cannot edit the motioneye.conf file. How can I so I can access my network drive. Thank you for any help!

**Comment by chrisf4lc0n** [comment]
Have you stopped motioneye process?

**Comment by ccrisan** [comment]
@EpicGamer1YT, we need more details, such as:
1. What OS do you run?
2. What version do you use?
3. What command are you typing for editing the file?
4. What do you mean you "cannot edit"? Do you get an error? If yes, what is the error?

**Comment by EpicGamer1YT** [comment]
@ccrisan Never mind, I was new and just used the wrong command.
