### ISSUE TITLE
zoom

### ISSUE THREAD

**Issue by Binog** [ccrisan/motioneye#517]
Hey there, 
is there a way to zoom into a camera image? I don't find an option in motioned.any other way to realize that ?

**Comment by ccrisan** [comment]
There's no such option. If your camera supports some custom commands to zoom in/out, I'd recommend using [Action Buttons](https://github.com/ccrisan/motioneyeos/wiki/Action-Buttons) to control it.

**Comment by elmicha** [comment]
In Chrome Beta 71 on Android I can zoom in with the zoom finger gesture (it zooms the whole page). 

In desktop browsers zooming works only for a split second, then the image/video is resized to the browser window again.

Maybe there could be an option to turn that resizing off?

**Comment by desegura** [comment]
@ccrisan It would be nice to have this option for MJPEG cameras, just under VideoDevice > Video Rotation

setting a scale (eg: 125%) and an X and Y deviation (eg: X:-4% & Y:+12%)
