### ISSUE TITLE
Cannot Capture Video When Motion Is Detected.

### ISSUE THREAD

**Issue by Osirus126** [ccrisan/motioneye#525]

**Comment by Osirus126** [comment]
Hi Calin. I cannot seem to get motioneye to capture video after motion is detected.  A folder is created in /var/lib/motioneye but i cannot seem to get video to save.. i thought it was a permission problem so i changed the folder permission with chmod 777 yet that did not fix the issue. Any help would be appreciated as i need to have this camera up and running asap due to security issues in my neighbourhood. .

**Comment by ccrisan** [comment]
Please post your configuration (Movies, Motion Detection). Screenshots from the settings panel are fine.

**Comment by Osirus126** [comment]
here is some info. 
[motion.log](https://pastebin.com/GvM8T4vC)

as you can see, my log says that mp4 is not supported. I think issue #490 is my answer. My issue is identical to Issue #875 which is closed now, but also refers to issue #490.
