### ISSUE TITLE
Minimum GPU memory required with USB webcam ?

### ISSUE THREAD

**Issue by MacAre** [ccrisan/motioneye#531]
Hello,
With a webcam, should you reserve at least 128MB of GPU memory? Where is it better to put less to give more memory to the system ?
Example with Raspberry PI zero (512Mo total).

Can I put GPU memory down (16MB) ?
I do not start the GUI at startup.

https://github.com/ccrisan/motioneye/wiki/Troubleshooting (you have allocated at least 128 MB of RAM to the  #GPU).

My webcam works with PI zero but it is to optimize and provide the maximum capacity to PI.

**Comment by ccrisan** [comment]
There's no minimum GPU memory for a USB camera. I'd recommend 16MB, which is a small value that worked fine for me.
