### ISSUE TITLE
Run MotionEye as Root

### ISSUE THREAD

**Issue by snowman82** [ccrisan/motioneye#532]
Hi,

how does one run motionEye as root  to enable smb shares ? I need to save my motion pictures and movies elsewhere... 

thanks,
Nuno

**Comment by ccrisan** [comment]
It runs as root by default if you follow the [installation instructions](https://github.com/ccrisan/motioneye/wiki/Installation).

**Comment by tnikiel82** [comment]
Hello, 
I installed everything with the instruction. 

But when I run smb_share on TRUE, systemn not running.

Why?
tnikiel

**Comment by MarcoMirisola** [comment]
Hi, 
same here, set smb_share to true make the service not running.
Anyone can help?

**Comment by MarcoMirisola** [comment]
I found the solution [here](https://github.com/ccrisan/motioneye/issues/244#issuecomment-322562566) you should install cifs-utils !

**Comment by Wojcioo** [comment]
Hi
I've installed MotionEye on Debian using this instruction: https://github.com/ccrisan/motioneye/wiki/Install-On-Debian. I've changed smb_share on TRUE and system is not running. Then I've installed install cifs-utils, and MotionEye started but there is still no Network Share Option.
