### ISSUE TITLE
banana pi

### ISSUE THREAD

**Issue by hs6666** [ccrisan/motioneye#534]
hi,

sorry dont know if this is place to post here.....

trying to install motioneyeos from https://github.com/ccrisan/motioneyeos/releases/download/20170329/motioneyeos-bananapi-20170329.img.gz

after "burning" to sdcard (w32diskimager) to banana pi (original board) get no bootup?

any ideas please?

**Comment by ccrisan** [comment]
Well? What was the problem?

**Comment by hs6666** [comment]
Hi calin,

I had downloaded an older img file, the new file worked fine

Finished initial setup, your software works really really well ☺

only issue was mounting the sata drive, but running mount command in your startup file worked fine

harry
