### ISSUE TITLE
Block part of the screen

### ISSUE THREAD

**Issue by onlize** [ccrisan/motioneye#543]
Hello, I use Raspberry PI 3 and motionEyeOS. Part of the screen that my camera see has lots of traffic and I do not want to monitor is.

Is there any way to block this part?

Thank you.

**Comment by ChriZathens** [comment]
There is a masking feature in motioneye.

**Comment by onlize** [comment]
Found it, thank you.

**Comment by ChriZathens** [comment]
You're welcome.

**Comment by ccrisan** [comment]
I believe we can close this issue now.

**Comment by onlize** [comment]
Yes, thank you.
