### ISSUE TITLE
avi.thumb files will not be deleted

### ISSUE THREAD

**Issue by hthiery** [ccrisan/motioneye#55]
when deleting a movie file the corresponding thumb file is still in the output folder

**Comment by ccrisan** [comment]
What version of motionEye are you using? What is (was) the path of the movie?

**Comment by hthiery** [comment]
meye-caa8f060 from motioneyeos for rasperry pi

**Comment by hthiery** [comment]
can i find a version string in webinterface?

**Comment by hthiery** [comment]
Current Version: 20151103

**Comment by ccrisan** [comment]
You didn't answer my question: what was the path of the movie? What is the full path of the .thumb file? Are there any other files in that folder?

**Comment by hthiery** [comment]
Currently I don't have access to the system. But as far as I know it is the default path. I added two cameras. Both write their files (avi and jpg) to that location.

**Comment by ccrisan** [comment]
When you get back to the... system, could you please try to see if the issue is reproducible? As far as I can tell from my code, it should delete the thumb files as well. In case you manage to reproduce the issue, could you please enable the debug logging and send me the log file?
