### ISSUE TITLE
Suggestion for "Delete"

### ISSUE THREAD

**Issue by DonGrego617** [ccrisan/motioneye#550]
Hi, 
Great app, love it!!  Just one suggestion?  In the "play video" section, where I can click on a video and "preview" it...and the preview enlarges and show's a really large image of the video - you have the two options:  [CLOSE] and [DOWNLOAD].  

It would be SUPER USEFUL if there was a third button there for [DELETE].  I find myself having to go back and forth between the enlarged picture to preview it to see if it's worth keeping or deleting, but then having to close that preview window, remember which video I just previewed, then clicking "DELETE", then clicking the next video to enlarge and preview the next one, close it, delete it, open next, preview it, close it, delete it.  lol.

You get the point  Just a usability suggestion!  Thanks!!
Don

**Comment by zoidy** [comment]
This would be great!

**Comment by mcmidget** [comment]
+1

**Comment by rotrials** [comment]
+1

**Comment by CRImier** [comment]
There's a button to upvote the original comment instead of adding yet another "+1" comment

![image](https://user-images.githubusercontent.com/3173633/58709012-d95a2080-83c1-11e9-9eff-391f50fe7670.png)
