### ISSUE TITLE
rtsp not supported

### ISSUE THREAD

**Issue by theo-69** [ccrisan/motioneye#557]
I am confused it shows rtsp supported, however its not!
<img width="403" alt="screenshot_42" src="https://user-images.githubusercontent.com/28484958/27141984-050658b0-512a-11e7-80a2-4445d7866963.png">

**Comment by chrisf4lc0n** [comment]
Old motion?

**Comment by theo-69** [comment]
i updated all to the newest

**Comment by chrisf4lc0n** [comment]
Have you tested that URL outside MotionEye?

**Comment by ccrisan** [comment]
@theo-69, make sure you have motion 4.x installed.

**Comment by theo-69** [comment]
just realized motion does not want to start
