### ISSUE TITLE
How do I upgrade Motion?

### ISSUE THREAD

**Issue by FilippoChiappo** [ccrisan/motioneye#559]
Hello, I have installed MotionEye.
I understand that I have version 3.2.12 of motion, how can I upgrade it?
Can anyone send me the whole path I have to do?
Sorry, but I'm not good at ubuntu.
Thank you

**Comment by chrisf4lc0n** [comment]
Download the right version for you from here: [https://github.com/Motion-Project/motion/releases/](https://github.com/Motion-Project/motion/releases/) and Google how to install *.deb under Ubuntu.
