### ISSUE TITLE
webhook on the end of event

### ISSUE THREAD

**Issue by ukasiu** [ccrisan/motioneye#56]

**Comment by ccrisan** [comment]
Support for webhook at the end of the event is already supported. Support for webook calling with each media file creation has just landed and will be included in 0.29.

**Comment by ukasiu** [comment]
Actually I meant this kind of webhook (so I can have another when event ends):
![zrzut ekranu 2015-12-05 o 22 11 37](https://cloud.githubusercontent.com/assets/816363/11610246/2e0c7d28-9b9d-11e5-8670-6f3f25ee773a.png)
