### ISSUE TITLE
New install - Added USB Cam == No picture

### ISSUE THREAD

**Issue by usamitysam** [ccrisan/motioneye#561]
This is a new install of motioneye.  My USB cam shows up in the pull down menu.  When add it, the image spins for a while then changes to a camera icon. 

First off I suspect my issues is that I'm running Ubuntu 12.04 and cannot install FFmpeg from the repo provided in the instructions.

My FFmpeg is version 0.8.17-4:0.8.17-0ubuntu0.12.04.2.

What version does this project need?  

Of note is that I've been running motion for a while with no issues.  (yes I stopped motion before starting motioneye)

I'm not sure where to start debugging.

Thanks

**Comment by ccrisan** [comment]
I recommend using ffmpeg 2.8 with motion 4.x. I can't help you with how to upgrade to those versions.
