### ISSUE TITLE
Motioneye raspbian and offline access point

### ISSUE THREAD

**Issue by mamulates** [ccrisan/motioneye#568]
First of all, @ccrisan I want to thank you for the motioneye. It really works great and it has enabled me to do many things.

I'm currently using my raspberry pi 2 as a dashcam on my car, running the latest raspbian os coupled with your motioneye. I was wondering if it's possible to run a local web server (using a wireless adapter) from the pi for nearby mobile devices to connect to and view the local webpage that motioneye creates. I don't want it to connect to the internet, I just want the pi to make a local hotspot so I can stream the video to my phone. (by connecting to the local webpage)

Is there an easy to way to do this?
Thank you for your time.

**Comment by ccrisan** [comment]
This is not something that motionEye should do. Please look for tutorials on how to turn your Raspberry PI into a hotspot. On top of that, if motionEye runs, you can access it via its IP address, just like you would do if it were a WiFi client.
