### ISSUE TITLE
How to change to a different wifi connection / Red border ?

### ISSUE THREAD

**Issue by raymate** [ccrisan/motioneye#578]
Using a Pi3 and the internal WiFi is a little weak for the location I have it setup, purchased a long range WiFi dongle and want to use this. How can I disable the internal wifi I assume WLAN0 and I want to use WLAN1?

Also sometimes when I log in and I see the image from from the camera I see a red border around the image, then it goes back to normal grey, what is that telling me?

**Comment by ccrisan** [comment]
Use [/data/etc/modprobe.conf](https://github.com/ccrisan/motioneyeos/wiki/modprobe.conf) to `blacklist brcmfmac` module.
