### ISSUE TITLE
jessie install server not running

### ISSUE THREAD

**Issue by bscuderi13** [ccrisan/motioneye#581]
Installed on an odroid XU4 running jessie by following the directions on the page and the server isn't running. Ive had this previously working before so I am not sure what the holdup is but I would appreciate any help you may have.. I have included the output of systemctl status motioneye below. 

root@odroid-jessie:~# systemctl status motioneye -l
● motioneye.service - motionEye Server
   Loaded: loaded (/etc/systemd/system/motioneye.service; enabled)
   Active: failed (Result: exit-code) since Sat 2017-07-08 22:58:38 UTC; 2min 53s ago
  Process: 598 ExecStart=/usr/local/bin/meyectl startserver -c /etc/motioneye/motioneye.conf (code=exited, status=1/FAILURE)
 Main PID: 598 (code=exited, status=1/FAILURE)

Jul 08 22:58:38 odroid-jessie meyectl[598]: working_set = WorkingSet._build_master()
Jul 08 22:58:38 odroid-jessie meyectl[598]: File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 449, in _build_master
Jul 08 22:58:38 odroid-jessie meyectl[598]: ws.require(__requires__)
Jul 08 22:58:38 odroid-jessie meyectl[598]: File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 745, in require
Jul 08 22:58:38 odroid-jessie meyectl[598]: needed = self.resolve(parse_requirements(requirements))
Jul 08 22:58:38 odroid-jessie meyectl[598]: File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
Jul 08 22:58:38 odroid-jessie meyectl[598]: raise DistributionNotFound(req)
Jul 08 22:58:38 odroid-jessie meyectl[598]: pkg_resources.DistributionNotFound: pycurl
Jul 08 22:58:38 odroid-jessie systemd[1]: motioneye.service: main process exited, code=exited, status=1/FAILURE
Jul 08 22:58:38 odroid-jessie systemd[1]: Unit motioneye.service entered failed state.

**Comment by ccrisan** [comment]
You need to install pycurl (`pip install pycurl`).
