### ISSUE TITLE
rtsp support in motion (and motion 4.0 for Fedora 25)

### ISSUE THREAD

**Issue by spxak1** [ccrisan/motioneye#583]
Hi,
I am running stock Fedora 25 motion 3.3.0 and I cannot add an rtsp feed (camera) in motioneye.
I had previously set up motion to get the streams fine, but apparently motioneye requires a newer binary (4.0+) of motion to support rtsp. Is this right?

If so, can anyone point me to a fedora 25 binary/rpm? 

Thanks.

**Comment by chrisf4lc0n** [comment]
http://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_guide.html#Install_Build

**Comment by ccrisan** [comment]
motion 3.3 does not support RTSP. You'll need to upgrade, as per @chrisf4lc0n's indication.
