### ISSUE TITLE
motioneye web page not working when local_time_file enabled

### ISSUE THREAD

**Issue by jdschuitemaker** [ccrisan/motioneye#585]
When I remove the # in front of the following line, it is not possible to open the motioneye web page anymore.

change from:
`#local_time_file /etc/localtime`

to:
`local_time_file /etc/localtime`

The stream is showing the UTC time while I want it to show the local time. I hoped I would be able to change this by enabling this.

I am using motioneye on Raspbian with a manual install.

**Comment by ccrisan** [comment]
If you use motionEye and **not** motionEyeOS, please ignore that setting - it should be handled by the OS you're running.
