### ISSUE TITLE
Strange options, when choosing camera in "add camera" dialogue

### ISSUE THREAD

**Issue by bjoernhoefer** [ccrisan/motioneye#587]
Hi, 

I have a strange behavior, when I'm trying to add a network-camera (Wansview W2) to motioneye.

I can see the stream in VLC - so I don't think its an url/adress issue...

when I add the camera to the system I don't get something like camera 1, 2 or 3 - I'll get some strange "text" which you can see: http://imgur.com/a/AwE5D here.

Any idea, why this is happening?

If I add the device to my system I'll get "Unable to open video device"-message.

In the logs I get:
`[2] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
[2] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.200.200:554/live/ch0)
[2] [CRT] [NET] netcam_start: Invalid netcam_url (rtsp://192.168.200.200:554/live/ch0)`

The configuration for this thread
```
# @webcam_resolution 100
# @upload_subfolders on
# @upload_server 
# @enabled on
# @network_server 
# @motion_detection on
# @upload_port 
# @upload_location 
# @preserve_movies 0
# @network_username 
# @upload_movie on
# @id 1
# @upload_password 
# @upload_method POST
# @upload_picture on
# @working_schedule_type outside
# @network_password 
# @upload_service ftp
# @name Camera1
# @preserve_pictures 0
# @storage_device custom-path
# @network_share_name 
# @upload_enabled off
# @webcam_server_resize off
# @working_schedule 
# @upload_username 

ffmpeg_output_movies off
height 480
stream_quality 85
threshold 1999
quality 85
noise_level 31
ffmpeg_output_debug_movies off
smart_mask_speed 0
pre_capture 1
noise_tune on
rtsp_uses_tcp off
stream_maxrate 5
output_pictures off
stream_localhost off
ffmpeg_variable_bitrate 8192
ffmpeg_video_codec mp4
text_changes off
movie_filename %Y-%m-%d/%H-%M-%S
auto_brightness off
stream_port 8081
rotate 0
stream_auth_method 0
lightswitch 0
framerate 2
emulate_motion off
snapshot_filename 
despeckle_filter 
snapshot_interval 0
minimum_motion_frames 20
stream_motion 0
target_dir /var/lib/motioneye/Camera1
netcam_url rtsp://192.168.200.200:554/live/ch0
text_double on
width 640
post_capture 1
output_debug_pictures off
on_picture_save /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" picture_save %t %f
on_movie_end /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" movie_end %t %f
text_left Camera1
picture_filename 
locate_motion_style redbox
locate_motion_mode off
netcam_keepalive off
max_movie_time 0
on_event_end /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" stop %t
text_right %Y-%m-%d\n%T
on_event_start /usr/local/lib/python2.7/dist-packages/motioneye/scripts/relayevent.sh "/etc/motioneye/motioneye.conf" start %t
event_gap 30
netcam_tolerant_check on
mask_file
```

I'm using motioneye 0.36.1 on debian 8

If you need any more information - I'll happly provide it to you :-)

Thanks in advance for helping

Björn

**Comment by ccrisan** [comment]
That is the RTSP server header: https://github.com/ccrisan/motioneye/blob/master/motioneye/utils.py#L550.
The server header is used as an identifier for the RTSP stream and is usually a small string. In your case it's quite huge but shouldn't affect how it works (or doesn't work).

If the URL doesn't work with motion, then make sure to upgrade motion to the latest version or, if the problem persists, contact the motion guys.
