### ISSUE TITLE
motion not detected when not room a bit dark

### ISSUE THREAD

**Issue by ari197** [ccrisan/motioneye#588]
Hi ..

I've set my motioneye, it works fine during the day when the room is well lit. but at night, even when I have lights on and I can see movement from the video stream, motion did not make any picture or send notification. 

I'm using a RasPi-2B with NOIR camera

attach is my config. 

thanks

[motion.conf.txt](https://github.com/ccrisan/motioneye/files/1150795/motion.conf.txt)
[motioneye.conf.txt](https://github.com/ccrisan/motioneye/files/1150797/motioneye.conf.txt)
[thread-1.conf.txt](https://github.com/ccrisan/motioneye/files/1150796/thread-1.conf.txt)

**Comment by ccrisan** [comment]
This sounds like a problem of tweaking motion parameters. It's not a motionEye issue.
