### ISSUE TITLE
Uploads media on GDrive twice

### ISSUE THREAD

**Issue by Jabrahx** [ccrisan/motioneye#590]
Hello :) 
I'm using MotionEyeOS on my Rasp. Pi Zero W with the following versions:
motionEye Version	0.36.1
Motion Version	4.0.1+git37b3595
OS Version	motionEyeOS 20170710

When motion is detected I will be notified via E-Mail (with attachments) and the pictures are also uploaded to Google Drive. Now I have the issue that on E-Mail there are missing some pictures of the sequence and on Google Drive I have every Picture twice (same second). 

Is there any chance to find something in the logs? 

I hope there is any solution for that. 

Greetings Jabra

**Comment by ccrisan** [comment]
They are in fact two separate pictures but they have the same name, because the (default) naming pattern doesn't allow more than one picture within a second. You can always add %q to the naming pattern so that the frame number is also part of the file name.
