### ISSUE TITLE
How to flush config after restoring wrong config?

### ISSUE THREAD

**Issue by websitefreedom** [ccrisan/motioneye#597]
I'm running Motioneye under Raspbian. All was well until, within Motioneye, I restored a backup created by Motioneyeos. Is there an easy way of flushing the config to defaults without rebuilding?

**Comment by chrisf4lc0n** [comment]
`cp /usr/local/share/motioneye/extra/motioneye.conf.sample /etc/motioneye/motioneye.conf`
