### ISSUE TITLE
wiki suggestion

### ISSUE THREAD

**Issue by sgiannulli** [ccrisan/motioneye#60]
Hi,
just a suggestion to update requirements on wiki page about how to compile mr-dave fork of motion:
"sudo apt-get install dh-autoreconf"
raspbian at least does not include it in standard image
Thanks

**Comment by ccrisan** [comment]
Normally if you have followed the instructions from the [wiki page](https://github.com/ccrisan/motioneye/wiki/Compiling-Motion), on a Debian systems you would have installed `build-essential`, which should have normally pulled the `autoconf` package. If it didn't, just let me know and I'll explicitly add it to the wiki page.

**Comment by sgiannulli** [comment]
I had build-essential already installed on my Raspbian and trying to compile mr-dave motion from a directory where the config script was missing the result was:
"autoreconf: command not found"
so I think autoconf is not pulled with build-essential package as reported in this page https://help.ubuntu.com/community/CompilingSoftware

**Comment by ccrisan** [comment]
Alright then. I added autoconf to the packages that need to be installed in order to compile motion on Debian.
