### ISSUE TITLE
Support for SMS Activate/Deactivate!

### ISSUE THREAD

**Issue by Ohem** [ccrisan/motioneye#606]
Hi!

I wonder if you would consider adding the option or support for PiAnywhere or any 3G/4G dongle for activating and deactivating the surveillance. Not everyone cares to have it all scheduled, It's unnecessary for the system to record and take pictures if I'm already home or have to spontaneously leave for <insert reason>. Having the system to send SMS if motion is detected is probably something that'd be cool to have.

Also I have posted another suggestion a few days ago on the integrated version of motioneye https://github.com/ccrisan/motioneyeos/issues/1054

Edit:

You may also update the installation instructions for Ubuntu, /usr/local has been changed to /home/<username>/.local (yes the folder is hidden) upon installation and few config files has to be edited to make the pathing correct. The meyectl also refuse to run entirely, the terminal tells me the file is either not there or doesn't have the proper permissions for /var/lib/motioneye - but the file is there. Now I just have figure out how to change permissions.

Edit 2:

Nevermind, I forgot to create the folder - DOH!

But systemctl still complains about the motioneye service though.

**Comment by ccrisan** [comment]
I'm not sure what this issue is about, but SMS activation/deactivation is not something I'm willing to implement. There should be other methods to activate/deactivate motion detection that motionEye *should* support, but that's another story.
