### ISSUE TITLE
forgot ssh password 

### ISSUE THREAD

**Issue by sidealice** [ccrisan/motioneye#607]
i forgot the password for the ssh. 

when i check the backup file "motion.conf".
at the top of this file i guess it is my old password but it didn't work.

# @normal_password ********
# @enabled on
# @show_advanced on
# @admin_username admin
# @admin_password ********
# @normal_username admin

how to reset the ssh password?

**Comment by ccrisan** [comment]
Assuming this is motionEyeOS (and not just motionEye on some Linux distro), your SSH password should be your admin password. If you managed to log in to your motionEye as admin to recover the config files, you should know your admin password. If it still doesn't work, things might have gotten corrupted on your data partition, at which point I recommend rewriting the OS image from scratch.
