### ISSUE TITLE
 change motioneye.conf

### ISSUE THREAD

**Issue by davidedavlab** [ccrisan/motioneye#611]
How do i modify the motioneye.conf read-only file? I have to change the media_path so that the registrar ends up on a usb keychain I mounted in /home/ftp/storage/usb

**Comment by Ohem** [comment]
sudo nano /etc/motioneye/motioneye.conf?

**Comment by davidedavlab** [comment]
Welcome to meye-426a93e9!
[root@meye-426a93e9 ~]# sudo /etc/motioneye.conf 
-sh: sudo: command not found



[root@meye-426a93e9 ~]# /etc/motioneye.conf 

                                                                    [ File '/etc/motioneye.conf' is unwritable ]

**Comment by Ohem** [comment]
You forgot to include nano, it's the texteditor. sudo gives you root privilegies for that commandline.

**Comment by davidedavlab** [comment]
[ File '/etc/motioneye.conf' is unwritable ]

**Comment by ccrisan** [comment]
Have you read the [FAQ](https://github.com/ccrisan/motioneyeos/wiki/FAQ#why-do-i-get-read-only-file-system-when-trying-to-edit-a-file)? Also you might want to edit the [`/data/etc/motioneye.conf`](https://github.com/ccrisan/motioneyeos/wiki/motioneye.conf).
