### ISSUE TITLE
tornado.httpclient not found after upgrade to newest version

### ISSUE THREAD

**Issue by Samfox2** [ccrisan/motioneye#618]
Hi,

I upgraded motioneye to the newest version but now I`m getting the following error message:
from tornado.httpclient import AsyncHTTPClient
ImportError: No module named tornado.httpclient

I already tried to re-install tornado but it always tells me that I allready have the most recent version installed. 

Does anyone have the same issue?

**Comment by ccrisan** [comment]
Do you run it using python2 or python3?

**Comment by Samfox2** [comment]
I`m using python2

**Comment by ccrisan** [comment]
If you run `python2` and then type `import tornado.httpclient`, does it give an error?

**Comment by Samfox2** [comment]
Does'nt find the module. But pip tells me that it is allready installed...

**Comment by Samfox2** [comment]
Solved it. The problem was a sym link to an old python version.
