### ISSUE TITLE
[Feature request] FIX Time Zone and Clock Format

### ISSUE THREAD

**Issue by emilioaray** [ccrisan/motioneye#622]
Fix GMT America/Caracas
Current state = GMT-4:30
Fix To = GMT-4:00
https://greenwichmeantime.com/time-zone/south-america/venezuela/time-venezuela/
And please add in the future the ability to change the clock to format 24 hours to 12 hrs (AM PM)
Thank you so much

**Comment by ccrisan** [comment]
Noted.

**Comment by ccrisan** [comment]
Assuming that this is in fact about motionEyeOS, not motionEye, commin https://github.com/ccrisan/thingos/commit/5a34392996c50c6229e83f679007afb6004dce0e fixes this issue. The code will be merged into motionEyeOS soon.
