### ISSUE TITLE
 WARNING: Connect error on fd 15: ECONNREFUSED

### ISSUE THREAD

**Issue by Olegone23** [ccrisan/motioneye#625]
Hi Guys,

Started using cool motioneye, but still can't get FPS more then 10 and error above come out.
I've got a full HD netcam, used by RTSP, while motioneye running get  WARNING: Connect error on fd 15: ECONNREFUSED.
Is it possible to find out a solution to avoid such an issue and get FPS around 30 with full HD resolution?
Spec: Ubuntu 16.04; Motion 4.01; Motioneye 0.36.1
Thanks in advance!

**Comment by ccrisan** [comment]
If you get that error, you should take a look over the motion log file and see if you find anything suspicious. If you do, please contact the [motion](https://github.com/Motion-Project/motion) guys. This is not a valid motionEye issue.

Also, from my experience with motion and regular hardware, it's very unlikely that you reach 30 fps at full HD.
