### ISSUE TITLE
Hub with motioneye slaves?

### ISSUE THREAD

**Issue by Tinker-Bel** [ccrisan/motioneye#636]
Hello,
is it possible to create a network with the server running on MotioneyeOS and the slaves running Motioneye?

Kind regards

**Comment by chrisf4lc0n** [comment]
Of course it is. When you run MotioEyeOS as a slave it will act as a glorified streamer. I have originally done that with my Raspi 1, but it was 1. Too resource hungry. 2. Limited me on what else I could do on the little Pi.
