### ISSUE TITLE
Unable to view media

### ISSUE THREAD

**Issue by jasonlshelton** [ccrisan/motioneye#647]
When I click the photos icon to view the still that have been taken, the interface looks like it's trying to pull the list, but eventually it fails with

`meyectl[11051]: ERROR: timeout waiting for the media listing process to finish
`

in the log and the interface says "Failed to get media list"

**Comment by ccrisan** [comment]
Clean up your media folder. You have too many movies/pictures and it takes your PI too much time to parse them all. You basically have 3 options:

1. Take out your SD card (assuming you're on a Raspberry PI), plug it into a Linux machine and clean up the media files on the data partition.
2. Increase the [`list_media_timeout`](https://github.com/ccrisan/motioneye/wiki/Configuration-File#list_media_timeout) setting.
3. Use a faster storage.
