### ISSUE TITLE
Random grey areas in camera output

### ISSUE THREAD

**Issue by lastfreenick** [ccrisan/motioneye#650]
I've always had some random grey areas popping up in one of my camera's video output (usually starting at the bottom of the picture,)and thought it would be either caused by the poor wifi connection or the use of an old model b pi board (too much work for this slower model?). But recently, I've upgraded both the pi to newer model 2 and significantly improved wifi. 

Still I get these grey areas a lot, I feel even more now. Is this just my camera hardware failing? It's a noir model camera by the way.

**Comment by lastfreenick** [comment]
Here is one extreme example
![img_20170905_072933](https://user-images.githubusercontent.com/10379025/30046567-0b227724-920c-11e7-893e-8fdb9f887ec2.jpg)

**Comment by ccrisan** [comment]
Are you using motion 4.x? If not, upgrade. If yes, please report this to [motion](https://github.com/Motion-Project/motion).
