### ISSUE TITLE
Help with FTP 

### ISSUE THREAD

**Issue by bigpaolo** [ccrisan/motioneye#652]
Thanks for FTP on Motioneye.
I have install it on Raspbian on a latest version of Raspberry.
I have a server FTP (192.168.1.10, port 2222)
I have a router (192.168.1.1)
I have the raspberry with motioneye (192.168.1.5)

But wich

**Comment by bigpaolo** [comment]
I have created a directory in ftp server called: ipcamera

But what i must enter in motioneye to setup ftp connection?
Server address: 192.168.1.10
Server port: 2222
Location: ???

Thanks 
Paolo

**Comment by ccrisan** [comment]
You should enter the path to your folder, which is "/ipcamera".
