### ISSUE TITLE
Install on Raspbian with Apache

### ISSUE THREAD

**Issue by hervethouzard** [ccrisan/motioneye#653]
Hello,

I have used the instructions on this page to install motioneye on an existing Raspbian installation:
https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian

On the Raspberry Pi I need to keep Apache (I'm using many Php scripts), is there a way to change the port used by motioneye ?

Bye

**Comment by chrisf4lc0n** [comment]
`sudo nano /etc/motioneye/motioneye.conf`
