### ISSUE TITLE
Install issue/query

### ISSUE THREAD

**Issue by ioquatix** [ccrisan/motioneye#655]
When I installed `motion-git` I got two directories `/etc/motion` and `/etc/motioneye` and also two services `systemctl status motion` and `systemctl status motioneye` (that one from following the instructions in the wiki). What's the difference? Is my install normal?

**Comment by chrisf4lc0n** [comment]
Yes it is normal. MotionEye is a frontend for Motion.

**Comment by ioquatix** [comment]
I see - so I shouldn't start motion by itself?

**Comment by ioquatix** [comment]
I will close this issue since we've established that it's normal. I guess it was just a bit confusing since at first I tried to do `systemctl status motion` and for a new user, I didn't know the difference.
