### ISSUE TITLE
Email

### ISSUE THREAD

**Issue by Sean2603** [ccrisan/motioneye#66]
Ive tried editing the sendmail.py to make the email a "nicer" format but the changes never seem to take effect?

Am i editing the right file?
Also would you consider adding support for sms alerts?

**Comment by ccrisan** [comment]
`sendmail.py` is indeed the file that needs to be changed. More precisely, the two vars at the beginning called `messages` and `subjects` are to be modified per your needs. Have you restarted motionEye after making those changes?

Nope, SMS support is not planned.

**Comment by chrisf4lc0n** [comment]
If it comes to SMS you can do it yourself, just Google mail to SMS, then setup a separate notification and in "Run Command" option set it all up.
