### ISSUE TITLE
Different between MotionEyeOS and MotionEYE?

### ISSUE THREAD

**Issue by Schmello** [ccrisan/motioneye#661]
Is the only difference that MotionEyeOS is a separate OS and MotionEye can be installed on any Linux distibution?

Or has one of the two more or less functions?

**Comment by chrisf4lc0n** [comment]
Function wise they are pretty much the same.

**Comment by ccrisan** [comment]
As @chrisf4lc0n there's no significant functional difference between the two. It's just the size, the ease of OS updates and the high availability that makes motionEyeOS interesting.
