### ISSUE TITLE
Motion notification via email - no picture attached

### ISSUE THREAD

**Issue by Alpengroove** [ccrisan/motioneye#668]
Hi ccrisan,

First of all congratulations and thanks for the great piece of software you programmed!

When testing around for the first time with motioneyeos, I managed to get a notification email with pictures of the motion event attached.

Actually I get emails, but no pictures attached any more.

Where is my mistake?

Edit: 
Atteched pictures time span = 5sec
Still pictures =on, 2min interval (not motion)
best regards,
Martin

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#what-should-i-do-to-have-pictures-attached-to-motion-notification-emails.

Also, you forgot to mention the version you use. The latest prerelease (although manifesting some bugs) has an improved email picture attachment mechanism.
