### ISSUE TITLE
MotionEye camera view doesn't work when motion auth is enabled

### ISSUE THREAD

**Issue by guaycuru** [ccrisan/motioneye#67]
Everything works fine until I enable authentication for motion (stream_auth_method 1).
Whenever I do that, the camera live view stops working on the motioneye web ui. Why is that?
I've added the camera as a local camera (Raspberry Cam) so I do not understand why that happens. Is there a way to have auth enabled and the live view working?

**Comment by ccrisan** [comment]
What version of motionEye are you using?

**Comment by guaycuru** [comment]
@ccrisan 
```
$ pip show motioneye
---
Name: motioneye
Version: 0.29
```

**Comment by ccrisan** [comment]
It's a bug indeed, a but that has been resurrected recently. I'll fix it asap.

**Comment by guaycuru** [comment]
Great, thanks @ccrisan !

**Comment by ccrisan** [comment]
The bug has been fixed and the fix will be available with the soon-to-be-released 0.29.1.

**Comment by guaycuru** [comment]
@ccrisan just tested on 0.29.1 and got the same result. :(

**Comment by ccrisan** [comment]
Have you restarted motionEye server after upgrading? Does the UI indicate version 0.29.1? If yes, could you please try readding your cameras?

**Comment by guaycuru** [comment]
Yes, I have restarted the motionEye server and the raspberry pi just in case.
The UI does indicate version 0.29.1: ```Current Version	0.29.1```
I'm not sure what you mean by "please try readding your cameras".

**Comment by ccrisan** [comment]
Can you remove the camera and add it back again?

**Comment by guaycuru** [comment]
@ccrisan removing and re adding the camera worked! Thanks a lot!
