### ISSUE TITLE
Error on banana pi-m64

### ISSUE THREAD

**Issue by dntwrd** [ccrisan/motioneye#673]
Why does not the "motioneye" see the webcam?
![motion](https://user-images.githubusercontent.com/25764482/30936615-228e08e6-a3dd-11e7-9d67-701ddf404901.png)
![motion1](https://user-images.githubusercontent.com/25764482/30936715-647ef350-a3dd-11e7-9322-27bff4088304.png)

**Comment by ccrisan** [comment]
what does v4l2-ctl --list-devices say?

**Comment by dntwrd** [comment]
![motion2](https://user-images.githubusercontent.com/25764482/30977002-ec6f7f86-a47e-11e7-8da3-9c4360b804e5.png)

**Comment by dntwrd** [comment]
who can help me?

**Comment by ccrisan** [comment]
@dntwrd I have no idea what "the XX" is, but it's good that you can now add your camera. If there's no video, please **attach** here (via github, not email) your motion.log file.

**Comment by dntwrd** [comment]
where is the motion.log?

**Comment by ccrisan** [comment]
Normally at `/var/log/motion.log`.

**Comment by dntwrd** [comment]
`/usr/local/bin/motion: error while loading shared libraries: libjpeg.so.62: cannot open shared object file: No such file or directory
`

**Comment by dntwrd** [comment]
If I write "sudo apt-get install jpeg62", I get this error
![jpeg](https://user-images.githubusercontent.com/25764482/31058932-2454cb80-a705-11e7-9b7f-fea7558a8819.png)

**Comment by ccrisan** [comment]
Well this is not a motionEye issue. Make sure your motion installation works.
