### ISSUE TITLE
Some disk space improvement

### ISSUE THREAD

**Issue by jeanmarc77** [ccrisan/motioneye#68]
Hello,
I use a small dedicated usb drive to store motion media files but it is already full ;).
I would like a new feature that allow to remove older files when the space is full and also the ability to allocate/manage a space size using the FIFO principle.
Thanks indeed

**Comment by ccrisan** [comment]
The only way to keep your disk clean is to set a preservation limit on your media files. There are no plans to implement a disk usage-based removal of files.
