### ISSUE TITLE
Directory for photos not changing

### ISSUE THREAD

**Issue by karl69942** [ccrisan/motioneye#682]
Hey, so I changed the target directory for the photos but its not actually changing.. I don't know how to produce a log or whatever to give to you or I would do that right off the bat, sorry. I have been messing around with it all day & it doesn't wanna change.. I had it working before just fine! I don't understand why its not working anymore...

media_path /home/kzp/Mounted/PiStorage
I have tried using chmod on the PiStorage folder also.. its a USB I have mounted on etc/fstab, but even if I try to put it as /home/kzp/Documents, it won't work..

**Comment by ccrisan** [comment]
I don't unserstand what your problem is. You can change the **File Storage > Root Directory** from the UI. The `media_path` option only controls the **default** path.

**Comment by karl69942** [comment]
:S where on the UI is this?

**Comment by karl69942** [comment]
I don't see this option anywhere... I can't even make it automatically record movement either.. Is there a menu for the UI somewhere that I'm not seeing? :/

**Comment by ccrisan** [comment]
You probably are logged in with normal user. Make sure you're logged in with admin.

**Comment by karl69942** [comment]
I am logged in with admin though!

**Comment by karl69942** [comment]
https://imgur.com/a/8RZUO

**Comment by karl69942** [comment]
ohh... I hit advanced and everything changed... I didn't know that!! Sorry! 
This is a really cool program you made, sorry to have bothered you, I seriously didn't know all that stuff changed when I click advanced mode, I only saw a few things change before & didn't realize it gave me all these other options.. really sorry! Thanks for your help!
