### ISSUE TITLE
Failed when change Password

### ISSUE THREAD

**Issue by cbholm** [ccrisan/motioneye#688]
Hi After installing
motionEye Version | 0.37.1
Motion Version | 4.0.1+git37b3595
OS Version | motionEyeOS 20171003
When change password i cant login
if i the  look in the log files there is a error on the password and som files in the file system
i have formated the SD Card and put on a new image.
pleas advise for fix this error i have tryed using older vesion and this error is now pressisten
 

[boot (1).log](https://github.com/ccrisan/motioneye/files/1373266/boot.1.log)

[motioneye (8).log](https://github.com/ccrisan/motioneye/files/1373262/motioneye.8.log)
[messages (5).log](https://github.com/ccrisan/motioneye/files/1373259/messages.5.log)

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/issues/1116. Also read the release notes of [20171003](https://github.com/ccrisan/motioneyeos/releases/tag/20171003).

In a nutshell, you forgot to clear the browser's cache. Clear the cache, refresh, use `*****` (five stars) as password and update your admin password.
