### ISSUE TITLE
Limited menu options

### ISSUE THREAD

**Issue by dragonflyuk** [ccrisan/motioneye#689]
I've moved to motioneye from motioneyeos, installed on raspbian stretch. However most of the menus are missing like there is no options at all under the video streaming option, and no motion detection menu at all. Anybody know what is wrong?

**Comment by ccrisan** [comment]
Most likely you forgot to enable Advanced Settings.

**Comment by dragonflyuk** [comment]
Your right, god I'm a complete plank at times.

Thanks
