### ISSUE TITLE
generating ssh keys

### ISSUE THREAD

**Issue by julzKB** [ccrisan/motioneye#694]
Hi there,

I'm trying to generate an ssh keypair but it's seems to be impossible to save it since "/root" is read only

`Saving key "/root/.ssh/id_rsa" failed: No such file or directory`

ssh-keygen is present as part of the OS but how would you guys create an ssh key pair ?

**Comment by ccrisan** [comment]
What are you trying to achieve in the end? Do you want to have an ssh client running on your motionEyeOS machine to use those keys when authenticating with an external SSH server?

**Comment by julzKB** [comment]
yes exactly , (or the other way around), generate public keys on the motionEyeOS and authenticate to an other ssh server in which case I run into this :

`Failed to add the host to the list of known hosts (/root/.ssh/known_hosts).`

The idea to is use rsync to send the files over to an other server .

**Comment by ccrisan** [comment]
Generating keys for the local user is not currently supported.

The other way around, you could place your keys in `/data/etc`, as indicated by the `/etc/sshd_config`.

**Comment by julzKB** [comment]
Fair enough, thanks for looking into it .

**Comment by ccrisan** [comment]
I wrote [this article](https://github.com/ccrisan/motioneyeos/wiki/SSH-Client-On-motionEyeOS) to help users run SSH commands from motionEyeOS.
