### ISSUE TITLE
Downloaded video filename

### ISSUE THREAD

**Issue by themouseNZ** [ccrisan/motioneye#705]
When downloading video files for viewing, the downloaded file name should contain the camera name and date/time of the clip but this does not always happen for every camera.  I discovered its when a camera name has a space in it, the downloaded file name is missing everything after the space including the filename extension.

**Comment by themouseNZ** [comment]
OK, I have found the reason, if there is a space in the camera name then the file name does not get the time added to the downloaded filename. Is this a bug or expected behavior?

**Comment by ccrisan** [comment]
It surely sounds like a bug. I'll investigate it.

**Comment by themouseNZ** [comment]
I replaced the spaces in the camera names with under-score's and now the file names download properly. Just as a quick question can you add the date to the file name as well as the time? Thanks

**Comment by ccrisan** [comment]
I'm sorry but I wasn't able to reproduce this issue.
