### ISSUE TITLE
recorded movies aren't sorted propery

### ISSUE THREAD

**Issue by arkenoa** [ccrisan/motioneye#707]
Please see attached image. 
![capture](https://user-images.githubusercontent.com/33282790/32272679-ca5c81d4-bf07-11e7-8f94-7737e22cc898.JPG)

**Comment by jasaw** [comment]
You mean list is not sorted chronologically?

**Comment by arkenoa** [comment]
Thank you for answering. That's right. The previous month newest events appeared on the top of the list, now I must scroll to the bottom to see November records.

**Comment by ccrisan** [comment]
@arkenoa those are in fact folders with media files. Folders are sorted alphabetically (lexicographically) by motionEye. The default naming pattern (YYYY-MM-DD) will show the folders in chronological order when sorted alphabetically.

I can see that you have changed it to DD-MM-YYYY. When you sort folders using this naming pattern, you definitely won't get stuff displayed chronologically. My advice is that you stick with the default naming pattern.
