### ISSUE TITLE
motioneye access log file ?

### ISSUE THREAD

**Issue by G00SS** [ccrisan/motioneye#709]
Hi there, I'm not used to post messages and neither about tornado server.... I've already been able to check infos, warnings, errors and even debug logs for motion... But I'd like to know if there is a way to check for the access (and fail try) on motioneye ?
Whatever, Thank you so much for your hard working on that project !

**Comment by ccrisan** [comment]
Assuming that you're on systemd, use `journalctl -u motioneye > motioneye.log` to obtain a log file for motionEye.
