### ISSUE TITLE
no picture with mmal camera on pi

### ISSUE THREAD

**Issue by jose1711** [ccrisan/motioneye#711]
after upgrading to 0.38 on my raspbian based system (osmc) and setting pi camera to mmal protocol i am no more getting a picture in motioneye. only gray rectangle with timestamp data. bcm2835-v4l2 is disabled and i also rebooted the system.

**Comment by ccrisan** [comment]
@jose1711 you must be running a motion version that's mmal compatible. Does your motion accept the mmal options? You can look at the beginning of your motion.log file for such unrecognized options.

**Comment by jose1711** [comment]
hey ccrisan, i just realized that for some reason i had motion 3.2.12 installed. after upgrade to motion 4.0.1 everything's running smoothly. thank you, closing
