### ISSUE TITLE
Motioneye service stays stopping and starting

### ISSUE THREAD

**Issue by enieuwenhuis** [ccrisan/motioneye#72]
Hi
I tried several times to install motioneye on my raspbian. 
I get no errors on service motioneye start
But, it does not work. The service keeps on stopping and starting. See this log, any idea whats wrong? 

Name: motioneye
Version: 0.29

Best regards
Erik 

Dec 10 22:40:40 raspberrypi systemd[1]: Unit motioneye.service entered failed state.
Dec 10 22:40:40 raspberrypi systemd[1]: motioneye.service holdoff time over, scheduling restart.
Dec 10 22:40:40 raspberrypi systemd[1]: Stopping motionEye Server...
Dec 10 22:40:40 raspberrypi systemd[1]: Starting motionEye Server...
Dec 10 22:40:40 raspberrypi systemd[1]: Started motionEye Server.
Dec 10 22:40:43 raspberrypi systemd[1]: motioneye.service: main process exited, code=killed, status=4/ILL
Dec 10 22:40:43 raspberrypi systemd[1]: Unit motioneye.service entered failed state.
Dec 10 22:40:44 raspberrypi systemd[1]: motioneye.service holdoff time over, scheduling restart.
Dec 10 22:40:44 raspberrypi systemd[1]: Stopping motionEye Server...
Dec 10 22:40:44 raspberrypi systemd[1]: Starting motionEye Server...
Dec 10 22:40:44 raspberrypi systemd[1]: Started motionEye Server.
Dec 10 22:40:47 raspberrypi systemd[1]: motioneye.service: main process exited, code=killed, status=4/ILL
Dec 10 22:40:47 raspberrypi systemd[1]: Unit motioneye.service entered failed state.
Dec 10 22:40:47 raspberrypi systemd[1]: motioneye.service holdoff time over, scheduling restart.
Dec 10 22:40:47 raspberrypi systemd[1]: Stopping motionEye Server...
Dec 10 22:40:47 raspberrypi systemd[1]: Starting motionEye Server...
Dec 10 22:40:47 raspberrypi systemd[1]: Started motionEye Server.

**Comment by ccrisan** [comment]
Have you tried manually starting motionEye: meyectl startserver -d?

**Comment by enieuwenhuis** [comment]
I have just entered the command sudo meyectl startserver -d
But that makes no difference. No error when I give meyectl startserver -d

**Comment by ccrisan** [comment]
What's the output that you get? Does it work or not?

**Comment by enieuwenhuis** [comment]
There is no output on the command meyectl startserver -d
The prompt returns, without output.

**Comment by chrisf4lc0n** [comment]
Are you using the new pre-compiled by Calin ffmpeg?

**Comment by enieuwenhuis** [comment]
Yes I do use the pre-compiled ffmpeg

**Comment by ccrisan** [comment]
How about `motion -h`?

**Comment by enieuwenhuis** [comment]
There is no output on that command
![schermafdruk van 2015-12-13 15 56 52](https://cloud.githubusercontent.com/assets/10836771/11767557/3751258a-a1b2-11e5-8031-57a85e928d61.png)

**Comment by ccrisan** [comment]
Have you followed the procedure at step 1 from [these instructions](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian)?

**Comment by enieuwenhuis** [comment]
Yes, I followed those instructions at step 1, and other steps.

**Comment by ccrisan** [comment]
Have you had the *deb-multimedia* repo installed on your system before? If yes, have you removed it and then reinstalled the packages `libavcodec-extra-56`, `libavformat56`, `libavresample2` and `libavutil54`?

**Comment by enieuwenhuis** [comment]
Yes I had deb-multimedia repo installed. I removed this line from /etc/apt/sources.lst
Then I did sudo apt-get update
then I did sudo apt-get install --reinstall libavcodec-extra-56 libavformat56 libavresample2 libavutil54

the problem still exists. I don't know it anymore...

**Comment by chrisf4lc0n** [comment]
Removing the repo from the repos list is not enough. You would need to:
sudo apt-get purge ffmpeg
sudo apt-get remove libavcodec-extra-56 libavformat56 libavresample2 libavutil54
sudo apt-get autoremove
Then you can start installing everything step by step.

**Comment by ccrisan** [comment]
@enieuwenhuis Indeed, your command looks a bit different than the one mentioned in the wiki. Please use @chrisf4lc0n's instructions and see if it works.

**Comment by enieuwenhuis** [comment]
Thanks for your support. I tried this but the result is the same. 
![screen-enieuwenhuis-001](https://cloud.githubusercontent.com/assets/10836771/11973609/5496242c-a95c-11e5-92fb-ab20b08ab793.jpg)

I don't know it anymore, the problem is not your support ! You can close this issue, if you want.

**Comment by ccrisan** [comment]
The only suggestion I have left is to start over with a clean and up-to-date Raspbian.

**Comment by enieuwenhuis** [comment]
I will try fresh installation during Christmas. Thanks and best regards.

**Comment by chrisf4lc0n** [comment]
If you do not use your Raspberry Pi for anything else than MotionEye the MotionEye OS would be even better option. It pretty much works out of the box with most of the cameras...

**Comment by enieuwenhuis** [comment]
Hello, a fresh installation of Raspbian is the solution for me. It works. Thanks.

**Comment by ccrisan** [comment]
Great! I'll close the issue then.

**Comment by chrisf4lc0n** [comment]
There must have been some ffmpeg leftovers on your system preventing you from getting it work properly.
