### ISSUE TITLE
OPCION NETWORK CAMARA NO APARECE EN MENU DESPLEGABLE

### ISSUE THREAD

**Issue by MarioMP1993** [ccrisan/motioneye#723]
Good morning, first of all, congratulations on the APP, I am going to raise a doubt that I have since I am not able to resolve.

when I install the system on a sd card, when adding a new camera, if I see the NETWORK CAMERA option in the pull-down menu, but when installing it on rapsbian I only see these two options, because it can be ?

On the other hand, when it comes to adding a hard drive to make the recordings the software does not detect it, there is a solution with respect to it?

Thank you.
![motioneye](https://user-images.githubusercontent.com/28504983/33256506-9af047be-d352-11e7-9046-174500316276.jpg)

**Comment by ccrisan** [comment]
Make sure you have motion 4.1 installed.

**Comment by MarioMP1993** [comment]
Buenos días,

Gracias por la respuesta. Como puedo realizar la instalación de motion 4.1 en raspbian ? 

Me podrías pasar los comandos ?? 

Gracias! 

Mario

**Comment by ccrisan** [comment]
You'll have to check out motion's [github page](https://github.com/Motion-Project/motion).

**Comment by MarioMP1993** [comment]
Buenos días ,gracias por la respuesta.

Me podrías pasar por favor un link o como realizarlo?

Por otro lado, tengo otra duda porque el programa no me detecta un disco duro externo para poder realizar las grabaciones ??

Gracias otra vez por la respuesta. Necesitaría que me contestaste ya que sólo me queda ese paso y no consigo ver la opción NETWORK CAMERA en el menú desplegable.

Gracias

**Comment by MarioMP1993** [comment]
Buenos días necesitaría por favor que me pasases cómo realizar la instalación de Motion, soy nuevo en esto y como le comento tengo todo instalado perfecto pero en el menú desplegable no me aparece la opción de network camera y las opciones de grabación tampoco me aparecen. Me sería de gran ayuda saber cómo instalar motion.

Saludos 



Mario

**Comment by MarioMP1993** [comment]
Buenos días, de la versión 4.1 que paquete tengo que instalar en mi Raspberry y como? Que comandos tengo que utilizar, gracias por todo. 

![eb662ff2-08da-44cf-b91a-676be82e9cee](https://user-images.githubusercontent.com/28504983/33260318-bd1537fc-d35f-11e7-8481-ca634c81de3a.jpeg)
