### ISSUE TITLE
Installing on Ubuntu cannot start service

### ISSUE THREAD

**Issue by pkwentus** [ccrisan/motioneye#725]
Rpi 3 install, Ubuntu MATE 16.04

In step #7 (part 2) of the Ubuntu instructions 
https://github.com/ccrisan/motioneye/wiki/Install-On-Ubuntu

I keep getting the error: 
CP: cannot start '/usr/local/share/motioneye/extra/motioneye.systemd-unit-local' : no such file or directory

When I navigate to this location, I only see motioneye.conf.sample 

This is my 2nd time installing.  I removed partitions from the SD card, reinstalled MATE and followed the instructions above.

**Comment by pkwentus** [comment]
I've tried re-installing Ubuntu 3x
I've tried a new memory card.  
It looks like the installation instructions or the content they are pullign have gotten corrupted.
Attached are screenshots of the termin window:

![screenshot at 2017-11-29 17-44-15](https://user-images.githubusercontent.com/4838902/33405248-386940c8-d52d-11e7-9d89-635d57ab7716.png)
![screenshot at 2017-11-29 17-45-13](https://user-images.githubusercontent.com/4838902/33405249-3884cdc0-d52d-11e7-98c5-fad606101692.png)
![screenshot at 2017-11-29 17-45-28](https://user-images.githubusercontent.com/4838902/33405250-38ad5ad8-d52d-11e7-8197-2c9524f073b3.png)

**Comment by ccrisan** [comment]
Installing motionEye did not work because you don't have all the prerequisites: `curl` is missing. Make sure the motionEye installation succeeds before proceeding with the copy commands.
