### ISSUE TITLE
Debian - Motioneye not running when SMB_share true

### ISSUE THREAD

**Issue by tnikiel82** [ccrisan/motioneye#737]
Hello, 

I installed the motioneye on Debian 9. I did it according to the instructions on your project.

When I set SMB_share in motioneye.config and restart program then not running properly.

Where is the problem  - how I should run motioneye as root??

Regards, 
tnikiel

**Comment by ccrisan** [comment]
Yes, you must run it as root when enabling smb share management.

**Comment by tnikiel82** [comment]
Hi,
yes,  I know this but I don't know how :)
Maybe some hint?

Regards, tnikiel.

**Comment by ccrisan** [comment]
@tnikiel82 you simply start your motionEye server as root. If you're on systemd, it already runs as root. If not, it's up to your startup method to execute the command as root.

**Comment by tnikiel82** [comment]
Thanks, a lot!

Problem was diferent - In log I found - install **cifs utils** :)

When I added this pack everything work:)

Regards, tnikiel
