### ISSUE TITLE
movies not stored

### ISSUE THREAD

**Issue by frankge973** [ccrisan/motioneye#739]
Hello,
I installed the last version. I selected my external USB hard drive mounted at /mnt/usb
from frontend inside camera, I selected the hard drive and the initial path /cam1 I applied settings but folder has been created but no movies inside.
Can you help me?
Thanks

**Comment by ccrisan** [comment]
Have you enabled Movies and Motion detection?

**Comment by frankge973** [comment]
ah, yes. now it's ok. But one problem. I tried to dopwnload the movie .mp4 and one downloaded, I cannot play with any video player (Videolan or windows media player).
