### ISSUE TITLE
Cannot play mp4 recorded movies

### ISSUE THREAD

**Issue by frankge973** [ccrisan/motioneye#740]
I tried to download the recorded  movie .mp4 and once downloaded, I tried to play it in my windows PC but I cannot play with any video player (Videolan or windows media player).

**Comment by NikonD7200** [comment]
Have you try to change the movie format , for exemple H.264(mp4) ?

**Comment by Mrnt** [comment]
If you downloaded it using the web interface (rather than Samba) did it by chance rename it by adding '.mpg' to the end of the file name - eg it downloaded as XXXX.mp4.mpg? If so try removing the '.mpg' file extension and try playing it again.

**Comment by ccrisan** [comment]
Fixed via #785.
