### ISSUE TITLE
Video stream output problems

### ISSUE THREAD

**Issue by parmiani** [ccrisan/motioneye#741]
Hello,

i have installed motioneye on my raspberry pi 3 and i have connected the network camera Sricam SP007. The output stream is on rtsp://192.168.x.x:554/onvif1. I see that randomly there is a problem on output frames and the video is "damaged". A picture is attached: 
![12-51-14 mp4](https://user-images.githubusercontent.com/29644088/34129512-ab208f9c-e444-11e7-805b-a16fcfd528e1.jpg)
This creates problems, specially because causes false positive events in motion detection systems.
Someone has a suggestion for me?

Thanks
Alessandro

**Comment by ccrisan** [comment]
The video stream is processed by [motion](https://github.com/Motion-Project/motion), not by motionEye. Please make sure you run the latest version of motion (4.1) and, if you do, please [report a motion issue](https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue).
