### ISSUE TITLE
Cannot secure Snapshot URL 

### ISSUE THREAD

**Issue by scotty92fr** [ccrisan/motioneye#751]
Hi,

I am discovering this great os/camera firmware.

I install it on a Raspberry Pi zero w and it work very great. but I cannot securte the "Snapshot URL" : I can use the Snapshot URL and see it without password.

I give password for Admin and User, 
I tried authentication mode for video streaming to basic or DIgest 

did I miss something ? Is it possible to secure this access ?

**Comment by ccrisan** [comment]
The snapshot URL has a signature embedded as a query argument which serves as an authentication token. The snapshot URL is something that should normally not be disclosed unless it's a public camera and can be safely accessed by everyone.

The snapshot URL is designed for automation and was never supposed to be directly accessed by the human user (who can be prompted for credentials). If you need that, you're probably after the embed URL.
