### ISSUE TITLE
Can not get BananaPi to boot from image

### ISSUE THREAD

**Issue by mage00000** [ccrisan/motioneye#754]
I have tried several versions of motioneyeos:
I use the supplied writeimage script (only renamed it) on linux.

[root@localhost Banana PI]# ./writeMEyesOSimage -i motioneyeos-bananapi-20180101.img -d /dev/sdd -n SinBelle:xxxxxxxx -s 192.168.1.210/24:192.168.1.1:8.8.8.8
:: writing disk image to sdcard
220+0 records in
220+0 records out
230686720 bytes (231 MB, 220 MiB) copied, 20.8475 s, 11.1 MB/s
:: re-reading sdcard partition table
:: mounting sdcard
:: creating wireless configuration
:: setting static IP configuration
:: unmounting sdcard
:: you can now remove the sdcard

But the images do not boot. Only the red (power) led lights up....
also tried: motioneyeos-bananapi-20170329.img and motioneyeos-bananapi-20171008.img
same problem.
I use a 16Gb SD card which works fine if I put a fedora image on it, but the motioneye images just don't work (for me).

Any idea how to proceed?

**Comment by ccrisan** [comment]
What Banana PI board variant do you have? Can we see a picture of it?

**Comment by mage00000** [comment]
Thanks for your quick response!
I've got a M3 V1.2 , see image:
![cimg2397k](https://user-images.githubusercontent.com/35095113/34555366-ffff41da-f163-11e7-87c0-e0d8ffc41f7e.JPG)

**Comment by ccrisan** [comment]
Unfortunately only Banana PI M1 is currently supported by motionEyeOS.

**Comment by mage00000** [comment]
OK, thanks for the info!
I'll get another board and try again!
