### ISSUE TITLE
How to pass  "-ex night -awb night" parameters to "Extra Motion Options"?

### ISSUE THREAD

**Issue by Alpengroove** [ccrisan/motioneye#757]
Hi!

Is it possible to use the night exposure mode with motioneye?
How ist the correct syntax?

best regards
Martin

**Comment by ccrisan** [comment]
Just make sure:
 * you're using motionEye 0.38 (or later)
 * you're using motion 4.1
 * you're on a RPi with a CSI camera and you have added it as MMAL camera (as opposed to V4L2)

Then you can use the Extra Motion Options to pass your options via [mmalcam_control_params](https://htmlpreview.github.io/?https://github.com/Motion-Project/motion/blob/master/motion_config.html#mmalcam_control_params).
