### ISSUE TITLE
Configure Wifi for Pi Zero W without USB Ethernet Adapter

### ISSUE THREAD

**Issue by StuartOswald** [ccrisan/motioneye#762]
I do not have a USB Ethernet adapter. I would like to use my Pi Zero W with motionpie over wifi.

Any suggestions for achieving this without obtaining additional hardware? I have access to a pi 2 and pi 3.

Thanks,

**Comment by ccrisan** [comment]
https://github.com/ccrisan/motioneyeos/wiki/Troubleshooting-Raspberry-PI-Models-A-%28Plus%29-And-Zero
