### ISSUE TITLE
"Authorization Key" field blank after entering key and applying/testing

### ISSUE THREAD

**Issue by Felixrising** [ccrisan/motioneye#764]
It seems that the key doesn't work after rebooting... I've tried it with both Google Drive and Dropbox, I get one video upload and then nothing more.. and the Authorization Key field remains blank after that... until I re-enter the key.

**Comment by ccrisan** [comment]
The authorization key is used only once, the first time you hit Apply or Test. You should *not* fill it again ever after, until you reconfigure your upload service. I know it could be misleading but I couldn't come up with a better variant.

**Comment by Felixrising** [comment]
So no way to indicate to the user that it has been populated?
