### ISSUE TITLE
Unable to connect IP Camera

### ISSUE THREAD

**Issue by duckulaj** [ccrisan/motioneye#765]
I am trying to connect a Wansview W3 IP Camera but keep getting authentication failure.

![screenshot from 2018-01-15 15-54-38](https://user-images.githubusercontent.com/15449562/34950970-a572ed1e-fa0c-11e7-88db-a5d580a720b5.png)

![screenshot from 2018-01-15 15-55-12](https://user-images.githubusercontent.com/15449562/34950986-ae6dc81c-fa0c-11e7-96f7-f48831fbe966.png)

![screenshot from 2018-01-15 15-55-43](https://user-images.githubusercontent.com/15449562/34950993-b47ea6a4-fa0c-11e7-9304-db61ea371c04.png)

![screenshot from 2018-01-15 15-56-09](https://user-images.githubusercontent.com/15449562/34951001-ba0c0166-fa0c-11e7-8e8f-b6d1fcbcea57.png)

I have tried also with authentication turned off for RTSP and still get authentication failure.

Also tried to add this as a simple MJPEG camera and stated unsupported camera type.

I changed the log level to debug, nothing in log file when trying to connect to the camera.

Any asistance would be appreciated

**Comment by chrisf4lc0n** [comment]
The RTSP address is normally something like: rtsp://192.168.0.24:554/onvif1 or rtsp://192.168.0.24:554/onvif2 not just the IP address and port.

**Comment by duckulaj** [comment]
Thank you very much for your fast response, all working now.

I used

rtsp://192.168.0.24:554/live/ch0

Thanks again

**Comment by kduytsch** [comment]
I know it's closed and I have another issue for authentication (using http). But I put a comment on this one as when I try to use the rtsp, I've got another error (and it looks like I have the same camera):

![image](https://user-images.githubusercontent.com/36768834/42683070-9121f230-868c-11e8-85c5-d594d140fab8.png)

**Comment by ewanyande** [comment]
I have installed motioneye on a PC with ubuntu but when I connect a camera it shows the "no signal sign". The same settings work well on motioneye on Raspberry. Please assist. I have attached a screenshot of the camera settings too.

![Capture](https://user-images.githubusercontent.com/50234647/57307664-a5a31800-70ed-11e9-871c-339b61c82b9f.JPG)
![Capture2](https://user-images.githubusercontent.com/50234647/57307666-a63bae80-70ed-11e9-8e9e-b5a48579f9a2.JPG)

**Comment by chrisf4lc0n** [comment]
What Ubuntu Version?

**Comment by ewanyande** [comment]
Hi,

I am using Ubuntu 16.04 LTS.

I have used the above script to allow traffic from camera and my laptop IP and still getting the same results. Also tried disabling the firewall and still not getting any results.

**Comment by chrisf4lc0n** [comment]
Same Motion Version used on Pi and Ubuntu?

**Comment by ewanyande** [comment]
Pi uses the following:

- motionEye Version | 0.39.3
- Motion Version | 4.1.1
- OS Version | motionEyeOS 20190119

The PC version user the following:
- motionEye Version | 0.35.1
- Motion Version | 3.2.12+git20140228

can one update the motion motion version to that of the Pi?

**Comment by chrisf4lc0n** [comment]
`sudo pip motioneye --upgrade`
Install motion from the Wiki of MotionEye.
