### ISSUE TITLE
Downloaded videos from Firefox are converted from .mp4 to .mp4.mpeg

### ISSUE THREAD

**Issue by seb49** [ccrisan/motioneye#775]
Hello,

I have an issue with Firefox. Downloaded videos from Firefox are converted from .mp4 to .mp4.mpeg I use VLC to view them but in this situation video show only the first image.

Regards

**Comment by Mrnt** [comment]
@seb49 if you rename them back to xyz.mp4 by deleting the 'mpeg' suffix do they work? 
I suspect the problem is that all video is downloaded with mime type 'video/mpeg' regardless of actual type resulting in Firefox appending '.mpeg' which in turn is confusing VLC.

**Comment by ccrisan** [comment]
Fixed via #785.
