### ISSUE TITLE
can't add D-Link 950g Camera

### ISSUE THREAD

**Issue by hammerniko** [ccrisan/motioneye#777]
Hello, i am using a D-Link DCS-950G IP Cam and it works fine standalone. When i try to add this cam in MotionEye with the url it fails. 

The URL to the MJPEG-Fold is http://ipadress:800/iMode.asp 
I have set my Webport of the cam to 800.

Is ist possible in Motioneye to use a File with .asp?

regards 
Niko

**Comment by ccrisan** [comment]
See https://github.com/ccrisan/motioneyeos/wiki/FAQ#i-get-an-error-when-trying-to-add-my-network-camera-is-it-supported.

Also, keep in mind that whenever you're seeing the `.asp` file extension in a URL, it **will never actually give you an ASP file**. You'll usually end up with an HTML file which is what your browser understands. The file extension may give you a hint about what technologies were used to build the website.

In any case, your camera's streaming URL is most definitely not as simple as the one you've mentioned. Please look up your camera's MJPEG/RTSP streaming URL online and try with that one.
