### ISSUE TITLE
Arch Linux ARMv7 requires lsb-release

### ISSUE THREAD

**Issue by SuperKingZ** [ccrisan/motioneye#786]
Motioneye on Arch Linux ARMv7 requires the ```lsb-release``` package for the MMAL camera to work.
Without the package you get an error
```/bin/sh: lsb_release: command not found```

You also need to add the path of "/opt/vc/bin" to your /etc/profile
Can someone please update the wiki with this info. 
Thanks in advance!

**Comment by ccrisan** [comment]
Done. Thanks.
