### ISSUE TITLE
How do I set the time zone?

### ISSUE THREAD

**Issue by laphlaw** [ccrisan/motioneye#798]
Note I'm using motioneye, not motioneyeos

**Comment by chrisf4lc0n** [comment]
Depends on the OS you are using. Google it.

**Comment by laphlaw** [comment]
are you suggesting to do it via the command line? Im talking about setting the time zone for the local time inside motion eye, i.e. on the time stamp of the camera, I can see MY local time

**Comment by laphlaw** [comment]
Ok I figured it out. I set it using sudo dpkg-reconfigure tzdata. I had to then restart the motion eye service. Thanks guys

**Comment by laphlaw** [comment]
I should note that I'm using Raspian Jessie as my OS
