### ISSUE TITLE
Displaying camera feeds on small screens

### ISSUE THREAD

**Issue by chrisf4lc0n** [ccrisan/motioneye#80]
Hi,
I have noticed that you have added some more options for camera feed layouts, unfortunately it does not seem to be doing the job on my small Xubuntu Lenovo X61s screen. Everything looks rather weird and out of place, the old options from 0.30rc1 seemed to be much better for my little screen.

**Comment by chrisf4lc0n** [comment]
Just went back to:
sudo pip install git+git://github.com/ccrisan/motioneye.git@5b78d91c2040d7383b30a0f0d731ff6809d2068e
commit.

**Comment by ccrisan** [comment]
If you're talking about the full screen layout in 0.30rc2 vs 0.30rc1, I know about that regression - I experienced it myself :)

**Comment by chrisf4lc0n** [comment]
That I exactly what I meant... When I switch the tool view on the side of the camera feeds the feeds themselves do not seem to scale, they windows just get smaller with a small piece of viewable area from the feed.

**Comment by ccrisan** [comment]
It'll be taken care of in time for 0.30 final release.
