### ISSUE TITLE
Video downloads

### ISSUE THREAD

**Issue by ADYoungberg** [ccrisan/motioneye#805]
Love this program! Running on a Raspberry Pi 3
Have a problem with downloading videos through the web interface VS accessing the same file on the HDD. Video downloaded through the web interface is locked on the 1st frame. Video on HDD plays correctly. I've attached the videos to show.  
Do I have a setting set up wrong?

Thanks again for the help!

[Video Files.zip](https://github.com/ccrisan/motioneye/files/1754237/Video.Files.zip)

**Comment by ccrisan** [comment]
Are you saying that the downloaded file is different from the one present on HDD?

**Comment by ADYoungberg** [comment]
It appears that way. I'll test it on a few other computers to ensure it's not a problem with the one computer.

**Comment by ADYoungberg** [comment]
Found the problem... VLC media player doesn't like the MP4 files generated by MotionEye, but they play just fine with Windows Media and the Android video player. I'll just use those if I need to view something. Thanks!

**Comment by chrisf4lc0n** [comment]
@ADYoungberg since your issue has been resolved could you close it, please?
