### ISSUE TITLE
Protocol rtsp not supported 

### ISSUE THREAD

**Issue by thinkdao** [ccrisan/motioneye#81]
INFO: hello! this is motionEye server 0.30rc2
![rtsp](https://cloud.githubusercontent.com/assets/16149867/11970306/91f1558a-a920-11e5-9b41-6f6394a06564.jpeg)

**Comment by TheHolm** [comment]
What "motion" are you using? It seems you are using "official" one. Id does not support rtsp. Grab one from git.

**Comment by thinkdao** [comment]
@TheHolm , i'm using https://github.com/Mr-Dave/motion and standalone motion working with rtsp.

**Comment by chrisf4lc0n** [comment]
@thinkdao What OS/hardware?

**Comment by thinkdao** [comment]
@chrisf4lc0n, Gentoo/Xiaomi XiaoYi,  but all rtsp links doesn't work

**Comment by ccrisan** [comment]
@thinkdao what does "motion -h" say?

**Comment by chrisf4lc0n** [comment]
@thinkdao Did you build it yourself? I assume there were no errors? Give the SVN version a go and report back if you can.

**Comment by thinkdao** [comment]
@chrisf4lc0n , hm, when building from setup.py - doesn't work rtsp and no show errors. When install it from pip all okay.

**Comment by chrisf4lc0n** [comment]
Sorry, I was not specific enough... Did you build the motion from the source?

**Comment by thinkdao** [comment]
@chrisf4lc0n , yeah, all packages in gentoo building from sources.

**Comment by chrisf4lc0n** [comment]
Yup SVN supports RTSP, also what is the output of Calin's question?

**Comment by chrisf4lc0n** [comment]
Also once you have built it issue ./motion -h from the folder you built it...

**Comment by thinkdao** [comment]
@chrisf4lc0n 
>$ motion -h
>motion Version Unofficial-Git-2caced3, Copyright 2000-2005 Jeroen Vreeken/Folkert van >Heusden/Kenneth Lavrsen
>
>usage:  motion [options]
>
>
>Possible options:
>
>-b                      Run in background (daemon) mode.
>-n                      Run in non-daemon mode.
>-s                      Run in setup mode.
>-c config               Full path and filename of config file.
>-d level                Log level (1-9) (EMG, ALR, CRT, ERR, WRN, NTC, INF, DBG, ALL). default: 6 / NTC.
>-k type                 Type of log (COR, STR, ENC, NET, DBL, EVT, TRK, VID, ALL). default: ALL.
>-p process_id_file      Full path and filename of process id file (pid file).
>-l log file             Full path and filename of log file.
>-m                      Disable motion detection at startup.
>-h                      Show this screen.
>
>Motion is configured using a config file only. If none is supplied,
>it will read motion.conf from current directory, ~/.motion or /etc/motion.

**Comment by thinkdao** [comment]
>Yup SVN supports RTSP, also what is the output of Calin's question?

yeah, svn version build without errors and rtsp working. 
> motion -h
>motion Version trunkREV561, Copyright 2000-2005 Jeroen Vreeken/Folkert van Heusden/Kenneth Lavrsen

**Comment by chrisf4lc0n** [comment]
Good to hear we got to the bottom of it... Initially I seemed to have a similar problem on the Ubuntu Server 14.04.3 with the Mr Dave version of motion but SVN worked with no issues, right now both of them work with no issues.
Regards Chris.

**Comment by ccrisan** [comment]
Well is the issue really solved @thinkdao?

**Comment by thinkdao** [comment]
@ccrisan , yeah, install via setup.py working only with SVN build motion for rtsp support. Add notice on wiki :+1:
