### ISSUE TITLE
What is motioneye version most compatiable with motion 3.2.12

### ISSUE THREAD

**Issue by Olegone23** [ccrisan/motioneye#813]
Hi Cris,

What is motioneye version most compatiable with motion 3.2.12

Kind Regards,
Oleg

**Comment by ccrisan** [comment]
All motionEye versions are compatible with motion 3.2. There will however be some unavailable functionalities.

**Comment by Olegone23** [comment]
Seems version 0.35.2 most suitable, got no errors!!!!

**Comment by Olegone23** [comment]
One more question, (sorry) what is a ffmpeg file for mov file creation? Now I've a problem with mov format.
I badly need it, cause only mov format supported by web browser video streaming!
