### ISSUE TITLE
Reconnect for RTSP 

### ISSUE THREAD

**Issue by thinkdao** [ccrisan/motioneye#82]
Doesn't reconnect and doesn't show gray background for offline cam. Only frozen picture.

**Comment by chrisf4lc0n** [comment]
Hold on I am getting lost here... It does connect to the RTSP camera now, but it when connected no picture gets streamed?
Can you change the log level to debug in /etc/motioneye/motioneye.conf and post the output of the /var/log/motioneye.log covering all the sensitive data?

**Comment by thinkdao** [comment]
@chrisf4lc0n yep, it connect to RTSP camera, but when has issue with network or camera going reboot - motioneye continues streaming video with frozen picture. 

debug lvl:

    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: creating mjpg client for camera 1
    DEBUG: mjpg client for camera 1 connected on port 8081
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: mjpg client for camera 1 on port 8081 has been idle for 10 seconds, removing it
    DEBUG: connection closed for mjpg client for camera 1 on port 8081
    DEBUG: mjpg client for camera 1 on port 8081 removed
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...
    DEBUG: running garbage collector for mjpg clients...

**Comment by drewzh** [comment]
I think you might find that switching to motion-mrdave binary will work fine, I had the same issues when using the latest available motion build but have since switched and have no issues since. :+1:

**Comment by ccrisan** [comment]
In some cases (usually RTSP-related) motion-mrdave binary works better. That's why motionEyeOS defaults to it.
