### ISSUE TITLE
Fast Network Camera on Raspbian + MotionEye?!

### ISSUE THREAD

**Issue by flaschenge1st** [ccrisan/motioneye#822]
Hi all,
I've a new install of Raspbian Lite plus MotionEye. Unfortunately, there's no Fast Network Camera option in the menu. For the Raspi cam I have to use MMAL as camera type.
Is it possible to use the fast network camera mode with raspbian? Do I need some more programs?

Thank you.

**Comment by ccrisan** [comment]
Fast Network Camera is only available on motionEyeOS.

**Comment by ccrisan** [comment]
@flaschenge1st of course. It's basically [raspimjpeg.py](https://github.com/ccrisan/streameye/blob/master/extras/raspimjpeg.py) + [streamEye](https://github.com/ccrisan/streameye) + [streameyectl.py](https://github.com/ccrisan/motioneyeos/blob/master/board/raspberrypi/motioneye-modules/streameyectl.py).

**Comment by smumryak** [comment]
hey @flaschenge1st, have you managed to get this up and running without motioneyeos?

**Comment by flaschenge1st** [comment]
Nope, never really tried.

**Comment by ccrisan** [comment]
@puccaso you won't get the nice Fast Network Camera UI with plain motionEye. What you can do is configure and run streamEye manually.
