### ISSUE TITLE
Feature request: sound

### ISSUE THREAD

**Issue by rottieGO** [ccrisan/motioneye#836]
Was wondering if anyone worked on adding sound to video through available microphone either USB based or built-in into a webcam?

**Comment by getarun** [comment]
Or if working with a RasPi, one could use an external one attached to the Pi itself?
Would dig the code if i wouldn't have to write a PhD 🗡 

Video if always better with audio and would increase the field of useage like Baby-Cams etc.

**Comment by MrDornback** [comment]
I also am interested in the ability to connect a simple audio sensor (from a Pi pack for example) and record sound an video.

**Comment by electron1979** [comment]
Is no sound done for legal issues in certain countries?

**Comment by ccrisan** [comment]
This first needs to happen in Motion.
