### ISSUE TITLE
Installation instructions incomplete

### ISSUE THREAD

**Issue by probonopd** [ccrisan/motioneye#839]
Installation instructions on https://github.com/ccrisan/motioneye/wiki/Install-On-Debian are missing

* `libz-dev` ("The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source.")
* `python-setuptools`

at least on `Armbian_5.38_Orangepizero_Debian_stretch_next_4.14.14.img` these are needed.

**Comment by ccrisan** [comment]
Updated. Thanks.
