### ISSUE TITLE
I can't install motioneye to Rasberry PI 3B+ ?

### ISSUE THREAD

**Issue by alpozdemir** [ccrisan/motioneye#851]
I can't install motioneye to Rasberry PI 3B+ Im using minimal image based on Debian Stretch. Its normal?

**Comment by ccrisan** [comment]
Unless you give us more details about your problem, we can't help you. What error do you get? What went wrong?

**Comment by blackdot** [comment]
I faced propably similar/same issue on my clean raspbian minimal image. I saw something like:
`The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source.`

Installation of `zlib1g-dev` package helped.

**Comment by timrowledge** [comment]
Probably related to #855

**Comment by ccrisan** [comment]
Added `zlib-dev` to deps on the wiki page. I have just followed the instructions on a fresh install and everything worked perfectly.
