### ISSUE TITLE
How to change timezone via Docker installation on QNAP NAS?

### ISSUE THREAD

**Issue by vedranius** [ccrisan/motioneye#856]
Hi all, and especially @ccrisan :)
First, I'd like to thank you for your great work, as I was looking for a software for my IP cameras that just works, and after testing tons of them MotionEye seems like the best choice for what I want :) 

Today I'm trying to install MotionEye via my QNAP NAS ContainerStation inside the Docker. 
Everything works great, MotionEye works fine, streaming cameras, recording etc. 

But, I can't change the time zone, I was trying to change the option inside the motioneye.conf but it seems that's only related to MotionEye**Os**... 

And it seems that somehow I need to change it inside the Docker container if I'm not wrong? But I'm not sure how to do it... 

Can someone help me with this problem? 

Thanks! ;)

**Comment by kleini** [comment]
Please read in the wiki the linked chapter:
https://github.com/ccrisan/motioneye/wiki/Install-In-Docker#image-from-docker-hub
