### ISSUE TITLE
Set username and password for http streaming

### ISSUE THREAD

**Issue by djehrenr** [ccrisan/motioneye#858]
How do I set a "digest" username and password.  I have search a bunch but cannot not find any information.

I did change the motion.conf file to the following:

# Set the authentication method (default: 0)
# 0 = disabled
# 1 = Basic authentication
# 2 = MD5 digest (the safer authentication)
stream_auth_method 2

# Authentication for the stream. Syntax username:password
# Default: not defined (Disabled)
stream_authentication myusername:mypassword

saved and rebooted but still no luck

**Comment by ccrisan** [comment]
1. What OS (version)?
2. What motionEye version?
3. What motion version?

**Comment by djehrenr** [comment]
OS Version | Raspbian 9.3
motionEye Version | 0.39
Motion Version | 4.1.1

**Comment by ccrisan** [comment]
Go to Video Streaming and set your desired Authentication Mode.

**Comment by djehrenr** [comment]
Hi there,

So when I set the authentication mode and then go to the streaming address, a user name and password prompt appears.  I tried both admin and user accounts but they don't work.  Is there something I'm missing here?

Thanks
Dave

**Comment by ccrisan** [comment]
Hmm, that's weird. Look through your `thread-1.conf` file that's generated by motionEye. You'll see a `stream_authentication user:pass` line. What does it say?

P.S. `thread-1.conf` is at `/data/etc`, if you're using SSH to access your system.

**Comment by djehrenr** [comment]
Awesome! I was able to fix everything.  Thanks for the help!!!!
