### ISSUE TITLE
Documentation: sphinx

### ISSUE THREAD

**Issue by txemavs** [ccrisan/motioneye#861]
Hi

I've been documenting the source to try and understand how it works.

This is the Read the Docs preview site:
https://github.com/txemavs/motioneye/files/1907461/motioneye-docs-preview.zip

I created a new docs folder with sphinx and the RtD theme.
https://github.com/txemavs/motioneye/tree/docs

Should I pull request this?

**Comment by ccrisan** [comment]
I don't think having generated docs for the current source code is useful enough to include them in the repo. The current source code lacks docstrings and users can inspect the existing functions at any time using their preferred editor. Besides that, the code is quite disorganized and needs a major refactorization. Thanks anyways for the effort.
