### ISSUE TITLE
Duplicate Cameras in Config : Feed not changing

### ISSUE THREAD

**Issue by thomashermine** [ccrisan/motioneye#862]
Hi,

Having a few cameras with exactly the same config, I tried to manually edit the config file in one Backup before Restoring it.

It (kinda) worked : 1 original + 2 duplicated camera appears, and the name in the overlay is correct.
But the feed is the one of the first camera.
<img width="1399" alt="screen shot 2018-04-15 at 23 18 18" src="https://user-images.githubusercontent.com/4315469/38783516-50f9753a-4103-11e8-822b-169ec6fa44d5.png">

I've checked multiple times the value of netcam, and it is different in thread-1, thread-2 and thread-3 :
`netcam_url rtsp://192.168.0.33:554/11`
`netcam_url rtsp://192.168.0.34:554/11`
`netcam_url rtsp://192.168.0.35:554/11`

When I add a new camera with a different feed URL trough the web app, it works like a charm:
<img width="1405" alt="screen shot 2018-04-15 at 23 15 56" src="https://user-images.githubusercontent.com/4315469/38783545-a057c88e-4103-11e8-9fcf-911def54053f.png">

I don't see any difference in the duplicated non-working conf file (thread-2 and thread-3) and in working file generated by the webapp (thread-4)

**How can it be? It the feed url set anywhere else in the system?**

Here is my (redacted) config: [motioneye-config-redacted.gz](https://github.com/ccrisan/motioneye/files/1913360/motioneye-config-redacted.gz)

**Comment by Qudyjac** [comment]
You forgot to change the streaming port ;-)
The manually copied cameras are all streaming on port 8081.

**Comment by thomashermine** [comment]
Oh, my bad!
Sorry & thanks a lot for your help !
