### ISSUE TITLE
Running on port 80 alongside apache?

### ISSUE THREAD

**Issue by dragonflyuk** [ccrisan/motioneye#870]
Is there anyway to have MotionEye work in a web subdirectory, so the address would be something like http://raspberrypi.local/cctv

I already have it working on port 80, but I really need it working alongside an apache install on the same port, so that both can be accessed from dataplicity?

**Comment by ccrisan** [comment]
This is not a valid motionEye issue. Please look for help on Apache docs/forums.

**Comment by dragonflyuk** [comment]
Not really, how can I change where motion eye responds to, i.e cctv subdirectory instead of root?

**Comment by ccrisan** [comment]
@dragonflyuk it's up to Apache to route requests coming to e.g. `/your/cams/path` to motionEye's "root". [Running Behind Nginx](https://github.com/ccrisan/motioneye/wiki/Running-Behind-Nginx) might help.

**Comment by dragonflyuk** [comment]
Thanks @ccrisan that works perfectly, I can actually do all I need with nginx.

**Comment by ccrisan** [comment]
@dragonflyuk I know :) Nginx kind of rules.
