### ISSUE TITLE
No option to add "Network Camera"-- only "Simple MJPEG" and "Motioneye Camera"

### ISSUE THREAD

**Issue by alc6379** [ccrisan/motioneye#873]
I followed the "installing on Ubuntu" instructions. I'm running Armbian on an ODROID Hardkernel XU4. Installed version of motioneye is 0.39. 

I wanted the XU4 to be a central monitoring interface for multiple cameras around my house. Right now, I have a Raspberry Pi Zero W running as a Fast Network Camera. I wanted to add the camera to the XU4 as a Network Camera, but the only options I have are "Motioneye Camera" and "Simple MJPEG Camera". 

I thought that this was perhaps due to motion not being installed on my machine, but I wasn't sure. Basically, I wanted to use a Pi as an FNC camera and have the XU4 do all of the motion detection/processing so I could get a higher framerate. I had seen a post by @ccrisan saying he was doing something like this, but didn't see much more detail. Any thoughts? 

Also, if this type of operation hasn't been documented, I'd be happy to contribute by writing up a section on doing it, once this is all figured out.

**Comment by ccrisan** [comment]
> I thought that this was perhaps due to motion not being installed on my machine, but I wasn't sure. 

Well, you need to make sure of that, because that's the behaviour of motionEye when it doesn't detect a `motion` binary installed :)
