### ISSUE TITLE
Question: ffmpeg precompiled

### ISSUE THREAD

**Issue by sgiannulli** [ccrisan/motioneye#88]
https://github.com/ccrisan/motioneye/wiki/precompiled/ffmpeg_2.8.3.git325b593-1_armhf.deb
Hi,
just need to know if this has been compiled under raspbian jessie: I'm moving my RPi2 from wheezy to jessie and no more way to compile MrDave motion on a very fresh install
Thanks

**Comment by ccrisan** [comment]
Yes, it's been compiled on a jessie setup.

**Comment by sgiannulli** [comment]
[errori.txt](https://github.com/ccrisan/motioneye/files/75969/errori.txt)
never got those errors compiling motion on raspbian wheezy
could it be due to missing library dependencies?
Thanks

**Comment by ccrisan** [comment]
Have you started with a clean installation? If not, please try to remove any previous ffmpeg-related packages, as indicated [here](https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian#instructions). Then, you could try ./configuring and compiling motion again.

If that fails, either try to use this [prebuilt motion binary](https://github.com/ccrisan/motioneye/wiki/precompiled/motion-mrdave-raspbian) or try with a new clean and up-to-date Raspbian installation.

**Comment by sgiannulli** [comment]
yes, every try has been made on a clean Rasbian Jessie install and every time the same error; according to me there's something conflicting between MrDave motion and your ffmpeg precompiled.
The solution was to use both the precompiled motion binary and ffmpeg deb packet you gave.
By now the only thing that sounds strange is that motioneye.log is not created while motion.log is and the only way to check if something is going wrong is having a look at syslog
