### ISSUE TITLE
MotionEye and other apps on the same raspberry

### ISSUE THREAD

**Issue by CptSnoopy86** [ccrisan/motioneye#881]
Good afternoon all,

Bought my first Pi last week. I've been playing around and I really like PiVPN and MotionEye.

But when I install MotionEye, the software, which I mount on the SD card on my PC, prevents me from installing anything else.

Is there a work-around? Or MotionEye-light or so?

Thanks!

And if this problem is already solved, please refer me to it.

**Comment by ccrisan** [comment]
Use motionEye on Raspbian instead of motionEyeOS.
