### ISSUE TITLE
Get motion event information into frontend 

### ISSUE THREAD

**Issue by Olegone23** [ccrisan/motioneye#887]
Hi Crissian,

Do you think is it possible to get motion event information into front end (not mail, web hook or script run)?
I mean highlight in color cameras' screen with motion detected. Seems no, but you know this much better then i.

Kind Regards,
Alex

**Comment by ccrisan** [comment]
@Olegone23 the camera frame turns red upon motion detection. Isn't that what you need?

**Comment by Olegone23** [comment]
Hi Ccrisian,

Thank you. 

Seems you are right, sorry for bothering you!

Kind regards,
Oleg
