### ISSUE TITLE
.AppleDouble directory errors

### ISSUE THREAD

**Issue by mvanbreeden** [ccrisan/motioneye#89]
Accessing files from a Mac on a network drive creates .AppleDouble directories. Which are hidden normally. However MotionEye does pick up these directories and also tries to scan them and add thumbnails. Since filenames in the .AppleDouble directories appear to be pictures and movies, the thumbnail handler will return errors and do unnecessary work.

Workaround/solution is to exclude all hidden, or more specific, .AppleDouble dirs from search paths (line 83 in media files.py)

**Comment by ccrisan** [comment]
You're right, hidden folders should simply be ignored.

**Comment by mvanbreeden** [comment]
I put in a pull request to suggest solution. Did focus on appledouble though, since that is automatically created without (most) users knowledge.
