### ISSUE TITLE
Trouble crating Cron job

### ISSUE THREAD

**Issue by kyleser** [ccrisan/motioneye#905]
I’m wanting to setup a weekly Cron job to simply reboot the motioneyeos system without manually pressing “Reboot”.  I can’t figure out if I need to accomplish this via SSH command line or tweak an configuration file.  I’ve tried typing “reboot now” into SSH but nothing happens.

I’m confident I’m a newbie at this probably have no idea how to accomplish this simple task.

**Comment by ccrisan** [comment]
The command is `reboot` not `reboot now` and should work via cron. I believe this is about motionEyeOS, rather than motionEye. See [this](https://github.com/ccrisan/motioneyeos/wiki/Tweaks#running-commands-at-regular-intervals-cron-support) for cron details.
