### ISSUE TITLE
Adding a new Simple MJPEG Camera

### ISSUE THREAD

**Issue by airamramirez** [ccrisan/motioneye#909]
I have motioneyeOS already installed on a Raspberry PI Zero and motionEye installed on a PC with Ubuntu. If I try to add the camera conected to the Raspberry don’ t find any problem but If the camera Is configured as “Fast network camera” there is no way to add it on Ubuntu.
I have tried to add it as “Network Camera”, “Remote motionEye camera” and “simple mjpeg camera”, using also as URL expressions like http://MyIP:80...MyIP:8081...MyIP:8765 and also adding “/cam/...

**Comment by ccrisan** [comment]
Try network camera again. If it doesn't work, give us some details (screenshots, logs).

**Comment by danilo-jlle** [comment]
Hi. I'm also having problems.

Details:

I am running motionEyeOS version: 0.39.3 on Raspbian Stretch.
I am using the following board/model: Raspberry PI 1.
I am using the following type of camera: Network Camera/MJPEG Camera.
My camera model is: Apexis J602-WS-IR.
My motionEyeOS unit is connected to the network via: Ethernet.
Can't locate ir on /var/log

Adding a network IPcam as Simple MJPEG camera fails because of "cannot concatenate 'str' and 'NoneType' objects" message displayed where the name of the device should be listed.

The stream url works on VLC and browser (Chrome/Safari).

**Comment by ccrisan** [comment]
@danilo-jlle, your logs can be obtained using `journalctl -u motioneye`. That's were we should see details about the error you get.

**Comment by danilo-jlle** [comment]
Thank you for the answer.
Actually I found that was a blank password in the camera. Apparently I cannot configure it without defining a password.
But now I got no image from the camera.
There is only "no camera" logo on the screen (no warning, no messages).
Output of journalctl -u motioneye
-- Logs begin at Fri 2018-09-14 19:52:06 -03, end at Fri 2018-09-14 20:33:05 -03. --
set 14 19:52:17 localhost systemd[1]: Started motionEye Server.
set 14 19:52:36 servidor.lan meyectl[297]:     INFO: hello! this is motionEye server 0.39.3
set 14 19:52:37 servidor.lan meyectl[297]: /usr/bin/ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or direct
set 14 19:52:37 servidor.lan meyectl[297]:    ERROR: ffmpeg: could find version: Command '/usr/bin/ffmpeg -version' returned non-zero exit status 127
set 14 19:52:37 servidor.lan meyectl[297]:     INFO: motion not installed
set 14 19:52:38 servidor.lan meyectl[297]:     INFO: cleanup started
set 14 19:52:38 servidor.lan meyectl[297]:     INFO: wsswitch started
set 14 19:52:38 servidor.lan meyectl[297]:     INFO: tasks started
set 14 19:52:38 servidor.lan meyectl[297]:     INFO: mjpg client garbage collector started
set 14 19:52:39 servidor.lan meyectl[297]:     INFO: server started
set 14 19:55:30 servidor.lan meyectl[297]: /usr/bin/ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or direct
set 14 19:55:30 servidor.lan meyectl[297]:    ERROR: ffmpeg: could find version: Command '/usr/bin/ffmpeg -version' returned non-zero exit status 127
set 14 19:55:43 servidor.lan meyectl[297]: /usr/bin/ffmpeg: error while loading shared libraries: libmmal_core.so: cannot open shared object file: No such file or direct
set 14 19:55:43 servidor.lan meyectl[297]:    ERROR: ffmpeg: could find version: Command '/usr/bin/ffmpeg -version' returned non-zero exit status 127

I've installed "motion" package as per instruction.
I don't know why it doesn't recognize it.

**Comment by danilo-jlle** [comment]
Hi again. After trying to install motion package and noticing some missing libs, I just switch to MotionEye OS and everything works just fine. I was struggling with Raspbian because of the smb shares and then I noticed I could do it with MotionEye OS.

**Comment by ccrisan** [comment]
In motionEye you did not have `motion` installed. Also, when you add the camera as a Simple MJPEG Camera, some browsers, in some cases, might not display the MJPEG stream.

**Comment by wacher74** [comment]
"some browsers, in some cases, might not display the MJPEG stream."
Try add &username=...&password=... It helped me.
