### ISSUE TITLE
Problem with PTZ Cam

### ISSUE THREAD

**Issue by helmar74** [ccrisan/motioneye#910]
Hi,

I've an issue with an USB PTZ Cam.
I only can zoom in and out, but Pan and Tilt isn't working.
uvcdynctrl -c
[libwebcam] Unknown V4L2 camera class (UVC) control ID encountered: 0x009A0920 (V4L2_CID_CAMERA_CLASS_BASE + 32)
[libwebcam] Unknown V4L2 camera class (UVC) control ID encountered: 0x009A0921 (V4L2_CID_CAMERA_CLASS_BASE + 33)
Listing available controls for device video0:
  Brightness
  Contrast
  Saturation
  White Balance Temperature, Auto
  Gain
  Power Line Frequency
  White Balance Temperature
  Sharpness
  Backlight Compensation
  Exposure, Auto
  Exposure (Absolute)
  Exposure, Auto Priority
  Focus (absolute)
  Focus, Auto
  Zoom, Absolute
  Pan (Speed)
  Tilt (Speed)

I don't get Pan (relative) or Tilt (relative). So I can not move the cam.
If I do uvcdynctrl -s 'Pan (Speed)' 1 it moves to the one side, but I can't move only  one step.
Anyone an idea?

**Comment by ccrisan** [comment]
This is not a motionEye problem. Please use the [motionEye google group](http://groups.google.com/group/motioneye) to get help from the community.
