### ISSUE TITLE
No Expert settings in Motioneye installed on  Raspberian / Pi2 

### ISSUE THREAD

**Issue by DanielGabris** [ccrisan/motioneye#911]
Hello ccrisan, 

I have installed motioneye  via pip on rapsbian (PI2), but I don't see some settings like expert settings so I am not able to turn the raspi camera to FNC. Is that on purpose or have I done something wrong? When installed motioneyeOS, all is fine. I can't use OS as there is no support for my wifi dongle yet and have to install it manualy.
Thanks

Daniel

**Comment by ccrisan** [comment]
Those options are only available on motionEyeOS. Sorry about that.

**Comment by zaneclaes** [comment]
@ccrisan is there an equivalent (fast) solution for Docker + MotionEye on Raspbian base hardware?

**Comment by ccrisan** [comment]
@zaneclaes You could try to use https://github.com/ccrisan/streameye yourself.
