### ISSUE TITLE
SSL self signed certificate

### ISSUE THREAD

**Issue by mcnutt666** [ccrisan/motioneye#913]
I have been trying to connect an IP camera and when i do it give me the ssl error and when i try to change Validate_certs in motioneye.conf it is not there and the file is read only. any help would be appreciated. 
ps. i have tried a fresh install

**Comment by ccrisan** [comment]
You're probably using motionEyeOS, not just plain motionEye. Add the option to your [/data/etc/motioneye.conf](https://github.com/ccrisan/motioneyeos/wiki/modprobe.conf).

**Comment by mcnutt666** [comment]
Thank you, that fixed it
