### ISSUE TITLE
Feature Request: More Action Buttons

### ISSUE THREAD

**Issue by helmar74** [ccrisan/motioneye#918]
Hi,

at the moment it's only possible to have 8 Action Buttons.
Would it be possible to get more in a future release?
e.g. for connecting a PTZ camera with 9 presets you need at least 16 action buttons
6 for PTZ, 1 for a snapshot and 9 for the presets.
Thanks a lot

Helmar

**Comment by ccrisan** [comment]
I don't have plans to redesign the UI so that it can accommodate more than 8 buttons. At least not in the near future.

**Comment by helmar74** [comment]
OK, thanks for the information
