### ISSUE TITLE
Bandwidth limiter

### ISSUE THREAD

**Issue by darkplatinum** [ccrisan/motioneye#919]
Hi, I was wondering if there is a way to limit bandwidth transfer to google drive? As the videos are being uploaded, my wifi slows to almost absolute stop. As the camera will be on almost 24/7, it would be really useful to have a substantial wifi connection for other devices (Phones/computers). I found that many people have a problem when uploading to google drive. They use bandwidth limiters for google drive. Is it possible for motioneyeos to get this option implemented?

Thanks

**Comment by ccrisan** [comment]
This is definitely something that very few users would find useful. It's also something that does not pertain to motionEye (nor motion) but rather to the underlying OS. I believe it could be achieved using `iptables` but that's for you to find out. I would start by googling "iptables rate limiting".
