### ISSUE TITLE
configure new camera

### ISSUE THREAD

**Issue by davidcgu** [ccrisan/motioneye#920]
Good morning

I have just installed motioneye on my raspberry pi 3 following the steps indicated on the wiki:  https://github.com/ccrisan/motioneye/wiki/Install-On-Raspbian

I have made the installation under su as was not working directly under pi user.

Now I can open the console and make the logging but when trying to add a camera does not allow me to write nothing on the mandatory box for the camera and don't know what to do to move forward.

![image](https://user-images.githubusercontent.com/34965121/41829292-2deecb4e-783a-11e8-8f76-b632db34c89d.png)

Just as a not, on the config file  /etc/motioneye/motioneye.conf   I have:

# enable adding and removing cameras from UI
add_remove_cameras true

I will appreciate any help.

Thansk in advance

**Comment by ccrisan** [comment]
The URL is invalid. Remove the `admin:@` part.

**Comment by davidcgu** [comment]
wowwwww Thanks a lot ccrisan
