### ISSUE TITLE
Optimum Pi Camera v2 Settings

### ISSUE THREAD

**Issue by jerryfudd** [ccrisan/motioneye#947]
Hi,

I installed 'motioneye**os**' onto my Rpi3 with the v2 Pi Camera and the results seemed very impressive compared to what I'd had previously achieved just experimenting with motion alone, however I did need to run a script on the Pi also (using it to control a motorised vehicle) so did the 'motioneye' install over Raspian Stretch Lite and although it works the camera performance doesn't quite seem as good even before loading on said script.

Should there be a noticeable difference between the two installations? ...or is there just some extra configuration that needs doing? motioneyeos just worked on login whereas I had to add the camera to motioneye.

thanks,

Dan

**Comment by ccrisan** [comment]
There should be no sensible performance difference between motionEye and motionEyeOS on the same board. Make sure you're not eating up CPU with other stuff on your motionEye setup and make sure you're actually using the same resolution and framerate settings in both cases.
