### ISSUE TITLE
Settings panel missing 'Motion Detection'

### ISSUE THREAD

**Issue by LNFWebsite** [ccrisan/motioneye#953]
Hi!

My settings panel appears to be missing most of the configuration options I've seen in screenshots. The camera is RTSP configured as Network Camera.

Here's a screenshot:

![screenshot 74](https://user-images.githubusercontent.com/9419359/43056630-48881b54-8e0b-11e8-9807-5299b19697d6.png)

Thanks ahead!

**Comment by ccrisan** [comment]
Enable Advanced Settings.

**Comment by LNFWebsite** [comment]
I'm such an idiot! Thank you for the quick response, I turned it on before, but never scrolled down to see that the menu changed.
