### ISSUE TITLE
Unable to open video device

### ISSUE THREAD

**Issue by RedGuilhas** [ccrisan/motioneye#961]
Hello,

I have a Xiaofang camera that I flashed the Fang Hacks firmware. It works by rtsp. I can view it through VLC so I know it works.
When I added it to MotionEye I got a blank screen with the message "Unable to open video device".

This all I have in the logs:

jul 27 17:38:00 hassi motion[6010]: [1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 404 Stream Not Found
jul 27 17:38:00 hassi motion[6010]: [1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://192.168.1.78:554/): Server returned 404 Not Found
jul 27 17:38:10 hassi motion[6010]: [1:ml1] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
jul 27 17:38:10 hassi motion[6010]: [1:ml1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.1.78/)
jul 27 17:38:10 hassi motion[6010]: [1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 404 Stream Not Found
jul 27 17:38:10 hassi motion[6010]: [1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://192.168.1.78:554/): Server returned 404 Not Found
jul 27 17:38:20 hassi motion[6010]: [1:ml1] [WRN] [ALL] motion_loop: Retrying until successful connection with camera
jul 27 17:38:20 hassi motion[6010]: [1:ml1] [ALR] [NET] netcam_start: Network Camera thread starting... for url (rtsp://192.168.1.78/)
jul 27 17:38:20 hassi motion[6010]: [1:ml1] [ERR] [ENC] ffmpeg_avcodec_log: method DESCRIBE failed: 404 Stream Not Found
jul 27 17:38:20 hassi motion[6010]: [1:ml1] [ERR] [NET] netcam_rtsp_open_context: unable to open input(rtsp://192.168.1.78:554/): Server returned 404 Not Found

I have Motioneye installed on a old netbook running Ubuntu.

**Comment by ccrisan** [comment]
If you think your URL, protocol, credentials & everything are correct, please [Report A Motion Issue](https://github.com/ccrisan/motioneye/wiki/Report-Motion-Issue).

**Comment by ageorgios** [comment]
Same here, did you find a way to use Xiaofang with fang-hacks to motioneye?

**Comment by RedGuilhas** [comment]
Yes you have to put the link correctly.

rtsp://cameraip/unicast(without the forward slash in the end)

**Comment by ageorgios** [comment]
Is it stable for you? 
It is somewhat stable after removing audio from snx_rtsp server that is running in xiaofang (removing the -a option)
sometimes it crashes the rtsp server on the xiaofang camera
