### ISSUE TITLE
h.264/omx Not Working

### ISSUE THREAD

**Issue by jerryfudd** [ccrisan/motioneye#962]
Hi,

I'm making use of a Rock64 board I had laying around and installing Stretch minimal then motioneye worked fine however the only issue was that h.264/omx movies wouldn't work everything else was working.

Seeing a post saying that in order to resolve any ffmpeg issues I'd need to be running Bionic (https://github.com/ayufan-rock64/linux-build/issues/147), I switched - of course now following the Ubuntu installation of motioneye... a few more hiccups this time but throwing in 'pip install --upgrade setuptools' then 'sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev tcl8.6-dev tk8.6-dev python-tk' got the installation in and again motioneye is running fine yet still cannot save movies using 'h.264/omx'.

>ffmpeg -version

ffmpeg version 3.4.git-1ayufan2 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 7 (Ubuntu/Linaro 7.3.0-5ubuntu1)
configuration: --prefix=/usr --extra-version=1ayufan2 --toolchain=hardened --libdir=/usr/lib/aarch64-linux-gnu --incdir=/usr/include/aarch64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-rkmpp --enable-version3 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
libavutil      56.  7.100 / 56.  7.100
libavcodec     58.  9.100 / 58.  9.100
libavformat    58.  3.100 / 58.  3.100
libavdevice    58.  0.100 / 58.  0.100
libavfilter     7. 11.101 /  7. 11.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100

is there anything else I can do to make this work?

Dan

**Comment by ccrisan** [comment]
@jerryfudd enabling/disabling various codecs and libraries in ffmpeg, taking advantage of the GPU acceleration and other similar issues do not fall into the responsibilities of motionEye. Long story short, motionEye looks through `ffmpeg -codecs` and enables h264 OMX support if it finds `h264_omx`.

Please use our [Google Group](http://groups.google.com/group/motioneye) to expose your problem and look for other users that might be able to help you.

You could seek help from the [Motion Project](https://github.com/motion-project/motion) community as well, but keep in mind this is not a valid Motion issue.
