### ISSUE TITLE
Camera Resolution and Video rotation ignored.

### ISSUE THREAD

**Issue by surak** [ccrisan/motioneye#965]
motionEye Version | 0.39.2
Motion Version | 4.1.1
OS Version | Raspbian 9.4
 
I installed it on friday, and everything was fine. Today, the image was inverted and in lo-res (see pic).

![screen shot 2018-07-30 at 16 33 51](https://user-images.githubusercontent.com/878399/43403823-6a88a122-9416-11e8-848e-8784ecf3a900.png)

**Comment by ccrisan** [comment]
@surak can we see a screenshot of your preferences (the first part of the settings menu)?

**Comment by surak** [comment]
In fact, it's more being ignored. The text overlay is also ignored. 
![screen shot 2018-07-30 at 17 04 38](https://user-images.githubusercontent.com/878399/43405700-b6ea3694-941a-11e8-9c11-d650b297266c.png)

**Comment by ccrisan** [comment]
Your prefs are fine. There might be an issue with the camera driver, saying it supports higher resolutions whereas the camera doesn't actually support it. Try lowering the resolution and see if you can make it obey what you're asking it for.

Regarding the text overlay, why do you think it's ignoring it?

**Comment by surak** [comment]
The camera WAS capturing at the right resolution with motioneye - it's the official Pi NoIR I wonder what happened after I updated everything. If I take pictures with raspistill they are at full resolution.

If you look at this picture, there is the camera name on the left, which is set up there. And the rotation is 180º, as the camera is upside down. After the update, it's upside down and the label is default, as you can see on the previous images.

![camera1_17-38-08](https://user-images.githubusercontent.com/878399/43453450-7407c9ae-94ba-11e8-9978-d2b66386cab3.jpg)

**Comment by ccrisan** [comment]
Beats me. Try readding it from scratch. Try adding it as a MMAL camera, if say it's the official RPi camera.

**Comment by surak** [comment]
I have no clue what's going on either. I did all of it (I wouldn't ever open an issue before doing something). I only use it under raspbian because this device specifically has a screen - in all others, I use motioneyeos and it works like a charm. 

Will clear up raspbian and start clean.

**Comment by surak** [comment]
Now with 0.39.3 it's all back to work
