### ISSUE TITLE
optimization video qualitiy vs. frame rate

### ISSUE THREAD

**Issue by jojo2203** [ccrisan/motioneye#971]
I use raspberry pi 3 with the CSi standard camera v 2.1 under Rasphian in an extra WLAN with 300 MBIT. I have to reduce the image size to 800x600 to get a frequency of 20 frames / sec with a picture quality of 20%. How are your experience bezgl. Image quality vs frame rate? Over WLAN? What is there for optimization possibilities?

**Comment by ccrisan** [comment]
This is not a valid issue. Please our [Google group](http://groups.google.com/group/motioneye) to discuss this kind of matters.
