### ISSUE TITLE
Extra Motion Options Field

### ISSUE THREAD

**Issue by vdagamb** [ccrisan/motioneye#98]
Hello Crisan,
thanks for the great piece of software. I just set-up version 0.30 on a fresh Jessie Raspberry2  and runs like hell. One question from my side: I noticed the field "Extra Motion Options" . To limit the detection area, I inserted "  area_detect 9  " (without quotes) and I feel it does not work. Moreover, I did not see it in motion.conf in my  ~/motioneye/conf directory. Anything else I should consider?

Thanks a lot,
Bernd

**Comment by ccrisan** [comment]
You should see it in ~/motioneye/conf/thread-1.conf file. motion.conf contains the general (camera-independent) options.

**Comment by vdagamb** [comment]
That really makes sense ... should have known by my own. Thanks, Bernd

**Comment by tekgeek1** [comment]
vdagamb - were you ever able to get the area_detect working?  I tried adding area_detect 3 to my thread file and noting happened.
