### ISSUE TITLE
Where do i set the time zone?

### ISSUE THREAD

**Issue by joland** [ccrisan/motioneye#986]
I searched all the internet but no definite answer on how to set the time zone. Current (probably by default) timezone is UTC. 
[root@meye-61c67703 etc]# date
Tue Aug 28 11:29:38 UTC 2018

But i need CET.

I am running this version:

motionEye Version | 0.39.3
Motion Version | 4.1.1
OS Version | motionEyeOS dev20180730

FYI, i haven't seen an option to change the timezone in the UI either...

**Comment by ccrisan** [comment]
Have you enabled advanced settings?

**Comment by joland** [comment]
I managed to change with : date -s
However it is not a permanent solution. After reboot it loses the changes.
If anyone knows how to do a permanent fix, let me know.

**Comment by ccrisan** [comment]
Let's see a screenshot of your settings panel with various sections opened.

**Comment by joland** [comment]
@ccrisan I am sorry and can't believe I completely looked over this. 
Admin -> General Settings -> Time zone.

**Comment by ITCMD** [comment]
I just made the same mistake and after a few days found your post! THANKS!
