### ISSUE TITLE
Icons action buttons

### ISSUE THREAD

**Issue by reparator** [ccrisan/motioneye#990]
Not an issue, more a question:
I found the icons for the action buttons in github: motioneye/motioneye/static/img/.
But where are they in the linux system? I wanted to change some specific for scripts in my system (a birdhouse observation) but could not find the location. Could you help me?
Regards

**Comment by ccrisan** [comment]
Look for them in `/usr/lib/python2.7/site-packages/motioneye/static/img/` or `/usr/local/lib/python2.7/site-packages/motioneye/static/img/`.

**Comment by reparator** [comment]
Thanks a lot ccrisan!
The path is /usr/local/lib/python2.7/dist-packages/motioneye/static/img
