### ISSUE TITLE
How to change default HTML output

### ISSUE THREAD

**Issue by Girum** [ccrisan/motioneye#998]
Hi! I'm using the default HTML output, where I can see the N cameras I'd attached. But, the HTML is so simple... Ok, I can make another HTML and insert into a iframe... but, to use the same HTML provided, where can I find the configuration file for it (that one who generates the HTML)?

**Comment by ccrisan** [comment]
If you'd like to write your own web frontend for Motion, go ahead. You can fork motionEye, if you feel that some parts of it are useful to you.

motionEye's HTML "files" are generated starting from https://github.com/ccrisan/motioneye/tree/master/motioneye/templates and using various JavaScript files that can be found at https://github.com/ccrisan/motioneye/tree/master/motioneye/static/js.
